### ISSUE TITLE
About the removal from CurseForge

### ISSUE THREAD

**Issue by Luxocracy** [Luxocracy/NeatPlates#10]
So the project has been removed/hidden from CurseForge, the following is the reason given by the moderators:

> This project is a derivative work from another project which was released as All Rights Reserved. Unless you have permission from the original owner or owners, and can provide such proof, this project cannot be hosted on CurseForge.

The whole reason it was released under a different name to begin with was that we couldn't get into contact with the original authors and wanted to make this project easier to access for people who, like us, love this addon and couldn't imagine playing WoW without it.

So that is the situation and why it is no longer on CurseForge in case anyone is wondering why it is gone. The project will still live on here on GitHub and continue to be updated until the situation changes.

**Comment by Luxocracy** [comment]
You can download it straight from github under the [releases section](https://github.com/Luxocracy/TidyPlatesContinued/releases).
I haven't really looked at any potential alternatives to curseforge/twitch at the moment.

**Comment by ja0b** [comment]
Ok, that's a shame is not enough with the description we have in the readme file?

> The primary reason for this github is to keep this addon working in the abscence of its authors. As such the likely hood of adding or improving features is relatively low.

wowmatrix or its own website, I can help with the second option.

**Comment by Luxocracy** [comment]
It's a lot more appealing to have an the addon be updated through an addon client than it is to create a website for it. Github has a thing called Github Pages which is essentially a website/frontpage for the addon, that would probably be something worth looking into over creating a dedicated website for it.

**Comment by Luxocracy** [comment]
No, it won't be getting updated on the twitch client. The Twitch client is the client used for the stuff on CurseForge, so if it isn't on curse, it doesn't update in the Twitch client.

I was refering to wowmatrix. I've never used it personally, but from what I gathered it works about the same as the Twitch client when it comes to updates.

**Comment by AHigi** [comment]
I've contacted the admin regarding this issue, maybe there's a way to revive the original dead project. But it's too soon to tell. I'll keep you guys posted about any news regarding this.
Till then you can just download the addon from git and install it manually

**Comment by medivh91** [comment]
I love this addon，thank you

**Comment by Mezq** [comment]
Can you guys fix the combo point issue its not the same look ? that would be really cool.

**Comment by Luxocracy** [comment]
@Mezq Not sure what you mean the combo points should look exactly like before, unless you've changed the style of it in the options.

**Comment by Hezkezl** [comment]
That's a bit sad they removed it from Curseforge, but I can see it if there might be an issue with someone putting up a fraudulent version up to try to steal downloads away for some reason... hopefully there's some kind of method they'll let you guys use for the disappearance of the original author :(  Maybe renaming it something different...? Though that might get you in trouble with them anyways for having copied the original code, hmm.

In either difference though, myself and many others hugely appreciate the work you've done to keep this addon going <3

**Comment by AHigi** [comment]
All I got from the admin is that the project was created with the All Rights Reserved type copyright... So there's nothing he or we can do about it. It's simply a copyright issue.
We could only host this project on curse if we would just create one from scratch... Not sure how to proceed now... We can just host it here, maybe I could create a downloader for it in C# that would install it just like the twitch client does, or just change the addon so it would not be so similar to the original project :(

**Comment by ShizCalev** [comment]
If it's a copyright issue, modifying the code to make it not as similar to the original isn't going to fly. You wouldn't be able to use any of the original's code.

**Comment by 1988fido** [comment]
:3 man open donation site 
Am sure you will get help
At least as far as I know financially you might be able to hire a programmer to do it for us <3 
I will be first to donate XD in October

**Comment by WhatsTheIssue** [comment]
@AHigi Have you made it clear with Curse that "If and when the original author returns, this project and source code will be immediately surrendered to said author, and they can choose what to do with it."

**Comment by Mezq** [comment]
@Luxocracy ive tried it its not the same as the original tidyplates dont know if u can fix it or not i can screenshot you the original combo points frame so you can added it ?

**Comment by AHigi** [comment]
@WhatsTheIssue I've made several appeals, like we're willing to contribute to the original project, or just to fill in until the original author returns, but since it's a copyright issue the hands of the curse team are bound. Nothing they can do about that unfortunately

**Comment by Luxocracy** [comment]
@Mezq Open a new issue where you have a screenshot showing the issue you are having and I will look into it. Because the combo points art style should be the same.

**Comment by vertices86** [comment]
Thank you all for keeping this alive! I can't imagine not having my Tidy Plates.  Your efforts are very much appreciated.

**Comment by Pief23** [comment]
I love this addo

**Comment by Diablolock** [comment]
The author of Tidy Plate released an update for Tidy Plate. Maybe it's a good idea to contact him now so you guys can merge the project....

**Comment by MetalHeadSeven** [comment]
I tried the update from the original Tidy Plates "author" it... sort of works.  But this one works so much better!  Thanks for keeping it going.

**Comment by Nexxado** [comment]
> The author of Tidy Plate released an update for Tidy Plate. Maybe it's a good idea to contact him now so you guys can merge the project....

Yeah, I just noticed it got updated on curseforge.
Any idea what that's about?

**Comment by Shimiya** [comment]
Many thanks for the updates, I personally stick on TPC !

**Comment by yishuangfrank** [comment]
Although TP restored update recently. 
I prefer TPC whether  in update frequency or features.

**Comment by Luxocracy** [comment]
So, just to give an update on the whole CurseForge issue because things have changed.

I noticed that the original author of Tidy Plates has changed the license attached to the project from 'all rights reserved' to an 'MIT License'. This licensing change, as I've confirmed with a mod over at CurseForge, would allow this project to be restored and get updates through the Curse/Twitch client.

However, the one requirement for doing so is to change the name of the project, once again, to something distinguishing it from the original, as to not cause confusion.

Bear in mind that this would most likely break your settings etc. when transitioning to the new name. However the planned 6.22 release would be a great time to do so because it will most likely transition into using global profiles instead of character specific ones.
With that in mind I believe that I could create a pre-release that could move over any profiles you want over to the new system and name. But I haven't confirmed if this is doable or not.

I don't really mind one way or the other if the project stays just on GitHub or is on CurseForge, but others might, so I would appreciate any input on this before deciding on anything.

**Comment by hollo6** [comment]
I don't care where I update the addon from at all, but I spent a lot of time setting it up, so if automated settings transfer is not doable, I vote for staying here keeping the name.

**Comment by ja0b** [comment]
Booyah! that's good news, I think is better to have the addon on curse as the majority of ppl uses it but the code and issue tracker here.

The config of this addon is not painful and I think the goal get more ppl to use it.

Other solution for this could be to change the PowerShell you have there?

Good name for the addon.... 
 - Phoenix Plates
 - Sleek Plates 😉 
 - Neat Plates 😉 
 - Trim Plates 😉

**Comment by AHigi** [comment]
@Luxocracy I've transferred the ownership of the project on curseforge to you... since my life is pretty hectic nowadays, I can't spare any time just yet for the addon unfotunately... You can update it as you see fit now.. Cheers! Keep up the work of the gods :)

**Comment by Luxocracy** [comment]
@ja0b The powershell script is definitely an option, but it's not really as painless as I would like.

I was thinking I could just define the new files in the pre-release version I was talking about and convert it at that point. But it doesn't work that way and I'm not quite sure why I thought that it did when I was typing it out.

Another option I'm considering is to have you load both TPC and the new plate addon and have it ask if you would want to transfer settings over from the TPC addon at that point since the variables should be accessible by the new plate addon as long as TPC gets loaded . After doing this you could remove TPC without having to worry about your settings.

I would have really preferred it be doable without weird workarounds like these. But I will have to look into what exactly is required for the game to load these variables. Because it might be as simple as just including the _.toc_ files for the main addon and the hub for them to load and be accessible.

**Comment by hollo6** [comment]
I could live with any method of settings transfer, even installing the new addon and ask it to read the settings from the old. But since you now have the ownership, it doesn't seem necessary to rename the addon, right?

**Comment by Luxocracy** [comment]
@hollo6 Ahigi simply passed on the ownership of the previously existing TPC project as he was the one who set that up. It still needs to be renamed before that project would be approved by the moderators of Curse.

**Comment by Diablolock** [comment]
Yea man, moving it to curse is definately the best to do. TPC will have a greater reach to the community on curse that´s for sure.

**Comment by Luxocracy** [comment]
The project is now back on curse under the new name [Neat Plates](https://wow.curseforge.com/projects/neat-plates).

Hopefully it will remain that way :)

**Comment by yishuangfrank** [comment]
Great!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by yishuangfrank** [comment]
It's OK，I found this on curse：

“If you are transitioning from 'Tidy Plates Continued' to 'Neat Plates' and wish to keep your settings. You can do this by loading both TPC and Neat Plates, at that point Neat Plates should show a prompt asking if you wish to import these settings.”
