### ISSUE TITLE
Blizzard default plates not going away

### ISSUE THREAD

**Issue by Greenvase** [Luxocracy/NeatPlates#100]
![bars](https://user-images.githubusercontent.com/53133227/61586678-5f841f00-ab48-11e9-86bd-55f965692641.PNG)

As you can see, the default blizzard plates aren't being replaced by the addon, the addon plates are simple being applied over them.  This is a constant issue. 
I have attached screenshots of my entire addon list, maybe this will help?

![addons 1](https://user-images.githubusercontent.com/53133227/61586740-3dd76780-ab49-11e9-8eda-d224c3f29f49.PNG)
![addons 2](https://user-images.githubusercontent.com/53133227/61586741-3dd76780-ab49-11e9-946b-233fc35c641a.PNG)
![addons 3](https://user-images.githubusercontent.com/53133227/61586742-3dd76780-ab49-11e9-900d-225050909ace.PNG)
![Addons 4](https://user-images.githubusercontent.com/53133227/61586743-3dd76780-ab49-11e9-87a2-6c7e2b20a2a7.PNG)
![addons 5](https://user-images.githubusercontent.com/53133227/61586744-3e6ffe00-ab49-11e9-865c-32ada54b9eed.PNG)
![addons 6](https://user-images.githubusercontent.com/53133227/61586745-3e6ffe00-ab49-11e9-8efd-44aae78021a9.PNG)
![addons 7](https://user-images.githubusercontent.com/53133227/61586746-3e6ffe00-ab49-11e9-901c-f35eff2406c0.PNG)
![addons 8](https://user-images.githubusercontent.com/53133227/61586747-3e6ffe00-ab49-11e9-871d-ef5c447d485d.PNG)
![addons 9](https://user-images.githubusercontent.com/53133227/61586748-3f089480-ab49-11e9-9b5f-fdeb2a42f2c1.PNG)
![addons 10](https://user-images.githubusercontent.com/53133227/61586749-3f089480-ab49-11e9-905d-11427be6c5b9.PNG)
![addons 11](https://user-images.githubusercontent.com/53133227/61586750-3f089480-ab49-11e9-8bcc-2f46b863aeaa.PNG)

**Comment by Luxocracy** [comment]
Remove/turn off Tidyplates. Using two nameplate add-ons is never a good idea.

**Comment by Greenvase** [comment]
Uninstalled and deleted the saved data for tidyplates. Same issue is constant. Is there any other data I can send you to help assess the problem?
![bars 2](https://user-images.githubusercontent.com/53133227/61592801-fcc17080-aba5-11e9-9aad-7c8f3f298f76.PNG)

**Comment by Luxocracy** [comment]
I'm fairly sure this is an issue with another addon modifying/adding nameplates, because those are not the default blizzard plates, I'm just not sure which addon is doing it.

So my suggestion would be to disable all addons, leaving Neatplates enabled, and then re-enabling them one by one. Even just checking if the issue still persists with just Neatplates enabled might be a good idea to rule out there being any kind of remnants from removed addons remaining in your interface folder.

**Comment by Greenvase** [comment]
Seems like it was an issue with an Spartan UI module. The fix was just reducing the size of their name plates to 0 lmao.
Thanks for all your help
