### ISSUE TITLE
About highlighting options.

### ISSUE THREAD

**Issue by yishuangfrank** [Luxocracy/NeatPlates#101]
I use the newest version for days， and I am still not used to the Arrows.
Could you revert the removal of Border please?
And we can customize the width and color of the border.

**Comment by Luxocracy** [comment]
I haven't removed border, I just renamed it to 'Theme Default' as that is what it essentially was. And I'm assuming you mean adjusting the thickness of the border when you say width. Which pretty much isn't doable right now as the 'borders' are just a texture overlay.

**Comment by yishuangfrank** [comment]
I will check "Theme Default" later.
And “border width” is just the mean you said.
When the monsters are great many，we can't identify which nameplate the arrow belongs to. And border is more obvious，especially the thick one.

**Comment by Nukme** [comment]
Speaking of which, is it convenient to add border/shades for the artwork of arrows? It feels kinda thin to me.

**Comment by Luxocracy** [comment]
I altered the arrow textures slightly in the latest release by adding a thin black border and attempted to make them look less _flat_, which hopefully should also help with them looking a bit off.

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
