### ISSUE TITLE
Auras without duration time don't show stacks

### ISSUE THREAD

**Issue by Nukme** [Luxocracy/NeatPlates#102]
version: 6.23.7b

bug:  Auras without duration time do not show stacks

Noticed this last night during raid after updating NP to 6.23.7b. The stackable buffs on bosses (Blackwater Behemoth/ The Queen's Court) show up without stacks number.

Test & confirm this with a frost DK talented with Cold Heart.

**Comment by Luxocracy** [comment]
This would be due to how I fixed Stacks appearing underneath the cooldown spiral by attaching it to the same frame as the cooldown. Which apparently doesn't work because if there is no duration that frame is hidden...

Should be an easy fix though.
