### ISSUE TITLE
Bug on Warlock Absolute Corruption

### ISSUE THREAD

**Issue by Diablolock** [Luxocracy/NeatPlates#104]
Hi!

WOuld like to report a bug com the timer of corruption when AC is selected. (the talent that makes Corruption permanent on target)

Sometimes it replicates que timer on Agony although it shoulnd't have any timer since it's permament. I noticed this happen specialy when the debuff of (https://www.wowhead.com/item=168905/shiver-venom-relic&bonus=4798:1487) on is target.

Screenshot with the AC talent on: https://imgur.com/a/DVtjO2k

**Comment by Luxocracy** [comment]
This should be fixed as of 6.23.8a.

I could have sworn I've fixed this issue once before, so I am surprised it is back again. Hopefully it stays fixed this time around.

**Comment by Diablolock** [comment]
Thx Luxo! Seems to be fixed now!
