### ISSUE TITLE
Show who interrupted cast not working

### ISSUE THREAD

**Issue by jazzman1234** [Luxocracy/NeatPlates#105]
The option "Show interrupted cast" is marked but it isn't working; only shows the "interrupted" message but not the name of interruptor.

**Comment by Yasinahh** [comment]
Yes Same problem here.

This option is nice when its work

**Comment by Luxocracy** [comment]
I apparently forgot to capitalize one of the variables for this when I was moving stuff around, which affected this. Should be fixed later today.
