### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by natelaunchbury** [Luxocracy/NeatPlates#107]
(I know this isn't what issues are for)

Really cool project, I was always a fan of TidyPlates so I'm really excited to see you're continuing to keep it updated! 

I'd like to test/set up this addon for classic, do you have a recommendation on the best way to do so? I imagine it won't work on 1.12 private servers?

**Comment by Luxocracy** [comment]
No, it wouldn't work on a private server sadly.

If all you want to do is set it up before Classic launch, I believe the classic version([6.23.10-Classic](https://www.curseforge.com/wow/addons/neat-plates/files/2762369)) should still work on retail as it is basically just a stripped down version of the addon. 

So you could set up a profile there and then move over your retail _SavedVariables_ folder to the classic version and you should be able to select that profile when you can can log into Classic.

**Comment by natelaunchbury** [comment]
Thanks for the info. I've heard that there's not threat API in classic, will Reaction by Thread work for enemy nameplates?

**Comment by Luxocracy** [comment]
Not currently no. But hopefully someone will make a threat lib, just like in vanilla, that estimates threat that can be incorporated so this works again later down the road in Classic.
