### ISSUE TITLE
Range Indicator Coloress

### ISSUE THREAD

**Issue by Diablolock** [Luxocracy/NeatPlates#108]
Hi Lux.

After the most recent update the range indicator is coloress no matter what.

Would you check plz?

Thx in advance.

/e

It also is not showing sometimes. It will show after a /rl and then it's gone somehow.

**Comment by Luxocracy** [comment]
This should be working correctly again.

**Comment by Diablolock** [comment]
Seems to be fixed now. Thx Lux!
