### ISSUE TITLE
selecting "target" in Healthbar frame causing several bugs

### ISSUE THREAD

**Issue by zergpvz141** [Luxocracy/NeatPlates#110]
These bugs only appears when I am in combat and after I select "target" in Healthbar frame -> enemy information text. 
1. Enemy's target does not show on enemy healthbar. 
2. Enemy's castbar disappears . 
3. It seems like the target appearance only works with the first enemy I hit (ie. cause me in combat) When I select on others, the target appearance disappear, but when I select the first enemy, it cames back.

If I am out of combat or choose "none" in Healthbar frame -> enemy information text, these bugs all disappear.

I disable all the addons except NeatPlates.
I updated to the current newest version (8.2.0.3)
There are two kinds of lua errrors:

=============================================================

Message: Interface\AddOns\NeatPlatesHub\functions\Text.lua:161: attempt to concatenate global 'unitid' (a nil value)
Time: Sat Aug 24 06:43:34 2019
Count: 59
Stack: Interface\AddOns\NeatPlatesHub\functions\Text.lua:161: attempt to concatenate global 'unitid' (a nil value)
Interface\AddOns\NeatPlatesHub\functions\Text.lua:161: in function <Interface\AddOns\NeatPlatesHub\functions\Text.lua:159>
(tail call): ?
(tail call): ?
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:856: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:843>
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:939: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:891>
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1195: in function `?'
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1103: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1102>

Locals: unit = <table> {
 levelcolorBlue = 0
 healthmax = 269347
 interruptLogged = false
 levelcolorGreen = 0.820000
 level = 120
 red = 0.999998
 isTapped = false
 isCasting = true
 spellInterruptible = false
 isMarked = false
 spellIsShielded = true
 isInCombat = true
 threatSituation = "HIGH"
 health = 267799
 blue = 0
 reaction = "HOSTILE"
 green = 0
 levelcolorRed = 1
 threatValue = 3
 interrupted = false
 style = "Default"
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = "target"
(*temporary) = "attempt to concatenate global 'unitid' (a nil value)"

==============================================================

Message: Interface\AddOns\NeatPlatesHub\functions\Text.lua:161: attempt to concatenate global 'unitid' (a nil value)
Time: Sat Aug 24 06:43:19 2019
Count: 54
Stack: Interface\AddOns\NeatPlatesHub\functions\Text.lua:161: attempt to concatenate global 'unitid' (a nil value)
Interface\AddOns\NeatPlatesHub\functions\Text.lua:161: in function <Interface\AddOns\NeatPlatesHub\functions\Text.lua:159>
(tail call): ?
(tail call): ?
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:856: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:843>
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1031: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1020>
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1207: in function `?'
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1103: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1102>

Locals: unit = <table> {
 guid = "Creature-0-3913-1718-12351-150541-0000611235"
 isMouseover = false
 class = ""
 interruptLogged = false
 rawName = "赞齐尔奴隶主"
 threatSituation = "HIGH"
 red = 0.999998
 isInCombat = true
 unitid = "nameplate2"
 isMini = false
 interrupted = false
 pvpname = "赞齐尔奴隶主"
 levelcolorBlue = 0
 isBoss = false
 isFocus = false
 healthmax = 359128
 isTarget = true
 levelcolorGreen = 0.820000
 isTapped = false
 type = "NPC"
 blue = 0
 spellInterruptible = false
 isCasting = false
 spellIsShielded = true
 style = "Default"
 level = 120
 name = "赞齐尔奴隶主"
 levelcolorRed = 1
 reaction = "HOSTILE"
 green = 0
 isMarked = false
 threatValue = 3
 isDangerous = false
 health = 116626
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = "target"
(*temporary) = "attempt to concatenate global 'unitid' (a nil value)"

==============================================================

the name "赞齐尔奴隶主" is Zanj'ir Slaver. A mob in Nazjatar I use it to test these bugs.

**Comment by zergpvz141** [comment]
ps: When I try other name plates such as plater, these issues don't show up. But I really like NeatPlates, so I hope these can be fixed.

**Comment by Luxocracy** [comment]
This should be fixed.

**Comment by zergpvz141** [comment]
It works now, Thank you and keep up the good work!
