### ISSUE TITLE
Classic - Gouge

### ISSUE THREAD

**Issue by fynerboi** [Luxocracy/NeatPlates#111]
The issue is, Gouge CCs the target for 5,5sec (when talented) but the addon shows it as 50sec.

**Comment by Luxocracy** [comment]
What version of the addon are you on? Because this is something that I'm pretty sure I fixed during the stresstest. And the latest release even uses an external library to get aura durations, which also should support the talent.

**Comment by fynerboi** [comment]
Oh yeah, my bad. I'm sorry, I was using an older version. Gonna try the latest one when I'll have some time ^^
Thank you.
