### ISSUE TITLE
Wrong debuff time for Gouge (Rogues) [wowclassic]

### ISSUE THREAD

**Issue by jorgefalcao** [Luxocracy/NeatPlates#113]
**Description:** The debuff timer for [Gouge](https://wowwiki.fandom.com/wiki/Gouge) showing above the enemy's health bar is not accurate. This situation has been noticed after adding at least **one point** to the talent [improved gouge](https://wowwiki.fandom.com/wiki/Improved_Gouge).

**Version:** wowclassic

**Screenshoot:**
![Wrong debuff timer for Gouge](https://i.imgur.com/qenrKyc.jpg)

**Comment by jorgefalcao** [comment]
It seems this **has been fixed** already. I got the wrong version altough it said it was the newest for that addon. You can **delete** this issue.

**Comment by Luxocracy** [comment]
Just out of curiosty, where did you download the addon from? Because you are the 2nd or 3rd person commenting on this event though this was fixed several weeks ago.
