### ISSUE TITLE
Not available on Twitch search under Classic

### ISSUE THREAD

**Issue by mrswadge** [Luxocracy/NeatPlates#114]
I can't find NeatPlates in the "Get More Addons" tab when Classic is selected as the game. It does not appear to be in the classic library.

I found a workaround where I locate NeatPlates under retail (BFA), but then switch the dropdown to Classic. It then allows me to install it.

**Comment by Luxocracy** [comment]
I have noticed this and I've contacted Curse support about it, who told me to contact Twitch support. And I've yet to hear anything from Twitch support so far, but I am looking into it.

**Comment by Luxocracy** [comment]
This seems to finally have been resolved and it should now appear within the twitch client.
