### ISSUE TITLE
Threat highliting and scale.

### ISSUE THREAD

**Issue by WorthyPenguin** [Luxocracy/NeatPlates#115]
Hello! I really appreciate this addon, good job, it's even better than I expected.

The only issue I have is that either that's a bug, or I don't understand something. While browsing settings I configured some scales based on threat and later some highlights. I then noticed that my changes and settings work on "red" mobs, which are aggressive ones, but do not work on "yellow" mobs, neutral ones. What I mean is that **when I'm fighting an aggressive red mob - it nameplate is highlighted and enlarged a little bit, but when I taunt and fight yellow neutral mob - it's nameplate stays the same.** I added some screenshots of those nameplates out of combat and during combat, as well as my settings for those categories.

Thank you very much.

![Screenshot (6)](https://user-images.githubusercontent.com/54903317/64271851-6a4f1380-cf3e-11e9-8688-51a7bf8e58e5.png)
![Screenshot (7)](https://user-images.githubusercontent.com/54903317/64271852-6ae7aa00-cf3e-11e9-9596-060b5a2e0123.png)
![Screenshot (8)](https://user-images.githubusercontent.com/54903317/64271855-6ae7aa00-cf3e-11e9-9dd2-c4d626cd029b.png)
![Screenshot (9)](https://user-images.githubusercontent.com/54903317/64271856-6ae7aa00-cf3e-11e9-8a0e-26150a0e56de.png)
![Screenshot (11)](https://user-images.githubusercontent.com/54903317/64271857-6ae7aa00-cf3e-11e9-844a-3980ec70d60f.png)
![Screenshot (12)](https://user-images.githubusercontent.com/54903317/64271859-6b804080-cf3e-11e9-8ff4-3ea671103a2a.png)

**Comment by Luxocracy** [comment]
Pretty much anything that has to do with threat isn't working correctly in the Classic version due to the client not having a built in threat API. There is a branch of the addon that has a Threat Lib API added to it, but I haven't had time to test it properly in Classic yet. So it is something I will fix in the future.

**Comment by Luxocracy** [comment]
With the addition of a working Threat Lib, this should now work properly.
