### ISSUE TITLE
Wont work on certain characters

### ISSUE THREAD

**Issue by ZenNugget** [Luxocracy/NeatPlates#116]
For some reason it works on some of my characters but others it will not work.
Like it work for my night elf hunter and tauren shaman but not on my undead rouge for some reason.
i have relaoded, disable it and redownload but nothing work i cant get it to work on my rouge for some reason and need help.

**Comment by Luxocracy** [comment]
Have you enabled nameplates in the blizzard interface options? This is usually the issue when people have this issue.

**Comment by ZenNugget** [comment]
i disbable everything on nameplates and re enable  and now it works!
