### ISSUE TITLE
Color.lua:466: Usage: UnitIsInMyGuild("name")

### ISSUE THREAD

**Issue by DogmaTX** [Luxocracy/NeatPlates#117]
Message: Interface\AddOns\NeatPlatesHub\functions\Color.lua:466: Usage: UnitIsInMyGuild("name")
Time: Sat Sep  7 11:06:19 2019
Count: 16
Stack: Interface\AddOns\NeatPlatesHub\functions\Color.lua:466: Usage: UnitIsInMyGuild("name")
[C]: ?
Interface\AddOns\NeatPlatesHub\functions\Color.lua:466: in function `func'
Interface\AddOns\NeatPlatesHub\functions\Color.lua:629: in function `SetNameColor'
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:779: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:770>
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:843: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:824>
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:372: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:348>
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:493: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:489>
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1053: in function `?'
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1088: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1087>

Locals: (*temporary) = nil

**Comment by Luxocracy** [comment]
I don't seem to be able to reproduce this issues on my end, is there anything in particular that causes it to happen? And is this happening on the Classic or Retail version of the game?

**Comment by DogmaTX** [comment]
[_1.13.2.13-Classic_](https://drive.google.com/file/d/1V8xUGoWGw4UZlgoVzXwE7-VZ7-D6IzBV/view)

[_1.13.2.12-Classic_](https://drive.google.com/file/d/1YFZ88pXqY7FMi6WB5BKZijRAJ-iKT46c/view)

Version "1.13.2.12-Classic" works without error.

**Comment by ruebeus** [comment]
I've been getting the exact same error since updating yesterday. No idea what is triggering it. Playing current BFA patch.

**Comment by ruebeus** [comment]
Message: Interface\AddOns\NeatPlatesHub\functions\Color.lua:450: Usage: UnitIsInMyGuild("name")
Time: Sun Sep  8 11:56:45 2019
Count: 5
Stack: Interface\AddOns\NeatPlatesHub\functions\Color.lua:450: Usage: UnitIsInMyGuild("name")
[C]: ?
[C]: ?
Interface\AddOns\NeatPlatesHub\functions\Color.lua:450: in function <Interface\AddOns\NeatPlatesHub\functions\Color.lua:449>
(tail call): ?
Interface\AddOns\NeatPlatesHub\functions\Color.lua:613: in function `SetNameColor'
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:799: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:790>
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:863: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:844>
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:374: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:349>
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:496: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:492>
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1069: in function `?'
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1104: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1103>

**Comment by Luxocracy** [comment]
Managed to figure out what was going on, this shouldn't happen anymore as of the latest release.

**Comment by DogmaTX** [comment]
The error disappeared in new versions, thanks a lot.
