### ISSUE TITLE
Server disconect while in combat causes addon to break upon restart

### ISSUE THREAD

**Issue by dotblank** [Luxocracy/NeatPlates#118]
I was on my warlock and everything was peachy untill I got DC'd by blizzard from the recent DDoS.

Addon settings and menu commands seem to work but it doesn't actually display the name plates.

**Comment by Luxocracy** [comment]
Are you sure nameplates are enabled in the blizzard interface options? Because I've never heard of an addon suddenly not working after getting DC'd.

**Comment by dotblank** [comment]
I was just DC'd again, I was able to use the shift click on the reset configuration and that did the trick

I'll let you know if it breaks again when I re-log

**Comment by dotblank** [comment]
Hmm, not reproducible, it worked fine after the DC
