### ISSUE TITLE
Nameplates resetting after leaving combat.

### ISSUE THREAD

**Issue by TimpAofc** [Luxocracy/NeatPlates#120]
I'm having issues with nameplates getting turned off every time I leave combat. (Have to manually turn it on by pressing V again)
Doesn't affect other players or NPC's, but it affects my pet.
No automation on either Enemy or Friendly nameplates.

Before Combat:
![before combat](https://user-images.githubusercontent.com/55051941/64488098-f796ae80-d243-11e9-8ec2-8b47b3584c05.png)

During Combat:
![during combat](https://user-images.githubusercontent.com/55051941/64488099-f796ae80-d243-11e9-9591-2efc45cb165d.png)

After Combat:
![after combat](https://user-images.githubusercontent.com/55051941/64488097-f6fe1800-d243-11e9-9c5d-f099b9b03b9b.png)

After pressing V:
![after v](https://user-images.githubusercontent.com/55051941/64488131-67a53480-d244-11e9-8a31-b2b223166bd3.png)

**Comment by Luxocracy** [comment]
The only thing that would do that is the Nameplate automation. Make sure it isn't enabled by changing to something and then changing it back to _No Automation_.

**Comment by TimpAofc** [comment]
Leatrix Plus was interfering.
