### ISSUE TITLE
Orange Highlighitng ? How do i get rid of it.

### ISSUE THREAD

**Issue by Andoido1** [Luxocracy/NeatPlates#123]
So.. When ever i pulled agro  using NEON - it had the Red spikes.

now when i AOE, i see tons of Orange and i hate it. how do i turn it off? with this new update

**Comment by Luxocracy** [comment]
Well orange means you are about to pull aggro, but to disable just the orange you would have to change the _Transition color_ to the same as the _Safe Color_. Or you could disable threat warning color all together by changing the _Enemy Bar Color_ to something other than threat.

**Comment by Andoido1** [comment]
willgive it a shot - reverted to the previous release to get rid of it, but ill udpate and try ty.

**Comment by Homeguard** [comment]
As far as I remember the threat bar icon would only activate when in a group, and be disabled while solo'ing, which makes sense as you always have threat when solo'ing unless you are a pet class.
Since the latest update the threat bar is always active, even when solo.
