### ISSUE TITLE
Threat bar always active, even when solo since the latest update (.17)

### ISSUE THREAD

**Issue by Homeguard** [Luxocracy/NeatPlates#124]
Since .17 at least (have not tried .16) the threat bar is always active.
As far as I remember the threat bar icon would only activate when in a group, and be disabled while solo'ing, which makes sense as you always have threat when solo'ing unless you are a pet class.
Since the latest update the threat bar is always active, even when solo.

**Comment by Luxocracy** [comment]
I'll have to confirm how it works in the retail client, as that would be the intended way, as I don't remember if this is how it is supposed to be. It doesn't feel like it should however and it might have something to do with the threat lib working slightly differently than the Blizzard threat API

**Comment by Homeguard** [comment]
Just tested .16 and it does not show the threat bar alert when solo.
Seems to be limited to a change in .17

**Comment by Luxocracy** [comment]
This behavior is consistent with retail so I'm not gonna consider this an active bug, but rather one that has been fixed. 
I also see this behavior in the .16 version, with the difference being that it is enough to have a mob target you in the .17 version where as the .16 version requires you to do at least some damage.

**Comment by Homeguard** [comment]
Just to be sure we are talking about the same thing.
version 17: [https://imgur.com/a/NEr6oTv](url)
version 16: [https://imgur.com/a/TCZQZHF](url)

**Comment by Luxocracy** [comment]
The .16 version behaves as I described. The latest version that would have behaved the way you describe would have been .13, as that is the latest version without the threat lib implemented.

**Comment by Homeguard** [comment]
Not sure what to tell you. I am actively using .16 right now where this is not happening.
As soon as I group up with someone the threat alert starts showing, and when I leave group the alert does not appear anymore.
In .17 the threat alert always shows regardless of party status.

**Comment by Homeguard** [comment]
No threat alert on the nameplate unless in group on .16...

**Comment by Luxocracy** [comment]
Ok so I've figured out why our experiences are different. The threat lib turns off if you are solo, as you are experiencing. But I'm currently playing a hunter in Classic, and even without having a pet, it doesn't turn off when I'm solo.

**Comment by Luxocracy** [comment]
Because the threat lib defaults to being disabled when not in a party/have a pet that is now also the default state of the nameplates. And I've instead added an option to display threat while solo as in the retail version of the addon.

**Comment by Homeguard** [comment]
Thank you
