### ISSUE TITLE
Nameplate Threat/aggro highlighting inverted past 1.13.2.6 version (classic)

### ISSUE THREAD

**Issue by TobalJackson** [Luxocracy/NeatPlates#128]
Hello,

Beyond version 1.13.2.6 the aggro status (red border/tick marks around enemy nameplates) has been inverted.  Up to this version, the nameplate highlighting (red ticks) indicated when you had aggro, and monsters not targeting you did not have the ticks/red highlighting.

Beyond this version (confirmed in 1.13.2.13 or .16, can't remember which) this highlighting only applies when monsters are NOT aggroed/targeting you, making battles in a party very confusing.

**Comment by Luxocracy** [comment]
It doesn't make sense that it would work in .12 but not in .13. Beyond this it could make sense as I implemented a threat lib and that might be reporting the threat differently for some classes. But I highly doubt that is it.

But just for my sanity, because I can't replicate this, you aren't tanks are you?
Because it being blue while having aggro is intended behavior for tanks if your threat mode is either set to _Auto_ or _Tank_.
The auto mode counts you as a tank for things like bear form for druids, righteous fury for paladins, and if you are in defensive stance or have a shield for warriors.

**Comment by dennybrah** [comment]
> 
> 
> It doesn't make sense that it would work in .12 but not in .13. Beyond this it could make sense as I implemented a threat lib and that might be reporting the threat differently for some classes. But I highly doubt that is it.
> 
> But just for my sanity, because I can't replicate this, you aren't tanks are you? And your _Threat Mode_ under _Threat & Highlighting_ isn't set to _Tank_?
> Because it being blue while having aggro is intended behavior for tanks if your threat mode is either set to _Auto_ or _Tank_.
> The auto mode counts you as a tank for things like bear form for druids, righteous fury for paladins, and if you are in defensive stance or have a shield for warriors.

yes, I am a tank, druid tank to be exact.

for a while, if i HAD aggro, it was red, which I am use to and preferred, being blue when I have aggro is throwing me off. How would I switch it back to red = aggro and blue = not aggro?

**Comment by Luxocracy** [comment]
In your profile settings it's under _Threat & Highlighting > Threat Mode_, and just set that to _DPS/Healer_. And it will be red when you have aggro and blue when not.

**Comment by TobalJackson** [comment]
I've never changed this setting though I believe I've seen it set to Auto. I also play a druid, however when I was testing this with the latest (1.13.2.22) I'm almost certain the behavior persisted while in cat form.  However I won't be able to play for another 6 hours so I will test this and this mode setting then.

**Comment by TobalJackson** [comment]
Well it looks like I was doing my testing in bear form not realizing what was happening. Latest (24) version seems to work just as intended! Sorry for the confusion and thank you for such a great addon!
