### ISSUE TITLE
Friendly NPC vendor text

### ISSUE THREAD

**Issue by CrustyCode** [Luxocracy/NeatPlates#132]
I'm not seeing any options to show for example: "\<Cloth Armor Merchant\>, \<Tailoring Supplies\>, etc" underneath friendly NPCs. Did I miss this option, or can this be implemented please?

**Comment by Luxocracy** [comment]
In healthbar mode it doesn't exist, I've been considering adding it along side guild names. But it does exist in Headline/text only mode under _Enemy/Friendly Headline Subtext_.

Usually you would run with _All NPCs_ disabled for friendly units and then enabling _Active/Damaged Units_ if you were interested in displaying that information.

**Comment by CrustyCode** [comment]
None of the settings under "Friendly Headline Subtext" seem to be showing the vendor text I'm looking for unfortunately. 

I want to avoid having to toggle because the default nametag text is super pixelated and the goal is to set and forget.

**Comment by Luxocracy** [comment]
It's called _NPC Role_

**Comment by CrustyCode** [comment]
With NPC Role enabled, it says "Friendly" under these vendor NPCs.

**Comment by Luxocracy** [comment]
That is quite odd, none of the options should display what their reaction is.
Any chance you could send me a screenshot? And maybe I can tell what is going from that.

**Comment by CrustyCode** [comment]
[https://i.imgur.com/WHJnXxG.jpg](https://i.imgur.com/WHJnXxG.jpg)

**Comment by CrustyCode** [comment]
[https://i.imgur.com/cVFPiDb.jpg](https://i.imgur.com/cVFPiDb.jpg)

**Comment by CrustyCode** [comment]
Just double checked that I am running the latest version: 1.13.2.24.

**Comment by Luxocracy** [comment]
Ok, so I think I've figured out what is going on. I forgot myself how this works, but it grabs the NPC role information from your tooltip, the second row more specifically. So I am assuming your tooltip addon is changing the order of these items and causing it to mess up.

I'll have to look into if there's some more reliable way to grab it but that is what's going on right now.

**Comment by CrustyCode** [comment]
Ah, that makes sense. I'm struggling to find the offender though, I thought it was TinyTooltip, but apparently not.

AddOn list:
`!MoncaiCompare
AdvancedInterfaceOptions
ArkInventoryClassic
ArkInventoryClassicConfig
ArkInventoryClassicRules
ArkInventoryClassicRules_Example
ArkInventoryClassicSearch
Atlas
AtlasLootClassic
AtlasLootClassic_Collections
AtlasLootClassic_Crafting
AtlasLootClassic_DungeonsAndRaids
AtlasLootClassic_Factions
AtlasLootClassic_Options
AtlasLootClassic_PvP
Atlas_ClassicWoW
Auctionator
ClassicSpellActivations
ClassicThreatMeter
DingPics
Dominos
Dominos_Cast
Dominos_Config
Dominos_Encounter
Dominos_Progress
Dominos_Roll
FiveSecondRule
FriendsInfo
Leatrix_Maps
Leatrix_Plus
LunaUnitFrames
MonkeyBuddy
MonkeyLibrary
MonkeyQuest
MonkeyQuestLog
NeatPlates
NeatPlatesHub
NeatPlatesWidgets
NeatPlates_Alvara
NeatPlates_BlizzardPlates
NeatPlates_ClassicPlates
NeatPlates_Graphite
NeatPlates_Grey
NeatPlates_Neon
NeatPlates_Quatre
NeatPlates_Renaitre
NeatPlates_Roth
NeatPlates_Simple
NeatPlates_Slim_Horizontal
NeatPlates_Slim_Vertical
OmniCC
OmniCC_Config
Prat-3.0
Prat-3.0_Libraries
QuestLogEx
Questie
RealMobHealth
Recount
RingMenu
WeakAuras
WeakAurasModelPaths
WeakAurasOptions
WeaponSwingTimer
XpCounter
addonlist.txt
`

**Comment by CrustyCode** [comment]
All AddOns off, my tooltip looks like this: [https://i.imgur.com/QX43cW1.png](https://i.imgur.com/QX43cW1.png). Friendly in the second row.

**Comment by Luxocracy** [comment]
Are you color blind by chance? Because I'm able to replicate this if I enable the "colorblindMode" CVar.

**Comment by CrustyCode** [comment]
I am! It's adding lines to the tooltip in colourblind mode, just checked. :)

**Comment by Luxocracy** [comment]
Well I should be able to add an exception for when this CVar is enabled so this should work properly for you in the next release.

**Comment by CrustyCode** [comment]
Awesome, thank you.
