### ISSUE TITLE
UI Error

### ISSUE THREAD

**Issue by Bredn** [Luxocracy/NeatPlates#133]
When i hit Darkeye Bonecaster in Trisfal = Agamand Mills with my Priest long range skill i got this error . Because mob have frostbolt cast .
Message: Interface\AddOns\NeatPlatesHub\functions\Alpha.lua:31: attempt to compare number with nil
Time: Sun Sep 15 01:20:06 2019
Count: 27
Stack: Interface\AddOns\NeatPlatesHub\functions\Alpha.lua:31: attempt to compare number with nil
Interface\AddOns\NeatPlatesHub\functions\Alpha.lua:31: in function <Interface\AddOns\NeatPlatesHub\functions\Alpha.lua:29>
(tail call): ?
Interface\AddOns\NeatPlatesHub\functions\Alpha.lua:173: in function `SetAlpha'
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:831: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:828>
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:957: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:904>
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1338: in function `?'
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1120: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1119>

Locals: unit = <table> {
 spellInterruptible = true
 isCasting = true
 interrupted = false
 interruptLogged = false
}
(*temporary) = nil
(*temporary) = true
(*temporary) = "attempt to compare number with nil"
InCombatLockdown = <function> defined =[C]:-1
LocalVars = <table> {
 TextShowOnlyOnActive = false
 WidgetAuraSort = 1
 TextShowOnlyOnTargets = false
 ColorFriendlyBarMode = 1
 WidgetBuffEnrage = false
 UnitSpotlightLookup = <table> {
 }
 EnableOffTankHighlight = false
 BorderBuffEnrage = 1
 OpacityFilterNonElite = false
 Theme = "Blizzard"
 SpellCastEnableFriendly = false
 WidgetPandemic = false
 OpacityFilterPlayers = false
 StyleEnemyBarsInstanceMode = false
 ColorSchoolHoly = <table> {
 }
 FriendlyNameColorMode = "Default"
 HighlightMouseoverScale = <table> {
 }
 ColorTarget = <table> {
 }
 ColorEnemyStatusTextMode = 1
 WidgetRangeMode = 1
 OpacityNonTarget = 0.500000
 EmphasizedSlots = 1
 FilterScaleLock = false
 StyleEnemyBarsOnElite = true
 StyleEnemyBarsNoTotem = false
 IntCastWhoEnable = true
 OpacityFilterFriendlyNPC = false
 UnitSpotlightColor = <table> {
 }
 StyleEnemyBarsClickThrough = false
 StyleFriendlyBarsClickThrough = false
 StatusTextRight = 7
 StyleFriendlyBarsOnPlayers = true
 FrameVerticalPosition = 0.700000
 HighlightFocustMode = 1
 CustomColorList = ""
 WidgetEnableExternal = true
 ColorSchoolFrost = <table> {
 }
 WidgetQuestIcon = false
 StatusTextCenterColor = true
 ColorFriendlyNameMode = 1
 TextColorGuildMember = <table> {
 }
 StyleEnemyMode = 1
 HighlightTargetMode = 1
 HeadlineFriendlySubtext = "RoleGuildLevel"
 StyleFriendlyBarsNoTotem = false
 WidgetBuffPurgeable = false
 WidgetThreatIndicator = true
 ThreatSoloEnable = false
 TextColorNeutral = <table> {
 }
 ScaleFunctionMode = "ByThreat"
 ColorEnemyNameMode = 1
 StyleFriendlyBarsInstanceMode = false
 ColorFriendlyNPC = <table> {
 }
 EnemyBarColorMode = "ByReaction"
 WidgetAuraTrackMagic = true
 ScaleMouseoverSpotlight = false
 TextColorFriendlyPlayer = <table> {
 }
 OpacityFilterMini = false
 HeadlineEnemyColor = 4
 OpacityFullNoTarget = true
 ColorPartyAggro = <table> {
 }
 StatusTextLeftColor = true
 UnitSpotlightBarEnable = true
 HeadlineFriendlyColor = 4
 ColorHighHealth = <table> {
 }
 ColorSchoolNature = <table> {
 }
 StyleHeadlineMiniMobs = false
 StyleFriendlyBarsNoMinions = false
 SafeColorSolo = false
 FriendlyStatusTextMode = "HealthFunctionExact"
 HideAuraDuration = false
 ColorCastBySchool = true
 UnitSpotlightOpacity = 1
 StyleFriendlyBarsOnElite = false
 WidgetAbsorbIndicator = false
 ColorHealthBarMode = 3
 CastBarWidth = 1
 StyleFriendlyBarsOnActive = true
 EmphasizedAuraList = ""
 WidgetAuraTrackCurse = true
 HeadlineEnemySubtext = "RoleGuildLevel"
 FriendlyBarColorMode = "ByReaction"
 ColorRangeFar = <table> {
 }
 StyleHeadlineOutOfCombat = false
 AltShortening = false
 ColorThreatTransition = <table> {
 }
 UseGlobalSet = false
 WidgetComboPoints = true
 IntCastEnable = true
 TextColorPartyMember = <table> {
 }
 WidgetEliteIndicator = true
 ColorHostileNPC = <table> {
 }
 WidgetDebuffPriority = <table> {
 }
 UnitSpotlightGlowEnable = true
 WidgetAuraTrackDisea

**Comment by Luxocracy** [comment]
I think this should be fixed in the latest release, but I'm not sure if I found the actual cause of it. If it keeps appearing for you please to tell me.

**Comment by Bredn** [comment]
I updated and its fixed . Ty so much !
