### ISSUE TITLE
BFA LUA Error

### ISSUE THREAD

**Issue by Apoxiosis** [Luxocracy/NeatPlates#134]
Hey Lux. Updated to the most recent version and my bugcatcher is yelling at me during raid

31x NeatPlatesHub\functions\Scale.lua:44: attempt to concatenate field 'unitid' (a nil value)

Hope this helps

**Comment by Luxocracy** [comment]
It's weird that this error is only showing itself now considering I've barely made any changes to the retail version in a while. Hopefully it is somehow the same issue as the classic version seems to have and the same fix will work.

If it doesn't please comment here again.
