### ISSUE TITLE
Global Error 

### ISSUE THREAD

**Issue by Chzconey** [Luxocracy/NeatPlates#135]
Date: 2019-09-15 01:42:45
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\NeatPlatesHub\functions\Alpha.lua line 41:
   attempt to compare nil with number
Debug:
   [C]: ?
   NeatPlatesHub\functions\Alpha.lua:41:
      NeatPlatesHub\functions\Alpha.lua:38
   (tail call): ?
   NeatPlatesHub\functions\Alpha.lua:173: SetAlpha()
   NeatPlates\NeatPlatesCore.lua:831:
      NeatPlates\NeatPlatesCore.lua:828
   NeatPlates\NeatPlatesCore.lua:1050:
      NeatPlates\NeatPlatesCore.lua:1038
   NeatPlates\NeatPlatesCore.lua:1350: ?()
   NeatPlates\NeatPlatesCore.lua:1120:
      NeatPlates\NeatPlatesCore.lua:1119
Locals:

AddOns:
  MoncaiCompare, v7.2.0
  Swatter, v8.2.6377 (SwimmingSeadragon)
  ACP, v3.5.6 
  AdvancedInterfaceOptions, v1.3.2
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.04
  AtlasLootClassic, vv1.1.11
  AucAdvanced, v8.2.6385 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6368 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Auctionator, v8.1.0
  AuctionDB, vv0.14.00-classic
  AutoLootPlus, v2.0.0-11302
  BagBrother, v
  BagFreeSpaceCounter, v1.0.2
  Bagnon, v8.2.9
  BankStack, vv11302.0
  Bartender4, v4.8.7
  BeanCounter, v8.2.6381 (SwimmingSeadragon)
  BetterVendorPrice, vv1.08.00-classic
  BiSTracker, v1.2 
  ClassicSpellActivations, v
  Coordinates, v2.1.0
  DBMCore, v1.13.8
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DejaClassicStats, v1302r022
  Details, v
  DetailsTinyThreat, v
  GatherMate2, v1.45
  GTFO, v4.49.2
  InFlightLoad, v1.13.002
  Informant, v8.2.6374 (SwimmingSeadragon)
  KillTrack, vv1.13.0
  LeatrixMaps, v1.13.30
  LibSharedMedia30, v3.0-113
  lsToasts, v11302.02
  MapFader, v1.0.4
  Mapster, v1.8.4
  MaxCam, vv2.4.2
  MBB, v4.0
  MikScrollingBattleText, v5.7.149
  Misspelled, v1.7.4
  MonkeyBuddy, v
  MonkeyLibrary, v
  MonkeyQuest, v
  MonkeyQuestLog, v
  MonkeySpeed, vv3.4.0
  NeatPlates, v1.13.2.25
  NeatPlatesAlvara, v5a
  NeatPlatesBlizzardPlates, v1.5
  NeatPlatesClassicPlates, v
  NeatPlatesGraphite, v
  NeatPlatesGrey, v
  NeatPlatesNeon, v
  NeatPlatesQuatre, v
  NeatPlatesRenaitre, vv7.0.3
  NeatPlatesRoth, v
  NeatPlatesSimple, v7.3.0
  NeatPlatesSlimHorizontal, v2.2
  NeatPlatesSlimVertical, v2.2
  NeatPlatesHub, v
  NeatPlatesWidgets, v
  OmniCC, v8.2.4
  oRA3, vv2-classic
  Peggle, v2.2.3
  Prat30, v3.7.36
  Prat30Libraries, v
  Quartz, v3.5.1
  QuestFrameFixer, v1.1.1
  QuestIconDesaturation, v3.1
  Questie, v4.0.18 BETA
  RealMobHealth, v2.10
  Scrap, v13.19
  ScrapSpotlight, v13.19
  ShadowedUnitFrames, vv4.2-Classic-Beta7
  SilverDragon, vv11302.0
  SilverDragonClassic, vv11302.0
  SimpleMap, v1.2.1
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SmartQuest, v1.18
  Spy, v1.0.5
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TipTac, v19.03.31
  TipTacItemRef, v19.03.31
  TitanClassic, v1.0.7.11302
  TitanClassicAmmo, v1.0.7.11302
  TitanClassicBag, v1.0.7.11302
  TitanClassicClock, v1.0.7.11302
  TitanClassicGold, v1.0.7.11302
  TitanClassicLocation, v1.0.7.11302
  TitanClassicLootType, v1.0.7.11302
  TitanClassicPerformance, v1.0.7.11302
  TitanClassicRepair, v1.0.7.11302
  TitanClassicVolume, v1.0.7.11302
  TitanClassicXP, v1.0.7.11302
  TitanSocial, v1.13.2
  TomCats, v0.0.2
  TomTom, vv11302-1.0.7
  TradeSkillMaster, vv4.8.7
  TradeSkillMasterAppHelper, vv4.0.4
  VendorPrice, v1.2.4
  WeakAuras, v2.14.6
  WeakAurasCompanion, v1.0.0
  WeaponSwingTimer, v4.1.0
  WhatsTraining, v1.8.4
  WIM, v3.7.33
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=c3c)

**Comment by Luxocracy** [comment]
Same issue as #133, any further discussion would be best handled in one thread.
