### ISSUE TITLE
[classic]Error in Alpha.lua

### ISSUE THREAD

**Issue by Talimar** [Luxocracy/NeatPlates#137]
133x NeatPlatesHub\functions\Alpha.lua:31: attempt to compare number with nil
NeatPlatesHub\functions\Alpha.lua:31: in function <NeatPlatesHub\functions\Alpha.lua:29>
(tail call): ?
NeatPlatesHub\functions\Alpha.lua:173: in function `SetAlpha'
NeatPlates\NeatPlatesCore.lua:831: in function <NeatPlates\NeatPlatesCore.lua:828>
NeatPlates\NeatPlatesCore.lua:1050: in function <NeatPlates\NeatPlatesCore.lua:1038>
NeatPlates\NeatPlatesCore.lua:1350: in function `?'
NeatPlates\NeatPlatesCore.lua:1120: in function <NeatPlates\NeatPlatesCore.lua:1119>

Locals:
InCombatSkipped

**Comment by Luxocracy** [comment]
Same issue as #133, any further discussion would be best handled in one thread.
