### ISSUE TITLE
NPC Plates

### ISSUE THREAD

**Issue by Flyindance7** [Luxocracy/NeatPlates#138]
I used same seeting,but there are two styles,how can i set to  show npc original plates like picture1？I want npc original plates.
My English is not good,sorry,and thank you.
![picture1](https://user-images.githubusercontent.com/55343694/64918819-12ce6480-d7d6-11e9-8122-b379c1c557b3.png)
![picture2](https://user-images.githubusercontent.com/55343694/64918821-17931880-d7d6-11e9-8b28-5bae21f9084f.png)

**Comment by Luxocracy** [comment]
`/run SetCVar("nameplateShowFriendlyNPCs", 0)`

Paste that in your chat window and it will turn off nameplates for friendly NPCs which I think is what you are after. If that isn't what you are after change the 0 to a 1, and it will go back to default.

**Comment by Flyindance7** [comment]
> `/run SetCVar("nameplateShowFriendlyNPCs", 0)`
> 
> Paste that in your chat window and it will turn off nameplates for friendly NPCs which I think is what you are after. If that isn't what you are after change the 0 to a 1, and it will go back to default.

Thank you very much,this is what i want.
