### ISSUE TITLE
Missing localization item "Emulate Target Nameplate" in CurseForge page

### ISSUE THREAD

**Issue by SwimmingTiger** [Luxocracy/NeatPlates#139]
There are no the following items in https://www.curseforge.com/wow/addons/neatplates/localization so we cannot translate them.
```lua
L["This feature is highly experimental, use on your own risk"] = true
L["Emulate Target Nameplate"] = true
```

**Comment by Luxocracy** [comment]
Must have forgotten to update it, my bad. Should be there now.
