### ISSUE TITLE
Classic Wow - Nothing

### ISSUE THREAD

**Issue by Saece** [Luxocracy/NeatPlates#142]
Hey i cannot get this addon to work, any reason for this?

It shows up on the login Addon page, It shows up on the in game addon page 

But no commands work and it just will not function?

https://imgur.com/a/Ze6d8uj

**Comment by Luxocracy** [comment]
You seem to be using the BFA version of the addon, there should be a warning message informing you of this but I guess something is preventing it from doing its job.
