### ISSUE TITLE
Error on Classic:

### ISSUE THREAD

**Issue by Havenloft** [Luxocracy/NeatPlates#144]
2x NeatPlates\NeatPlatesCore.lua:1419: attempt to index field 'timeout' (a nil value)
NeatPlates\NeatPlatesCore.lua:1419: in function `?'
NeatPlates\NeatPlatesCore.lua:1226: in function <NeatPlates\NeatPlatesCore.lua:1225>

Locals:
self = "COMBAT_LOG_EVENT_UNFILTERED"
_ = 1568772836.237000
event = "SPELL_AURA_REMOVED"
_ = false
sourceGUID = "Creature-0-4391-230-20969-8927-00000191A2"
sourceName = "Dark Screecher"
sourceFlags = 2600
_ = 0
destGUID = "Player-4409-008F5F83"
destName = "Jwar"
_ = 1304
_ = 0
spellID = 0
spellName = "Aural Shock"
spellSchool = 32
plate = nil
unitType = "Creature"
_ = "0"
_ = "4391"
_ = "230"
_ = "20969"
creatureID = "8927"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "00000191A2"
(*temporary) = "00000191A2"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'timeout' (a nil value)"
ParseGUID = <function> defined @NeatPlates\NeatPlatesUtility.lua:192
ShowIntCast = true
PlatesByGUID = <table> {
 Creature-0-4411-0-347-9081-000000EA34 = NamePlate14 {
 }
 Creature-0-4411-0-347-5394-000000EA34 = NamePlate4 {
 }
 Creature-0-4411-0-347-9080-000000EA34 = NamePlate5 {
 }
 Creature-0-4411-0-347-9077-000000EA34 = NamePlate3 {
 }
 Creature-0-4411-0-347-8155-000000EA34 = NamePlate11 {
 }
}
IsEmulatedFrame = <function> defined @NeatPlates\NeatPlatesCore.lua:211
spellCCList = <table> {
 Blackout = true
 M73 Frag Grenade = true
 Polymorph = true
 Hammer of Justice = true
 Hibernate = true
 Counterspell - Silenced = true
 Blind = true
 Pounce = true
 Stunning Blow = true
 Impact = true
 Psychic Scream = true
 Mithril Frag Bomb = true
 Hi-Explosive Bomb = true
 Large Copper Bomb = true
 Scatter Shot = true
 Shield Bash - Silenced = true
 Scare Beast = true
 Gnomish Mind Control Cap = true
 Mace Stun Effect = true
 Kidney Shot = true
 Starfire Stun = true
 Intimidation = true
 Intercept Stun = true
 Charge Stun = true
 Sap = true
 Cheap Shot = true
 Sleep = true
 Dark Iron Bomb = true
 Death Coil = true
 Silence = true
 The Big One = true
 Big Iron Bomb = true
 Freezing Trap Effect = true
 Seduction = true
 War Stomp = true
 Kick - Silenced = true
 Intimidating Shout = true
 Concussion Blow = true
 Revenge Stun = true
 Pyroclasm = true
 Rough Copper Bomb = true
 Glimpse of Madness = true
 Arcane Bomb = true
 Thorium Grenade = true
 Reckless Charge = true
 Goblin Mortar = true
 Improved Concussive Shot = true
 Flash Bomb = true
 Iron Grenade = true
 Big Bronze Bomb = true
 Gouge = true
 Small Bronze Bomb = true
 Tidal Charm = true
 Spell Lock = true
 Inferno Effect = true
 Mind Control = true
 Stun = true
 Howl of Terror = true
 Wyvern Sting = true
 Fear = true
 Bash = true
 Repentance = true
}
UnitSpellcastInterrupted = <function> defined @NeatPlates\NeatPlatesCore.lua:1212
GetPetOwner = <function> defined @NeatPlates\NeatPlatesUtility.lua:269
OnInterruptedCast = <function> defined @NeatPlates\NeatPlatesCore.lua:1071
SpellCastCache = <table> {
 Player-4409-0048F5A4 = <table> {
 }
}
CTICache = <table> {
  = <table> {
 }
 Creature-0-4391-230-20969-8927-00000191A2 = <table> {
 }
 Player-4409-00A89D16 = <table> {
 }
 Player-4409-00690DC8 = <table> {
 }
 Player-4409-00518FC1 = <table> {
 }
 Player-4409-00392174 = <table> {
 }
 Player-4409-00410B38 = <table> {
 }
 Player-4409-006616BF = <table> {
 }
 Player-4409-0070162A = <table> {
 }
 Player-4409-0038139A = <table> {
 }
 Player-4409-003A56A5 = <table> {
 }
 Player-4409-00495466 = <table> {
 }
 Pet-0-4414-229-3138-2850-07000C5225 = <table> {
 }
 Player-4409-00CAC4D9 = <table> {
 }
 Player-4409-004A00A3 = <table> {
 }
 Player-4409-0073E79F = <table> {
 }
 Pet-0-4412-1-347-1860-0300011BDB = <table> {
 }
 Player-4409-004DE9DC = <table> {
 }
 Player-4409-00772EB7 = <table> {
 }
 Pet-0-4414-409-2384-416-0800001909 = <table> {
 }
 Player-4409-00807B23 = <table> {
 }
 Player-4409-00AD7220 = <table> {
 }
 Player-4409-004EA0F9 = <table> {
 }
 Player-4409-00D27B66 = <table> {
 }
 Player-4409-006646C0 = <table> {
 }
 Player-4409-0078839F = <table> {
 }
 Player-4409-00626236 = <table> {
 }
 Player-4409-00967806 = <table> {
 }
 Player-4409-00B02E40 = <table> {
 }
 Player-4409-0048F5A4 = <table> {
 }
 Creature-0-4411-0-347-2831-0000019129 = <table> {
 }

**Comment by Luxocracy** [comment]
I believe this should have been fixed already and I just forgot to comment about it, if it isn't please just comment here again and I'll reopen the issue.
