### ISSUE TITLE
Target of target

### ISSUE THREAD

**Issue by Arthoniuspwns** [Luxocracy/NeatPlates#145]
I downloaded this for Classic WoW about a week and a half ago.  I've disabled all my addons, and come to find out, Neat Plates is the addon that causes my Target of Target not to work.  Any idea why?  I've literally not changed anything, except update some addons today.  I don't normally change options. on any addons, so was curious on why this started happening.  If anyone has any suggestions, I'll gladly try it.

**Comment by Luxocracy** [comment]
Hopefully this is related to ElvUIs buffs and debuffs not working properly, in which case I believe this shouldn't be an issue any more as of version 32.
If not I would recommend you downgrade to version .26 or .27 for now.
