### ISSUE TITLE
Conflict with ClassicCodex:

### ISSUE THREAD

**Issue by Havenloft** [Luxocracy/NeatPlates#147]
15x ClassicCodex\quest.lua:406: Attempt to access forbidden object from code tainted by an AddOn
[C]: in function `GetName'
ClassicCodex\quest.lua:406: in function `CheckNamePlate'
ClassicCodex\quest.lua:122: in function <ClassicCodex\quest.lua:24>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}

**Comment by Luxocracy** [comment]
I don't think this is caused by NeatPlates, as I cannot reproduce it, nor does it make sense looking at the code. And this error doesn't explicitly state that NeatPlates caused the 'taint'. Just that an addon is the cause.

**Comment by Havenloft** [comment]
Yes I meant to delete this. I disabled Neatplates and received the same error so it is not Neatplates.
