### ISSUE TITLE
Classic - Mob health not showing on plates

### ISSUE THREAD

**Issue by andrewkrok** [Luxocracy/NeatPlates#148]
Hello,

For some reason, mob health isn't showing on my NeatPlates. I have Real Mob Health, and I've dug through the /np settings to try and find something I'm missing, but I'm coming up empty. 

I use the Alvara style, if that matters.

**Comment by Luxocracy** [comment]
It's under _Enemy Status Text_

**Comment by andrewkrok** [comment]
So it is. Thank you so much! I am clearly just a dummy.
