### ISSUE TITLE
instance bug

### ISSUE THREAD

**Issue by Laborant89** [Luxocracy/NeatPlates#149]
this bug only at instances
https://ibb.co/52ckWwn

**Comment by Laborant89** [comment]
> this bug only at instances
> https://ibb.co/52ckWwn
All frienly nameplates in instances are like this

**Comment by Laborant89** [comment]
tryed all versions of Neatplates, and tryed delete another addons but still this bug...

**Comment by kchang** [comment]
Also running into the same bug. It shows up only in dungeons. I've tested all addons off except for neatplates. I'm on v1.13.2.32

**Comment by Luxocracy** [comment]
If the bug you are referring to is the _gap_ in the healthbar, it is something I'm looking into but have yet found what is the cause. Because it doesn't really make sense that it is there since friendly nameplates cannot be altered by addons in instances.

**Comment by Birdalf** [comment]
> If the bug you are referring to is the _gap_ in the healthbar, it is something I'm looking into but I have yet to find out what is causing it. It doesn't really make sense that it is there since friendly nameplates cannot be altered by addons in instances.

I don't think that is what he is referring to.

There is a bug where friendly NamePlates look/work great outside of instances but look normal/default inside of them. Here is a link that shows the issue on my end. Along with a screenshot of all my addons. 

https://imgur.com/a/xYgHjw9

![Capture2](https://user-images.githubusercontent.com/55786354/65585917-209f8a80-df38-11e9-8185-e1b4239c582a.PNG)
![WoWScrnShot_092419_215623](https://user-images.githubusercontent.com/55786354/65585919-209f8a80-df38-11e9-861d-dc82fdc6e69e.jpg)
![WoWScrnShot_092419_215634](https://user-images.githubusercontent.com/55786354/65585921-21382100-df38-11e9-8809-2c8b0d74a13c.jpg)

**Comment by Luxocracy** [comment]
@Birdalf That is not a bug, it is a restriction by blizzard. Friendly nameplates cannot be modified by addons while in an instance/raid.
Which is why the gap I was talking about, which is a bug, is really odd and difficult to track down.

**Comment by kchang** [comment]
@Luxocracy I think you fixed it. I'm on 1.13.2.34 and I haven't seen the gap when I'm in a dungeon party

**Comment by Laborant89** [comment]
Thanks!!!!!
