### ISSUE TITLE
Bug On Launch

### ISSUE THREAD

**Issue by Chzconey** [Luxocracy/NeatPlates#150]
Date: 2019-09-25 16:26:32
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\NeatPlates\NeatPlatesCore.lua line 238:
   attempt to call field 'SetScale' (a nil value)
Debug:
   [C]: SetScale()
   NeatPlates\NeatPlatesCore.lua:238:
      NeatPlates\NeatPlatesCore.lua:237
   NeatPlates\NeatPlatesCore.lua:1248: ?()
   NeatPlates\NeatPlatesCore.lua:1232:
      NeatPlates\NeatPlatesCore.lua:1231
Locals:

**Comment by Luxocracy** [comment]
I believe this should be fixed now in the latest release. Couldn't really confirm as this didn't happen to me before, but I think I know what caused it.

**Comment by Chzconey** [comment]
Ok I did not get a lua error thank you.

**Comment by Chzconey** [comment]
Super fast help by the way good job.
