### ISSUE TITLE
Rogue DoTs/Finishers

### ISSUE THREAD

**Issue by Sythalin** [Luxocracy/NeatPlates#151]
Rogue DoT finisher timers on nameplates are not being set to the correct timers.  For example, a 3 CP Rupture should last 12sec, but the timer always starts at 5 sec (text and animation).  After the 5 sec expires, the icon just stays there with no timer.

**Comment by Luxocracy** [comment]
Any aura duration issues would generally be related to the library that is used([LibClassicDurations](https://github.com/rgd87/LibClassicDurations)), and is pretty much out of my control as a result. But I'll take a look and see if there is anything I can do about it.

**Comment by Luxocracy** [comment]
Not entirely sure but I updated the library for durations and I noticed there were some mention of rupture having been fixed, but I can't personally verify if it works now or not.
