### ISSUE TITLE
quest indicator missing in 8.2.5

### ISSUE THREAD

**Issue by hollo6** [Luxocracy/NeatPlates#152]
Since 8.2.5, the quest indicators are missing. The option is enabled in the config.

**Comment by Luxocracy** [comment]
Check if the _showQuestTrackingTooltips_ CVar is enabled.
`/console showQuestTrackingTooltips 1`

It is possible that something else has change but I'm fairly sure this is something that was working on the 8.2.5 PTR a while back when I was checking it out.

**Comment by hollo6** [comment]
The CVar is set to 1 and everything appears in the tooltips as they should, just not on the nameplates.

**Comment by hollo6** [comment]
I just noticed that now there is a little icon next to the text in the tooltip (a dot if the objective is not completed yet and a tick if it is), maybe this breaks your pattern matching?

**Comment by Luxocracy** [comment]
Maybe, but if the rest is the same it should still work. I won't be able to look at to make sure until later today, but hopefully it's something simple like that.

**Comment by muderr0** [comment]
https://i.imgur.com/LX8PCsf.png that's how my tooltip looks like

**Comment by Luxocracy** [comment]
This should be working again.

Seems the pattern matching I used to have to do, to find out which row belonged to the player when in a group, was no longer necessary as they made it its own line above the one with the quest info. So they did change it quite a bit since I tried it on the PTR.

**Comment by muderr0** [comment]
thanks, everything back to normal.

**Comment by hollo6** [comment]
indeed looks good now, thank you!
