### ISSUE TITLE
Error in NeatPlatesCore.lua   line 1388  CoreEvents:COMBAT_LOG_EVENT_UNFILTERED

### ISSUE THREAD

**Issue by alexqu0822** [Luxocracy/NeatPlates#154]
First thank u for ur work.NP is really beautiful and useful, a great work!

I found an error occurerd when I was controlled by mobs‘ “mind control" and the effect ended when Nameplates turned around for enemies and friends.
[Here maybe I took damage or buff or debuff from my fellows or mods]

sourceGUID will be nil  or be nil after trunk if ShowIntCast then ... end.

I added "if not sourceGUID then return end" before and after this trunk to temporarily sove it.

For classic 1.13

**Comment by Luxocracy** [comment]
I believe this should be fixed in the latest release.
