### ISSUE TITLE
When the enemy is too big, the health plate will often be pushed out of the computer screen. Is there a solution? QAQ

### ISSUE THREAD

**Issue by Ame1012** [Luxocracy/NeatPlates#156]
plz

**Comment by Luxocracy** [comment]
Try enabling _Stacking Nameplates_, as far as I know the _Nameplate Inset CVars_ which keeps nameplates on screen only work when you have stacking nameplates enabled. No idea why this is the case but hopefully this should help.

Although, if this is regarding the Classic client then I don't believe these CVars work at all and I don't think there's a solution to this. At least not one that i know of.
