### ISSUE TITLE
feature request?

### ISSUE THREAD

**Issue by mostoxic** [Luxocracy/NeatPlates#158]
O YO ill start with saying that this is the best nameplate addon i could find after elvui did a revamp with one of the patches i think it was 8.2 but its irrelevant. i just would like to know or maybe throw some ideas ur way. i really love the quarte theme becasue it was very similar to the one i used to use from elvui the only issue i have is in pve where unless i have my camera pretty zoom in when a boss or enemy is casting something ill use Adderis from temple of sethraliss as an example when casting cyclone strike the cast bar with the name and the icon all underneath the name plate makes it very difficult for me to see which way its facing i read that you were trying to make the cast bars a separate entity from the nameplate it self but was having issues with it heres a screen shot from the current NP theme and the old elvui theme i enjoyed a lot personally i think its much more refined and compact easier to see the targets direction etc but yea man love the addon still use it for months now but thanks for your time boss <3     
![nameplates](https://user-images.githubusercontent.com/56463913/66694679-f275b680-ec6a-11e9-95e8-486b0b4c4fa3.png)

**Comment by Luxocracy** [comment]
Not really sure what you are even asking for, but if you want me to change the defaults of the Quatre theme to be more like the ElvUI one then that is a no.

However, once the new customization options are finished you should be able to move and resize pretty much every element of the nameplate. Which should allow you to make it look much more like the ElvUI nameplates.
