### ISSUE TITLE
Missing nameplates

### ISSUE THREAD

**Issue by staviq** [Luxocracy/NeatPlates#159]
I have noticed that sometimes, for some players or NPCs nameplates will not display at all.

When i get close to them, their names disappear bot no nameplate shows up.

Additionally, i have noticed, that when standing in AH, if i repeatedly disable and enable nameplates ( ctrl+v ) i get randomly diffrent people or NPCs with no nameplates, sometimes i can get most of the nameplates to disappear.

I don't see any errors showing up in the gui, at least not when enabling/disabling nameplates, or when i notice nameplates missing.

doing "/reload ui" does seem to help for a while.

EDIT: I just caught an error like this:

`
Date: 2019-10-13 03:25:48
ID: 1
Error occured in: Global
Count: 1
Message: ..\SharedXML\C_TimerAugment.lua line 30:
   C_Timer.After requires a non-negative duration
Debug:
   [C]: After()
   ..\SharedXML\C_TimerAugment.lua:30:
      ..\SharedXML\C_TimerAugment.lua:11
   (tail call): ?
   NeatPlatesWidgets\AuraWidget.lua:242:
      NeatPlatesWidgets\AuraWidget.lua:214
   NeatPlatesWidgets\AuraWidget.lua:256:
      NeatPlatesWidgets\AuraWidget.lua:246
   NeatPlatesWidgets\AuraWidget.lua:472:
      NeatPlatesWidgets\AuraWidget.lua:289
   NeatPlatesWidgets\AuraWidget.lua:496:
      NeatPlatesWidgets\AuraWidget.lua:493
   NeatPlatesWidgets\AuraWidget.lua:506: UpdateContext()
   NeatPlatesHub\functions\Widgets.lua:388: OnContextUpdate()
   NeatPlates\NeatPlatesCore.lua:761:
      NeatPlates\NeatPlatesCore.lua:746
   NeatPlates\NeatPlatesCore.lua:629:
      NeatPlates\NeatPlatesCore.lua:620
   NeatPlates\NeatPlatesCore.lua:321:
      NeatPlates\NeatPlatesCore.lua:298
Locals:
(*temporary) = Infinite
(*temporary) = <function> defined @Interface\SharedXML\C_TimerAugment.lua:14

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AucAdvanced, v8.2.6407 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Auctionator, v8.1.0
  BagBrother, v
  Bartender4, v4.8.8
  BeanCounter, v8.2.6381 (SwimmingSeadragon)
  BetterVendorPrice, vv1.09.01
  ClassicQuestLog, v1.4.5-Classic
  ClassicAuraDurations, v
  Cleanup, v
  ColoredInventoryItems, v1.4
  DBMCore, v1.13.15
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsTinyThreat, v
  Enchantrix, v8.2.6411 (SwimmingSeadragon)
  FieldGuide, vv1.5-release
  GatherMate2, v1.45.5
  GatherMateSharing, vv1.12
  Informant, v8.2.6374 (SwimmingSeadragon)
  Inventorian, v1.13.2.4
  LeatrixPlus, v1.13.34
  LunaUnitFrames, v1.0
  MoveToolTip, v1.0.6
  NeatPlates, v1.13.2.38
  NeatPlatesAlvara, v5a
  NeatPlatesBlizzardPlates, v1.5
  NeatPlatesClassicPlates, v
  NeatPlatesGraphite, v
  NeatPlatesGrey, v
  NeatPlatesNeon, v
  NeatPlatesQuatre, v
  NeatPlatesRenaitre, vv7.0.3
  NeatPlatesRoth, v
  NeatPlatesSimple, v7.3.0
  NeatPlatesSlimHorizontal, v2.2
  NeatPlatesSlimVertical, v2.2
  NeatPlatesHub, v
  NeatPlatesWidgets, v
  Necrosis, v5.0
  NugEnergy, v1.13.10
  Prat30, v3.7.36
  Prat30Libraries, v
  QuestFrameFixer, v1.1.1
  Questie, v4.2.0 0 3bf27b9
  RangeDisplay, vv4.9.0
  RealMobHealth, v2.13
  SimpleMap, v1.2.1
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SortBags, v0.1.2
  Spy, v1.0.9
  Stubby, v8.2.6376 (SwimmingSeadragon)
  WeakAuras, v2.15.2
  WeaponSwingTimer, v4.1.0
  XToLevel, v11302
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=74c)

`

https://i.imgur.com/3nhrWDm.png

**Comment by Luxocracy** [comment]
Do you have pandemic highlighting enabled by chance?
At least according to the error that seems to be what is causing it and this isn't something that exists in Classic either way. It's just an option that I've missed to remove in the classic release.

**Comment by staviq** [comment]
I seems like i had pandemic highlighting enabled, also, the other settings:
https://i.imgur.com/7G6ZVsN.jpg
https://i.imgur.com/7CEQgd4.jpg

**Comment by Luxocracy** [comment]
Are you still having this issue? At first I interpreted your response as it being resolved, but at a second glance I'm unsure.

If you are still having this issues could you see if this still happens if NeatPlates is the only addon enabled? Because I'm really not able to re-produce this no matter what settings I change.
