### ISSUE TITLE
Friendly nameplates reverting to blizz defaults inside instances

### ISSUE THREAD

**Issue by kakkakk** [Luxocracy/NeatPlates#160]
I've scoured the options, so forgive me if this is just a setting I've overlooked. Please advise how to have Neatplates *friendly* plates work inside dungeons... enemy/neutral work fine, but oh god are the blizzard defaults huge and ugly...

Thanks :)

**Comment by Luxocracy** [comment]
This isn't a bug sadly, it's a restriction by Blizzard. Nothing I can do about it.

**Comment by skinnay-dev** [comment]
I saw a stream today where someone has modified friendly nameplates inside MC: https://www.twitch.tv/videos/498056387
He's using the addon Plater.
However, those nameplates still look different from how they look for him outside of instances. It's still something though, and looks better than the default frames.

**Comment by Luxocracy** [comment]
From the look of those nameplates, he's simply replaced the default nameplate textures with empty/blank ones.

This isn't something I'd even consider adding as a default part of the addon since it can't be controlled by in-game settings.
