### ISSUE TITLE
Not sure if an issue or not but

### ISSUE THREAD

**Issue by lostcause1238** [Luxocracy/NeatPlates#162]
In a group party members and their pets are of blizzards style or not at all also is it possible to change the font so I can everything matching thanks

**Comment by Luxocracy** [comment]
Sadly friendly nameplates cannot be altered while in instances. As for fonts, there isn't an option for changing it at the moment.

**Comment by lostcause1238** [comment]
Wow thanks for the speedy response

**Comment by BoNaStudio** [comment]
"Sadly friendly nameplates cannot be altered while in instances."
Is that how it is supposed to be or it will be fixed? 
I mean for a heal this addon is useless then...

**Comment by Luxocracy** [comment]
I guess I kinda forgot to mention, but it's not something I have any control over. It's a restriction by Blizzard because people were doing some really clever things with nameplates. So they just blocked it while in instances...

**Comment by BoNaStudio** [comment]
That is just too bad...but thanks for reply!
