### ISSUE TITLE
Could you please add an option for changing  stratum of neatplates?

### ISSUE THREAD

**Issue by Colinelleo** [Luxocracy/NeatPlates#163]
Part of damage text is obstructed by neatplates. So if possible, could you pleasses add an option to change stratum?

**Comment by Luxocracy** [comment]
If we're talking about the default damage text then changing the frame strata won't help. In addition to this, Neatplates is already set to the lowest frame strata possible(Background).

**Comment by Colinelleo** [comment]
Got it. Thanks for reply.
