### ISSUE TITLE
In Classic version not mark mobs attacking another tank correctly.

### ISSUE THREAD

**Issue by hasnogaems** [Luxocracy/NeatPlates#164]
It just ignore em, and mark like usual party member aggro color.
![Безымянный](https://user-images.githubusercontent.com/14231492/67164859-70327400-f387-11e9-965e-1700e56e115d.png)

**Comment by hasnogaems** [comment]
Another tank aggro should be blue, but for me it just red if I do not hold aggro.

**Comment by Luxocracy** [comment]
This should be fixed in the latest release. Also under _Threat & Highlighting_ you need to enable the _Highlight Mobs on Off-Tanks_ option if you haven't already.

**Comment by hasnogaems** [comment]
You such a life saver man, I really dig neatplates.

**Comment by hasnogaems** [comment]
Any way to manually assign tank unit with some slash command would be nice. It not always correct assigned by default.

**Comment by Luxocracy** [comment]
I added a new slash command in the latest version(**/nptank**) that allows you to manage tanks manually. It's really simplistic and simply toggles the currently targeted units assignment between **Tank** and **None**, which gets printed in the chat. 
However, units assigned as **Tank** in the raid frames will still override anything you assign manually.

**Comment by hasnogaems** [comment]
Working like a charm! Thank you so much!
