### ISSUE TITLE
Request : Emphasize a "group" of auras

### ISSUE THREAD

**Issue by VPrax** [Luxocracy/NeatPlates#166]
Hey, thanks for the job you're doing on this add-on.

Would it be possible to emphasize/track a group of aura (e.g. "Stun" "Silence" "Root" "Snare" "Fear", "Blind"...) by using the "All" or "My" part + *wanted group* when setting new emphasied/additional auras instead of entering every spells that would fit the corresponding group ?

If I'm blind and it is already implemented, I'm sorry !

Have a nice day !

**Comment by Luxocracy** [comment]
To implement a feature like this, where it groups auras by their effects, would require you to index all the stuns, snares and so on as this information isn't available through the client.

It's just not something I wish to spend time on creating and maintaining when it essentially isn't any different from what anyone can do with the current system.
