### ISSUE TITLE
Bug: General Spell Filter List Broken

### ISSUE THREAD

**Issue by Nukme** [Luxocracy/NeatPlates#167]
**version**: 
NP 8.2.5.12

**description**:
1. ALL previously stored spell-ids in General Spell Filter box are wiped after installing 8.2.5.12.
2. Newly edited spell-ids become character-only and couldn't be seen on another character under the same account as before.

**Comment by Luxocracy** [comment]
This should be fixed in the latest release.

When I revamped the automation settings I changed the type of their related variables from string to objects, and it seems this caused the 'General Aura Filters' not to restore properly for characters that still had the old variable types.
