### ISSUE TITLE
Pet Nameplate working differently

### ISSUE THREAD

**Issue by Marangwe** [Luxocracy/NeatPlates#169]
Ever since the last update my PET'S NAME has been acting weird. After messing with the settings I found that the pet is considered an ENEMY PET under names. Any idea what may cause this? Here are some screenshots to show what I mean.
[images](https://imgur.com/a/dPELFQt)

**Comment by Luxocracy** [comment]
As I already mentioned over on curse, this is solely on blizzards end. I'm not sure if this is because of how it was in vanilla or if it's a big. But there's nothing to be done on the addon side.
