### ISSUE TITLE
Bug: Profile Settings UI becomes a total mess

### ISSUE THREAD

**Issue by Nukme** [Luxocracy/NeatPlates#172]
**version:**
8.2.5.15

**environment:**
WoW BFA@Windows 10, zhCN

**description:**
1. clean upgrade NP to 8.2.5.15 from .14
2. start game and log-in
3. parts of UI for profile settings are misaligned. From _Style_ to _Scale_.

<img src="https://i.ibb.co/ws37DPH/Neatplates8-2-5-15-1.png" alt="Neatplates8-2-5-15-1" border="0">
<img src="https://i.ibb.co/FXWXWpQ/Neatplates8-2-5-15-2.png" alt="Neatplates8-2-5-15-2" border="0">

**Comment by Luxocracy** [comment]
Ah... I was in a bit of a hurry when I made the releases and must have merged something wrong from the classic branch.
I'll fix it asap, sorry about this.

**Comment by Nukme** [comment]
Thx for the quick fix!
