### ISSUE TITLE
Neat plates 8.2.5.16 won't open, tons of errors

### ISSUE THREAD

**Issue by grospapa** [Luxocracy/NeatPlates#173]
(Classic -- had been working fine.  Deleted and reinstalled via twitch no change)

Date: 2019-11-24 08:54:00
ID: 1
Error occured in: Global
Count: 1
Message: ...tPlates\libs\LibRangeCheck-2.0\LibRangeCheck-2.0.lua line 1047:
   Attempt to register unknown event "PLAYER_TALENT_UPDATE"
Debug:
   [C]: RegisterEvent()
   ...tPlates\libs\LibRangeCheck-2.0\LibRangeCheck-2.0.lua:1047: activate()
   ...tPlates\libs\LibRangeCheck-2.0\LibRangeCheck-2.0.lua:1091: in main chunk
Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "PLAYER_TALENT_UPDATE"

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AtlasLootClassic, vv1.3.4
  AtlasLootClassicData, vv1.3.4
  AtlasLootClassicDungeonsAndRaids, vv1.3.4
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  AutoDismount, v1.0.3
  BagBrother, v
  Bagnon, v8.2.16
  Bartender4, v4.8.8
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  ClassicThreatMeter, v1.10
  DBMCore, v1.13.21
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  ExtendedCharacterStats, v1.5
  GatherMate2, v1.45.5
  GroupCalendar, v
  InFlightLoad, v8.2.006
  ItemRack, v
  NeatPlates, v8.2.5.14
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Stubby, v8.2.6510 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=447)

**Comment by Luxocracy** [comment]
8.2.5.xx is the retail version, make sure you have the Classic version (1.13.2.xx). Not sure what is up with the twitch client lately as I've heard other people mention the same issue where it installs the wrong update.

**Comment by grospapa** [comment]
Did it from scratch, it is installing the Retail version for some reason. Thanks!  Will do manually.
