### ISSUE TITLE
Threat color isn't working properly

### ISSUE THREAD

**Issue by mscott87** [Luxocracy/NeatPlates#175]
This is for classic.  Having trouble getting the bar color and threat to show properly as it used to before updating.  Attached is a screenshot of what it's doing now, even when set to tank.  I've tried deleting the addon, even clearing my saved variables folder and it's still not displaying the threat correctly.  

![NP](https://user-images.githubusercontent.com/58245874/69697352-cd68c600-10a7-11ea-93a6-1bc9860bf50d.png)

**Comment by Luxocracy** [comment]
What exactly is happening that is incorrect? It's kinda hard to tell from the image alone, as it appears to treat you as tank and the mobs healthbar is the safe/blue color while attacking you.

**Comment by mscott87** [comment]
That is correct.

**Comment by Luxocracy** [comment]
So you aren't a tank? Then you should set it to dps/healer if it assumes wrong.

**Comment by mscott87** [comment]
Correct.  But when I change it to Tank/DPS it's still showing the safe
color.  I'll upload some more pictures when I get a chance.

**Comment by mscott87** [comment]
![np1](https://user-images.githubusercontent.com/58245874/69764278-6265d080-1135-11ea-9ded-9898ed760268.png)
![np2](https://user-images.githubusercontent.com/58245874/69764287-6a257500-1135-11ea-9395-4217096a301e.png)

**Comment by Luxocracy** [comment]
In the pictures you linked it's behaving as expected, they're not really highlighting the issue you claim to have. If you don't want it to show a _safe/blue_ color when mobs attack you the threat mode needs to be set to **DPS**.
The reason it assumes you are a tank on auto is because of the shield. What would really help is if you explain to me what you expect to happen, because I can't see any issues in these pictures.

**Comment by mscott87** [comment]
Here is what it looks like on my warlock.  
![nps](https://user-images.githubusercontent.com/58245874/69783474-3bc98900-1179-11ea-96e7-aedae3ce257d.png)

**Comment by Luxocracy** [comment]
Set your threat mode to 'Dps/Healer' and **not** 'Tank' if you want it to behave like your a DPS, aka like on your warlock. It's always been reversed for tanks but the _Auto_ mode doesn't always work in Classic.

**Comment by mscott87** [comment]
I see.. I guess that makes sense.  Thanks for your help!  I kinda feel stupid now for not trying that to begin with.  It just seemed a little counter intuitive.
