### ISSUE TITLE
Health bar - Can not choose the target by clicking health bar

### ISSUE THREAD

**Issue by Mr-Priest** [Luxocracy/NeatPlates#177]
I can not choose the target by clicking their health bar. 
This is annoying because it is really difficult to dispel buff of the enemies.

**Comment by Luxocracy** [comment]
Make sure that **Clickthrough** isn't checked in the profile settings. Another thing that you might need to check is that the **Clickable Width/Height of Nameplates** isn't set to a really low value in the main settings.
