### ISSUE TITLE
Infinite Errors: Attempt to call field SetSubText

### ISSUE THREAD

**Issue by Accendor** [Luxocracy/NeatPlates#178]
Basically impossible to use the addon atm for me :(

Message: Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1432: attempt to call field 'SetSubText' (a nil value)
Time: Mon Dec  2 19:08:37 2019
Count: 9742
Stack: Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1432: attempt to call field 'SetSubText' (a nil value)
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1432: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1430>
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:349: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:337>
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:372: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:360>
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:497: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:487>
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:179: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:156>

Locals: index = nil
unitSubtext = nil
unitPlateStyle = nil
(*temporary) = nil
(*temporary) = <table> {
 guid = "Creature-0-1631-1643-7532-129869-00006540E0"
 isMouseover = false
 class = ""
 rawName = "Hungry Rooter"
 threatSituation = "LOW"
 red = 0.999998
 levelcolorRed = 1
 unitid = "nameplate1"
 isPet = false
 name = "Hungry Rooter"
 pvpname = "Hungry Rooter"
 levelcolorBlue = 0
 isBoss = false
 isFocus = false
 healthmax = 53170
 isTarget = false
 levelcolorGreen = 0.820000
 isTapped = false
 type = "NPC"
 isCasting = false
 isTrivial = false
 isMini = false
 level = 120
 isInCombat = false
 isMarked = false
 reaction = "HOSTILE"
 green = 0
 isDangerous = false
 threatValue = 0
 health = 53170
 blue = 0
}
(*temporary) = "attempt to call field 'SetSubText' (a nil value)"
style = <table> {
 threatcolor = <table> {
 }
 customtext = <table> {
 }
 highlight = <table> {
 }
 eliteicon = <table> {
 }
 castborder = <table> {
 }
 mouseover = <table> {
 }
 focus = <table> {
 }
 healthborder = <table> {
 }
 subtext = <table> {
 }
 extrabar = <table> {
 }
 targetindicator_arrowleft = <table> {
 }
 spelltext = <table> {
 }
 target = <table> {
 }
 level = <table> {
 }
 targetindicator_arrowsides = <table> {
 }
 extraborder = <table> {
 }
 targetindicator_arrowtop = <table> {
 }
 targetindicator = <table> {
 }
 healthbar = <table> {
 }
 castbar = <table> {
 }
 targetindicator_arrowright = <table> {
 }
 threatborder = <table> {
 }
 skullicon = <table> {
 }
 raidicon = <table> {
 }
 spellicon = <table> {
 }
 durationtext = <table> {
 }
 name = <table> {
 }
 hitbox = <table> {
 }
 extratext = <table> {
 }
 frame = <table> {
 }
 rangeindicator = <table> {
 }
 castnostop = <table> {
 }
}
activetheme = <table> {
 threatcolor = <table> {
 }
 customtext = <table> {
 }
 highlight = <table> {
 }
 eliteicon = <table> {
 }
 castborder = <table> {
 }
 mouseover = <table> {
 }
 focus = <table> {
 }
 healthborder = <table> {
 }
 subtext = <table> {
 }
 extrabar = <table> {
 }
 targetindicator_arrowleft = <table> {
 }
 spelltext = <table> {
 }
 target = <table> {
 }
 level = <table> {
 }
 targetindicator_arrowsides = <table> {
 }
 extraborder = <table> {
 }
 targetindicator_arrowtop = <table> {
 }
 targetindicator = <table> {
 }
 healthbar = <table> {
 }
 castbar = <table> {
 }
 targetindicator_arrowright = <table> {
 }
 threatborder = <table> {
 }
 skullicon = <table> {
 }
 raidicon = <table> {
 }
 spellicon = <table> {
 }
 durationtext = <table> {
 }
 name = <table> {
 }
 hitbox = <table> {
 }
 extratext = <table> {
 }
 frame = <table> {
 }
 rangeindicator = <table> {
 }
 castnostop = <table> {
 }
}
unit = <table> {
 guid = "Creature-0-1631-1643-7532-129869-00006540E0"
 isMouseover = false
 class = ""
 rawName = "Hungry Rooter"
 threatSituation = "LOW"
 red = 0.999998
 levelcolorRed = 1
 unitid = "nameplate1"
 isPet = false
 name = "Hungry Rooter"
 pvpname = "Hungry Rooter"
 levelcolorBlue = 0
 isBoss = false
 isFocus = false
 healthmax = 53170
 isTarget = false
 levelcolorGreen = 0.820000
 isTapped = false
 type = "NPC"
 isCasting = false
 isTrivial = false
 isMini = false
 level = 120
 isInCombat = false
 isMarked

**Comment by Luxocracy** [comment]
The only point at which I can recreate this issue is when I have no themes loaded, and the error data seems to suggest the same. So I would recommend you double check that there are themes loaded in the addons section.

**Comment by Accendor** [comment]
For whatever reason indeed no theme was loaded, this solved it - thank you very much!
Might I suggest to handle this error with a customized error message instead if possible?
