### ISSUE TITLE
Request regarding friendly health bar

### ISSUE THREAD

**Issue by wanghedi1991** [Luxocracy/NeatPlates#185]
Hi, 

Thanks for the great work and happy holidays. I really love this addon but after a certain version, I find the colors of my teammate and enemy mage/shaman are very similar. Would you consider change the dark blue back for teammates? Or could you tell me which file I should change? I personally don't like to use marks on teammates and would prefer to have teammate hp bar visible so I can easily tell where they are and if they are cc'd in bg/arena.

Thanks!!!

**Comment by Luxocracy** [comment]
You can change pretty much all colors under the _Reaction_ section. Although some might get overridden depending on your _Bar color_ mode. So that might also be of interest to look at.

**Comment by wanghedi1991** [comment]
> You can change pretty much all colors under the _Reaction_ section. Although some might get overridden depending on your _Bar color_ mode. So that might also be of interest to look at.

Thanks for the quick reply! so are you talking about in game settings or the actual code?

**Comment by Luxocracy** [comment]
These are options in the profile settings of the addon in-game.

**Comment by wanghedi1991** [comment]
found it！ Thanks : ) happy new year btw
