### ISSUE TITLE
Unit nameplates keeps getting turned off

### ISSUE THREAD

**Issue by miskoog** [Luxocracy/NeatPlates#186]
Hello friends.

I have 'always show nameplates' checked aswell as 'enemy units' in blizzard interface. But as soon as im going out of combat the 'enemy units' box gets unchecked.

I've figured maybe some option in neatplates is messing with this but i cant seem to figure out which one.
I have tried changing colors (green/red/white) under Automation in neatplates but this does not help.
Any ideas? or can i make this work some other way?

Have a nice day.

**Comment by Luxocracy** [comment]
If nameplates still turn off when exiting combat even after the _Automation options_ aren't enabled (appear in white), I would look towards other addons potentially controlling nameplates. I believe a common one is _Leatrix Plus_, that has something like this enabled by default.

**Comment by miskoog** [comment]
Wow, you were 100% right. Thanks for this fast answer :) Leatrix plus was the bad guy here!
