### ISSUE TITLE
(Classic) Theme customization: level indicator's "Offset X" not working

### ISSUE THREAD

**Issue by Srljm** [Luxocracy/NeatPlates#190]
![NeatPlatesLevelOffset](https://user-images.githubusercontent.com/55985046/72366046-c1899f80-36f9-11ea-9ec1-b9331b5d3941.jpg)

The "Offset X" setting does nothing.
In the picture you can see that the mage's level indicator is close to the bar while the value is far to the right.
I use the Blizzard theme style for bars if that helps.

**Comment by Luxocracy** [comment]
Guess I forgot to comment on this, but this should have been fixed a while ago.
