### ISSUE TITLE
Some Units don't show Quest Icon

### ISSUE THREAD

**Issue by yishuangfrank** [Luxocracy/NeatPlates#191]

**Comment by yishuangfrank** [comment]
![1](https://user-images.githubusercontent.com/44251440/74231090-b0d04780-4d00-11ea-9e40-362edeae9474.png)
v8.3.0.4

**Comment by yishuangfrank** [comment]
![1](https://user-images.githubusercontent.com/44251440/74232167-2c32f880-4d03-11ea-8f68-b97f6e06e769.png)

**Comment by Luxocracy** [comment]
Are you in a group when this issue happens? And is this your quest or a party members?

Because I had to remove/fix the tracking of party members quests as it was causing some issues with the quest tracking in 8.3. And it wasn't really meant to keep track of party members quests to begin with.

**Comment by yishuangfrank** [comment]
the 1st picture：I am single.
the 2nd picture：I am in a party.

**Comment by Luxocracy** [comment]
I'll look into it later today when I am able. 

But this might be due to some differences in the client between the English and Chinese version. Because when I am solo, at least when I made the change, my name doesn't appear in the quest tooltip.

**Comment by yishuangfrank** [comment]
The same unit.

![1](https://user-images.githubusercontent.com/44251440/74232641-30abe100-4d04-11ea-83b6-51c079118b88.png)
 When I am in a party.

![2](https://user-images.githubusercontent.com/44251440/74232673-3f929380-4d04-11ea-80b5-03fe782978a9.png)
 When I am single.

**Comment by Luxocracy** [comment]
Hmm, then it might just be an issue with it not matching your characters name properly with the name that appears in the tooltip.

**Comment by Luxocracy** [comment]
Sorry it took awhile before I could look into this.
Don't know how this ever worked for me before when I was in a group, as it really shouldn't have, but anyways it should be working properly now in the latest release.

**Comment by yishuangfrank** [comment]
![1](https://user-images.githubusercontent.com/44251440/74761968-ebfde800-52b7-11ea-8c9c-158fb96ee18b.png)
v8.3.0.5,Single.
Most units show Quest Icon correctly.

**Comment by yishuangfrank** [comment]
![1](https://user-images.githubusercontent.com/44251440/74814782-0032fb00-5333-11ea-9a9f-7fc23d92c170.png)
The unit belongs two quests

**Comment by Luxocracy** [comment]
I can't reproduce this issue on my end, it works as expected with the quest icon showing up even if one of the quests is completed.
I didn't have any overlapping world quests up however, so it might be something specifically related to WQs but I'll have to just keep an eye out for when one appears that overlaps in this way.

**Comment by Luxocracy** [comment]
I just can't seem to reproduce this, so I'm not quite sure what is going on.
![image](https://user-images.githubusercontent.com/2884542/75065569-619cca80-54e9-11ea-854a-cd9344f3bc62.png)
![image](https://user-images.githubusercontent.com/2884542/75065667-885b0100-54e9-11ea-9b30-ea8a6205993a.png)

Is it limited to just the few cases you linked above or does it always happen when there are overlapping quests and one is completed?

**Comment by yishuangfrank** [comment]
It seems that Quest Icon bugs are fixed in the latest version.
Thanks for your working!
