### ISSUE TITLE
Font adjustment?

### ISSUE THREAD

**Issue by jevinon** [Luxocracy/NeatPlates#193]
Floating text above NPC/enemies is sort of small. Is there a way to adjust the size/width/boldness of a font? Even if i just have to go into a specific file and mess with the size thats alright. Thanks

**Comment by Luxocracy** [comment]
Not sure exactly which text you are referring to, but it can probably be changed by modifying the theme file of whatever theme you are using.

Altering the fonts was something that was supposed to be possible through the in-game theme customization when that was added. But that needs a bit more work before it is ready, however, I think font size could be added even if it would only exist for some elements.

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
