### ISSUE TITLE
Percent health subtext not updating

### ISSUE THREAD

**Issue by killyox** [Luxocracy/NeatPlates#198]
Hi, 
First, thanks for your work, it's really a great great addon !

I have a little bug when I configure "Enemy subtext" as "Percent health" or "Percent health (colored)" in WoW Classic : It's not updating every time enemy health change (but it works fine in "Enemy status text"), as you can see on this screenshot : 

![Neat Plates health bug](https://user-images.githubusercontent.com/3913411/77247282-ce61cc80-6c2f-11ea-8c27-daf1802381d9.jpg)

**Comment by Luxocracy** [comment]
Hmm, this must have been broken for quite some time as the subtext usually only updates when the plate is created or the units _name_ data has changed.

Anyways, this should be resolved in the latest release.

**Comment by killyox** [comment]
Thanks for the rapidity ! You're dawn good ! It works fine now :)

I don't know if it's broken for long time, coz i just discovered your addon. But i'm really happy I did, it's really a great addon, lot of customization, options are really clear. Please, continue like that, i'll tell everybody your addon is nice ! :)
