### ISSUE TITLE
Interaction with LibThreatClassic2 

### ISSUE THREAD

**Issue by fagitomania** [Luxocracy/NeatPlates#199]
Hello, i am using the ThreatClassic2 addon. It has a feature to support threat coloring, but it doesnt work along with neatplates. I opened an issue on the projects github and i got told that my nameplates addon should use LibThreatClassic2. (https://github.com/dfherr/ThreatClassic2/issues/37)
Is it possible to implement this somehow, so it works with my threatmeter addon?
I saw a request from Jan to update to LibThreatClassic2, did u find time to look into it?

**Comment by Luxocracy** [comment]
LibThreatClassic2 is being used, so not sure why it wouldn't work.

**Comment by fagitomania** [comment]
Do i need to select an option from NeatPlates or enable something then?
