### ISSUE TITLE
Neon 风格下施法条的问题

### ISSUE THREAD

**Issue by yumilili2020** [Luxocracy/NeatPlates#200]
您好：首先非常感谢你提供了这么好用的插件，但是我在使用过程中遇见了一个问题；我在选择Neon风格的时候出现了施法条与血条直接有很大的空隙，而且施法条与血条不是垂直显示的

我尝试在Theme Customization中做修改  但是仍然无法解决
![a7Q5-mbmK2cT1kSfh-ap](https://user-images.githubusercontent.com/63009571/78162396-67d37e80-7479-11ea-82b3-73a7f4f6f49a.jpg)
在这里寻求你的帮助

**Comment by Luxocracy** [comment]
The castbar is a bit special in the Them Customization as it has a lot of different parts to it, and currently they have to be moved individually. It is one of the few options that I would like to add the option to move as one, but haven't found the time to do so yet.

The elements you need to change are:
- Castborder (non-interuptible)
- Spell Icon
- Castbar
- Castbar Spell Text
- Duration/Cast time Text
- Castbar Border

Here's a google translate version of what I said, hopefully it will successfully communicate what I'm saying:

> Castbar在Them Customization中有些特殊，因为它有很多不同的部分，目前它们必须单独移动。 这是我要添加作为一体移动选项的少数选项之一，但是还没有时间这样做。
> 
> 您需要更改的元素是：
> -Castborder（不可中断）
> -咒语图标
> -Castbar
> -Castbar拼写文字
> -持续时间/播放时间文字
> -Castbar边框
