### ISSUE TITLE
Fake cast bug

### ISSUE THREAD

**Issue by loftyleroi** [Luxocracy/NeatPlates#201]
When an enemy fake cast, the cast bar stay when this enemy move. this is awful. i use Quatre.
can you fix it ?

**Comment by Luxocracy** [comment]
Assuming this for Classic it is a no.

Classic has very limited information when it comes to units casting spells. And there is no way to detect the outcome of a spell cast, successful or not, in Classic. All the information we really have access to is that a spell was used.
