### ISSUE TITLE
Health bars are not full at 100% health

### ISSUE THREAD

**Issue by melforx** [Luxocracy/NeatPlates#203]
After updating today, I have the issue, that all health bars appear as if the units were on 50-60 percent health, when they're actually 100 percent. 
![WoWScrnShot_041820_222945](https://user-images.githubusercontent.com/63930085/79670638-d8420580-81c4-11ea-8dd9-53b4e4cba45e.jpg)
The bars still shrink proportionally to the health value, so they're still working correctly, but it's initial size / length at 100% is not correct.

**Comment by Luxocracy** [comment]
Woops, this is because I forgot to remove some code I added while debugging earlier.
Will fix asap.
