### ISSUE TITLE
New patch broke the addon

### ISSUE THREAD

**Issue by Slaytanic420** [Luxocracy/NeatPlates#208]
Title says it all. Updated the patch today (04/29) that came out on April 25 (8.3.0.13) and now it doesn't work at all, but it DOES give me a pop up telling me that I'm not updated to the most recent version. I don't understand.

**Comment by Luxocracy** [comment]
If it's the popup I think it is then it is telling you that you are using the wrong version. For example using the classic version (1.13.4.xx) for BFA or vice versa.
If you are installing through the twitch client make sure it is installing the correct version as for some reason it gets confused sometimes.

**Comment by Slaytanic420** [comment]
I think I found the problem. It's Curse Client. It took 14 addons that I had and replaced them with the version designated for Classic. Now I have to uninstall Classic, uninstall all of those addons and replace them. Hopefully that will correct it.

**Comment by Slaytanic420** [comment]
Yup. That was it. Sorry to have bothered you. Thank you for your quick response. :)
