### ISSUE TITLE
Nameplates automatically turning off

### ISSUE THREAD

**Issue by kvanvolk** [Luxocracy/NeatPlates#209]
Heyy, so is there an option to stop name plates from automatically turning off outside of combat? Every time I leave combat it turns off the nameplates an turns them on when i enter combat and if im just casually running around and target someone I cannot see there healthbar unless i attack or press V which gets annoying after a while. Really enjoying the addon other than this minor issue. My question is, is there an option to keep name plates on all the time and not disappear out of combat?

**Comment by kvanvolk** [comment]
ps. Ive checked the force headline while out-of0combat and that hasnt helped either

**Comment by Luxocracy** [comment]
In the main neatplates settings there's an _Automation_ section that can handle nameplate automation.

But these aren't enabled by default. A common culprit is Leatrix plus, or similar addons. As they sometimes have options for nameplate automation.

**Comment by kvanvolk** [comment]
![image](https://user-images.githubusercontent.com/64628865/80786092-86986400-8b50-11ea-8c34-c6e40eddd064.jpg)

**Comment by kvanvolk** [comment]
So I have everything in the automation section set to green (show) and I have the dummy targeted to the left if you can see and still no health bar unless I attack or hit V. Leatrix isn’t the problem I checked that I also use immersive and unchecked for name plates to fade/disappear. I’m not sure where to go at this point :/

**Comment by Luxocracy** [comment]
The combat option shouldn't be set to green if you want nameplates to always show. Leave it white/off. As the combat option has priority over the others in a way.

**Comment by kvanvolk** [comment]
FIXED!! Thanks so much man I appreciate it love the addon glad it was simple:)

**Comment by kvanvolk** [comment]
Also one last question, unrelated. Is there a way in combat to auto target your next closest target after your current target is dead? I had it work on one of my characters but I didn’t do anything to make that happen it just kind of did it itself. Makes dungeons much easier lol

**Comment by Luxocracy** [comment]
Not through neatplates, but I do recall something like it possibly through CVars but not sure.
But usually I just tab if I want to swap targets easily.

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
