### ISSUE TITLE
Keeps deleting profiles and gives error

### ISSUE THREAD

**Issue by Busake** [Luxocracy/NeatPlates#210]
**Hey so i started doing this when i get inside citys:**

Message: ...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:448: Action[FrameMeasurement] failed because[Can't measure restricted regions]: attempted from: <unnamed>:GetLeft().
Time: Fri May  1 10:12:27 2020
Count: 2
Stack: ...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:448: Action[FrameMeasurement] failed because[Can't measure restricted regions]: attempted from: <unnamed>:GetLeft().
[string "=[C]"]: in function `GetLeft'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:448: in function `GetPreferredInsets'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:138: in function `UpdateInsetsForType'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:122: in function `ApplyFrameOptions'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:93: in function `OnNamePlateAdded'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:51: in function <...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:42>

Locals: (*temporary) = <unnamed> {
 otherHealPrediction = <unnamed> {
 }
 b = 0
 myHealAbsorbLeftShadow = <unnamed> {
 }
 border = <unnamed> {
 }
 background = <unnamed> {
 }
 overAbsorbGlow = <unnamed> {
 }
 barTexture = <unnamed> {
 }
 0 = <userdata>
 r = 0.999998
 totalAbsorb = <unnamed> {
 }
 myHealPrediction = <unnamed> {
 }
 g = 0.999998
 totalAbsorbOverlay = <unnamed> {
 }
 myHealAbsorbRightShadow = <unnamed> {
 }
 overHealAbsorbGlow = <unnamed> {
 }
 myHealAbsorb = <unnamed> {
 }
}

**and this one as well:**

Message: ...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:448: Action[FrameMeasurement] failed because[Can't measure restricted regions]: attempted from: <unnamed>:GetLeft().
Time: Fri May  1 10:12:27 2020
Count: 2
Stack: ...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:448: Action[FrameMeasurement] failed because[Can't measure restricted regions]: attempted from: <unnamed>:GetLeft().
[string "=[C]"]: in function `GetLeft'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:448: in function `GetPreferredInsets'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:138: in function `UpdateInsetsForType'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:122: in function `ApplyFrameOptions'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:93: in function `OnNamePlateAdded'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:51: in function <...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:42>

Locals: (*temporary) = <unnamed> {
 otherHealPrediction = <unnamed> {
 }
 b = 0
 myHealAbsorbLeftShadow = <unnamed> {
 }
 border = <unnamed> {
 }
 background = <unnamed> {
 }
 overAbsorbGlow = <unnamed> {
 }
 barTexture = <unnamed> {
 }
 0 = <userdata>
 r = 0.999998
 totalAbsorb = <unnamed> {
 }
 myHealPrediction = <unnamed> {
 }
 g = 0.999998
 totalAbsorbOverlay = <unnamed> {
 }
 myHealAbsorbRightShadow = <unnamed> {
 }
 overHealAbsorbGlow = <unnamed> {
 }
 myHealAbsorb = <unnamed> {
 }
}

**Comment by Luxocracy** [comment]
Could you disable all other addons just to make sure it is actually neatplates causing this issue because I see nothing related to neatplates in these errors other than it saying nameplate.

**Comment by Busake** [comment]
Hey thanks for answer,

i will try disable everything then start with your mod and add other mods 1 at the time (when i get home from work)

**Comment by Busake** [comment]
So, oddly enough the error hasen't showed up yet and i done the disable all, and add 1 addon at the time tactic, i am now playing with all of them with no issues.

Really weird, thanks for the support!

**Comment by Busake** [comment]
So.. it did it again later on yesterday, same error.

When i went in the NeatPlates interface half of the menu was missing, i closed it and re-opened it and the headline was stuck in the menu, staying at the same spot even though i scrolled down, 3rd time it went back to normal and i got the errors, seems to happen when entering a restet place with other players as it pops up when i enter Boralus.

Let me know if you have any ideas.

**Comment by Luxocracy** [comment]
That sounds like a serious issue, possibly some form of corruption. I'd recommend you try to uninstall the addon removing any savedvariables associated with, and then installing it again.

There is really no reason the menu would be messed up due to an error related to nameplates.

**Comment by Busake** [comment]
I actually removed Neatplates and installed Tidy plates when it statede happening, didnt get error but that probably means nothing as it appear random.

I went back to Neatplates as i like all the extra options, it is Neat so to speak :]

I think you're right, im probably facing a complete Re-install of my OS and programs, things has bugged other places as well recently, or maybe my HDD is soon on the last spins :[

Ill update on this after a few days, thanks for suggestions :)

**Comment by Luxocracy** [comment]
You're not accidentally running both tidyplates and neatplates at once are you? Because that would definitely cause issues.

**Comment by Busake** [comment]
I am not, i currently only have Neatplates, do you happen to know where the profile for addons are stored? i want to save a few and reinstall everything :x

**Comment by Luxocracy** [comment]
`World of Warcraft\_retail_\WTF\Account\{ACCOUNT_NAME/ID}\SavedVariables`
for global addon settings, though some might be per character and then they are stored in 
`World of Warcraft\_retail_\WTF\Account\{ACCOUNT_NAME/ID}\{SERVER_NAME}\{CHARACTER_NAME}\SavedVariables`

**Comment by Busake** [comment]
Okey so ive tried to reinstall all addons and so on but it still gives errors.

Discovered : If i go to (Nameplate Style) and check the (Player) under Friendly Health Bars it gives a error on my pc.

I got 2 other Addons active: Z-Pearls and Raider IO.

Im exporting the profile i use here in case you wanna check it out : ^1^T^STextShowOnlyOnActive^b^SWidgetAuraSort^N1^STextShowOnlyOnTargets^b^SWidgetBuffEnrage^b^SUnitSpotlightLookup^T^t^SEnableOffTankHighlight^b^SBorderBuffEnrage^N1^SOpacityFilterNonElite^b^STheme^SSlim~`Horizontal^SSpellCastEnableFriendly^b^SWidgetPandemic^b^SStyleEnemyBarsInstanceMode^b^SFriendlyNameColorMode^SByHealth^SHighlightMouseoverScale^T^Sy^N1^Sx^N1^Soffset^T^Sy^N0^Sx^N0^t^t^SColorTarget^T^Sa^F9007179390517248^f-53^Sr^F9007179390517248^f-53^Sg^F9007179390517248^f-53^Sb^F9007179390517248^f-53^t^SColorThreatWarning^T^Sa^F9007179390517248^f-53^Sr^F7205743405039616^f-53^Sg^N0^Sb^N0^t^SWidgetRangeMode^N1^SOpacityNonTarget^N0.5^SEmphasizedSlots^N1^SFilterScaleLock^b^SStyleEnemyBarsOnElite^B^SStyleEnemyBarsNoTotem^b^SIntCastWhoEnable^B^SOpacityFilterFriendlyNPC^b^SUnitSpotlightColor^T^Sb^N0^Sg^N0^Sr^N0.8^t^SStyleEnemyBarsClickThrough^b^SStyleFriendlyBarsClickThrough^b^SStatusTextRight^N7^SHideAuraInHeadline^b^SFrameVerticalPosition^N0.7^SHighlightFocustMode^N1^SCustomColorList^S^SWidgetEnableExternal^B^SWidgetQuestIcon^b^SWidgetBuffFilter^N1^STextColorNeutral^T^Sa^F9007179390517248^f-53^Sr^F8901212883648512^f-53^Sg^F6358009202606080^f-53^Sb^F7629611043127296^f-56^t^SStatusTextCenterColor^B^SSpellIconEnable^B^STextColorGuildMember^T^Sa^F9007179390517248^f-53^Sr^F8477345245560832^f-55^Sg^F5934141564518400^f-53^Sb^F9007179390517248^f-53^t^SScaleFunctionMode^SByThreat^SStyleEnemyMode^N1^SHighlightTargetMode^N2^SHeadlineFriendlySubtext^SRoleGuildLevel^SEnemyBarColorMode^SByThreat^SWidgetBuffPurgeable^b^SWidgetThreatIndicator^B^SHeadlineEnemyColor^N4^SWidgetAuraScaleOptions^T^Sy^N1^Sx^N1^Soffset^T^Sy^N0^Sx^N0^t^t^SUnitSpotlightOpacityEnable^B^SOpacityFilterNonPartyMembers^b^SStyleFriendlyBarsInstanceMode^b^SColorFriendlyNPC^T^Sa^F9007179390517248^f-53^Sr^N0^Sg^F9007179390517248^f-53^Sb^N0^t^SPreciseAuraThreshold^N10^SWidgetAuraTrackMagic^b^SScaleMouseoverSpotlight^b^STextColorFriendlyPlayer^T^Sa^F9007179390517248^f-53^Sr^F8477345245560832^f-55^Sg^F5934141564518400^f-53^Sb^F9007179390517248^f-53^t^SOpacityFilterMini^b^SFriendlyStatusTextMode^SHealthFunctionLevel^SOpacityFullNoTarget^b^SUnitSpotlightOpacity^N1^SStatusTextLeftColor^B^SCastbarDurationMode^SNone^SCastBarWidth^N1^SColorHighHealth^T^Sa^F9007179390517248^f-53^Sr^N0^Sg^F9007179390517248^f-53^Sb^F7205743405039616^f-55^t^SColorRangeFar^T^Sa^F9007179390517248^f-53^Sr^F9007179390517248^f-53^Sg^F4521250869215232^f-53^Sb^N0^t^SStyleHeadlineMiniMobs^b^STextShowLevel^b^SHeadlineEnemySubtext^SRoleGuildLevel^SHeadlineFriendlyColor^N4^SOpacityFilterFriendlyPlayers^b^SWidgetDebuffPriority^T^S339^N4^SFacepalm~`Bolt^N7^SRake^N1^SRip^N2^SRejuvenation^N6^SMoonfire^N3^SRegrowth^N5^t^SEmphasizedAuraList^S^SStyleFriendlyBarsOnElite^b^SStyleFriendlyBarsNoMinions^b^SColorThreatTransition^T^Sa^F9007179390517248^f-53^Sr^F9007179390517248^f-53^Sg^F5651563854954496^f-53^Sb^N0^t^SColorHealthBarMode^N3^SStyleFriendlyBarsOnActive^b^SAuraScale^N1^SColorPandemic^T^Sa^F9007179390517248^f-53^Sr^F8124122840170496^f-53^Sg^F5368985608519680^f-55^Sb^F5368985608519680^f-55^t^SBorderBuffPurgeable^N1^SFriendlyBarColorMode^SByReaction^STextStatusForceShadow^b^SStyleHeadlineOutOfCombat^b^SAltShortening^b^SWidgetDebuffLookup^T^S339^N1^SFacepalm~`Bolt^N5^SRake^N2^SRip^N2^SRejuvenation^N2^SMoonfire^N2^SRegrowth^N2^t^SEnemySubtext^SNone^SColorNeutral^T^Sa^F9007179390517248^f-53^Sr^F9007179390517248^f-53^Sg^F9007179390517248^f-53^Sb^N0^t^SColorHostilePlayer^T^Sa^F9007179390517248^f-53^Sr^F9007179390517248^f-53^Sg^N0^Sb^N0^t^STextColorPartyMember^T^Sa^F9007179390517248^f-53^Sr^F8477345245560832^f-55^Sg^F5934141564518400^f-53^Sb^F9007179390517248^f-53^t^STextShowUnitTitle^b^SColorHostileNPC^T^Sa^F9007179390517248^f-53^Sr^F9007179390517248^f-53^Sg^N0^Sb^N0^t^SScaleSpotlightMode^N2^SUnitSpotlightGlowEnable^B^SWidgetAuraTrackDisease^b^SClassIconScaleOptions^T^Sy^N1^Sx^N1^Soffset^T^Sy^N0^Sx^N0^t^t^SStyleForceBarsOnTargets^b^SEmphasizedAuraPriority^T^t^SStyleEnemyBarsOnActive^B^SColorGuildMember^T^Sa^F9007179390517248^f-53^Sr^F8477345245560832^f-55^Sg^F5934141564518400^f-53^Sb^F9007179390517248^f-53^t^SClassColorPartyMembers^b^SSpacerSlots^N1^SScaleIgnoreNeutralUnits^B^SColorBuffPurgeable^T^Sa^F9007179390517248^f-53^Sr^N0^Sg^F7205743405039616^f-54^Sb^F9007179390517248^f-53^t^SWidgetAuraTrackCurse^b^SEmphasizedUnique^b^SOpacitySpotlightMouseover^b^SUnitSpotlightScaleEnable^B^SThreatWarningMode^SAuto^SColorPartyAggroText^b^STextColorElite^T^Sa^F4521250869215232^f-53^Sr^F8124122840170496^f-53^Sg^F6322686854692864^f-53^Sb^F5439629767475200^f-54^t^SScaleFiltered^N0.8^SOpacityFilterUntitledFriendlyNPC^b^SOpacityFilterEnemyPet^b^SScaleTargetSpotlight^b^SHideCooldownSpiral^b^SWidgetAuraAlignment^N1^SOpacityFilterList^SFanged~`Pit~`Viper~JLiberated~`Karabor~`Prisoner^SStyleFriendlyBarsOnPlayers^b^SUnitSpotlightList^S^SBorderPandemic^N1^SCustomMouseoverColor^b^SColorShowPartyAggro^b^SWidgetRangeUnits^N2^SStyleEnemyBarsOnNPC^B^SEnemyAlphaSpotlightMode^SNone^SOpacitySpotlightRaidMarked^b^SColorThreatSafe^T^Sa^F9007179390517248^f-53^Sr^F8477345245560832^f-57^Sg^F5298340912693248^f-53^Sb^F8124122840170496^f-53^t^SWidgetDebuff^b^SOpacityFilterLookup^T^SFanged~`Pit~`Viper^B^SLiberated~`Karabor~`Prisoner^B^t^SFocusAsTarget^b^SColorBuffEnrage^T^Sa^F9007179390517248^f-53^Sr^F9007179390517248^f-53^Sg^N0^Sb^F7205743405039616^f-55^t^SStyleFriendlyMode^N2^STextHealthTextMode^N1^SCustomization^T^SNameOnly^T^t^SDefault^T^t^SWidgetConfig^T^t^t^SOpacityFilterFriendlyPet^b^SWidgetAbsorbIndicator^b^SWidgetRangeIndicator^b^SWidgetAbsorbMode^N1^SSpellCastEnableEnemy^B^SOpacityFilterPartyMembers^b^SAdvancedEnableUnitCache^B^SColorMouseover^T^Sa^F9007179390517248^f-53^Sr^F9007179390517248^f-53^Sg^F9007179390517248^f-53^Sb^F9007179390517248^f-53^t^SEnemyStatusTextMode^SHealthFunctionNone^SColorRangeMelee^T^Sa^N0^Sr^F8124122840170496^f-53^Sg^F8124122840170496^f-53^Sb^F8124122840170496^f-53^t^SColorUnIntpellCast^T^Sa^F9007179390517248^f-53^Sr^F4627217912954880^f-53^Sg^F6781876303822848^f-53^Sb^F6887843347562496^f-53^t^SWidgetRangeScaleOptions^T^Sy^N1^Sx^N1^Soffset^T^Sy^N0^Sx^N0^t^t^SCustomColorLookup^T^t^SStyleHeadlineNeutral^b^SHighlightMouseoverMode^N2^SWidgetComboPointsScaleOptions^T^Sy^N1^Sx^N1^Soffset^T^Sy^N0^Sx^N0^t^t^SOpacityFilterNeutralUnits^b^SScaleIgnoreNonEliteUnits^b^SWidgetDebuffStyle^N1^SCustomTargetColor^b^SWidgetRangeMax^N40^STextColorFriendlyNPC^T^Sa^F9007179390517248^f-53^Sr^F6781876303822848^f-54^Sg^F7912188752691200^f-53^Sb^F5227696216866816^f-55^t^SOpacityFilterEnemyNPC^b^SEmphasizedAuraLookup^T^t^SStyleEnemyBarsNoMinions^b^SStatusTextLeft^N8^SColorPartyAggro^T^Sa^F9007179390517248^f-53^Sr^F9007179390517248^f-53^Sg^N0^Sb^F7205743405039616^f-54^t^SClassPartyIcon^b^SOpacityFilterLowLevelUnits^b^SUnitSpotlightScale^N1.4^SEnemyNameColorMode^SDefault^SStatusTextCenter^N5^SColorMediumHealth^T^Sa^F9007179390517248^f-53^Sr^F9007179390517248^f-53^Sg^F9007179390517248^f-53^Sb^N0^t^SWidgetTargetHighlight^B^SWidgetDebuffTrackList^SMy~`Rake~JMy~`Rip~JMy~`Moonfire~JAll~`339~JMy~`Regrowth~JMy~`Rejuvenation~JNot~`Facepalm~`Bolt^SClassEnemyIcon^b^SOpacitySpotlight^N0.85^SOpacityFiltered^N0^SOpacityTarget^N1^SOpacityFilterInactive^b^SHighHealthThreshold^N0.7^SStatusTextRightColor^B^STextColorHostileNPC^T^Sa^F9007179390517248^f-53^Sr^F9007179390517248^f-53^Sg^F7205743405039616^f-55^Sb^F4521250869215232^f-55^t^SColorLowHealth^T^Sa^F9007179390517248^f-53^Sr^F9007179390517248^f-53^Sg^N0^Sb^N0^t^SStyleShowPowerBar^b^STextShowServerIndicator^B^STextColorHostilePlayer^T^Sa^F9007179390517248^f-53^Sr^F9007179390517248^f-53^Sg^F7205743405039616^f-55^Sb^F4521250869215232^f-55^t^SWidgetAuraTrackPoison^b^STextNameColorMode^N1^SColorDangerGlowMode^N2^SWidgetComboPointsStyle^N2^SStyleEnemyBarsOnPlayers^B^SColorRangeOOR^T^Sa^F9007179390517248^f-53^Sr^F8124122840170496^f-53^Sg^F7912188752691200^f-57^Sb^F5368985608519680^f-56^t^SThreatGlowEnable^B^SWidgetTotemIcon^b^SColorTapped^T^Sa^F9007179390517248^f-53^Sr^F7770899897909248^f-54^Sg^F7770899897909248^f-54^Sb^F7770899897909248^f-54^t^SHighlightFocusScale^T^Sy^N1^Sx^N1^Soffset^T^Sy^N0^Sx^N0^t^t^SHighlightTargetScale^T^Sy^F7791227441250303^f-52^Sx^F6485183184240638^f-52^Soffset^T^Sy^N0^Sx^N0^t^t^SOpacitySpotlightSpell^b^SColorRangeClose^T^Sa^F9007179390517248^f-53^Sr^F7912188752691200^f-57^Sg^F7876866941648896^f-53^Sb^F7417676955648000^f-53^t^SWidgetAbsorbUnits^N1^STextUseBlizzardFont^b^SColorAttackingOtherTank^T^Sa^F9007179390517248^f-53^Sr^F8477345245560832^f-57^Sg^F6004786260344832^f-53^Sb^F7064454550257664^f-53^t^SWidgetRangeScale^b^SScaleStandard^N0.9^SWidgetAuraTrackDispelFriendly^b^SFrameBarWidth^N1^SFriendlyAlphaSpotlightMode^SNone^SScaleIgnoreInactive^b^SOpacityFilterEnemyPlayers^b^SColorPartyAggroGlow^B^SColorFriendlyPlayer^T^Sa^F9007179390517248^f-53^Sr^N0^Sg^N0^Sb^F9007179390517248^f-53^t^SCustomFocusColor^b^SWidgetDebuffFilter^N2^SColorPartyAggroBar^b^SColorNormalSpellCast^T^Sa^F9007179390517248^f-53^Sr^F8901212883648512^f-53^Sg^F4945117970432000^f-53^Sb^N0^t^SLowHealthThreshold^N0.3^SWidgetThreatPercentage^B^SHighlightFocusMode^N2^STextColorNormal^T^Sa^F7205743405039616^f-54^Sr^F5863497405562880^f-53^Sg^F5863497405562880^f-53^Sb^F5863497405562880^f-53^t^SColorIntpellCast^T^Sa^F9007179390517248^f-53^Sr^F9007179390517248^f-53^Sg^N0^Sb^N0^t^SWidgetEliteIndicator^B^SIntCastEnable^B^SWidgetComboPoints^B^SUseGlobalSet^b^SColorPartyMember^T^Sa^F9007179390517248^f-53^Sr^F8477345245560832^f-55^Sg^F5934141564518400^f-53^Sb^F9007179390517248^f-53^t^SFriendlyHeadlineColor^SByClass^SColorRangeMid^T^Sa^F9007179390517248^f-53^Sr^F5086407362084864^f-57^Sg^F7806222245822464^f-53^Sb^N0^t^SEnemyHeadlineColor^SByReaction^SScaleSpotlight^N1.41^SHideAuraDuration^b^SColorFocus^T^Sa^F9007179390517248^f-53^Sr^F9007179390517248^f-53^Sg^F9007179390517248^f-53^Sb^F9007179390517248^f-53^t^STextColorBoss^T^Sa^F7205743405039616^f-53^Sr^F9007179390517248^f-53^Sg^F7664932854169600^f-53^Sb^F7347032796692480^f-56^t^SThreatMode^N1^SUnitSpotlightBarEnable^B^SWidgetRangeStyle^N1^SScaleCastingSpotlight^b^SStyleFriendlyBarsOnNPC^b^SFriendlySubtext^SUnitTitle^SStyleFriendlyBarsNoTotem^b^t^^

**Comment by Luxocracy** [comment]
I did get an error from using your profile, but it wasn't the one you posted. When subtext is used and the aura widget is off it throws an error because the subtext normally shifts the position of the auras. But since auras are turned off it fails to move their position. 
This could be what is causing issues for you, but it is quite odd that there is a different error for you.

I've corrected this in the latest version, so you could give that a try and see if that fixes the issue.

**Comment by Busake** [comment]
Ah sorry about that, in my eyes all the errors looked the same :[

I ursually dont turn stuff on i dont know what is so i have a tendency to leave them off, sorry ^^'

Awesome! Ive downloaded your latest update and are using it with no issues so far, i will report back in a day or so to make sure its resolved, thank you!

**Comment by Busake** [comment]
No more errors, works like a charm!
