### ISSUE TITLE
Neatplates broken

### ISSUE THREAD

**Issue by Marangwe** [Luxocracy/NeatPlates#211]
Updated today and go this error logging in:

 
Message: Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1909: 'end' expected (to close 'do' at line 1259) near '<eof>'
Time: Wed May 6 14:26:40 2020
Count: 4

**Comment by l-deniau** [comment]
Yep, got this error too.

Just an "end" is missing here :
https://github.com/Luxocracy/NeatPlates/blob/080eba86cd1e461f5f75e7f8bdad866c8e5f5194/NeatPlates/NeatPlatesCore.lua#L1336-L1349

**Comment by Luxocracy** [comment]
Yeah sorry seems there was a bad merge. Should be fixed now.
