### ISSUE TITLE
After latest update to WoW Classic Nameplates the following error occurs

### ISSUE THREAD

**Issue by bjhinkel** [Luxocracy/NeatPlates#212]
Date: 2020-05-07 13:21:31
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\NeatPlates\NeatPlatesCore.lua line 1909:
   'end' expected (to close 'do' at line 1259) near '<eof>'
Debug:
   
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  WowheadLooter, v11304
  Altoholic, vClassic v1.13.4-014
  Atlas, vv1.47.00.11303.00
  AtlasClassicWoW, vv1.47.00.11303.00
  AtlasLootClassic, vv1.5.1
  AtlasLootClassicData, vv1.5.1
  AtlasLootClassicDungeonsAndRaids, vv1.5.1
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  AutoDismount, v1.0.3
  BadBoy, vv1-classic
  BagBrother, v
  Bagnon, v8.3.5
  Bartender4, v4.9.0
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  ClassicClassColors, v1.0.0
  ClassicRaiderProfile, v1.1.0
  DataStore, vv1.13.013
  DataStoreAuctions, vv1.13-013
  DataStoreCharacters, vv1.13-013
  DataStoreContainers, vv1.13-013
  DataStoreCrafts, vv1.13-013
  DataStoreInventory, vv1.13-013
  DataStoreMails, vv1.13-013
  DataStoreQuests, vv1.13-013
  DataStoreReputations, vv1.13-013
  DBMCore, v1.13.44
  DBMDefaultSkin, v
  DBMSoundEventsPack, v1.6.5
  DBMStatusBarTimers, v
  DejaClassicStats, v1304r002
  Elephant, v1.13.3d
  GatherMate2, v1.45.5
  GroupCalendar, v
  GTFO, v4.55
  Identity2, v4.2.0
  LibHealComm40, v
  LightHeaded, vv11302-1.0.0
  MikScrollingBattleText, v5.7.149
  Misspelled, v1.7.7
  NeatPlates, v1.13.4.18
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=648)

**Comment by Luxocracy** [comment]
Update to 1.13.4.19 and the issue is resolved. The changes I made didn't merge as expected from the retail version and caused the issue, which is probably why you shouldn't release stuff right before going to bed...

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
