### ISSUE TITLE
Filtered Non-Titled Friendly NPC not working

### ISSUE THREAD

**Issue by ringuralte** [Luxocracy/NeatPlates#213]
Hello the option Filtered Non-Titled Friendly NPC doesn't seem to be working. I tried it with Tidy Plates and it seemed to work there.

**Comment by Luxocracy** [comment]
This should be fixed in the latest release, non-titled also counts quest units and that was changed a while back when there were some issues with the quest indicator, and that's what was causing issues with this filter.
