### ISSUE TITLE
Display enemy arena nameplates as numbers

### ISSUE THREAD

**Issue by techniqs** [Luxocracy/NeatPlates#216]
Hi!
There's a script which displays the enemy nameplates numerated instead of their names, which helps a lot with orientation in the arena.
Script is unfortunately not working and I'm guessing it's interfering with the addon.
Below is the stated script.
`/run local U=UnitIsUnit hooksecurefunc("CompactUnitFrame_UpdateName",function(F)if IsActiveBattlefieldArena()and F.unit:find("nameplate")then for i=1,5 do if U(F.unit,"arena"..i)then F.name:SetText(i)F.name:SetTextColor(1,1,0)break end end end end)`
(FYI script has to be re-entered everytime UI reloads, idk if this knowledge is necessary)
I would love an option to somehow enumerate the nameplates !
Here's a screenshot to visualize what I'm talking about
![image](https://user-images.githubusercontent.com/17085186/82893244-00095380-9f51-11ea-8202-f56e6b9ea32c.png)

Regards

**Comment by Luxocracy** [comment]
I've added a new option for this in the latest release under _Other Widgets_, it's something I've been meaning to do for awhile but never gotten around to. You can also set _Status/Subtext_ to _Arena ID_, which will do the same thing.

**Comment by techniqs** [comment]
Nice work! Is there also an option to disable enemy names in arena? I still find myself looking at the name instead of the ID, also it seems little bit hard to configure since i can only see the ID in the arena game. Or maybe just lack of my knowledge how to configure the addon?

**Comment by Luxocracy** [comment]
It being hard to configure is a general issue with the customization at the moment, but sadly I don't have a quick solution for it. Ideally I would like to add either a test mode or that the thing you are editing shows up as a preview. But this is problematic as a lot of them need quite a bit of different information before they will even consider showing up.
But it is something I'm aware of and will hopefully resolve at some point.

As for disabling names while in arena, there currently isn't anything like that.

**Comment by Luxocracy** [comment]
I made the Arena ID show up, kinda like a test mode, while the _Theme Customization_ menu is open in the latest release to help with the configuration issue of it. Other things might get a similar treatment in the future but I'll have to see if this is a good approach for it or not.

**Comment by techniqs** [comment]
Thanks a lot for the quick implementation, will definitely check it out!

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
