### ISSUE TITLE
Don't show a powerbar for units with no power

### ISSUE THREAD

**Issue by wodim** [Luxocracy/NeatPlates#219]
![image](https://user-images.githubusercontent.com/1001553/83743716-62eaa100-a65b-11ea-8241-df0e2abc2ee3.png)

It would be nice if the powerbar wouldn't show for units that have no power. Currently it looks odd for those units, like some sort of shadow.

**Comment by Luxocracy** [comment]
I've fixed this in the latest release, the game apparently reports them as having rage even though their max power is 0.

**Comment by wodim** [comment]
Oh yeah. Thank you.
