### ISSUE TITLE
Using the Blizzard Theme, having health bars turned off for any unit will still show the outline of a health bar when hovering over them.

### ISSUE THREAD

**Issue by Zythixx** [Luxocracy/NeatPlates#221]
![InvisibleHealthBar](https://user-images.githubusercontent.com/62533923/83844363-d7adf180-a6d4-11ea-891e-03642daad9b2.png)

This image is from Retail. I don't know if it acts the same way in Classic.

**Comment by Luxocracy** [comment]
This is most likely related to the highlighting options and them not getting disabled for headline mode properly. I'll look into it later today, but if it really annoys you, you can turn off highlighting on mouseover and it should go away until it gets fixed.

**Comment by Zythixx** [comment]
It's also worth noting that, along with this bug, elite unit's skull icons don't disappear either when the health bar is hidden.

**Comment by Luxocracy** [comment]
Well the elite/skull icon remaining is intended, if you wish to disable them in **_Headline mode_** you can change it in the _**Theme Customization**_ by changing the _**Style Mode**_ to _**Headline/Text-Only**_ and unchecking _**Element Enabled**_ for elite/skull icon.

As for the highlighting issue, it should be fixed as of the latest release.
