### ISSUE TITLE
Not able to use the addon on retail

### ISSUE THREAD

**Issue by Wenkie** [Luxocracy/NeatPlates#222]
Hi,
Maybe I'm just being dumb, but I can't seem to make NeatPlates work. The newest version of the addon was installed, and it is activated, but the commands /neatplates and /np won't work and it does not show up in the addon list from Interface. What am I doing wrong?
Thanks,
Wenkie.

**Comment by Luxocracy** [comment]
Make sure you've got the retail(8.3.0.xx) version installed and not the classic(1.13.4.xx) one. That's about the only thing I can think of it being.

**Comment by Wenkie** [comment]
I deleted the whole file and re-downloaded it, and now it works. Dunno, maybe something went wrong during the first download.
