### ISSUE TITLE
Class Icons are not showing correct, wrong classes

### ISSUE THREAD

**Issue by nectarines** [Luxocracy/NeatPlates#224]
I can't get Neatplates to show the correct icons for targets, it sometimes shows the correct class, but then it bugs and constantly changes.

Sometimes a warrior is a druid, warlock, paladin, shaman, etc.
Sometimes a paladin is a warlock, mage, rogue, etc.

Any help would be appreciated as this is really confusing mid battle
![WoWScrnShot_060820_130948](https://user-images.githubusercontent.com/32919019/84077534-55e7ed80-a98c-11ea-8b68-097021266b32.jpg)

![WoWScrnShot_060820_132856](https://user-images.githubusercontent.com/32919019/84077547-5da79200-a98c-11ea-8552-b3f186db9e2b.jpg)
Im targeting a Rogue, it shows Warlock.

![WoWScrnShot_060820_133723](https://user-images.githubusercontent.com/32919019/84079166-fd661f80-a98e-11ea-8c41-706d7661c73b.jpg)
Here im targeting a Shaman, but it shows Warrior.

![WoWScrnShot_060820_133707](https://user-images.githubusercontent.com/32919019/84079228-18d12a80-a98f-11ea-8cd9-fcfebbef2f04.jpg)
Here im targeting a Mage, it show Warlock.

Clearly im targeted on a different class than showing on the class icon, what is causing this, or how to fix it?

**Comment by Luxocracy** [comment]
Seems it's a bug in the latest release, it's creating multiple class icons on top of each other instead of replacing the existing one. I'll fix it and push a new release asap.

**Comment by nectarines** [comment]
I had just turned this setting on, so I had no idea it was ever working properly, thank you for letting me know!

**Comment by Luxocracy** [comment]
There is a new release pending on curse but it's being rather slow right now for some reason. But it will be up at some point soonish.
