### ISSUE TITLE
Large mobs tanking inconvinience

### ISSUE THREAD

**Issue by hasnogaems** [Luxocracy/NeatPlates#225]
![2020-06-05 06_08_03-#general-tank - Discordanonimous-pc](https://user-images.githubusercontent.com/14231492/84263158-a34c9200-ab27-11ea-9d51-62861373100c.png)
It is from warrior discord tank channel. I think there is no covenient tool atm in classic or maybe even in retail for monitoring aggro on multiple large mobs. Because monitoring through color changing plates becoming unavailable or very uncomfortable. Is there any way it could be improved in neatplates? I thought about double plates on certain big mobs that on the list, something like that:
![WoWScrnShot_011220_12124adad8](https://user-images.githubusercontent.com/14231492/84263805-d3486500-ab28-11ea-89df-5747cbe20a15.jpg)
Or not double, maybe just reposition plates but only on big ones?

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
