### ISSUE TITLE
Error on Horde Side

### ISSUE THREAD

**Issue by Yarvillian** [Luxocracy/NeatPlates#226]
This is the error message I am receiving on Horde Side. Not sure why only horde but whenever I see any plates they are blizzard default and cause constant errors:
72x NeatPlates\NeatPlatesCore.lua:769: attempt to index field 'subtext' (a nil value)
[string "@NeatPlates\NeatPlatesCore.lua"]:769: in function `UpdateIndicator_Subtext'
[string "@NeatPlates\NeatPlatesCore.lua"]:723: in function <NeatPlates\NeatPlatesCore.lua:719>
[string "@NeatPlates\NeatPlatesCore.lua"]:386: in function <NeatPlates\NeatPlatesCore.lua:372>
[string "@NeatPlates\NeatPlatesCore.lua"]:510: in function <NeatPlates\NeatPlatesCore.lua:500>
[string "@NeatPlates\NeatPlatesCore.lua"]:182: in function <NeatPlates\NeatPlatesCore.lua:159>

Locals:
text = nil
r = nil
g = nil
b = nil
a = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "nameplate4"
(*temporary) = 470800
(*temporary) = 470800
(*temporary) = nil
(*temporary) = "attempt to index field 'subtext' (a nil value)"
style = <table> {
 powerbar = <table> {
 }
 subtext = <table> {
 }
 extrabar = <table> {
 }
 target = <table> {
 }
 level = <table> {
 }
 healthbar = <table> {
 }
 healthborder = <table> {
 }
 targetindicator_arrowright = <table> {
 }
 mouseover = <table> {
 }
 durationtext = <table> {
 }
 name = <table> {
 }
 hitbox = <table> {
 }
 raidicon = <table> {
 }
 customtext = <table> {
 }
 targetindicator = <table> {
 }
 eliteicon = <table> {
 }
 extratext = <table> {
 }
 focus = <table> {
 }
 extraborder = <table> {
 }
 castbar = <table> {
 }
 targetindicator_arrowleft = <table> {
 }
 highlight = <table> {
 }
 threatborder = <table> {
 }
 skullicon = <table> {
 }
 threatcolor = <table> {
 }
 targetindicator_arrowtop = <table> {
 }
 spelltext = <table> {
 }
 castborder = <table> {
 }
 spellicon = <table> {
 }
 targetindicator_arrowsides = <table> {
 }
 frame = <table> {
 }
 rangeindicator = <table> {
 }
 castnostop = <table> {
 }
}
activetheme = <table> {
 SetCastbarColor = <function> defined @NeatPlatesHub\functions\Color.lua:304
 SetCastbarDuration = <function> defined @NeatPlatesHub\functions\Text.lua:612
 SetAlpha = <function> defined @NeatPlatesHub\functions\Alpha.lua:145
 DefaultBackup = <table> {
 }
 OnChangeProfile = <function> defined @NeatPlatesHub\functions\Core.lua:534
 SetStyle = <function> defined @NeatPlatesHub\functions\Style.lua:146
 WidgetConfig = <table> {
 }
 SetThreatColor = <function> defined @NeatPlatesHub\functions\Color.lua:402
 WidgetConfigBackup = <table> {
 }
 SetScale = <function> defined @NeatPlatesHub\functions\Scale.lua:144
 OnContextUpdate = <function> defined @NeatPlatesHub\functions\Widgets.lua:624
 NameOnlyBackup = <table> {
 }
 SetSubText = <function> defined @NeatPlatesHub\functions\Text.lua:563
 NameOnly = <table> {
 }
 ApplyProfileSettings = <function> defined @NeatPlatesHub\functions\Core.lua:460
 OnActivateTheme = <function> defined @NeatPlatesHub\functions\Core.lua:525
 SetPowerbarColor = <function> defined @NeatPlatesHub\functions\Color.lua:288
 OnInitialize = <function> defined @NeatPlatesHub\functions\Core.lua:519
 Default = <table> {
 }
 SetCustomText = <function> defined @NeatPlatesHub\functions\Text.lua:377
 ApplyThemeCustomization = <function> defined @NeatPlatesHub\functions\Core.lua:313
 SetNameColor = <function> defined @NeatPlatesHub\functions\Color.lua:567
 OnUpdate = <function> defined @NeatPlatesHub\functions\Widgets.lua:655
 SetHealthbarColor = <function> defined @NeatPlatesHub\functions\Color.lua:241
}
unit = <table> {
 guid = "Player-61-0CAFE332"
 isMouseover = true
 class = "MAGE"
 rawName = "Fieryhobbs"
 threatSituation = "LOW"
 red = 0
 levelcolorRed = 1
 unitid = "nameplate4"
 isPet = false
 isMini = false
 pvpname = "Elder Fieryhobbs"
 levelcolorBlue = 0
 powermax = 100000
 isBoss = false
 isTrivial = false
 isFocus = false
 healthmax = 470800
 isTarget = false
 levelcolorGreen = 0.820000
 isInCombat = false
 absorbmax = 0
 isTapped = false
 absorb = 0
 blue = 0.999998
 power = 100000
 style = "Default"
 isMarked = false
 level = 120
 type = "PLAYER"
 isCasting = false
 reaction = "FRIENDLY"
 green = 0
 health = 470800
 threatValue = 0
 isDangerous = false
 name = "Fieryhobbs"
}
visual = <table> {
 highlight = <unnamed> {
 }
 customtext = <unnamed> {
 }
 healthbar = <unnamed> {
 }
 healthborder = <unnamed> {
 }
 castborder = <unnamed> {
 }
 threatborder = <unnamed> {
 }
 skullicon = <unnamed> {
 }
 castnostop = <unnamed> {
 }
 spellicon = <unnamed> {
 }
 eliteicon = <unnamed> {
 }
 name = <unnamed> {
 }
 spelltext = <unnamed> {
 }

**Comment by Luxocracy** [comment]
Just gonna close this as you mentioned it being related to having another nameplate addon running at the same time, which makes sense as to why it would break.

**Comment by Yarvillian** [comment]
Forgot to close the ticket. You are right. My bad. Thank you man!
