### ISSUE TITLE
Request for guild identification

### ISSUE THREAD

**Issue by perjr** [Luxocracy/NeatPlates#227]
Hello!

Im not sure if this is the correct way to add a request/suggestion but here goes.

Would it be possible to add the option for a "custom color" or some sort of easy identification on the nameplate of a friendly player if its a guildmate. I've spoken to several ppl in my guild (its a huge social lvl'ing guild) and they all think its a good idea. It would be easy to identify guildes in big ciapitals with tons of players.

Thanks for considering and thanks for a great addon!

//Kim

**Comment by Luxocracy** [comment]
Under the _Reaction_ section you can customize the color of guild members. This hopefully is what you were looking for.

**Comment by perjr** [comment]
EXACTLY what i was looking for. Thank for very much for the hint and also for the fast reply!

Have a good one!
