### ISSUE TITLE
Can't disable "Show Threat Percentage"

### ISSUE THREAD

**Issue by bibbis** [Luxocracy/NeatPlates#228]
The "Show Threat Percentage" option under "Threat & Highlighting" seems to be permanently on.
I've tried setting it to on and off, reloading and restarting the game, but I can't get rid of the threat percentage.

**Comment by Luxocracy** [comment]
Are you sure you are editing the currently active profile? And if so, could you attach an image of the _Threat Percentage_ you are trying to remove just to make sure it belongs to NeatPlates, as I was unable to replicate the issue on my end.

**Comment by bibbis** [comment]
Yeah I'm attaching some screen shots!
I'm confused now because when I first wrote I was seeing the threat displayed as text below the target's health bar.
But now I am seeing a new little bar above the target health, and the text from earlier is gone.
![settings](https://user-images.githubusercontent.com/13263159/85451266-f7c92600-b599-11ea-8ea1-eff138465a4f.png)
![plate](https://user-images.githubusercontent.com/13263159/85451280-fc8dda00-b599-11ea-9895-d096ef0393df.png)

**Comment by Luxocracy** [comment]
If you try creating a new profile, does that allow you to change this option? It's possible the profile got messed up somehow and is preventing the change.
You could also try reinstalling the addon to make sure nothings gotten messed up during an update or something.

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
