### ISSUE TITLE
Debuff duration

### ISSUE THREAD

**Issue by Iristates** [Luxocracy/NeatPlates#230]
Hello, I've been using Neatplate since the first weeks of Classic and I'm using the same profile on all my characters.

Since this morning, the debuff duration isn't displayed anymore. I'll give you an example : with my rogue I often start the fight with "Cheap Shot", yesterday (and everytime) it showed the icon just above the HP bar with the duration (2-1.5-1-0.5 seconds) and then disappears. What I noticed now : the icon will still be displayed but the remaining duration is not, of course the icon will disappear when it's over.

I have the same problem for all the characters : mages debuffs, warrior, warlock and so on.

Thanks for the help.

**Comment by Luxocracy** [comment]
Not sure what it could be as the duration tracking is handled by another library and I haven't released anything new for two weeks or so due to it being summer etc. But the lib(LibClassicDurations) was updated yesterday, so if you have that installed separately that could be the culprit. Even thought I checked and the latest release seemingly works correctly.

**Comment by seanbewtz** [comment]
Im currently having the same issue. Ive gone through and played with some options to no result. Ive also went through and disabled some additional addons in hope that it may solve the issue but have had no luck. Also just want to say i love your addon by the way, really appreciate the work.

**Comment by Iristates** [comment]
Thanks for the answers, but can't understand where is the problem ...
Like seanbewtz I tried to disable all the others addons but nothing changed. You recommand me to download and install the LibClassicDuration ?

**Comment by Luxocracy** [comment]
You could try and see if that fixes the issue. And if it does I can push a new release just to update the included libs for anyone else potentially having the same issues

**Comment by Iristates** [comment]
That's awesome !! Thanks dude.

So I downloaded through Twitch the last version of LibClassicDuration (1.60 - 25/06/2020) and it works just perfectly ! I think it was the problem because I noticed the deletion of the debuff duration the exact same day they uploaded the new version.

Hope it will help other people !! Have a nice day.
