### ISSUE TITLE
Profile Problem - How can i delete this Profile?

### ISSUE THREAD

**Issue by Kaithos** [Luxocracy/NeatPlates#231]
Hey I accidentally created an incorrect profile, which I can no longer delete. 
I used copy and paste to create a profile name, but accidentally inserted a lua string as the name. 
when I move the mouse over the profile I get an error message and i can´t delete this profile... 
Reinstall didn´t help. The whole profile is broken so that I cannot click anything and get the message directly. 
How can i delete this Profile?

![neatplates2](https://user-images.githubusercontent.com/67704851/86271683-a0483d00-bbcd-11ea-8cbe-6dc3059f6107.jpg)
![neatplates1](https://user-images.githubusercontent.com/67704851/86271688-a3dbc400-bbcd-11ea-97fd-c8c7ae745099.jpg)

Lua Message:

Message: [string "HubPanelProfile^1^T^STextShowOnlyOnActive^b^SWidgetAuraSort^N1^STextShowOnlyOnTargets^b^SColorFriendlyBarMode^N1^SWidgetBuffEnrage^b^SUnitSpotlightLookup^T^t^SEnableOffTankHighlight^b^SBorderBuffEnrage^N1^SOpacityFilterNonElite^b^STheme^SNeon^SSpellCastEnableFriendly^b^SWidgetPandemic^b^SOpacityFilterPlayers^b^SStyleEnemyBarsInstanceMode^b^SFriendlyNameColorMode^SDefault^SHighlightMouseoverScale^T^Sy^N1^Sx^N1^Soffset^T^Sy^N0^Sx^N0^t^t^SColorTarget^T^Sa^F9007179390517248^f-53^Sr^F9007179390517248^f-53^Sg^F9007179390517248^f-53^Sb^F9007179390517248^f-53^t^SColorEnemyStatusTextMode^N1^SWidgetRangeMode^N1^SOpacityNonTarget^N0.5^SEmphasizedSlots^N1^SFilterScaleLock^b^SStyleEnemyBarsOnElite^B^SStyleEnemyBarsNoTotem^b^SIntCastWhoEnable^B^SOpacityFilterFriendlyNPC^b^SUnitSpotlightColor^T^Sr^N0.8^Sg^N0^Sb^N0^t^SFriendlySubtext^SNone^SStyleEnemyBarsClickThrough^b^SColorRangeMelee^T^Sa^N0^Sr^F8124122840170496^f-53^Sg^F8124122840170496^f-53^Sb^F8124122840170496^f-53^t^SWidgetDebuffFilter^N2^SStatusTextRight^N7^SStyleFri:OnShow"]:4: attempt to index field '?' (a nil value)
Time: Wed Jul  1 18:57:14 2020
Count: 2
Stack: [string "HubPanelProfile^1^T^STextShowOnlyOnActive^b^SWidgetAuraSort^N1^STextShowOnlyOnTargets^b^SColorFriendlyBarMode^N1^SWidgetBuffEnrage^b^SUnitSpotlightLookup^T^t^SEnableOffTankHighlight^b^SBorderBuffEnrage^N1^SOpacityFilterNonElite^b^STheme^SNeon^SSpellCastEnableFriendly^b^SWidgetPandemic^b^SOpacityFilterPlayers^b^SStyleEnemyBarsInstanceMode^b^SFriendlyNameColorMode^SDefault^SHighlightMouseoverScale^T^Sy^N1^Sx^N1^Soffset^T^Sy^N0^Sx^N0^t^t^SColorTarget^T^Sa^F9007179390517248^f-53^Sr^F9007179390517248^f-53^Sg^F9007179390517248^f-53^Sb^F9007179390517248^f-53^t^SColorEnemyStatusTextMode^N1^SWidgetRangeMode^N1^SOpacityNonTarget^N0.5^SEmphasizedSlots^N1^SFilterScaleLock^b^SStyleEnemyBarsOnElite^B^SStyleEnemyBarsNoTotem^b^SIntCastWhoEnable^B^SOpacityFilterFriendlyNPC^b^SUnitSpotlightColor^T^Sr^N0.8^Sg^N0^Sb^N0^t^SFriendlySubtext^SNone^SStyleEnemyBarsClickThrough^b^SColorRangeMelee^T^Sa^N0^Sr^F8124122840170496^f-53^Sg^F8124122840170496^f-53^Sb^F8124122840170496^f-53^t^SWidgetDebuffFilter^N2^SStatusTextRight^N7^SStyleFri:OnShow"]:4: attempt to index field '?' (a nil value)
[string "=[C]"]: ?
[string "*:OnShow"]:4: in function <[string "*:OnShow"]:1>
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\InterfaceOptionsFrame.lua"]:28: in function `InterfaceOptionsList_DisplayPanel'
[string "@Interface\FrameXML\InterfaceOptionsFrame.lua"]:46: in function `InterfaceOptionsListButton_OnClick'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals: 

Message: Interface\AddOns\NeatPlates\NeatPlatesUtility.lua:540: attempt to index field 'Label' (a nil value)
Time: Wed Jul  1 18:56:40 2020
Count: 1
Stack: Interface\AddOns\NeatPlates\NeatPlatesUtility.lua:540: attempt to index field 'Label' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\NeatPlates\NeatPlatesUtility.lua"]:540: in function `CreateCheckButton'
[string "@Interface\AddOns\NeatPlatesHub\Templates.lua"]:72: in function <Interface\AddOns\NeatPlatesHub\Templates.lua:70>
[string "@Interface\AddOns\NeatPlatesHub\Hub.lua"]:85: in function <Interface\AddOns\NeatPlatesHub\Hub.lua:73>
[string "@Interface\AddOns\NeatPlatesHub\Hub.lua"]:698: in function <Interface\AddOns\NeatPlatesHub\Hub.lua:688>
[string "@Interface\AddOns\NeatPlatesHub\Hub.lua"]:721: in function <Interface\AddOns\NeatPlatesHub\Hub.lua:715>
[string "@Interface\AddOns\NeatPlatesHub\Hub.lua"]:882: in function <Interface\AddOns\NeatPlatesHub\Hub.lua:867>

Locals:

**Comment by Luxocracy** [comment]
You'd probably need to edit or delete the _NeatplatesHub.lua_ file located in `WTF/Account/{ACCOUNT_ID}/SavedVariables`.

**Comment by Kaithos** [comment]
Thank you!!! It works ^^
