### ISSUE TITLE
Friendly Nameplates not working under certain level

### ISSUE THREAD

**Issue by Smolderos** [Luxocracy/NeatPlates#234]
After going crazy trying to figure out why the friendly npc nameplates weren't working for my new lvl 1 character, I did some testing. I found out that out of my multiple characters those that were lvl 77 or above had their friendly npc nameplates working and those that were lvl 55 or less didn't have working friendly npc nameplates. I didn't have any characters between 55 and 77 so I couldn't find out exactly where the problem goes away but you might wanna test this and look into it.

**Comment by Smolderos** [comment]
For the record, I deleted my WTF folder before testing this.

**Comment by Luxocracy** [comment]
This is most likely CVars related, try this command in the chat window.
`/run SetCVar("nameplateShowFriendlyNPCs", 1)`

This used to be on by default for new characters but for some reason Blizzard changed it to off. And as far as I know there isn't a way to turn it back on again in the standard interface options.

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
