### ISSUE TITLE
I want to only show timer for DOTs

### ISSUE THREAD

**Issue by fagitomania** [Luxocracy/NeatPlates#235]
For example Agony, shows ramp up ticks as well like the default blizzard behavior, below the timer. I just want the timer to show as numbers nothing else. Other namaplate addons let me customize that, or straight up dont show it.

**Comment by Luxocracy** [comment]
I can add an option for this, similar to how you can hide the aura duration. It's just never occurred to me that you would want to hide the stacks of an aura.

**Comment by fagitomania** [comment]
That would be great if you can do so. With agony its not exactly stacks of an aura, more like ramp up indicator, you have no control over it so its kinda useless info

**Comment by fagitomania** [comment]
Alright it works as expected, thank you very much for the change
