### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by yishuangfrank** [Luxocracy/NeatPlates#236]
Hi, Luxocracy.

I was wondering if you could add a text to show the mob's target, and the text is only showed when the mob is casting.

Maybe the text can be showed in the castbar.

**Comment by Luxocracy** [comment]
I think that if I were to add it to the castbar, it would have to replace the spellname, as the space on the castbar is already quite limited. An alternative is to add it as an option under _Status Text_ like the current _Target Of_ but only when casting so add an option along the lines of _Target of Spell/Ability_.

**Comment by yishuangfrank** [comment]
You are right, the length of castbar is limited.
I just found a string in wago(https://wago.io/SyMc9BD87).
It shows the target's name on the nameplate. How about it?

**Comment by yishuangfrank** [comment]
There is already the mob's name on the nameplate.
How about show the target' name under the castbar?

**Comment by Luxocracy** [comment]
Below would work in most cases, but there are some themes that have the spellname below the castbar rather than on/inside it.

**Comment by Luxocracy** [comment]
I've added this to the latest release.

**Comment by yishuangfrank** [comment]
Cool...
I will try it later.

**Comment by yishuangfrank** [comment]
Thanks for the update！

![1](https://user-images.githubusercontent.com/44251440/88019750-0c7ae880-cb5d-11ea-814e-9b53673ddd85.jpg)
To make it more compact, how about “Spell/Ability→Target's Name”？ And when the target is yourself，just show “You”(你 for Chinese).
![2](https://user-images.githubusercontent.com/44251440/88021037-58c72800-cb5f-11ea-9f97-ee514ab5427d.png)
![3](https://user-images.githubusercontent.com/44251440/88021043-5cf34580-cb5f-11ea-8041-0a2fde571288.jpg)

**Comment by Luxocracy** [comment]
I can add the **you** part, but putting the spell and target on the same line I would have to make it super wide. It already doesn't completely display the spell name of certain spells, at least in English, and gets cut off because the width is limited.

**Comment by yishuangfrank** [comment]
![2](https://user-images.githubusercontent.com/44251440/88022794-7fd32900-cb62-11ea-9d75-4a2dd4b1b376.png)
How about this？

In my opinion, the Nameplate(4 lines: Name, HealthBar, CastBar, Spell/Ability and Target's Name) is a bit high.

**Comment by Luxocracy** [comment]
It might be, but I don't want to adjust the entire theme just for this one niche feature. But what you described can be done through the theme customization quite easily by moving the Y position of the _Castbar Spell Text_ & _Castbar Spell Target_ up around 10-11px. And maybe reducing the font size a bit to make it fit within the castbar.

**Comment by yishuangfrank** [comment]
OK, I will try.
Thanks!

**Comment by Luxocracy** [comment]
If you haven't customized anything else within the theme customization you can import this and I think that should be enough.
`^1^T^SNameOnly^T^t^SDefault^T^Sspelltarget^T^Senabled^T^Svalue^B^Stype^Sactual^t^Salign^T^Svalue^SCENTER^Stype^Sactual^t^Sw^T^Svalue^N0^Stype^Soffset^t^Swidth^T^Svalue^N0^Stype^Soffset^t^Sy^T^Svalue^N9^Stype^Soffset^t^Sh^T^Svalue^N0^Stype^Soffset^t^Sheight^T^Svalue^N0^Stype^Soffset^t^Sanchor^T^Svalue^STOP^Stype^Sactual^t^Sx^T^Svalue^N0^Stype^Soffset^t^Ssize^T^Svalue^N10^Stype^Sactual^t^t^Sspelltext^T^Senabled^T^Svalue^B^Stype^Sactual^t^Salign^T^Svalue^SCENTER^Stype^Sactual^t^Sw^T^Svalue^N0^Stype^Soffset^t^Swidth^T^Svalue^N0^Stype^Soffset^t^Sy^T^Svalue^N11.5^Stype^Soffset^t^Sh^T^Svalue^N0^Stype^Soffset^t^Sheight^T^Svalue^N0^Stype^Soffset^t^Sanchor^T^Svalue^STOP^Stype^Sactual^t^Sx^T^Svalue^N0^Stype^Soffset^t^Ssize^T^Svalue^N9^Stype^Sactual^t^t^t^SWidgetConfig^T^t^t^^`

**Comment by yishuangfrank** [comment]
So nice of you...

**Comment by yishuangfrank** [comment]
And I noticed that Target's Name was colored by the class.
Color “You” as green may be more conspicuous.
Just a suggestion.

**Comment by Luxocracy** [comment]
I've colored it as red currently, because I figured red = danger.

**Comment by yishuangfrank** [comment]
DK is red too. But is OK

**Comment by Luxocracy** [comment]
I mean hunter is green too, but its quite different and the ">> <<" should help distinguish between the two even further.

**Comment by yishuangfrank** [comment]
![1](https://user-images.githubusercontent.com/44251440/88084772-77590d80-cbb7-11ea-8291-94ae64294ecf.jpg)
 Thanks！
