### ISSUE TITLE
BigDebuff Nameplates-Functions

### ISSUE THREAD

**Issue by EdisonSu768** [Luxocracy/NeatPlates#237]
hello @Luxocracy can NeatPlates shows BigDebuff Nameplates-Functions ?

btw, i used Blizzard theme, thanks

**Comment by Luxocracy** [comment]
Yes, I believe there should be support for this now.

**Comment by EdisonSu768** [comment]
Yeah,it works well, thanks for replying.
Anyway, BigDebuffs-functions icon will cover the level unit when use blizzard theme.

**Comment by Luxocracy** [comment]
Fairly sure you can configure the position of the icon in the settings of BigDebuffs.
