### ISSUE TITLE
LUA error when spells cast out of plate range

### ISSUE THREAD

**Issue by Jeremy7600** [Luxocracy/NeatPlates#238]
When a spell is cast by an enemy mob outside of plate range, this error will occur:

Message: Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1130: attempt to concatenate field 'unitid' (a nil value)
Time: Wed Jul 22 11:46:49 2020
Count: 4
Stack: Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1130: attempt to concatenate field 'unitid' (a nil value)
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1130: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1129>

Locals: (*temporary) = nil
(*temporary) = "target"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate field 'unitid' (a nil value)"
unit = <table> {
 spellInterruptible = true
 isCasting = true
 interrupted = false
 interruptLogged = false
}
L = <table> {
 Scenario = "Scenario"
 subtext = "Unit Subtext"
 Offset Width = "Offset Width"
 Low Health Threshold = "Low Health Threshold"
 subtext_tooltip = "The units subtext"
 Raid = "Raid"
 Quest = "Quest"
 LEFT = "LEFT"
 Might require a '/reload' to display correctly = "Might require a '/reload' to display correctly"
 Arrow(Left) = "Arrow(Left)"
 Profile Management = "Profile Management"
 Couldn't update the targets role. = "Couldn't update the targets role."
 Arrow(Right) = "Arrow(Right)"
 On Players = "On Players"
 Show Unit Title = "Show Unit Title"
 QuestWidget = "Quest Widget"
 target_tooltip = "Target highlight texture"
 VERSION_WARNING_PROMPT_TEXT = "You seem to be running the wrong version of this addon for your client, things will most likely not work correctly.

Please ensure that you are on the correct version before continuing to use this addon."
 Enemy Status Text = "Enemy Status Text"
 NPC Role, Guild, or Level = "NPC Role, Guild, or Level"
 Un-interruptible = "Un-interruptible"
 Maximum Alpha Distance = "Maximum Alpha Distance"
 Spotlight Mouseover Units = "Spotlight Mouseover Units"
 Filter Non-Titled Friendly NPC = "Filter Non-Titled Friendly NPC"
 Include Purgeable Buffs = "Include Purgeable Buffs"
 Friendly Status Text = "Friendly Status Text"
 The size of the interactable area of the nameplates = "The size of the interactable area of the nameplates"
 Spotlight Target Units = "Spotlight Target Units"
 Poison = "Poison"
 Nameplate Style = "Nameplate Style"
 Safe = "Safe"
 Arena ID, Health, and Power = "Arena ID, Health, and Power"
 spelltarget = "Castbar Spell Target"
 Display Debuffs that have been applied by you = "Display Debuffs that have been applied by you"
 Buffs & Debuffs = "Buffs & Debuffs"
 Second Spec = "Second Spec"
 Export Profile = "Export Profile"
 raidicon = "Raid Icon"
 CVars could not applied due to combat = "CVars could not applied due to combat"
 TOPRIGHT = "TOPRIGHT"
 extratext_tooltip = "Bar text for Nazjatar Bodyguards"
 Cast Bar Width (%) = "Cast Bar Width (%)"
 Focus Highlighting = "Focus Highlighting"
 On Raid Targets = "On Raid Targets"
 Cast Bars = "Cast Bars"
 Show Friendly Cast Bars = "Show Friendly Cast Bars"
 High Health Threshold = "High Health Threshold"
 Override Target/Spotlight Scale = "Override Target/Spotlight Scale"
 ArenaIcon = "Arena Icon"
 Arena = "Arena"
 castnostop = "Castborder (non-interruptible)"
 High Health = "High Health"
 Your 'Out of Range' distance = "Your 'Out of Range' distance"
 TOP = "TOP"
 All Theme Customizations have been reset. = "All Theme Customizations have been reset."
 spellicon = "Spell Icon"
 level = "Level Indicator"
 Friendly NPC = "Friendly NPC"
 On Damaged Units = "On Damaged Units"
 Amount of Emphasized Auras = "Amount of Emphasized Auras"
 Helps ensure that everything is working as intended by enforcing certain CVars = "Helps ensure that everything is working as intended by enforcing certain CVars"
 Show = "Show"
 Show Enemy Class Art = "Show Enemy Class Art"
 Show Target Highlight = "Show Target Highlight"
 Funky Stuff = "Funky Stuff"
 ThreatPercentageWidget = "Threat Percent Widget"
 Show Personal Resource on Target = "Show Personal Resource on Target"
 Friendly Nameplates = "Friendly Nameplates"
 Filter Friendly Players = "Filter Friendly Players"

**Comment by Luxocracy** [comment]
I wasn't able to reproduce this myself, but I should be able to add something to prevent this error either way. So it should be fixed in the next release.

**Comment by Jeremy7600** [comment]
Appears to be fixed, thanks!
