### ISSUE TITLE
Target of Spell Shows incorrectly sometimes.

### ISSUE THREAD

**Issue by yishuangfrank** [Luxocracy/NeatPlates#239]
Normally，it shows Target of Spell correctly.
![namepalate](https://user-images.githubusercontent.com/44251440/89104465-26b1a200-d44c-11ea-9a28-0fdf5af61af0.png)
![target frame](https://user-images.githubusercontent.com/44251440/89104476-3630eb00-d44c-11ea-936e-faa782c22cb7.png)
Kings' Rest，The Golden Serpent，Spell：Spit Gold
Target Frame：Target of Spell was Druid.
Nameplate：Target of Spell was Warrior(Tank).

**Comment by yishuangfrank** [comment]
Waycrest Manor，Sister Briar，Spell：Jagged Nettles

**Comment by Luxocracy** [comment]
I was thinking this might be an issue as the name is only updated at the start of a cast right now, and I know NPCs aren't entirely consistent with updating target immediately.

I'll see what I can do to make the target update mid cast if it gets changed. Or grab the target by some other means as I believe the correct target will always be listed in the combat log event.

**Comment by yishuangfrank** [comment]
Look forward to your good news...

**Comment by Luxocracy** [comment]
I was wrong about the combat log, it only logs the target on a successful cast rather than at the start. However, I did find an event for when units swap target that seems to do the trick. Hopefully it also fixes the issue with the bosses you mentioned.

**Comment by yishuangfrank** [comment]
Thanks, I will try it later.

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
