### ISSUE TITLE
Lua Errors

### ISSUE THREAD

**Issue by Noparentsguy** [Luxocracy/NeatPlates#240]
I constantly have this message pop on my screen, making WoW Classic unplayable with NeatPlates addon loaded:

Message: Interface\AddOns\NeatPlates\NeatPlatesCore.lua:338: Usage: UnitGUID("unit")
Time: Thu Aug 13 12:31:17 2020
Count: 393
Stack: Interface\AddOns\NeatPlates\NeatPlatesCore.lua:338: Usage: UnitGUID("unit")

Locals:

**Comment by Luxocracy** [comment]
What version are you on? Because the line the error specifies is empty.

The latest version for Classic would be 1.13.5.8

**Comment by Luxocracy** [comment]
Actually never mind, don't know if the line numbering was just messed up for me on mobile or what. But now that I'm able to look at it on my computer I can see that it's related to the castbar. 

Presumably the castbar tries to update after the units nameplate has disappeared in-game but not yet been updated to reflect this in the code. I'll add some additional checks to keep this from happening. But it's surprising this hasn't crept up until now.

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
