### ISSUE TITLE
Fēi dāngqián mùbiāo dì xuè tiáo tòumíngdù tiáozhěng bù qǐ zuòyòng 17/5000 The transparency adjustment of health bars for non-current targets does not work

### ISSUE THREAD

**Issue by juugler** [Luxocracy/NeatPlates#244]
When multiple monsters are together, except for the current target, the other health bars become lighter, and changing the transparency does not work.

**Comment by Luxocracy** [comment]
Which opacity setting are you changing?

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
