### ISSUE TITLE
Bug: Castbar border (interruptible) showing even if it's disabled

### ISSUE THREAD

**Issue by DashaMG** [Luxocracy/NeatPlates#246]
In Theme customization, there is an option to disable the castbar border. 

Actual: sometimes, the border still shows (What I want is a clean castbar). Reloading sometimes helps clear the issue. Will try to provide a screenshot. 

Expected: The castbar border does not show.

**Comment by Luxocracy** [comment]
This should now be fixed in the latest release.
But it seems like curse is having some issues fetching some of the libraries used by the addon so I can't say for sure when it'll be available over on curse.

**Comment by meltiseugen** [comment]
Thank you so much!

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
