### ISSUE TITLE
Looping error during Bastion quest "The Work of One's Hands"

### ISSUE THREAD

**Issue by kittykat74** [Luxocracy/NeatPlates#247]
Get this error during the part of the quest where you balance a meter that pops up as extra UI frame.  With Neatplates enabled, the UI frame is hidden and the following error message loops until the quest is completed or the addon is disabled:

3270x NeatPlates\NeatPlatesCore.lua:844: attempt to index local 'widget' (a nil value)
[string "@NeatPlates\NeatPlatesCore.lua"]:844: in function <NeatPlates\NeatPlatesCore.lua:834>
[string "@NeatPlates\NeatPlatesCore.lua"]:397: in function <NeatPlates\NeatPlatesCore.lua:380>
[string "@NeatPlates\NeatPlatesCore.lua"]:518: in function <NeatPlates\NeatPlatesCore.lua:508>
[string "@NeatPlates\NeatPlatesCore.lua"]:188: in function <NeatPlates\NeatPlatesCore.lua:161>

Locals:
widgetSetID = 282
widgetSet = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
}
widgetID = 2222
widget = nil
(*temporary) = nil
(*temporary) = 2222
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'widget' (a nil value)"
unit = <table> {
 guid = "Creature-0-2084-2222-2177-159338-000075AB10"
 isMouseover = false
 class = ""
 style = "NameOnly"
 isMarked = false
 rawName = "Hold the heat steady"
 level = 51
 alphaMult = 0.254902
 red = 0
 isInCombat = false
 threatSituation = "LOW"
 levelcolorRed = 1
 powermax = 0
 healthmax = 6100
 health = 6100
 unitid = "nameplate1"
 isMini = false
 isPet = false
 isDangerous = false
 name = "Hold the heat steady"
 pvpname = "Hold the heat steady"
 levelcolorBlue = 0
 isBoss = false
 isFocus = false
 isTrivial = false
 isTarget = false
 levelcolorGreen = 0.820000
 isTapped = false
 type = "NPC"
 blue = 0
 power = 0
 showName = true
 reaction = "FRIENDLY"
 green = 0.999998
 isCasting = false
 threatValue = 0
}
visual = <table> {
 customtext = <unnamed> {
 }
 highlight = <unnamed> {
 }
 eliteicon = <unnamed> {
 }
 powerbar = <unnamed> {
 }
 subtext = <unnamed> {
 }
 extrabar = <unnamed> {
 }
 focus = <unnamed> {
 }
 target = <unnamed> {
 }
 level = <unnamed> {
 }
 extraborder = <unnamed> {
 }
 castborder = <unnamed> {
 }
 spelltarget = <unnamed> {
 }
 healthbar = <unnamed> {
 }
 castbar = <unnamed> {
 }
 spelltext = <unnamed> {
 }
 threatborder = <unnamed> {
 }
 mouseover = <unnamed> {
 }
 spellicon = <unnamed> {
 }
 castnostop = <unnamed> {
 }
 durationtext = <unnamed> {
 }
 name = <unnamed> {
 }
 hitbox = <unnamed> {
 }
 extratext = <unnamed> {
 }
 healthborder = <unnamed> {
 }
 skullicon = <unnamed> {
 }
 raidicon = <unnamed> {
 }
}

**Comment by Luxocracy** [comment]
I can fix so the error doesn't appear, but I would most likely need to do the quest myself to fix it, as the error doesn't really provide any information as to what is actually going wrong.

**Comment by Luxocracy** [comment]
Seems this was an entirely new type of bar widget for Shadowlands. I've added support for this widget type in the latest release, and I also added an option to use the Blizzard version of this widget instead, which is enabled by default.

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
