### ISSUE TITLE
Error when mob casts outside of nameplate range

### ISSUE THREAD

**Issue by Jeremy7600** [Luxocracy/NeatPlates#248]
In the latest for Classic I'm getting the following error when a mob that is outside of nameplate range casts a spell:

Message: Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1176: attempt to index field 'castnostop' (a nil value)
Time: Sun Oct 11 22:25:19 2020
Count: 10
Stack: Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1176: attempt to index field 'castnostop' (a nil value)
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1176: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1101>
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1622: in function `?'
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1365: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1364>

Locals: plate = NeatPlatesTarget {
 carrier = NeatPlatesCarrier-1 {
 }
 0 = <userdata>
 extended = <unnamed> {
 }
 unitGUID = "Creature-0-4412-1-66-6202-000003CC13"
}
guid = "Creature-0-4412-1-66-6202-000003CC13"
channeled = false
castBar = <unnamed> {
 0 = <userdata>
 Right = 1
 Left = 0
 SetAllColors = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesStatusbar.lua:53
 SetStatusBarColor = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesStatusbar.lua:40
 SetOrientation = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesStatusbar.lua:60
 Value = 732580846
 SetMinMaxValues = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesStatusbar.lua:80
 durationtext = <unnamed> {
 }
 SetTexCoord = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesStatusbar.lua:97
 GetMinMaxValues = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesStatusbar.lua:75
 Bottom = 1
 MaxVal = 732583855
 SetBackdropTexture = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesStatusbar.lua:106
 Backdrop = <unnamed> {
 }
 SetBackdropTexCoord = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesStatusbar.lua:102
 Top = 0
 MinVal = 732580846
 Dim = 1
 SetStatusBarTexture = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesStatusbar.lua:39
 Orientation = "HORIZONTAL"
 SetStatusBarGradient = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesStatusbar.lua:41
 SetValue = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesStatusbar.lua:34
 Bar = <unnamed> {
 }
}
unitType = "Creature"
_ = "0"
_ = "4412"
_ = "1"
_ = "66"
creatureID = "6202"
spell = <table> {
 finished = false
 name = "Fireball"
 school = 4
 startTime = 732580846
 spellTimeout = <table> {
 }
 increase = 1
}
startTime = 732580846
endTime = 732583855
increase = nil
spellEntry = <table> {
 castTime = 3009
}
r = 0.999998
g = 0.501960
b = 0
a = 1
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 Right = 1
 Left = 0
 SetAllColors = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesStatusbar.lua:53
 SetStatusBarColor = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesStatusbar.lua:40
 SetOrientation = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesStatusbar.lua:60
 Value = 732580846
 SetMinMaxValues = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesStatusbar.lua:80
 durationtext = <unnamed> {
 }
 SetTexCoord = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesStatusbar.lua:97
 GetMinMaxValues = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesStatusbar.lua:75
 Bottom = 1
 MaxVal = 732583855
 SetBackdropTexture = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesStatusbar.lua:106
 Backdrop = <unnamed> {
 }
 SetBackdropTexCoord = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesStatusbar.lua:102
 Top = 0
 MinVal = 732580846
 Dim = 1
 SetStatusBarTexture = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesStatusbar.lua:39
 Orientation = "HORIZONTAL"
 SetStatusBarGradient = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesStatusbar.lua:41
 SetValue = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesStatusbar.lua:34
 Bar = <unnamed> {
 }
}
(*temporary) = 1
(*temporary) = <userdata>
(*temporary) = 0
(*temporary) = "attempt to index field 'castnostop' (a nil value)"
UpdateReferences = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesCore.lua:271
extended = <u

It doesn't occur when the mob has a nameplate.

**Comment by welpenhund** [comment]
Date: 2020-10-12 09:09:59
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\NeatPlates\NeatPlatesCore.lua line 1176:
   attempt to index field 'castnostop' (a nil value)
Debug:
   [C]: ?
   NeatPlates\NeatPlatesCore.lua:1176:
      NeatPlates\NeatPlatesCore.lua:1101
   NeatPlates\NeatPlatesCore.lua:1622: ?()
   NeatPlates\NeatPlatesCore.lua:1365:
      NeatPlates\NeatPlatesCore.lua:1364
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.5.6
  AtlasLootClassicData, vv1.5.6
  AtlasLootClassicDungeonsAndRaids, vv1.5.6
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v9.0.1
  Bartender4, v4.9.0
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  CharacterStatsClassic, v3.6.5
  ClassicAuraDurations, v1.13.61
  ClassicCastbars, v1.3.12
  ClassicCastbarsOptions, v
  ClickMorph, v1.6.4
  DBMCore, v1.13.61
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.7
  DruidBarClassic, v0.7.8
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  GatherMate2, v1.45.5
  HealBot, v1.13.5.6
  HealBotData, v1.13.5.6
  HealBoten, v1.13.5.6
  HealBotExtraSkins, v1.13.5.6
  HealBotOptions, v1.13.5.6
  HealBotTips, v1.13.5.6
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  LeatrixMaps, v1.13.81
  LeatrixPlus, v1.13.81
  ModernTargetFrame, v1.8
  NeatPlates, v1.13.5.13
  NeatPlatesAlvara, v5a
  NeatPlatesBlizzardPlates, v2.0
  NeatPlatesClassicPlates, v
  NeatPlatesGraphite, v
  NeatPlatesGrey, v
  NeatPlatesNeon, v
  NeatPlatesQuatre, v
  NeatPlatesRenaitre, vv7.0.3
  NeatPlatesRoth, v
  NeatPlatesSimple, v7.3.0
  NeatPlatesSlimHorizontal, v2.2
  NeatPlatesSlimVertical, v2.2
  NeatPlatesHub, v
  NeatPlatesWidgets, v
  NovaWorldBuffs, v1.82
  OmniBar, vv10.8
  OmniCC, v8.3.6
  Quartz, v3.5-classic-5
  QuartzProcs, v3.6
  Questie, v6.0.5
  SaladCthun, v1.01
  Spy, v1.1.2
  Stubby, v8.2.6376 (SwimmingSeadragon)
  unitscan, v1.0.3
  WeakAuras, v2.18.4
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=763)

**Comment by Luxocracy** [comment]
I wasn't able to replicate this in my own testing, but I've released a fix that should resolve the issue and will be available shortly on curse.

**Comment by itwrld** [comment]
Sadly the error is still there.

**Comment by Luxocracy** [comment]
Ah, think I misread what the error actually said. I'll push a new release again and if this still doesn't fix it I'll have to spend some more time trying to replicate the issue.

**Comment by welpenhund** [comment]
To me that last update seems to have fixed it, the lua error is not popping up anymore for me. (tested on like 40 mobs)
If i am wrong and get the popup again in next days i will post an update.

**Comment by itwrld** [comment]
Correct, .15 seemed to fix the lua errors.

**Comment by Jeremy7600** [comment]
.15 has no more errors, thanks!
