### ISSUE TITLE
Prot Pally Holy Power on Target

### ISSUE THREAD

**Issue by Xorag** [Luxocracy/NeatPlates#250]
With 9.0 prot pallies and holy pallies have holy power again, I tried to enable personal resource display for enemy targets but holy power doesn't seem to show up for me in prot spec. I'm guessing the display might just be hard coded to spec? 

Thanks!

**Comment by Xorag** [comment]
Tested this with 9.0.2.3 on retail this evening after the prepatch went live.

**Comment by Luxocracy** [comment]
I'll have to look into this as it shouldn't be something that's hard coded from what I remember.

**Comment by Luxocracy** [comment]
Should be fixed in the latest release, still had to leave it hard coded however as the API still only responds with _mana_ when asking for a power type and not _holy power_ etc.

**Comment by yummyfish123** [comment]
Just downloaded the latest version, and holy power is not showing in the name plate for ret pally.
Is there any option I need to turn on for this? I used pretty much out of the box before patch, and it's there without much customization.

**Comment by Luxocracy** [comment]
Double check that the option to display personal resource on the target is enabled. It was recently changed to a drop down with different options rather than an on/off option and it might have impacted old settings.

**Comment by yummyfish123** [comment]
> Double check that the option to display personal resource on the target is enabled. It was recently changed to a drop down with different options rather than an on/off option and it might have impacted old settings.

Thanks Luxocrazy, got that working. Now I hope the enemy casting issue can be fix/resolve too.

**Comment by Xorag** [comment]
Thanks for the quick fix!
