### ISSUE TITLE
Massive lag when enemy casting a spell

### ISSUE THREAD

**Issue by yummyfish123** [Luxocracy/NeatPlates#251]
Not sure if it's clashing with other addons, but when I turn NP off, lag is not there.

**Comment by Luxocracy** [comment]
Which game version is this for?
And it would be great if you could confirm if this still happens when NeatPlates is the only addon running, I know it can be a bit of a hassle but it really helps with issues like this where I can't replicate them.

**Comment by yummyfish123** [comment]
Thanks for the quick reply Luxocrazy.
I've disabled all other addons, except NP and turning them back on one by one, funny enough the issue is not happening anymore. (tested on training dummy)
This is with testing on training dummy, where the lag was about half a sec freeze.
When I first encountered this issue was in Tempest Keep, killing KT, the freeze was about 3-5 seconds.
Hopefully this lag is not coming back.

**Comment by Luxocracy** [comment]
Hopefully so, nothings really changed with regards to spellcasts in the addon. So if it does return there's probably some change that I'm not aware of with Shadowlands.

**Comment by yummyfish123** [comment]
Hi Luxocrazy, just want to get back to you for an update.
I think I've located the problem, I believe it's something to do with Lorti UI. (Quite weird to me, as Lorti is quite lite and it only darkens the frames/actions bar) 
I can feel the game runs better, loads faster and no more addon error message when I just disable Lorti.
Thanks for your quick replies again and the awesome addon. <3

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
