### ISSUE TITLE
Not working on changing text of friendly NPC's EXCEPT on a single character

### ISSUE THREAD

**Issue by Ziliot85** [Luxocracy/NeatPlates#253]
I have 20 toons and I have checked all of them. Only on one character does it actually change the font style for friendly NPC's.
They all have the same profile but nothing I have tried can get any of the other toons fonts to change. 
 
![WoWScrnShot_101520_020006](https://user-images.githubusercontent.com/72915025/96101549-6e13d000-0e8a-11eb-8e56-7b8c6e307f7b.jpg)
![WoWScrnShot_101520_020151](https://user-images.githubusercontent.com/72915025/96101551-6f44fd00-0e8a-11eb-93e0-02862183e149.jpg)

**Comment by Luxocracy** [comment]
Try running this command `/script SetCVar("nameplateShowFriendlyNPCs",1)`
It might solve your issue, this is something that used to be enabled by default on new characters. But it was disabled and removed from the interface options at some point.

I'll see if I can add this to the current options in the future.

**Comment by Ziliot85** [comment]
That fixed it. Appreciate it!

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
