### ISSUE TITLE
Offset aura for target

### ISSUE THREAD

**Issue by Dairyman** [Luxocracy/NeatPlates#254]
Auras for the targeted nameplate are offset to the top:

![NeatPlates_TargetOffset](https://user-images.githubusercontent.com/1969327/96350129-62a3ed00-10b4-11eb-9bcc-cf992a35444e.png)

Didn't happen before the patch. Is there an setting I over saw for it?

**Comment by Luxocracy** [comment]
It might be the offset for the personal resource on target. Try setting personal resource to none under _Other Widgets_.

**Comment by Dairyman** [comment]
Thanks, yes it was personal resource.
