### ISSUE TITLE
When you set the buff/debuff offset to "0", the spells still aren't listed next to each other.

### ISSUE THREAD

**Issue by Fiveby21** [Luxocracy/NeatPlates#256]
Instead of being listed next to each other, in one line, the "buffs" always appear on the far-right side of the nameplate, while debuffs appear on the far left side. I believe the intention of this configuration would be for the buffs and debuffs to show up right next to each other, as they do in tidyplates.

**Comment by Luxocracy** [comment]
This separatation for buffs and debuffs is working as intended, the offset is meant to control how close they are allowed to be to each other.

**Comment by Fiveby21** [comment]
Is there another way I can remove the seperation? It bothers me when the buffs are off to the side, not even directly about the nameplate. Tidyplates has this.

**Comment by Luxocracy** [comment]
I'd have to add an option for it's behavior, but I can look into it.

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
