### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by a268-Beefy** [Luxocracy/NeatPlates#257]
Happened when i tried to make a new Profile
v 9 0  2 11

2x NeatPlatesHub\Hub.lua:679: attempt to index local 'LocalVars' (a nil value)
[string "@NeatPlatesHub\Hub.lua"]:679: in function `RefreshSettings'
[string "@NeatPlatesHub\Hub.lua"]:715: in function <NeatPlatesHub\Hub.lua:703>
[string "@NeatPlatesHub\Hub.lua"]:735: in function <NeatPlatesHub\Hub.lua:729>
[string "@NeatPlatesHub\Hub.lua"]:896: in function <NeatPlatesHub\Hub.lua:881>

Locals:
LocalVars = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'LocalVars' (a nil value)"
CallForStyleUpdate = <function> defined @NeatPlatesHub\Helpers.lua:6
ConvertAuraListTable = <function> defined @NeatPlatesHub\Helpers.lua:83
ConvertStringToTable = <function> defined @NeatPlatesHub\Helpers.lua:72
ConvertColorListTable = <function> defined @NeatPlatesHub\Helpers.lua:114

**Comment by Luxocracy** [comment]
This issue should be fixed as of the latest release (9.0.2.12)

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
