### ISSUE TITLE
Argent Tournament

### ISSUE THREAD

**Issue by a268-Beefy** [Luxocracy/NeatPlates#258]
Happen during Argent Tornament mount battles
9 0 2 11

1x ...eBlizzard_NamePlates\Blizzard_NamePlates.lua:470: Action[FrameMeasurement] failed because[Can't measure restricted regions]: attempted from: <unnamed>:GetLeft().
[string "=[C]"]: in function `GetLeft'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:470: in function `GetPreferredInsets'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:166: in function `UpdateInsetsForType'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:150: in function `ApplyFrameOptions'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:116: in function `OnNamePlateAdded'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:56: in function <...eBlizzard_NamePlates\Blizzard_NamePlates.lua:47>

Locals:
(*temporary) = <unnamed> {
 otherHealPrediction = <unnamed> {
 }
 overAbsorbGlow = <unnamed> {
 }
 myHealAbsorbLeftShadow = <unnamed> {
 }
 border = <unnamed> {
 }
 barTexture = <unnamed> {
 }
 totalAbsorb = <unnamed> {
 }
 myHealAbsorb = <unnamed> {
 }
 myHealPrediction = <unnamed> {
 }
 myHealAbsorbRightShadow = <unnamed> {
 }
 0 = <userdata>
 background = <unnamed> {
 }
 overHealAbsorbGlow = <unnamed> {
 }
 totalAbsorbOverlay = <unnamed> {
 }
}

**Comment by Luxocracy** [comment]
This is something that's happening in the normal blizzard nameplates because some addon, not necessarily Neatplates, has tainted the normal nameplate frame by modifying something that it shouldn't have.

This is something that's been reported before but I've never been able to replicate it when only running Neatplates. Which is why I can't say for sure if it is caused by Neatplates or not.

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
