### ISSUE TITLE
Show Personal Resource bug

### ISSUE THREAD

**Issue by HigureYume** [Luxocracy/NeatPlates#259]
When the option "None" is selected under show personal resource, Death Knight runes still appear below enemy health bars.

**Comment by Luxocracy** [comment]
Do you have personal resource on target enabled in your interface options? Because this will display the default blizzard resource bar.

**Comment by HigureYume** [comment]
I apologize, I was changing an old profile, not the one I was using. My mistake, it is working fine. Thank you!

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
