### ISSUE TITLE
alpha mask produces unclean border-shadows

### ISSUE THREAD

**Issue by bitdruid** [Luxocracy/NeatPlates#261]
Heyhey,

i did some customization on the quatre-theme and recognized some unclean alphas (as i think) so i attached a pic of it. 

my first intend was to resize the border to a very small line but i've never worked with tga before. are the border-sizes hard-coded? as i wasnt able to find any differences in rgb-values of the tga-files which may give the oppurtunity to change border styles and sizes.

additionally i found this grey shadow when borders are enabled and wasn't able to remove it. it's shape is also very bulky. would really like to get this cleaned up.

![image](https://user-images.githubusercontent.com/49254050/99876261-e8f0a900-2bf5-11eb-9db0-edf6c5acb22c.png)

**Comment by Luxocracy** [comment]
I would assume this was probably a stylistic choice at some point, but it's such a minor detail I doubt most people notice or care. And it would probably be nicer if it wasn't there considering the rather low resolution of it. So I'll probably remove it in the next release.

As for the borders, they are purely defined by the alpha channel for this theme in the TGA file.
RGB vs Alpha channel.
![RGB channels](https://user-images.githubusercontent.com/2884542/99877440-92d43380-2bfe-11eb-8625-7f9209adf071.jpg)
![Alpha channel](https://user-images.githubusercontent.com/2884542/99877442-949df700-2bfe-11eb-96f0-d691fc3e4aa0.jpg)

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
