### ISSUE TITLE
Arena ID is not working

### ISSUE THREAD

**Issue by awltr** [Luxocracy/NeatPlates#262]
Using current Version with Neon Theme and Arena ID ist not working. Is there any known issue?

**Comment by Luxocracy** [comment]
Not that I'm aware of, nothing should have really changed for Arena as far as I know.

**Comment by awltr** [comment]
Okay. Maybe I misunderstand sth here. The function should display the Arena ID (i.e. 1, 2, 3) on the left side of the plate (maybe depending on the theme). Is this correct? Because for me its unfortunately not displayed.

**Comment by Luxocracy** [comment]
I'll have to look into it once I get a chance.

**Comment by awltr** [comment]
That would be great. I like this Addon but Arena ID is pretty important for me. Thank you

**Comment by Luxocracy** [comment]
This should have been fixed as of the latest release

**Comment by awltr** [comment]
Yes, it's working again. It may look better from the UI perspective but that's another story. The main point is that it works now. Thanks a lot!
