### ISSUE TITLE
Couple Suggestions

### ISSUE THREAD

**Issue by mdouglas90** [Luxocracy/NeatPlates#264]
Hi, I have a couple suggestions that would make NeatPlates even more helpful for me:

1. In the headline view, be able to show the exact health in the subtext. Currently, it can only show % health.
2. In the spotlight section (both scale and opacity), allow us to spotlight units that are casting interruptible spells, rather than all spells.

If these are already in there, can you show me how to configure them. Thanks!

**Comment by Luxocracy** [comment]
I've added these suggestions to the latest release 9.0.2.17.

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
