### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by HuMa69** [Luxocracy/NeatPlates#265]
Hello, would be nice to track echoing reprimend of rogues on the combat point widget, its a skill that empowers a random CP and it lets you use it like if you have 7CP, im used to track the CP on the plates and its a bit weird now to me.... thanks! amazing addon btw

**Comment by Luxocracy** [comment]
Yes, this is something I am looking into. But it seems like it will require a little bit of time to add this with how the Combo point widget is setup. I'll see if I can find some time for it during the week, but if not, I'll most likely be able to add this next weekend.

**Comment by Luxocracy** [comment]
I've add this in the latest release 9.0.2.18, however, I don't have a rogue of the appropriate level to verify it actually working with the kyrian ability. So it would be great if you could confirm if it's working correctly or not.

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
