### ISSUE TITLE
neatplateswidget\CombopointWidget

### ISSUE THREAD

**Issue by Faredino** [Luxocracy/NeatPlates#266]
Keep getting this error as a Monk on all three specs. Causes the game to crash every time. Happens pretty often.

**Comment by Luxocracy** [comment]
You didn't post the error, but is it the same as https://github.com/Luxocracy/NeatPlates/issues/265? And is it still happening in the latest version 9.0.2.17?

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
