### ISSUE TITLE
Lots of Errors :(

### ISSUE THREAD

**Issue by Damidon1** [Luxocracy/NeatPlates#270]
I copied and pasted the few pages of errors that i kept getting. pasting down below. Any tips or advice would be greatly appreciated, thank you

Message: Interface\AddOns\NeatPlates\NeatPlatesCore.lua:471: attempt to index field 'extrabar' (a nil value)
Time: Sun Dec  6 00:54:15 2020
Count: 3
Stack: Interface\AddOns\NeatPlates\NeatPlatesCore.lua:471: attempt to index field 'extrabar' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\NeatPlates\NeatPlatesCore.lua"]:471: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:436>
[string "@Interface\AddOns\NeatPlates\NeatPlatesCore.lua"]:1323: in function `?'
[string "@Interface\AddOns\NeatPlates\NeatPlatesCore.lua"]:1277: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1275>

Locals: 

Message: Interface\AddOns\NeatPlates\NeatPlatesCore.lua:471: attempt to index field 'extrabar' (a nil value)
Time: Sun Dec  6 00:54:15 2020
Count: 3
Stack: Interface\AddOns\NeatPlates\NeatPlatesCore.lua:471: attempt to index field 'extrabar' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\NeatPlates\NeatPlatesCore.lua"]:471: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:436>
[string "@Interface\AddOns\NeatPlates\NeatPlatesCore.lua"]:1323: in function `?'
[string "@Interface\AddOns\NeatPlates\NeatPlatesCore.lua"]:1277: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1275>

Locals: 
Message: Interface\AddOns\NeatPlates\NeatPlatesCore.lua:471: attempt to index field 'extrabar' (a nil value)
Time: Sun Dec  6 00:54:15 2020
Count: 3
Stack: Interface\AddOns\NeatPlates\NeatPlatesCore.lua:471: attempt to index field 'extrabar' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\NeatPlates\NeatPlatesCore.lua"]:471: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:436>
[string "@Interface\AddOns\NeatPlates\NeatPlatesCore.lua"]:1323: in function `?'
[string "@Interface\AddOns\NeatPlates\NeatPlatesCore.lua"]:1277: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1275>

Locals: 
Message: Interface\AddOns\NeatPlates\NeatPlatesCore.lua:471: attempt to index field 'extrabar' (a nil value)
Time: Sun Dec  6 00:54:15 2020
Count: 3
Stack: Interface\AddOns\NeatPlates\NeatPlatesCore.lua:471: attempt to index field 'extrabar' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\NeatPlates\NeatPlatesCore.lua"]:471: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:436>
[string "@Interface\AddOns\NeatPlates\NeatPlatesCore.lua"]:1323: in function `?'
[string "@Interface\AddOns\NeatPlates\NeatPlatesCore.lua"]:1277: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1275>

Locals: 
Message: Interface\AddOns\NeatPlates\NeatPlatesCore.lua:471: attempt to index field 'extrabar' (a nil value)
Time: Sun Dec  6 00:54:15 2020
Count: 3
Stack: Interface\AddOns\NeatPlates\NeatPlatesCore.lua:471: attempt to index field 'extrabar' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\NeatPlates\NeatPlatesCore.lua"]:471: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:436>
[string "@Interface\AddOns\NeatPlates\NeatPlatesCore.lua"]:1323: in function `?'
[string "@Interface\AddOns\NeatPlates\NeatPlatesCore.lua"]:1277: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1275>

Locals: 
Message: Interface\AddOns\NeatPlates\NeatPlatesCore.lua:471: attempt to index field 'extrabar' (a nil value)
Time: Sun Dec  6 00:54:15 2020
Count: 3
Stack: Interface\AddOns\NeatPlates\NeatPlatesCore.lua:471: attempt to index field 'extrabar' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\NeatPlates\NeatPlatesCore.lua"]:471: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:436>
[string "@Interface\AddOns\NeatPlates\NeatPlatesCore.lua"]:1323: in function `?'
[string "@Interface\AddOns\NeatPlates\NeatPlatesCore.lua"]:1277: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1275>

Locals:

**Comment by Luxocracy** [comment]
Do you have any other nameplate addons enabled? Because that could cause potential issues.

**Comment by Damidon1** [comment]
ahhh that was it! it was an add on i had named "Nameplate SCT". it was a scrolling combat text add on. Thank you!

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
