### ISSUE TITLE
Animacharged Combo Points for Rogues not working correctly with Deeper Stratagem

### ISSUE THREAD

**Issue by Shadowmastr** [Luxocracy/NeatPlates#271]
Love the added feature for Animacharged Combo points showing on the frame for Kyrian rogues after using Echoing Reprimand. However, the combo points aren't showing up correctly when playing Deeper Stratagem. The animacharged combo point is misaligned on the nameplates, as shown below:

![NeatPlatesComobPts](https://user-images.githubusercontent.com/72906585/101284086-4109dc80-37ac-11eb-9772-1c0bc5de71af.jpg)

**Comment by Luxocracy** [comment]
Must have forgotten to align this with 6 combo points. I've pushed a new release that fixes this and it should be available shortly on curseforge.

**Comment by Shadowmastr** [comment]
Fixed! One other thing to mention as well with this is with how the blue animacharged combo points visual is implemented, it's difficult to tell when you have the correct number of combo points. For example, if the animacharged combo point is 3, and you have 2 combo points, it looks as if you have 3 combo points on the nameplates. When you hit 3 combo points, the blue combo point doesn't change visually very much, if at all. To fix this, the animacharged combo point could just be a blue outline instead of a fully filled in blue circle so you can still see the yellow/orange combo points inside.

**Comment by Luxocracy** [comment]
Ah yeah, I'll probably add something to highlight that you are on the correct amount of combo points. Perhaps as you suggest outline the combo point instead, and covering it when you are at the correct combo points.

**Comment by Shadowmastr** [comment]
There are certainly a few ways to make it work, happy to hear it's in consideration for change. Thanks for the Deeper Strat fix, and your hard work!

**Comment by Luxocracy** [comment]
I've pushed a new release 9.0.2.22, that should make it a bit clearer when you have the correct amount of combo points.
