### ISSUE TITLE
is this even possible? (possible feature request)

### ISSUE THREAD

**Issue by ANaPhOrAX** [Luxocracy/NeatPlates#274]
Hey,

I'm not sure if what I'm trying to achieve is even possible: I want the nameplates to change color when I have aggro, but stay the default color when I don't have aggro. Not the 'safe' color; the _default_ color. Is this possible? I want this for all roles. Tank, dps, heals. I don't need a safe color. Default color is plenty. But it seems like I can't disable this safe color, or am I missing something? I have threat mode set to DPS/Healer at the moment, because when googling I found that I needed to do that if I wanted to have the threat glow appear when I _have_ threat, not when I don't. 

To summarize: All I want is to have the threat glow appear when I do have aggro, and for the color of the bars to change when I do have aggro. I don't need them to change when I'm 'safe', or anything else really (although the transition thing could be useful if it works like I'm assuming in my question below).

A couple small follow-up questions:

Under Threat colors, apart from 'Safe', there's also

**Transition** - I assume this is the color for when you're starting to lose aggro to someone else in the group?
**Attacking another tank** - is this controlled by the "highlight mobs on off-tanks" under Threat & highlighting? Or is that something else?
**Group member aggro** - same as previous; is this controlled by "highlight group members holding aggro" under Threat & highlighting? Or is that something else?

**Comment by Luxocracy** [comment]
No, this isn't currently a supported feature. Any reason you couldn't just change the _safe_ color to be the same as _Hostile NPC_ color? Because outside of neutral units, that's the color the nameplates will be by _"default"_

And yes, your other assumptions on how the threat colors work are correct.

**Comment by ANaPhOrAX** [comment]
am I correct that 'safe' doesn't really mean safe, it just means, you're not the person holding aggro, but would still get aggro if the person holding aggro dies (i.e.)? like safe is basically the color for when you have threat on the mob, but aren't holding aggro?

but let's say I'm in a dungeon group.. and the tank pulls a pack. I'm standing at a safe distance, shadowmelded - do they still turn blue for me? even though I'm not in the fight at all?

**Comment by Luxocracy** [comment]
I guess safe is relative, but in this case it means you are in no danger of taking/losing aggro. It does not mean you have no threat on the target, or you aren't on the threat table.

**Comment by ANaPhOrAX** [comment]
okay but so then in my example I _would_ or _wouldn't_ get the blue bars? well, I'll test it and report back I guess

**Comment by Luxocracy** [comment]
I believe you'd still exist on the threat table, just at 0, so yes most likely you'd get blue bars if your threat settings are for dps

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
