### ISSUE TITLE
Could I set all nameplate of enemy highlight, not only the target which I selected.

### ISSUE THREAD

**Issue by Gary-93** [Luxocracy/NeatPlates#276]

**Comment by Luxocracy** [comment]
No, I don't believe this is possible. Would kind of defeat the purpose of highlighting as well if it was on all targets.

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
