### ISSUE TITLE
Skull icon

### ISSUE THREAD

**Issue by nakinacho** [Luxocracy/NeatPlates#283]
Hello, how to remove skull icon from the health bar?
![image](https://user-images.githubusercontent.com/77095346/105745948-7f6b7e80-5f47-11eb-90b5-0ac916636271.png)

**Comment by Luxocracy** [comment]
You would have to go into the _Theme Customization_, which can be found the bottom of your profile. And then find _Skull Icon_ in the list and **un-check** the _Element Enabled_ checkbox.
