### ISSUE TITLE
Exact health percent text

### ISSUE THREAD

**Issue by aurorascharff** [Luxocracy/NeatPlates#284]
Hello,
I would like to be able to see target exact hp, i.e 1.5% instead of just 1%.
This is functionality that Plater offers that I really miss from NeatPlates.
Love the addon though!

**Comment by Luxocracy** [comment]
I've added a new slider as of version 9.0.2.31 that allows you to specify the amount of precision you want on health percentages.

**Comment by aurorascharff** [comment]
Thank you so much, and thanks for the quick response and action.
