### ISSUE TITLE
error on login after installing

### ISSUE THREAD

**Issue by pilsbury** [Luxocracy/NeatPlates#285]
Date: 2021-02-12 16:21:05
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\NeatPlates\NeatPlatesCore.lua line 1504:
   Attempt to register unknown event "UNIT_SPELLCAST_INTERRUPTIBLE"
Debug:
   [C]: RegisterEvent()
   NeatPlates\NeatPlatesCore.lua:1504: in main chunk
Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "UNIT_SPELLCAST_INTERRUPTIBLE"

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  Atlas, vv1.48.02
  AtlasClassicWoW, vv1.48.00
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  GatherMate2, v1.45.6-classic
  NeatPlates, v9.0.2.31
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Stubby, v8.2.6510 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.6.11306 <none>
  (ck=314)

**Comment by Luxocracy** [comment]
I think you have wrong version installed. Make sure you have installed the Classic version (1.13.x.x). As I believe this is version you want.

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
