### ISSUE TITLE
neatplates hunter/totems dont show.

### ISSUE THREAD

**Issue by easiness12** [Luxocracy/NeatPlates#286]
I have enabled to show everything from blizzard interface and it still dont show, other than that the addon is fine

**Comment by Luxocracy** [comment]
There are a few things that can't be enabled through the interface options, or through NeatPlates at this time for that matter, regarding the showing/hiding of certain nameplates. I'll list some of the settings below, although some of these might exists in the interface options already.

`/console SetCVar("nameplateShowEnemyPets", 1)`
`/console SetCVar("nameplateShowEnemyTotems", 1)`
`/console SetCVar("nameplateShowEnemyMinions", 1)`
`/console SetCVar("nameplateShowEnemyGuardians", 1)`
`/console SetCVar("nameplateShowEnemyMinus", 1)` _* For smaller almost critter like npcs_

You can also replace the _Enemy_ part with _Friendly_ if you wish to enable it for friendly units. To disable just change the 1 to a 0.

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
