### ISSUE TITLE
cipher font problem

### ISSUE THREAD

**Issue by Perceval788** [Luxocracy/NeatPlates#290]
I have a problem, with 1 of my characters, the font of the numbers in the enemies' life bar is not the same font as my other characters and I can't change this (the image where I am living is the right font and the one that has a problem these the one where I am a ghost)
![2021-03-26 (14)](https://user-images.githubusercontent.com/81479067/112725926-ff4ba000-8f1a-11eb-97c8-fb83d96e30bd.png)

![2021-03-26 (15)](https://user-images.githubusercontent.com/81479067/112725879-b693e700-8f1a-11eb-8be1-f9434540207c.png)

**Comment by Luxocracy** [comment]
In the main settings check if _Force Multi-Lingual Font_ is checked on one of the characters. That's about the only thing that comes to mind, unless another addon is interfering with the fonts.

**Comment by Perceval788** [comment]
> Dans les paramètres principaux, vérifiez si _Forcer la police multilingue_ est coché sur l'un des caractères. C'est à peu près la seule chose qui me vient à l'esprit, à moins qu'un autre addon n'interfère avec les polices.

thank you what you gave me was well tick so I uncheck it and its put the correct font =)

**Comment by Luxocracy** [comment]
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.
