### ISSUE TITLE
error messages related to Text Formatting

### ISSUE THREAD

**Issue by icemansparks** [Luxocracy/NeatPlates#292]
1615x NeatPlatesHub\functions\Text.lua:136: invalid option in `format'
[C]: in function `format'
NeatPlatesHub\functions\Text.lua:136: in function <NeatPlatesHub\functions\Text.lua:128>
NeatPlatesHub\functions\Text.lua:140: in function <NeatPlatesHub\functions\Text.lua:139>
(tail call): ?
(tail call): ?
NeatPlates\NeatPlatesCore.lua:1080: in function <NeatPlates\NeatPlatesCore.lua:1067>
NeatPlates\NeatPlatesCore.lua:550: in function <NeatPlates\NeatPlatesCore.lua:525>
NeatPlates\NeatPlatesCore.lua:672: in function <NeatPlates\NeatPlatesCore.lua:667>
NeatPlates\NeatPlatesCore.lua:1486: in function `?'
NeatPlates\NeatPlatesCore.lua:1378: in function <NeatPlates\NeatPlatesCore.lua:1376>

Locals:
InCombatSkipped

**Comment by Luxocracy** [comment]
Could you check what your _Health Percent Precision_  under _Healthbar View > Additional Settings_ is set to. Or simply try changing it from whatever value it has right now to something else.

Because the only reason I can see for this specific error message is if the precision variable is set to something like '$'.

**Comment by icemansparks** [comment]
@Luxocracy you are amazing!
For some reason it was set to "-1" (don't know why) which of course will lead to an error. Changing it to a positive value fixed the errors.
![Bildschirmfoto 2021-04-25 um 14 22 10](https://user-images.githubusercontent.com/11578975/115993190-00332880-a5d2-11eb-81ee-82c56d36f136.jpg)

**Comment by Luxocracy** [comment]
Weird, I'll have to look into constraining the values better I guess.
