### ISSUE TITLE
Blizzard Theme is bugged

### ISSUE THREAD

**Issue by Xiverz** [Luxocracy/NeatPlates#298]
When an enemy is targeting you it has a weird buggy glow to it, only when using the Blizzard Theme plates

**Comment by Luxocracy** [comment]
I think you are referring to the _Warning Glow_ that happens when you get aggro. You can disable it in the _Threat & Highlighting_ section

**Comment by Xiverz** [comment]
Sorry I wasn't very clear...

![nameplate bug](https://user-images.githubusercontent.com/61852487/118904324-8ad92000-b911-11eb-9b74-3dec6cdf4499.png)

This is what i mean, I only see it against enemy Druids and mobs

I did think about the threat glow as well but disabling it didn't stop it :(
It only happens when the Druid/mob targets you, might happen with other Themes as well I don't know.
Thanks for the fast reply anyhow <3

**Comment by Luxocracy** [comment]
This should be the same issue as this #299, and should be resolved in the latest release.
