### ISSUE TITLE
Buggy glow

### ISSUE THREAD

**Issue by haroldinerince** [Luxocracy/NeatPlates#299]
There is a strange glow on nameplates for enemies that are targetting you. Please see the screenshot attached. Note: it IS a bug and not normal behaviour of the threat glow. This only started happening with the new patch today. 

I took a screenshot for you:

![Bug glow](https://user-images.githubusercontent.com/84470772/118862058-8266f200-b8dd-11eb-9155-8231aedadb4c.png)

Note this is the classic version.

**Comment by Luxocracy** [comment]
ah yeah, no that is definitely a bug. I'll take a look at it when I'm able.

**Comment by silverhawke249** [comment]
i would like to add that this bug also showed up in the TBC Beta. a similar bug affected Modern TargetFrame (making the TargetFrame glow red when you have threat), but they fixed this issue somehow.

**Comment by ANaPhOrAX** [comment]
_might_ have something to do with the absorb widget. I was getting the same exact thing, then I imported my custom profile and it got even worse - my neatplates were bugging out completely, wouldn't even show AT ALL. bugsack was showing the absorb widget as the culprit. I disabled it and no more errors, and also, no more glow bug thing.

**Comment by Luxocracy** [comment]
I could be the absorb widget as it is something that exists in retail, but not sure if it's something that exists in TBC right now.

**Comment by Luxocracy** [comment]
The absorb widget seems unrelated, but it's still an issue as it does indeed not exists as it does in retail. So I'll remove that for now at least. As for the buggy glow, it is definitely the warning glow texture that's gotten messed up some how so I'll see if I can figure out what the cause is.

**Comment by Luxocracy** [comment]
Seems the changed one of the textures I was using, as I grabbed it directly from the client. So I've bundled the texture with the theme instead, as I couldn't really be bothered to figure out what had changed with it...
Anyways, this should be working correctly in the latest release.
