### ISSUE TITLE
Threat warnings

### ISSUE THREAD

**Issue by tra8cer** [Luxocracy/NeatPlates#300]
in classic it used to be if i was in bear, (druid) Defensive(war) or had Rightous Fury on (pally) it automatically swaped between lost threat warning and gained threat warning.  This does not seem to work in TBC

**Comment by Luxocracy** [comment]
I'll see if I can take a look later today, this should have remained the same. But looks like I missed something if it isn't.

**Comment by Luxocracy** [comment]
I believe this should be fixed in the latest release, I haven't had the opportunity to test it fully. But I did notice I had missed some things, so hopefully that was the only issue with this.

**Comment by tra8cer** [comment]
Seems to be working, at least on pally so far, TY!
