### ISSUE TITLE
Castbars always show as uninterruptible

### ISSUE THREAD

**Issue by silverhawke249** [Luxocracy/NeatPlates#301]
![image](https://user-images.githubusercontent.com/50395934/119019428-c9351480-b9cf-11eb-9ba8-f0797ef8e040.png)

See picture above. At the very least, it would be nice to have an option for all castbars just appear plain instead.

Using NeatPlates 2.5.1.11, on TBC Classic.

**Comment by Luxocracy** [comment]
Yeah, it's supposed to be the other way around as there is no way for an addon to tell if a cast is interrutible or not in TBC.
Should be an easy fix

**Comment by Luxocracy** [comment]
This should be fixed in the latest version now

**Comment by silverhawke249** [comment]
![image](https://user-images.githubusercontent.com/50395934/119088213-e3f0a300-ba3a-11eb-90e1-bc04552f83bb.png)
Yes, it is fixed now. Thank you!
