### ISSUE TITLE
Latest Update Errors

### ISSUE THREAD

**Issue by MetalHeadSeven** [Luxocracy/NeatPlates#303]
Getting 2 errors using 9.0.5.7

1x AceLocale-3.0-6: NeatPlates: Missing entry for 'Force Health Updates'
[string "@NeatPlates\NeatPlatesPanel.lua"]:858: in function <NeatPlates\NeatPlatesPanel.lua:547>
[string "@NeatPlates\NeatPlatesPanel.lua"]:1150: in function `?'
[string "@NeatPlates\NeatPlatesPanel.lua"]:1170: in function <NeatPlates\NeatPlatesPanel.lua:1170>

1x AceLocale-3.0-6: NeatPlates: Missing entry for 'Forces health to update every .25sec, try this if you are having health update issues'
[string "@NeatPlates\NeatPlatesPanel.lua"]:861: in function <NeatPlates\NeatPlatesPanel.lua:547>
[string "@NeatPlates\NeatPlatesPanel.lua"]:1150: in function `?'
[string "@NeatPlates\NeatPlatesPanel.lua"]:1170: in function <NeatPlates\NeatPlatesPanel.lua:1170>

**Comment by Luxocracy** [comment]
Seems I missed merging this into the retail branch, I've pushed a new release that gets rid of these messages.

**Comment by MetalHeadSeven** [comment]
Thanks for the fast fix.
