### ISSUE TITLE
unable to configure

### ISSUE THREAD

**Issue by kysatwo** [Luxocracy/NeatPlates#304]
/neatplates /np /hub commands are not valid commands. I confirm the addon is  enabled in the client (currently 2.5.1.3835) I had to ensure that out of date addons can be loaded. I noticed that when I have all other addons disabled it also does not show in the interface menu under addons tab, its like it simply does not load. I can see there being some time before an up to date version is available for TBC classic, but its odd it doesn't even throw an error.

I had also deleted the addon from overwolf and manually installed from this site with the same behavior. current version I have installed is 1.13.5 shown as NeatPlates-1.1.3.7.3.zip

**Comment by Luxocracy** [comment]
There is a TBC version, it was available before pre-patch was even released. Does your curse forge client properly detect your wow install as TBC? Or is it listed as Classic still in the version tab in the top right?

This [https://www.curseforge.com/wow/addons/neatplates/files/3322186](https://www.curseforge.com/wow/addons/neatplates/files/3322186) is the latest version for TBC, if you'd like to try and manually install it once again.

**Comment by kysatwo** [comment]
well that was easy. thank you for the quick reply. I thought it was a bit odd that the overwolf client seemed to not match the addon version to the TBC client. that is likely something that will get sorted soon enough
