### ISSUE TITLE
Lua Error: Action[FrameMeasurement]

### ISSUE THREAD

**Issue by sylvju48** [Luxocracy/NeatPlates#307]
Encountered this error while playing, I pulled the error log but haven't been able to parse it out:

Message: Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1379: Action[FrameMeasurement] failed because[Can't measure restricted regions]: attempted from: NamePlate1:GetPoint().
Time: Mon Jun  7 22:36:57 2021
Count: 1
Stack: Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1379: Action[FrameMeasurement] failed because[Can't measure restricted regions]: attempted from: NamePlate1:GetPoint().
[string "=[C]"]: ?
[string "=[C]"]: in function `GetPoint'
[string "@Interface\AddOns\NeatPlates\NeatPlatesCore.lua"]:1379: in function `?'
[string "@Interface\AddOns\NeatPlates\NeatPlatesCore.lua"]:1323: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1321>

Locals:

**Comment by Srljm** [comment]
Yes this popped up for me today as well. I got this when engaging an enemy or killed a group of enemies in a dungeon. A quick solution is to use "/console cvar_default" but this will also reset some of the interface settings for graphics.

**Comment by Luxocracy** [comment]
I'll take a look at this later today when I'm able. But if it's CVar related you might be able to resolve it by simply unchecking a box in the main settings.

But seeing as this only just popped up and the addon doesn't have a new update, it can only mean that blizzard changed something during maintenance.

**Comment by Luxocracy** [comment]
The latest release should have resolved this issue, although as a result the _Emulated nameplate_ feature will behave slightly differently when compared to before this.
