### ISSUE TITLE
Lua error with latest update

### ISSUE THREAD

**Issue by silverhawke249** [Luxocracy/NeatPlates#308]
![image](https://user-images.githubusercontent.com/50395934/121115089-47563f80-c847-11eb-9067-8d7850aac391.png)

not sure what happened, i just updated and now i get these Lua errors every so often.

**Comment by l3uGsY** [comment]
Yes, and they are very persistent forcing you to turn off the addon.

**Comment by Luxocracy** [comment]
Closing this as this is a duplicate of https://github.com/Luxocracy/NeatPlates/issues/307
