### ISSUE TITLE
Feature Request: Make nameplate stacking faster

### ISSUE THREAD

**Issue by Srljm** [Luxocracy/NeatPlates#309]
Hello.

With tanking larger mob groups one nameplate can quickly move away or through other nameplates. The standard speed of stacking nameplates is slow and does often overlap nameplates for seconds when clicking a target is important.
Can you give a setting for the speed of how fast nameplates reach their position when nameplate stacking is enabled? This would be neat.

**Comment by Luxocracy** [comment]
I have no control over the stacking speed. It's completely controllwd by blizzard and the only CVar available, that I know of, regarding the stacking of nameplates is whether or not they should stack or overlap.

**Comment by Luxocracy** [comment]
Was looking through the available CVars for something else, and found what I think might be a CVar related to this. Just change the one to a value between 0 and 1, and I believe the default is 0.025 for reference. But not sure how well this option works, as when I tried it it just caused my nameplates to vibrate at 1 when they were stacked.
`/run SetCVar('nameplateMotionSpeed', 1)`
