### ISSUE TITLE
How fix this? health dont update

### ISSUE THREAD

**Issue by sqqr1** [Luxocracy/NeatPlates#311]
Im bad eng, but i make video^:

https://user-images.githubusercontent.com/87539559/125978011-9a6ab0ca-14b1-408a-903e-df85bb2a924d.mp4

Currently HP enemy mobs dont update. This update only when i mouseovered them. 
(i dont look number health, just percentage/floating red line)

**Comment by Luxocracy** [comment]
Try enabling _**Force Health Updates**_ in the main settings of the addon
