### ISSUE TITLE
Feature request- More scaling options

### ISSUE THREAD

**Issue by Golrathx** [Luxocracy/NeatPlates#312]
Would it be possible to add the ability to have multiple different scaling options. Such as setting counterstrike totem/psyfiend and other important abilities to a larger scale, yet still be able to downscale pets/minor minions.

**Comment by Luxocracy** [comment]
The question of multiple scaling/filter options have been asked before, and it is something that I do want to add. But it does require a re-work of the current scaling/filtering system.

A re-work would hopefully mean that I could combine _opacity, scaling, filters, and color conditions_ into one component. Which would not only make it easier to understand, and would also allow for more control over the feature.
