### ISSUE TITLE
Show totem art is removing the totem nameplates entirely

### ISSUE THREAD

**Issue by Golrathcr** [Luxocracy/NeatPlates#313]
Whenever I enable show totem art after 9.1 I am no longerable to see totem nameplates until I disable it. Addon is up to date

**Comment by Luxocracy** [comment]
Is this for enemy totems? I couldn't replicate it for friendly ones. But I did find some issues with the new timer feature for totem art, and have fixed it, I'll push a release tomorrow once I can double check everything works. Might also resolve this issue but not sure.

**Comment by Golrathcr** [comment]
The new update resolved this issue for me. Thank you, much appreciated.
