### ISSUE TITLE
Where are filtered units implemented?

### ISSUE THREAD

**Issue by bartekspitza** [Luxocracy/NeatPlates#317]
I hope this is fine as an issue, as this is not a bug but a question.

I am looking to play with default nameplates, but with the `Larger Nameplates` blizzard option enabled, but I would like to decrease the size of enemy minion nameplates. Neatplates can do this by reducing the scale of `filtered units`. Could you point me to what file this is implemented in? Also, I have never interacted with WoW API or Lua, but is it possible to modify the blizzard nameplates?

**Comment by Luxocracy** [comment]
The main handling for scaling is done [here](https://github.com/Luxocracy/NeatPlates/blob/e25a9a9a6ca6022a908ed581b880c78d73d243c4/NeatPlatesHub/functions/Scale.lua#L144-L178), also [here](https://github.com/Luxocracy/NeatPlates/blob/e25a9a9a6ca6022a908ed581b880c78d73d243c4/NeatPlates/NeatPlatesCore.lua#L137-L170)

But I take it you are simply trying to modify the default blizzard nameplates? In which case you might be more interested in the [SetScale](https://wowpedia.fandom.com/wiki/API_Region_SetScale) function that already exist for almost all frames. And possibly the [event ](https://wowpedia.fandom.com/wiki/NAME_PLATE_UNIT_ADDED)for when a unit nameplate gets displayed. Used [here](https://github.com/Luxocracy/NeatPlates/blob/e25a9a9a6ca6022a908ed581b880c78d73d243c4/NeatPlates/NeatPlatesCore.lua#L1351-L1377) in NeatPlates.
