### ISSUE TITLE
Hatred problem

### ISSUE THREAD

**Issue by Obscureman** [Luxocracy/NeatPlates#319]
When I lead to a monster, the monster with linkage hatred with it or the monster hatred led by it is displayed as a safe color, even if their target is me.

**Comment by Luxocracy** [comment]
Do you have an example? Because I'm not quite sure i entirely understand the issue.

But, in general, you being the target or not doesn't determine your threat/hatred. If the game doesn't report that you have the highest threat, the bars color will not change even if the mob is targeting you.
