### ISSUE TITLE
Enemy castbar all time non-interraptable (with icon shield)

### ISSUE THREAD

**Issue by sqqr1** [Luxocracy/NeatPlates#320]
How i can fix this?

**Comment by Luxocracy** [comment]
For which version of the game is this happening for you? And do you have an example where this happens specifically, as I haven't seen this issue personally.

**Comment by sqqr1** [comment]
Tbc client. Vers addon i think last
All instance mobs, raid mobs, summonstone, pvp players... all casts with shield

**Comment by Luxocracy** [comment]
I can't seem to replicate it on any of the themes when I tried on the TBC client. But the Blizzard themes border could be mistaken as a shield icon I think, so that might be what is going on? Do you have a screenshot of it?

**Comment by sqqr1** [comment]
Yellow border its hunters steady shot (i believe its non-interaptable cast and should be with shield)
Green color its my teammates - friendly castbars in 5ppl instance (disable all modifications, blizzlike)

Perhaps this icon in not a shields, just fat borders. But in combat (especially in raid) it seems like a shield.
And if its not a shield, then what will the shield look like (yellow should be non-interaptable cast)

![tV4FYog - Imgur](https://user-images.githubusercontent.com/87539559/131265518-ef6d33c2-0161-4d86-8a13-fd4c5d5d5a3a.png)

**Comment by Luxocracy** [comment]
The game doesn't send information about what spells are interruptible or not in TBC. So there will never be a shield displayed. And yes the Blizzard theme does have some slight differences from what is currently in TBC, but this is how the Blizzard theme has always looked within the addon.

If you want to make a bit clearer you could try disabling the _Castbar Border_  element through the _Theme Customization_ that can be found at the bottom of your profile.
