### ISSUE TITLE
Scaling Problems with Buffs/Debuffs/Target Marker

### ISSUE THREAD

**Issue by laendis** [Luxocracy/NeatPlates#321]
**What version of the game you are experiencing the issue with:**
TBC

**Describe the bug**
I want to put down the Debuffs a bit closer to the Nameplate itself.
So i tryd to play with Offset Y AuraWidget, suddenly it wont work for me.
The Offset X i can change perfectly somehow.
Neither the Scaling of my Target Highlighting works.

**To Reproduce**
1. Go to Buffs Debuffs
2. Click on Aura Offsets

Iam assuming something prior wont let me change the settings...

Thanks for help!

**Comment by Luxocracy** [comment]
See if you can move it through the _Theme Customization_ feature. You can find it at the bottom of your profile settings.
