### ISSUE TITLE
Problem with forced default blizzard nameplates in dungeons and raids

### ISSUE THREAD

**Issue by Ambry7700** [Luxocracy/NeatPlates#322]
**What version of the game you are experiencing the issue with:**
TBC

**Describe the bug**
When in dungeon default blizzard nameplates are broken

**To Reproduce**
1. Go to a dungeon
2. See an error

**Expected behavior**
Default blizzard nameplates with a level on the right of the nameplates.

**Screenshots**
[https://imgur.com/a/DtDn5RB](https://imgur.com/a/DtDn5RB)

**Additional context**
I recently came back to TBC and experienced this issue. I didn't have the problem in the whole classic with this.

Thanks for the help!

**Comment by Luxocracy** [comment]
This seems to have been something that was overlooked while making the TBC version, as it is based on the retail version of the addon and not the Classic one.

The retail version still has a fix for this issue, as it happens in all versions, but in retail the default nameplates are slightly wider when compared to the original ones. There should be a fix available for this shortly on Curseforge.

**Comment by octamooze** [comment]
is there a way to set it so the bars are always visable? my bars dissapear if i drop combat, and this really is stressfull in arena

**Comment by Luxocracy** [comment]
There's nothing that can be done about the forced blizzard party frames in raids. Addons aren't allowed to alter friendly nameplates in most group content.
