### ISSUE TITLE
Debuff icons offset from nameplate

### ISSUE THREAD

**Issue by Arkilyte** [Luxocracy/NeatPlates#325]
**What version of the game you are experiencing the issue with:**
Retail - v409

**Describe the bug**
The debuff icons above the nameplate are offset past the nameplate itself.

**To Reproduce**
1. Dot a mob and see the icon over to the left/right. Aura anchor is set as "left" and icon style is wide.

**Expected behavior**
Expect there to be icons above the nameplate and not above empty space. Looks like there is a maximum of five icons per row now instead of three.

![neatplates icons](https://user-images.githubusercontent.com/51346135/135724491-b76b7b25-ea9a-4687-a931-2b2bc3418cd8.PNG)
.

**Comment by Luxocracy** [comment]
Seems there was a minor mistake in the logic that sets the amount of auras per row.

I've pushed a new release that should resolve this.

**Comment by Arkilyte** [comment]
New update seems to work. Thanks!
