### ISSUE TITLE
Lua Error [TBC Classic]

### ISSUE THREAD

**Issue by MurderOnMyMind7** [Luxocracy/NeatPlates#330]
Hello, 

I apologize for bothering you, but I'm experiencing a strange lua error. I've never had a lua error before so I'm not sure what to do. It seems to trigger randomly. I'll see it every so often, sometimes I don't see it for hours. Maybe it's just a coincidence, but a few times while using the general interface menu, it popped up. As I mentioned before, I have no experience with these types of issues so I'm going to try and link a screenshot that I captured. Urgghhh I hate to bother you as I think this addon is AMAZING and I LOVE it, but when you get a chance, can you please look into this, it's a little annoying to deal with. Have a wonderful week :D 

Thanks,

**Comment by Luxocracy** [comment]
If you could link to either a screenshot as you mention or simply paste the entire error here. It would be incredibly helpful, as that would essentially tell me exactly what is going wrong.

**Comment by MurderOnMyMind7** [comment]
Thanks for the speedy response! <3 I'm trying to, but the file is size is too big... I'm trying to drop the resolution, but I'm not great with this kind of thing. I considered typing the error verbatim, but there's too great a chance I'll make errors copying it and just confuse you. haha

**Comment by MurderOnMyMind7** [comment]
[Screen Shot 2022-01-11 at 8.05.31 AM.zip](https://github.com/Luxocracy/NeatPlates/files/7847482/Screen.Shot.2022-01-11.at.8.05.31.AM.zip)

**Comment by MurderOnMyMind7** [comment]
^ Hope this is helpful :D

**Comment by MurderOnMyMind7** [comment]
Ironically, if you look at the NeatPlate to the right of the lua frame, you'll see the numbers in the enemies health bar; I decided to start using that feature like a day before the error started showing up! I'll try that now and get back to you soon <3 Thank you!

**Comment by MurderOnMyMind7** [comment]
. . . I guess after server maintenance *facepalm* XD

**Comment by MurderOnMyMind7** [comment]
So, under the setting under HEALTH BAR VIEW section, it's set to "Health total & Percent" if I'm thinking of the setting you are. Also, the "Status Text" settings are all default under the Theme Customization options. I changed it Health Total & Percent to something else, then closed interface settings, reloaded and set it back to the setting I was using. I'm hoping this will fix it, but I will keep you informed if the issue persists. If I misunderstood you or you have another idea for me to try, please let me know. 

Thanks again for taking time to help me and for being so quick to lend a hand! You rock. I've said it before, but I cannot play this game without NeatPlates as I totally LOVE it! If we're done here, enjoy your day!

**Comment by Luxocracy** [comment]
That's not the option I was thinking of. This is a slider that controls how many decimals are shown on the healthbar, I believe it's at the very bottom of the healthbar section.

**Comment by MurderOnMyMind7** [comment]
Okay, I'll check that out tonight when I get home. Hopefully it works <3

**Comment by MurderOnMyMind7** [comment]
Seems to have fixed it. It looks like the issue is the -0% on the slider, but I have no idea. haha I just moved it to 1 and it's good now. Thanks! Have a great weekend <3
