### ISSUE TITLE
Quatre Theme personal resource sometimes behind Elite/Rare Border

### ISSUE THREAD

**Issue by Kommeh** [Luxocracy/NeatPlates#331]
**What version of the game you are experiencing the issue with:**
Retail

**Describe the bug**
While using the Quatre theme the rare enemy border shows on top of the personal resource widget, whereas the elite border sits behind the personal resource widget which I assume is intended.

**To Reproduce**
1. Use quatre theme
1. Have elite border/icon enabled in all places
2. Fiind rare mob
3. Have an active amount of personal resource (in my example at least 1 chi to see it behind border)
4. Target mob

**Expected behavior**
Border should sit behind the personal resource widget like the elite border does.

**Screenshots**
Attached. Same settings for each picture.

**Additional context**
Let me know if you need any other info.
![Elite](https://user-images.githubusercontent.com/71908003/159594544-ede90596-3649-4c08-a04f-015eefd0ec3a.JPG)
![Rare](https://user-images.githubusercontent.com/71908003/159594547-0bd7069d-3cc7-4f60-9551-3ebf570d9121.JPG)

**Comment by Kommeh** [comment]
To add on to this. It was also happening on Elite mobs yesterday while playing. But it was not consistent for some reason. Sometimes the personal resource would be on top of the border frame and other times it was not. Very strange.

**Comment by Luxocracy** [comment]
This should be fixed in the latest release. The two frames ended up having the same frame level, so depending on when they were created, one would be in front of the other and vice versa.

**Comment by Kommeh** [comment]
Thanks Lux! Great work as always!
