### ISSUE TITLE
The addon does not show the colored names of allied players

### ISSUE THREAD

**Issue by sealser** [Luxocracy/NeatPlates#334]
Live version

Only when an ally is a target or the option to always show frames for allies is enabled. Allied names are always blue. I have tried various options without success

**Comment by Luxocracy** [comment]
Not entirely sure I understand the issue you are having.

But the two options that should be related to this are **Friendly Name Color** & **Friendly Headline Color**. The first one is located in the **Health Bar View** section, an the latter is in the **Headline View** section.

The **Headline view** is the version of the nameplate that doesn't display a healthbar, so it might be this one your looking for. Make sure it is set to **By Class**

**Comment by sealser** [comment]
Thank you. It seems to work. Can you tell me if it's possible to disable player signatures? I don't know what they are called..
[https://prnt.sc/cgSXIa2khYSs](url)

**Comment by sealser** [comment]
Doesn't work for all players
https://prnt.sc/Qs3L9XiHScyh

**Comment by Luxocracy** [comment]
For the first question, there's an option right below the friendly headline color to control what "subtext" gets displayed. In this case it seems to be set to one of the options that display the guildname.

As for the second thing, I believe that is a player of the opposite faction. So even though you are in a neutral area they still count as being of the opposite faction. I consider this to be the correct behavior, if you have enemy nameplates hidden

**Comment by sealser** [comment]
Oh thank you. I have one more question.  I choose to display enemy health by class color.  In the open world, everything works fine.  But when I come to rbg, there all the players have red health bars.
