### ISSUE TITLE
Make NeatPlates WowUp (Addon manager) compatible

### ISSUE THREAD

**Issue by Wensh** [Luxocracy/NeatPlates#335]
**Is your feature request related to a problem? Please describe.**
Curseforge blocked Wowup addon manager, would like to manually add Github to Wowup addon manager. But NeatPlates releases doesn't have the required WowUP structure described here:

https://wowup.io/guide/wowup/hub

**Describe the solution you'd like**
Adapted zip folder structure so I can manage NeatPlates in WowUp

**Comment by Luxocracy** [comment]
I'll probably migrate the structure over to the WoW Packager structure so that it will also push releases to both WoWInterface and Wago. Which I believe should resolve the issue.

**Comment by Luxocracy** [comment]
The addon is now available on both Wago and Wow interface. Hopefully this will resolve the issue.

**Comment by Wensh** [comment]
Yes, I just updated the addon in WowUp, thanks for your swift action
