### ISSUE TITLE
Arena numbers nameplate

### ISSUE THREAD

**Issue by ssbb112V** [Luxocracy/NeatPlates#336]
I really want the settings related to arena ID.
For example show only number "1" without name. Or "1 - name".
And main Font ID. What is active now is very different from the font in the name. This smaller, different color and... square brackets.

I really love NP. And I can't play without it. But these disadvantages do not allow to enjoy the possibilities of the addon in the arena as I have to turn it off.

Now it looks like *screen1*. And I want it to look like addon "arena nameplate numbers" *screen2*. Maybe with name "1 - name". And the number color white, and size increase
![image](https://user-images.githubusercontent.com/106621275/171257727-6210c7c8-336c-4b90-8930-55586480b5d4.png)
![image](https://user-images.githubusercontent.com/106621275/171257774-67fae3a3-4dd6-4a23-86f4-5a9edafa75a6.png)

**Comment by Luxocracy** [comment]
There's this profile setting in the healthbar section **Replace Unit Name with Arena ID** which will replace the unit name with it's Arena ID inside arenas.

**Comment by ssbb112V** [comment]
Cool, I didn't see that one!

The only thing left to do is to increase the font size of the "number" without increasing the font size of the "name". 
Now I have to use 2 profiles, but it would be cool to do in one.
