### ISSUE TITLE
Ability to MOVE Enemy Cast Bars

### ISSUE THREAD

**Issue by DarkDestiny0675** [Luxocracy/NeatPlates#337]
While I love the addon, I'd really love the ability to move the Enemy cast bars.  When you put in the quest text for the subtext field, the cast bar gets lost in the mix.  If I can move it below there, it would be perfect.  So, just a suggestion... add the ability to move cast bars on enemies.  Thanks.

**Comment by Luxocracy** [comment]
At the bottom of your active profile, there's a button for _Theme Customization_  where you can move the castbars and most other things as well.

**Comment by DarkDestiny0675** [comment]
Didn't realize the option was even in there.  I'll take another look at it again.  Thanks for the quick response.  Love the app.  Thanks for making it for us.
