### ISSUE TITLE
Nameplates Turn Off When Combat Starts

### ISSUE THREAD

**Issue by healidan** [Luxocracy/NeatPlates#338]
**What version of the game you are experiencing the issue with:**
TBC Classic

**Describe the bug**
So when I press "Ctrl + V" to show all nameplates it turns on, but when I engage into combat (as soon as I cast Smite and Shadow Word: Pain right after) the nameplate turns off... Even Friendly nameplates turn off... I don't understand why either. I have tried disabling all addons and it still glitches.

**To Reproduce**
1. Activate Friendly + Enemy nameplates
2. Enter combat state and use a few spells
3. Nameplates turn off on their own

**Comment by Luxocracy** [comment]
In the main settings, there's a section called automation. This will show/hide the nameplates depending on what you've selected. If you don't want any automation just make sure they're all set to nothing/white.

If the issue still isn't fixed I'd suggest taking a look if you have any other addons that might have similar features. A common one is Leatrix.

**Comment by healidan** [comment]
Perfect I think I did that last night and it’s resolved.

Thanks again!

Sent from my iPhone

On Jun 27, 2022, at 13:34, Luxocracy ***@***.***> wrote:

﻿

In the main settings, there's a section called automation. This will show/hide the nameplates depending on what you've selected. If you don't want any automation just make sure they're all set to nothing/white.

If the issue still isn't fixed I'd suggest taking a look if you have any other addons that might have similar features. A common one is Leatrix.

**Comment by Yarvillian** [comment]
I'm getting this similar issue with all my automation turned off. Including this error for more information:
9x ...eBlizzard_NamePlates\Blizzard_NamePlates.lua:247: Usage: GetRaidTargetIndex(unit)
[string "=[C]"]: in function `GetRaidTargetIndex'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:247: in function `OnRaidTargetUpdate'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:122: in function `OnNamePlateAdded'
[string "@Blizzard_NamePlates\Blizzard_NamePlates.lua"]:56: in function <...eBlizzard_NamePlates\Blizzard_NamePlates.lua:47>

Locals:
(*temporary) = nil

**Comment by Luxocracy** [comment]
This error is in regards to an action in the default blizzard nameplates. You usually don't see these errors unless you are in a beta test, or if an addon has tainted the base nameplates.

So if you are on a live version of the game, an addon has most likely tainted the base nameplates. Figuring out which addon did so can be a bit tricky, but if you can re-produce the issue the best method is to simply disable addons in an attempt to figure out which one is causing it.
