### ISSUE TITLE
ROGUE TBC BLADE FLURRY BUG!!!

### ISSUE THREAD

**Issue by barys187** [Luxocracy/NeatPlates#339]
Hello,

I recently  installed your addon and i realised that when im using blade flurry damage does not register to the nearby enemy's healthbar i have to focus that enemy and swap to my main target in order to see the damage i ve dealt to it.

*Please let me know if there's a fix to this issue that i'm having*  
Thx..
_Game-Mode_  :  **TBC Classic Blizzard**

**Comment by Luxocracy** [comment]
This is probably related to #333, try enabling **Force Healthupdates** in the main settings and see if this helps with the issue.

This option will be enabled by default for TBC in a future update, as it mainly seems to affect TBC, but I haven't gotten around to it yet.
