### ISSUE TITLE
Plates no longer showing properly since today's update

### ISSUE THREAD

**Issue by Orion2002** [Luxocracy/NeatPlates#342]
**What version of the game you are experiencing the issue with:**
Live/Retail, TBC, Classic
WOTLK Classic

**Describe the bug**
Name plates no longer show above enemies.

**To Reproduce**
1. Right click on any merchant
2. Error message pops up for the addon
3. Walk up to any mob in the wild
4. Name plates are missing, but it does show if they are part of a kill/loot quest still
5. Error is as follows:
6. Date: 2022-09-02 15:34:04
ID: 22
Error occured in: Global
Count: 1
Message: ..\AddOns\NeatPlates\NeatPlatesCore.lua line 1622:
   attempt to call method 'CreateTargetFrame' (a nil value)
Debug:
   [string "@NeatPlates\NeatPlatesCore.lua"]:1622:
      NeatPlates\NeatPlatesCore.lua:1616
   [string "@NeatPlates\NeatPlatesCore.lua"]:1633: ?()
   [string "@NeatPlates\NeatPlatesCore.lua"]:1557:
      NeatPlates\NeatPlatesCore.lua:1555
   [string "=[C]"]: TurnOrActionStop()
   [string "TURNORACTION"]:4:
      [string "TURNORACTION"]:1
Locals:
unitAlive = true
guid = "Creature-0-4392-0-115-1678-0000121376"
(*temporary) = nil
(*temporary) = <table> {
 IsFriend = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesUtility.lua:28
 GetTotemOwner = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesUtility.lua:280
 EnableHealerTrack = <function> defined @Interface\AddOns\NeatPlatesWidgets\HealerTrack.lua:332
 fade = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesUtility.lua:170
 IsTotem = <function> defined @Interface\AddOns\NeatPlatesWidgets\TotemIconWidget.lua:128
 GetNumRaidMembers = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesUtility.lua:38
 GetUnitQuestInfo = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesUtility.lua:315
 GetNumPartyMembers = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesUtility.lua:44
 GetUnitSubtitle = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesUtility.lua:218
 round = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesUtility.lua:165
 IsHealer = <function> defined @Interface\AddOns\NeatPlatesWidgets\HealerTrack.lua:16
 DisableHealerTrack = <function> defined @Interface\AddOns\NeatPlatesWidgets\HealerTrack.lua:341
 GetFriendlyThreat = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesUtility.lua:402
 RGBToHex = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesUtility.lua:137
 GetRelativeThreat = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesUtility.lua:526
 IsPartyMember = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesUtility.lua:33
 abbrevNumber = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesUtility.lua:111
 copyTable = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesUtility.lua:10
 HexToRGB = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesUtility.lua:120
 GetGroupInfo = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesUtility.lua:58
 GetSpec = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesUtility.lua:50
 ParseGUID = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesUtility.lua:184
 Colors = <table> {
 }
 GetArenaIndex = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesUtility.lua:380
 IsGuildmate = <function> defined =[C]:-1
 mergeTable = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesUtility.lua:75
 updateTable = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesUtility.lua:92
 GetPetOwner = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesUtility.lua:268
}
(*temporary) = "attempt to call method 'CreateTargetFrame' (a nil value)"
HasTarget = true
NeatPlatesTarget = nil
OnNewNameplate = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesCore.lua:421
toggleNeatPlatesTarget = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesCore.lua:232
PlatesByGUID = <table> {
}
SetUpdateAll = <function> defined @Interface\AddOns\NeatPlates\NeatPlatesCore.lua:196

**Expected behavior**
Name plates to be visible above allies/enemies

**Screenshots**
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/112730072/188233126-ad01b0d6-ad6a-43ac-ae0c-33bd7da762e5.png">

**Additional context**

**Comment by xuspu** [comment]
i was in AV, and a fast disconect ocurres me, when i log in other time my neat plates have disapear like in image  of our mate..... :(
i have a neat plates addon installed in curseforge but not apear in Addons in game

**Comment by Midiall-Git** [comment]
Also not seeing the nameplates after the latest update. I even rolled back to to 413 and still are having the same issue so I suspect its due to a version change with the client or something.

**Comment by orionshock** [comment]
<3 Blizzard 
Today they published the proper UI update for wrath.

NeatPlates\NeatPlatesGlobals.lua - Change Line 1 to:
`NEATPLATES_IS_CLASSIC_WOTLKC = WOW_PROJECT_ID == WOW_PROJECT_WRATH_CLASSIC -- Might get changed once actual release happens
`

LibRangeCheck also needs to be updated....

**Comment by Midiall-Git** [comment]
That did it!

For the less technically inclined, LibRangeCheck is in:

NeatPlates\libs\LibRangeCheck-2.0

on line 51 change:
local IsClassic = (WOW_PROJECT_ID == WOW_PROJECT_CLASSIC) or (WOW_PROJECT_ID == WOW_PROJECT_BURNING_CRUSADE_CLASSIC)

to:
local IsClassic = (WOW_PROJECT_ID == WOW_PROJECT_CLASSIC) or (WOW_PROJECT_ID == WOW_PROJECT_WRATH_CLASSIC)

**Comment by AeronV** [comment]
I've changed the LibRangeCheck on a fresh install, and it still doesn't work for me

**Comment by Midiall-Git** [comment]
> I've changed the LibRangeCheck on a fresh install, and it still doesn't work for me

You will need to change the main NeatPlatesGlobals.lua as well as Orionshock noted above

**Comment by poonuss** [comment]
ive changed both of the files and its still not working for me

**Comment by AeronV** [comment]
Thanks worked for me now.
Try manually deleting the files, then fresh installing.

**Comment by Neuroticz** [comment]
> 

Do you mind elaborating on the steps you took to fix it? I changed the lines and did multiple fresh installs and all it managed to do was make the settings available in game. It still doesnt load the nameplates though.

**Comment by KhimNever934** [comment]
Go to your addon folder and follow the steps below:

NeatPlates\libs\LibRangeCheck-2.0

on line 51 change:
local IsClassic = (WOW_PROJECT_ID == WOW_PROJECT_CLASSIC) or (WOW_PROJECT_ID == WOW_PROJECT_BURNING_CRUSADE_CLASSIC)

to:
local IsClassic = (WOW_PROJECT_ID == WOW_PROJECT_CLASSIC) or (WOW_PROJECT_ID == WOW_PROJECT_WRATH_CLASSIC)

then go to to NeatPlates/NeatPlatesGlobals

Change Line 1 to:
NEATPLATES_IS_CLASSIC_WOTLKC = WOW_PROJECT_ID == WOW_PROJECT_WRATH_CLASSIC -- Might get changed once actual release happens

**Comment by KhimNever934** [comment]
> > 
> 
> Do you mind elaborating on the steps you took to fix it? I changed the lines and did multiple fresh installs and all it managed to do was make the settings available in game. It still doesnt load the nameplates though.

Go to your addon folder and follow the steps below:

NeatPlates\libs\LibRangeCheck-2.0

on line 51 change:
local IsClassic = (WOW_PROJECT_ID == WOW_PROJECT_CLASSIC) or (WOW_PROJECT_ID == WOW_PROJECT_BURNING_CRUSADE_CLASSIC)

to:
local IsClassic = (WOW_PROJECT_ID == WOW_PROJECT_CLASSIC) or (WOW_PROJECT_ID == WOW_PROJECT_WRATH_CLASSIC)

then go to to NeatPlates/NeatPlatesGlobals

Change Line 1 to:
NEATPLATES_IS_CLASSIC_WOTLKC = WOW_PROJECT_ID == WOW_PROJECT_WRATH_CLASSIC -- Might get changed once actual release happens

**Comment by Luxocracy** [comment]
Seems Blizzard decided to hotfix in the correct project id while I was asleep, the latest should fix that issue.

Not sure if the range library has been updated to reflect this as well now, but I wasn't getting any errors while I was trying it out. But an updated version might be provided by another addon.

So if anyone is still having issues with the range library after the latest update I guess I'll have to included it directly instead of at the build stage until it gets updated.
