### ISSUE TITLE
 '/neatplates' no longer prompts menu and unit frames disappeared

### ISSUE THREAD

**Issue by joshuamcarroll** [Luxocracy/NeatPlates#343]
**What version of the game you are experiencing the issue with:**
TBC (WoTLK pre-patch) - version 3.4.0.45435

**Describe the bug**
/neatplates no longer prompts menu screen and unit frames no longer appear after latest update (wrath classic also had an update recently so may be related). 

**To Reproduce**
1. Log in to WoW Wrath Classic
2. type '/neatplates' and hit 'Enter'
3. Nothing prompts nor are unit frames displayed (I heard other unit frame addons weren't working today either). 

**Expected behavior**
Neat plates menu to prompt and unit frames to appear over friendly, enemy, and npc players

**Screenshots**

**Additional context**

**Comment by Luxocracy** [comment]
Hi, this would be the related to the same issue as #342
