### ISSUE TITLE
Retail - Rogue Combo Points displaying incorrectly with Deeper Stratagem talented

### ISSUE THREAD

**Issue by Shadowmastr** [Luxocracy/NeatPlates#344]
Combo points for rogue in retail is currently displaying one less combo point with Deeper Stratagem talented than are actually active. The nameplates still display 6 empty combo points properly, but 1 real combo point displays 0 combo points on the nameplate, 2 real combo points displays 1 combo point on the nameplate, etc.
![1lesscp](https://user-images.githubusercontent.com/72906585/188277589-69d5685b-38ee-4133-a8be-20a509e7d05a.jpg)

**Comment by Luxocracy** [comment]
This should be fixed in the latest release. Was due to a minor change that allows the combo point bar to show even if there were no combo points active, but you had a charged combo point.

The combo widget is generally just in need of a re-write as any minor change can have larger effects. Like this change.

**Comment by Shadowmastr** [comment]
Unfortunately, this still isn't fixed with the most recent update. Here's another screenshot showing Deeper Stratagem not working correctly as Kyrian (you can see the first screenshot, I am Venthyr, so no animacharged CP shenanigans). In this second screenshot, I am at full CP according to the default game, and the nameplates are only showing I have 5 combo points (I have not yet pressed Echoing Reprimand):
![5cp](https://user-images.githubusercontent.com/72906585/188287335-72dbfea2-fddd-4833-b79b-e7d62e08e38a.PNG)


Below is also a SS of being Kyrian with Deeper Stratagem talented, and immediately after casting a finisher consuming an animacharged combo point, the nameplates appear like this for around 1-2 seconds before returning back to normal and showing the animacharged combo point locations correctly:
![animachargedds](https://user-images.githubusercontent.com/72906585/188287394-c8cfa154-7484-448c-8f96-bb901849f91e.PNG)

Interestingly enough, the combo points DO show correctly as Kyrian, after using a finisher with animacharged combo points active on an animacharged CP (and after around 1-2 seconds for the nameplate to adjust/update):
![correctcpkyrian](https://user-images.githubusercontent.com/72906585/188287496-ca90da70-9b06-419f-90cf-03caaf6cf8f0.PNG)

Hopefully this helps!

**Comment by Shadowmastr** [comment]
Here's also the release I have downloaded for confirmation that I have the correct version:
![nprelease](https://user-images.githubusercontent.com/72906585/188287592-5cf937f2-2388-495d-a883-0820d134fabd.PNG)

**Comment by Luxocracy** [comment]
The deeper stratagem issue should have been fixed as of v416. So that would be 1 version to low.

**Comment by Shadowmastr** [comment]
v416 pushed to Curseforge yesterday evening for me, and it fixed everything. Many thanks!
