### ISSUE TITLE
Uninturruptable castbars shown as inturruptable casts correctly - wotlk classic

### ISSUE THREAD

**Issue by SyuSyuGG** [Luxocracy/NeatPlates#345]
**What version of the game you are experiencing the issue with:**
WOTLK Classic

**Describe the bug**
uninturruptable casts should be shown gray color + sheild mark, but it shows as normal cast.

**To Reproduce**
i got this bug from tbc classic in kr client. it always happened from 5 months when i use this addon first.

**Expected behavior**
when pally bubble and casting heals, it shown as normal orange cast, no shields no gray castbars.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/94262928/188282329-b05f4e86-fb16-476f-b8cc-02bf0becbcf0.png)

(look at Blizzard castbars on the left top side and neatplates castbar please.)

**Additional context**
i really really love NeatPlates, and i dont want to lose this perfect addon...
please help me to fix castbar issue TnT...

**Comment by SyuSyuGG** [comment]
the issue since tbc classic for me

**Comment by Luxocracy** [comment]
The necessary events to determine if a spell was interruptible or not shouldn't have been available during TBC. But I might have just missed them adding it into the classic version at some point, as it wasn't available at the start of TBC Classic at least.

But you are right in that it should be available for Wrath, so I'll do some adjustments so that it properly works in Wrath Classic.

**Comment by SyuSyuGG** [comment]
> 

Big thanks!! 
so its not bug only for me, just for everyone and you can fix it later, right?
my english is not good so i dont know that i understood correctly,,

**Comment by SyuSyuGG** [comment]
but the option that choosing color inturruptible or not is already in NeatPlates isn't it?
it doesnt work for me.

**Comment by SyuSyuGG** [comment]
> but the option that choosing color inturruptible or not is already in NeatPlates isn't it?
> it doesnt work for me.

**Comment by Luxocracy** [comment]
It's available now.

Had to ensure it was actually in WOTLKC before adding it.

**Comment by SyuSyuGG** [comment]
Oh i just checked!!!
Thank you very much. this is so good
