### ISSUE TITLE
Combo Point displaying incorrectly for Feral Druid

### ISSUE THREAD

**Issue by AeronV** [Luxocracy/NeatPlates#346]
Game Version - WotLK

When playing my Feral Druid. The combo points always shows 1 more combo point than the target actually has.
I've tested this on my rogue, and can't replicate the same issue.

Steps to Reproduce
1. Use a combo generator ability on an enemy
2. See error (additional combo point)
3. Continue using combo points until max 
4. See error (6 greyed out combo points)

**Expected behavior**
It always counts displays on more combo point that you actually have (unless zero), and even shows 6 at max combo points.

![image](https://user-images.githubusercontent.com/73405680/189389567-870d9888-754e-4d14-9f08-0d72de6bf288.png)

![image](https://user-images.githubusercontent.com/73405680/189389707-3e3db361-948e-4fd2-b9be-8950334fa41f.png)

**Comment by Luxocracy** [comment]
Are you using the latest version? There was a bug with this prior to v415, any version after this should have this issue fixed.

**Comment by AeronV** [comment]
Yup, I was on 414, curse wasn't showing an update to the most recent version.
