### ISSUE TITLE
Target castbar

### ISSUE THREAD

**Issue by Antalgick** [Luxocracy/NeatPlates#348]
**What version of the game you are experiencing the issue with:**
Classic WOTLK

**Describe the bug**
I have both blizzard and neatplates castbar overlaped under enemy target life bar.

**To Reproduce**
everytime

**Expected behavior**
Would like to have only neatplates castbar (much more beautiful !) and not blizzard one for a better visibility

Good job overall !

**Comment by Antalgick** [comment]
![Neatplates](https://user-images.githubusercontent.com/113716295/190702500-cf5ac9cd-4020-4166-a7e9-df0ff6fd43dd.png)

With a screenshot !
Thx

**Comment by Luxocracy** [comment]
You can try changing the CVar related to the targets castbar to 0 with this command and see if it does anything
`/console showTargetCastbar 0`
But I suspect this issue is related to some other addon, that is adding a castbar.

**Comment by Antalgick** [comment]
Hi mate !
Indeed it was an other addon (classiccastbar) causing this issue. Problem solved.
Thank you !
