### ISSUE TITLE
Enemy Cast Bars

### ISSUE THREAD

**Issue by kickr1989** [Luxocracy/NeatPlates#349]
Hi all, I am wasting my interrupt on enemys who are casting unkickable spells.  The shield on the blizzard default isn't reskinned or showing for me. How can I change this?

**Comment by Luxocracy** [comment]
Sorry for taking a while to respond, must have missed the notification for this. 

There's no setting that toggles this behaviour, there should be a shield that shows up. And when I tested it just now to double check it does show. There was an issue with this in the TBC/Wrath versions prior to v416, so I recommend you check what version the addon is and update if needed.
