### ISSUE TITLE
[Wotlk] Totems always shows

### ISSUE THREAD

**Issue by hasnogaems** [Luxocracy/NeatPlates#351]
If ally healthbars on, then ally totem plates always shown independent of any settings.

**Comment by Luxocracy** [comment]
The existing option to exclude totems from the Friendly nameplates does indeed seem to not be working as intended. I will take a closer look and see what is going on.

But this won't actually hide them in the way you might expect, as it just sets them to _Headline mode_, which is the text only version of the nameplates.

If you actually want to hide them and show no bar at all, you need to change the CVar relating to friendly totem nameplates. As this cannot be done through the standard interface options. You can do this with the command below.
`/run SetCVar("nameplateShowFriendlyTotems", 0)`

**Comment by hasnogaems** [comment]
This cvar worked, but it constantly being reset if I use nameplate automation. I use show ally plates in pvp and hide in pve.
Could you implement the option for it not being reset if I use automation?
