### ISSUE TITLE
When I enter dungeon my friendly nameplates settings resets to default seems like

### ISSUE THREAD

**Issue by hasnogaems** [Luxocracy/NeatPlates#352]
I have setup where friendly nameplates is just a class icon with name. It works fine in the world and battlegrounds but after I enter dungeon, it suddenly shows healthbars with no class icons.

I checked for any automation, and all seems to be disabled.

**Comment by Luxocracy** [comment]
Friendly nameplates sadly cannot be altered/skinned in dungeons. It's a limitation set by Blizzard a while back because people were getting a bit too clever with their addons.
