### ISSUE TITLE
NeatPlates Configuration error

### ISSUE THREAD

**Issue by s890214** [Luxocracy/NeatPlates#353]
**What version of the game you are experiencing the issue with:**
WLK

**Describe the bug**
the hostile >>> player options not work，and  friendly >>> player options  work to hostile

**To Reproduce**

uncheck or check   the  friendly >>> player options

**Screenshots**
![微信截图_20221013101747](https://user-images.githubusercontent.com/29193110/195483740-db8f6070-83ad-4479-b7f6-1be1882042b1.png)

**Comment by Luxocracy** [comment]
Sorry for the delayed response.

But I am unable to replicate this issue. I do however notice something odd in the screenshot you provided.

There should be a total of 3 options underneath the NPC label (highlighted in green), which might indicate an issue with your installation of the addon.
![195483740-db8f6070-83ad-4479-b7f6-1be1882042b1](https://user-images.githubusercontent.com/2884542/196053193-bec79b48-832d-44e1-bfab-598bd5265a11.png)

You could try to re-install the addon and see if that helps.

**Comment by s890214** [comment]
Sorry, the previous screenshot is old.
It's a new screenshot now.
This problem still exists.

shift+v open，
![微信图片_20221018110044](https://user-images.githubusercontent.com/29193110/196326423-bce7989d-456a-4d4e-931b-f4baa80cfb19.png)

shift+v open
![微信图片_20221018110050](https://user-images.githubusercontent.com/29193110/196326439-2b4e64f4-0826-4f0d-bdfd-d5e13444f4b2.png)

shift+v close
![微信图片_20221018110053](https://user-images.githubusercontent.com/29193110/196326446-cbff0168-59ab-4776-84f1-9a7b033d52d3.png)

shift+v close
![微信图片_20221018110056](https://user-images.githubusercontent.com/29193110/196326458-a0802e39-11d5-4330-a886-42dd4fcba314.png)

shift+v close
![微信图片_20221018110059](https://user-images.githubusercontent.com/29193110/196326463-27cfccf4-d9f6-4112-b542-0fe302fa7399.png)

**Comment by s890214** [comment]
> Sorry for the delayed response.
> 
> But I am unable to replicate this issue. I do however notice something odd in the screenshot you provided.
> 
> There should be a total of 3 options underneath the NPC label (highlighted in green), which might indicate an issue with your installation of the addon. ![195483740-db8f6070-83ad-4479-b7f6-1be1882042b1](https://user-images.githubusercontent.com/2884542/196053193-bec79b48-832d-44e1-bfab-598bd5265a11.png)
> 
> You could try to re-install the addon and see if that helps.

@Luxocracy
