### ISSUE TITLE
CUSTOM_CLASS_COLORS

### ISSUE THREAD

**Issue by nebularg** [Luxocracy/NeatPlates#354]
**What version of the game you are experiencing the issue with:**
Live/Retail

**Describe the bug**
v418-alpha bricks anything that uses CUSTOM_CLASS_COLORS. Don't create the global yourself, it has a [metatable](https://github.com/phanx-wow/ClassColors/blob/master/ClassColors.lua#L25) that lets addons register for updates. And DEFINITELY don't add it as a SavedVar for your addon.

<https://github.com/phanx-wow/ClassColors/wiki>

**Comment by Luxocracy** [comment]
Thank you for the info.

This was something that was included in the alpha release by mistake, because I seemingly used the wrong branch as a base for the Dragonflight updates. I'll clean it up as soon as I am able
