### ISSUE TITLE
LUA error on version NeatPlates-v418-alpha2

### ISSUE THREAD

**Issue by nearlysober80** [Luxocracy/NeatPlates#355]
**What version of the game you are experiencing the issue with:**
Live/Retail

**Describe the bug**
When targeting most enemy creatures, the following LUA pops up:

Message: ...nterface\AddOns\NeatPlatesWidgets\ResourceWidget.lua:300: attempt to concatenate local 'path' (a table value)
Time: Wed Oct 19 19:35:49 2022
Count: 7
Stack: ...nterface\AddOns\NeatPlatesWidgets\ResourceWidget.lua:300: attempt to concatenate local 'path' (a table value)
[string "=[C]"]: ?
[string "@Interface\AddOns\NeatPlatesWidgets\ResourceWidget.lua"]:300: in function <...nterface\AddOns\NeatPlatesWidgets\ResourceWidget.lua:297>
[string "@Interface\AddOns\NeatPlatesWidgets\ResourceWidget.lua"]:407: in function <...nterface\AddOns\NeatPlatesWidgets\ResourceWidget.lua:404>
[string "=[C]"]: in function `foreach'
[string "@Interface\AddOns\NeatPlatesWidgets\ResourceWidget.lua"]:404: in function `UpdatePoints'
[string "@Interface\AddOns\NeatPlatesWidgets\ResourceWidget.lua"]:536: in function `createFunction'
[string "@Interface\AddOns\NeatPlatesHub\functions\Widgets.lua"]:626: in function <Interface\AddOns\NeatPlatesHub\functions\Widgets.lua:613>
[string "@Interface\AddOns\NeatPlatesHub\functions\Widgets.lua"]:664: in function `OnInitializeWidgets'
[string "@Interface\AddOns\NeatPlatesHub\functions\Core.lua"]:531: in function `OnInitialize'
[string "@Interface\AddOns\NeatPlates\NeatPlatesCore.lua"]:759: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:715>
[string "@Interface\AddOns\NeatPlates\NeatPlatesCore.lua"]:1601: in function `?'
[string "@Interface\AddOns\NeatPlates\NeatPlatesCore.lua"]:1556: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1554>

Locals: 

**To Reproduce**
Target enemies

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Luxocracy** [comment]
This should be fixed in the latest alpha.
