### ISSUE TITLE
castbar not showing who interrupted like before

### ISSUE THREAD

**Issue by Spkilla** [Luxocracy/NeatPlates#362]
**What version of the game you are experiencing the issue with:**
Live/Retail 10.0

**Describe the bug**
Despite having option to show who interrupted in cast bar selected, it only shows (interrupted) instead of (interrupted-playername)
I have also attempted to disable all other addons but neatplates to see if other addons were interfering, but that was not the case. I installed plater and ran it side by side with tidy plates, and plater can show the interrupt author but neatplates currently can not
**To Reproduce**
1.Go to Neatplates in interface
2.Select profile 
3.scroll down to cast bars setting,
4.check Show interrupted cast bar and show who interrupted cast
5. go out and interrupt something

**Expected behavior**
when having option to show who interrupted in cast bar selected, it should show (interrupted-playername) not jsut (interrupted)

**Screenshots**
![WoWScrnShot_102622_155932](https://user-images.githubusercontent.com/38851009/198127056-8c9da272-1814-40fd-8dfd-8aeff63ea673.jpg)

**Comment by melshior** [comment]
same issue in wotlk classic

**Comment by Luxocracy** [comment]
I am not able to reproduce this issue.

With these settings enabled, when I interrupt an enemy it displays that I was the one that interruped. In both wotlk and retail.

I am a bit suspicious however, as #365 was also an issue about a setting that I was unable to reproduce. So it might be that there is something going on that I am unable to replicate. 

So I'm just going to quote what I mentioned in that issue.

> Something else you could try is creating a new profile, at first by copying from the default profile. And if that doesn't work either, you could try creating an entirely new profile. Just that we can rule out the issue being with that specific profile.

**Comment by Spkilla** [comment]
reset everything to default, created a new profile and set that as default with "Show Enemy Castbar" "Show Interrupted Castbar" and "Show who INterrupted Cast". still just just "interrupted". weird. deleted addon and all neatplates saved variables i can find, and did this again, and still could not get it to work

**Comment by Luxocracy** [comment]
I managed to figure what was going on. 

It wouldn't display because it was unable to fetch a class color, because for some reason the class color lookup was done differently there than everywhere else. But it was able to do so for me because of old variables that were still around.
Must have just been something I never picked up on while on the Dragonflight PTR.

Anyways this should be working in the latest update now.
