### ISSUE TITLE
Rogue Skill Echoing Reprimand Causing Persistent LUA Error

### ISSUE THREAD

**Issue by nearlysober80** [Luxocracy/NeatPlates#364]
**What version of the game you are experiencing the issue with:**
Retail 10.0 - latest version of NeatPlates

**Describe the bug**
When casting Echoing Reprimand during combat, LUA error pops up and keeps increasing in count multiple times per second, you cannot dismiss the error in combat as it comes right back up.  It likely has something to do with the graphical difference of combo point targeted by Echoing Reprimand.

**To Reproduce**
1. On a Rogue character with Echoing Reprimand in talent tree
2. Enter combat with any creature, cast Echoing Reprimand
3. Non-Stop LUA error (see below)

**Additional context**
Message: ...nterface/AddOns/NeatPlatesWidgets/ResourceWidget.lua:170: attempt to call field 'contains' (a nil value)
Time: Thu Oct 27 21:12:14 2022
Count: 2510
Stack: ...nterface/AddOns/NeatPlatesWidgets/ResourceWidget.lua:170: attempt to call field 'contains' (a nil value)
[string "=[C]"]: in function `contains'
[string "@Interface/AddOns/NeatPlatesWidgets/ResourceWidget.lua"]:170: in function <...nterface/AddOns/NeatPlatesWidgets/ResourceWidget.lua:152>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/NeatPlatesWidgets/ResourceWidget.lua"]:391: in function `UpdatePoints'
[string "@Interface/AddOns/NeatPlatesWidgets/ResourceWidget.lua"]:442: in function <...nterface/AddOns/NeatPlatesWidgets/ResourceWidget.lua:441>
[string "@Interface/AddOns/NeatPlatesWidgets/ResourceWidget.lua"]:497: in function <...nterface/AddOns/NeatPlatesWidgets/ResourceWidget.lua:492>

Locals:

**Comment by Luxocracy** [comment]
Seems this is actually due to a mistake I made while refactoring/cleaning up some stuff. I'll have a fix out in a little bit.
