### ISSUE TITLE
New bug since release v422 (occured just after updating it), playing warrior

### ISSUE THREAD

**Issue by sthdevilish** [Luxocracy/NeatPlates#368]
27x ...nterface/AddOns/NeatPlatesWidgets/ResourceWidget.lua:310: attempt to index local 'data' (a nil value)
[string "@Interface/AddOns/NeatPlatesWidgets/ResourceWidget.lua"]:310: in function <...nterface/AddOns/NeatPlatesWidgets/ResourceWidget.lua:306>
[string "@Interface/AddOns/NeatPlatesWidgets/ResourceWidget.lua"]:412: in function `UpdatePoints'
[string "@Interface/AddOns/NeatPlatesWidgets/ResourceWidget.lua"]:557: in function `createFunction'
[string "@Interface/AddOns/NeatPlatesHub/functions/Widgets.lua"]:626: in function <Interface/AddOns/NeatPlatesHub/functions/Widgets.lua:613>
[string "@Interface/AddOns/NeatPlatesHub/functions/Widgets.lua"]:664: in function `OnInitializeWidgets'
[string "@Interface/AddOns/NeatPlatesHub/functions/Core.lua"]:531: in function `OnInitialize'
[string "@Interface/AddOns/NeatPlates/NeatPlatesCore.lua"]:762: in function <Interface/AddOns/NeatPlates/NeatPlatesCore.lua:718>
[string "@Interface/AddOns/NeatPlates/NeatPlatesCore.lua"]:1623: in function `?'
[string "@Interface/AddOns/NeatPlates/NeatPlatesCore.lua"]:1578: in function <Interface/AddOns/NeatPlates/NeatPlatesCore.lua:1576>

Locals:
data = nil
(*temporary) = "WARRIOR"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'data' (a nil value)"
PlayerClass = "WARRIOR"
PlayerSpec = 72
t = <table> {
 DEATHKNIGHT = <table> {
 }
 PALADIN = <table> {
 }
 WARLOCK = <table> {
 }
 ROGUE = <table> {
 }
 MAGE = <table> {
 }
 DRUID = <table> {
 }
 RESOURCE_PATH = "Addons\NeatPlatesWidgets\ResourceWidget\"
 MONK = <table> {
 }
}

**Comment by zaphon** [comment]
Came here to report same error.

**Comment by Luxocracy** [comment]
Well that's a silly mistake to make...

Real sorry about that, I've released a new update that fixes this.

**Comment by sthdevilish** [comment]
No worries, thank you.
