### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by jsaue003** [Luxocracy/NeatPlates#369]
**What version of the game you are experiencing the issue with:**
Retail Live

**Describe the bug**
LUA error on login

**To Reproduce**
Message: ...nterface/AddOns/NeatPlatesWidgets/ResourceWidget.lua:310: attempt to index local 'data' (a nil value)
Time: Sat Oct 29 17:38:44 2022
Count: 3
Stack: ...nterface/AddOns/NeatPlatesWidgets/ResourceWidget.lua:310: attempt to index local 'data' (a nil value)
[string "@Interface/AddOns/NeatPlatesWidgets/ResourceWidget.lua"]:310: in function <...nterface/AddOns/NeatPlatesWidgets/ResourceWidget.lua:306>
[string "@Interface/AddOns/NeatPlatesWidgets/ResourceWidget.lua"]:412: in function `UpdatePoints'
[string "@Interface/AddOns/NeatPlatesWidgets/ResourceWidget.lua"]:557: in function `createFunction'
[string "@Interface/AddOns/NeatPlatesHub/functions/Widgets.lua"]:626: in function <Interface/AddOns/NeatPlatesHub/functions/Widgets.lua:613>
[string "@Interface/AddOns/NeatPlatesHub/functions/Widgets.lua"]:664: in function `OnInitializeWidgets'
[string "@Interface/AddOns/NeatPlatesHub/functions/Core.lua"]:531: in function `OnInitialize'
[string "@Interface/AddOns/NeatPlates/NeatPlatesCore.lua"]:762: in function <Interface/AddOns/NeatPlates/NeatPlatesCore.lua:718>
[string "@Interface/AddOns/NeatPlates/NeatPlatesCore.lua"]:1623: in function `?'
[string "@Interface/AddOns/NeatPlates/NeatPlatesCore.lua"]:1578: in function <Interface/AddOns/NeatPlates/NeatPlatesCore.lua:1576>

Locals: data = nil
(*temporary) = "HUNTER"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'data' (a nil value)"
PlayerClass = "HUNTER"
PlayerSpec = 254
t = <table> {
 DEATHKNIGHT = <table> {
 }
 PALADIN = <table> {
 }
 WARLOCK = <table> {
 }
 ROGUE = <table> {
 }
 MAGE = <table> {
 }
 DRUID = <table> {
 }
 RESOURCE_PATH = "Interface\Addons\NeatPlatesWidgets\ResourceWidget\"
 MONK = <table> {
 }
}

**Comment by Luxocracy** [comment]
Closing this as it's the same as #368
This should be fixed as of the latest release
