### ISSUE TITLE
Unable to delete profiles

### ISSUE THREAD

**Issue by chrismeyers** [Luxocracy/NeatPlates#370]
**What version of the game you are experiencing the issue with:**
Live/Retail 10.0.0 (Addon v423)

**Describe the bug**
An error occurs when attempting to delete a profile

**To Reproduce**
1. Go to the NeatPlates options panel
2. Create a new profile
3. Attempt to delete the profile

**Expected behavior**
The profile should be deleted without error

**Screenshots**
N/A

**Additional context**
The following error occurs:
```
Message: Interface/AddOns/NeatPlates/NeatPlatesPanel.lua:153: bad argument #1 to 'foreach' (table expected, got nil)
Time: Sun Oct 30 10:30:54 2022
Count: 5
Stack: Interface/AddOns/NeatPlates/NeatPlatesPanel.lua:153: bad argument #1 to 'foreach' (table expected, got nil)
[string "=[C]"]: in function `foreach'
[string "@Interface/AddOns/NeatPlates/NeatPlatesPanel.lua"]:153: in function <Interface/AddOns/NeatPlates/NeatPlatesPanel.lua:147>
[string "@Interface/AddOns/NeatPlates/NeatPlatesPanel.lua"]:1135: in function `OnAccept'
[string "@Interface/FrameXML/StaticPopup.lua"]:5269: in function `StaticPopup_OnClick'
[string "*StaticPopup.xml:24_OnClick"]:1: in function <[string "*StaticPopup.xml:24_OnClick"]:1>

Locals: (*temporary) = nil
(*temporary) = <function> defined @Interface/AddOns/NeatPlates/NeatPlatesPanel.lua:153
(*temporary) = "table expected, got nil"
```

**Comment by Luxocracy** [comment]
This should be working now as of v424.

There's still a bug with it not refreshing the list of profiles on the lefthand side. But I've yet to figure out a way to force a refresh in the new settings panel. So for now, as a work around, you can toggle the '+' button and it should refresh.

**Comment by chrismeyers** [comment]
Awesome, thanks for the fast response!
