### ISSUE TITLE
NeatPlatesWidget error after latest update

### ISSUE THREAD

**Issue by Bradington** [Luxocracy/NeatPlates#371]
**What version of the game you are experiencing the issue with:**
WOTLK CLASSIC

**Describe the bug**
Large amount of LUA errors.

**Expected behavior**
Chat box Spam

ERROR AS FOLLOWED: 
1033x NeatPlatesWidgets\ResourceWidget.lua:91: attempt to concatenate local 'runeType' (a nil value)
[string "@NeatPlatesWidgets\ResourceWidget.lua"]:91: in function <NeatPlatesWidgets\ResourceWidget.lua:60>
[string "=(tail call)"]: ?
[string "@NeatPlatesWidgets\ResourceWidget.lua"]:414: in function `UpdatePoints'
[string "@NeatPlatesWidgets\ResourceWidget.lua"]:369: in function `Expire'
[string "@NeatPlatesWidgets\WidgetCore.lua"]:61: in function <NeatPlatesWidgets\WidgetCore.lua:52>

Locals:
self = <table> {
 GetPower = <function> defined @NeatPlatesWidgets\ResourceWidget.lua:60
 POWER = 5
 POINT = "DK-Rune-Classic"
}
points = <table> {
}
runeMap = <table> {
 RUNETYPE_CHROMATIC = "Unholy"
 3 = "Unholy"
 RUNETYPE_BLOOD = "Blood"
 RUNETYPE_FROST = "Frost"
 2 = "Frost"
 RUNETYPE_DEATH = "Death"
 1 = "Blood"
}
runeOrder = <table> {
 1 = 1
 2 = 2
 3 = 5
 4 = 6
 5 = 3
 6 = 4
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = 1
 2 = 2
 3 = 5
 4 = 6
 5 = 3
 6 = 4
}
(for control) = 1
_ = 1
i = 1
point = <table> {
 EXPIRATION = 0
 ICON = "DK-Rune-Classic"
 DURATION = 0
 STATE = "Off"
}
start = 0
duration = 10
runeReady = true
expiration = 10
runeType = nil
(*temporary) = "DK-Rune-Classic"
(*temporary) = "-"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate local 'runeType' (a nil value)"
getPointIcon = <function> defined @NeatPlatesWidgets\ResourceWidget.lua:46

**Comment by Sibedeux** [comment]
**_**Same thing here, pretty sure it is crashing my game completely.**_**


630x NeatPlatesWidgets\ResourceWidget.lua:91: attempt to concatenate local 'runeType' (a nil value)
[string "@NeatPlatesWidgets\ResourceWidget.lua"]:91: in function <NeatPlatesWidgets\ResourceWidget.lua:60>
[string "=(tail call)"]: ?
[string "@NeatPlatesWidgets\ResourceWidget.lua"]:414: in function `UpdatePoints'
[string "@NeatPlatesWidgets\ResourceWidget.lua"]:465: in function <NeatPlatesWidgets\ResourceWidget.lua:464>
[string "@NeatPlatesWidgets\ResourceWidget.lua"]:520: in function <NeatPlatesWidgets\ResourceWidget.lua:515>

Locals:
self = <table> {
GetPower = <function> defined @NeatPlatesWidgets\ResourceWidget.lua:60
POWER = 5
POINT = "DK-Rune-Classic"
}
points = <table> {
}
runeMap = <table> {
RUNETYPE_CHROMATIC = "Unholy"
3 = "Unholy"
RUNETYPE_BLOOD = "Blood"
RUNETYPE_FROST = "Frost"
2 = "Frost"
RUNETYPE_DEATH = "Death"
1 = "Blood"
}
runeOrder = <table> {
1 = 1
2 = 2
3 = 5
4 = 6
5 = 3
6 = 4
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
1 = 1
2 = 2
3 = 5
4 = 6
5 = 3
6 = 4
}
(for control) = 1
_ = 1
i = 1
point = <table> {
EXPIRATION = 0
ICON = "DK-Rune-Classic"
DURATION = 0
STATE = "Off"
}
start = 1917.650000
duration = 10
runeReady = false
expiration = 1927.650000
runeType = nil
(*temporary) = "DK-Rune-Classic"
(*temporary) = "-"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate local 'runeType' (a nil value)"
getPointIcon = <function> defined @NeatPlatesWidgets\ResourceWidget.lua:46

**Comment by Luxocracy** [comment]
Sorry that this has taken a while to get to, but seems like I forgot to add the integer for the "Death" rune to the rune mappings. As that is the only rune I was unable to test properly in the new resource widget.

This should be fixed in the latest release.
