### ISSUE TITLE
Pets opacity

### ISSUE THREAD

**Issue by ssbb112V** [Luxocracy/NeatPlates#372]
Hello
Can I make all enemy/friendly pets opacity 80%?
3.4.0 wotlk, blizzard preset
Now all pets have opacity 100% (Although for all non-target should be 85% with my settings). Unit filter (image №3 is not worked
![image](https://user-images.githubusercontent.com/106621275/199476166-019187d4-378f-4713-8457-bcd0252978ab.png)
![image](https://user-images.githubusercontent.com/106621275/199476500-bb08aabb-814a-4f13-904f-bda75dfdd9fc.png)
![image](https://user-images.githubusercontent.com/106621275/199476570-95fce464-edc9-4275-b48f-4d9b7153c43e.png)

**Comment by Luxocracy** [comment]
For some reason the way Neatplates checked if a unit is a pet no longer works for Warlock pets as they are considered a "Create" instead of "Pet" in their GUIDs. So I've added a backup check for warlock pets that seems to fix the issue.
