### ISSUE TITLE
WotLK combo points visual

### ISSUE THREAD

**Issue by ssbb112V** [Luxocracy/NeatPlates#374]
**What version of the game you are experiencing the issue with:**
WotLK Classic

**Describe the bug**
After the 9/4/2022 update, the standard combo points have been changed.
Now they are showed even when 0 cp. And they have changed a lot in appearance.

**Expected behavior**
I want new versions to bring back the old combo point look

**Screenshots**
1st screen its latest version, 2nd its v417 from 9/4/2022 update
![image](https://user-images.githubusercontent.com/106621275/200118359-e490df76-8e43-43bc-8a2e-2f1aef0ff487.png)
![image](https://user-images.githubusercontent.com/106621275/200118365-d9199efa-c1a3-4dca-9010-f62379dda41c.png)

**Comment by Luxocracy** [comment]
Sorry for taking a while to respond, but the old styling will get added to the new resource widget in the future. Hopefully in a very short amount of time.

And you can check the **Hide when empty** option to hide the combo points when they are at 0.

**Comment by ssbb112V** [comment]
![image](https://user-images.githubusercontent.com/106621275/213291418-c4dfd622-ae06-424d-bcef-935dd95bc65e.png)
Greetings
in patch 3.4.1 I had to update to the latest addon version (where the old style was removed). Accidentally found that when you put the "Show on" option to "none", the old and favorite style I wanted appears! 
Happy update to the ulduar patch, thanks for the support
