### ISSUE TITLE
DK-NeatPlatesWidgets error

### ISSUE THREAD

**Issue by s890214** [Luxocracy/NeatPlates#375]
**1:**
NeatPlatesWidgets\ResourceWidget.lua:91: attempt to concatenate local 'runeType' (a nil value)
[string "@NeatPlatesWidgets\ResourceWidget.lua"]:91: in function <NeatPlatesWidgets\ResourceWidget.lua:60>
[string "=(tail call)"]: ?
[string "@NeatPlatesWidgets\ResourceWidget.lua"]:414: in function `UpdatePoints'
[string "@NeatPlatesWidgets\ResourceWidget.lua"]:465: in function <NeatPlatesWidgets\ResourceWidget.lua:464>
[string "@NeatPlatesWidgets\ResourceWidget.lua"]:520: in function <NeatPlatesWidgets\ResourceWidget.lua:515>

Locals:
self = <table> {
GetPower = <function> defined @NeatPlatesWidgets\ResourceWidget.lua:60
POWER = 5
POINT = "DK-Rune-Classic"
}
points = <table> {
}
runeMap = <table> {
RUNETYPE_CHROMATIC = "Unholy"
3 = "Unholy"
RUNETYPE_BLOOD = "Blood"
RUNETYPE_FROST = "Frost"
2 = "Frost"
RUNETYPE_DEATH = "Death"
1 = "Blood"
}
runeOrder = <table> {
1 = 1
2 = 2
3 = 5
4 = 6
5 = 3
6 = 4
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
1 = 1
2 = 2
3 = 5
4 = 6
5 = 3
6 = 4
}
(for control) = 1
_ = 1
i = 1
point = <table> {
EXPIRATION = 0
ICON = "DK-Rune-Classic"
DURATION = 0
STATE = "Off"
}
start = 41093.378000
duration = 10
runeReady = false
expiration = 41103.378000
runeType = nil
(*temporary) = "DK-Rune-Classic"
(*temporary) = "-"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate local 'runeType' (a nil value)"
getPointIcon = <function> defined @NeatPlatesWidgets\ResourceWidget.lua:46

**2:**
NeatPlatesWidgets\ResourceWidget.lua:87: attempt to perform arithmetic on local 'start' (a nil value)
[string "@NeatPlatesWidgets\ResourceWidget.lua"]:87: in function <NeatPlatesWidgets\ResourceWidget.lua:60>
[string "=(tail call)"]: ?
[string "@NeatPlatesWidgets\ResourceWidget.lua"]:414: in function `UpdatePoints'
[string "@NeatPlatesWidgets\ResourceWidget.lua"]:369: in function `Expire'
[string "@NeatPlatesWidgets\WidgetCore.lua"]:61: in function <NeatPlatesWidgets\WidgetCore.lua:52>

Locals:
self = <table> {
GetPower = <function> defined @NeatPlatesWidgets\ResourceWidget.lua:60
POWER = 5
POINT = "DK-Rune-Classic"
}
points = <table> {
}
runeMap = <table> {
RUNETYPE_CHROMATIC = "Unholy"
3 = "Unholy"
RUNETYPE_BLOOD = "Blood"
RUNETYPE_FROST = "Frost"
2 = "Frost"
RUNETYPE_DEATH = "Death"
1 = "Blood"
}
runeOrder = <table> {
1 = 1
2 = 2
3 = 5
4 = 6
5 = 3
6 = 4
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
1 = 1
2 = 2
3 = 5
4 = 6
5 = 3
6 = 4
}
(for control) = 1
_ = 1
i = 1
point = <table> {
EXPIRATION = 0
ICON = "DK-Rune-Classic"
DURATION = 0
STATE = "Off"
}
start = nil
duration = nil
runeReady = nil
(*temporary) = "string"
(*temporary) = "DK-Rune-Classic"
(*temporary) = "string"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'start' (a nil value)"
getPointIcon = <function> defined @NeatPlatesWidgets\ResourceWidget.lua:46

**Comment by Luxocracy** [comment]
Hi, this should be fixed in the latest release. Please refer to #371 for more details.
