### ISSUE TITLE
Today (11/08/2022) - Local (error) - 2313

### ISSUE THREAD

**Issue by Kyreaper** [Luxocracy/NeatPlates#377]
Date: 11/08/2022
Bug is occurring on retail. I am only playing retail atm.

**Describe the bug**
I keep getting the same error whenever I am in combat. It seems to be related to enemy unit frames (or possibly friendly unit frames) and some sort of coloring on them that NeatPlates is trying to add or modify. 

**_I only get this error in combat & I cannot seem to replicate it outside of combat._** 

During combat, I am repeatedly flooded with the same error though.

**To Reproduce**

1. Start attacking a mob or hostile player.

2. Click on said mob or player, or hover over their nameplates / unit frames whilst still in combat with them.

3. See the errors flood your chat. 

13x bad argument #2 to '?' (Usage: self:SetTextColor(color [, a]))
[string "=[C]"]: in function `SetTextColor'
[string "@Interface/AddOns/NeatPlates/NeatPlatesCore.lua"]:1313: in function <Interface/AddOns/NeatPlates/NeatPlatesCore.lua:1298>
[string "@Interface/AddOns/NeatPlates/NeatPlatesCore.lua"]:694: in function <Interface/AddOns/NeatPlates/NeatPlatesCore.lua:665>
[string "@Interface/AddOns/NeatPlates/NeatPlatesCore.lua"]:810: in function <Interface/AddOns/NeatPlates/NeatPlatesCore.lua:800>
[string "@Interface/AddOns/NeatPlates/NeatPlatesCore.lua"]:380: in function <Interface/AddOns/NeatPlates/NeatPlatesCore.lua:353>

Locals:
(*temporary) = "bad argument #2 to '?' (Usage: self:SetTextColor(color [, a]))"

![Screenshot 2022-11-08 160211](https://user-images.githubusercontent.com/12869693/200675776-9f94310a-211e-4b3e-8d78-c26a3de46d5b.png)

![Screenshot 2022-11-08 160247](https://user-images.githubusercontent.com/12869693/200675810-952974be-07a1-495d-8c72-c53f76fbfd08.png)

**Comment by Luxocracy** [comment]
Hi, could you check what your _Enemy Status Text_ is set to. Because this seems to be an issue when it's trying to set the text that is displayed on the health bar itself. It could be somehow set incorrectly, because I am unable to replicate the issue regardless of what option I use.
<img width="121" alt="image" src="https://user-images.githubusercontent.com/2884542/201471109-96a8a64e-9e9b-46c0-950e-dc96ef8dc98c.png">

**Comment by Kyreaper** [comment]
Hello,

Posting to update: I have played quite a lot over the past few days & it seems that, as of patch 10.0.2.46702, I am no longer getting this error & I can also no longer replicate it. 

I think NeatPlates has had an update once or twice since I last had a chance to play. I'm not sure if it was the WoW patch / hotfixes, or an update to NeatPlates itself, but as of right now this issue seems to be resolved. If anything else comes up in future, then I'll open a new issue, but this can probably be marked as resolved now as I can no longer replicate the error.


Thank you very much for all your work on this amazing addon!

**Comment by xinux-lv** [comment]
This is really easy to replicate using the latest release. Just set it to use the default tank profile and target any NPC currently in combat with another player. I ended up changing line 1313 to visual.customtext:SetTextColor(unit.levelcolorRed, unit.levelcolorGreen, unit.levelcolorBlue, a or 1) and the error stopped plus the current target name being yellow on the nameplate didn't look to bad.

![image](https://user-images.githubusercontent.com/8060258/209004363-a3a4d7a9-8d9a-408d-85a5-4b58cc05fa09.png)
