### ISSUE TITLE
Lua Error: Unsupported widget type

### ISSUE THREAD

**Issue by Nukme** [Luxocracy/NeatPlates#379]
**What version of the game you are experiencing the issue with:**
Live/Retail

**Describe the bug**
I was doing the judgement event in Ember Court. Not sure what I was pointing to but I heard the alert from bugsack. 

```
3x Interface/AddOns/NeatPlates/NeatPlatesCore.lua:1170: NeatPlates: Unsupported widget type (13) please report this and what you were doing to the addon author.
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/NeatPlates/NeatPlatesCore.lua"]:1170: in function <Interface/AddOns/NeatPlates/NeatPlatesCore.lua:1145>
[string "@Interface/AddOns/NeatPlates/NeatPlatesCore.lua"]:684: in function <Interface/AddOns/NeatPlates/NeatPlatesCore.lua:665>
[string "@Interface/AddOns/NeatPlates/NeatPlatesCore.lua"]:810: in function <Interface/AddOns/NeatPlates/NeatPlatesCore.lua:800>
[string "@Interface/AddOns/NeatPlates/NeatPlatesCore.lua"]:380: in function <Interface/AddOns/NeatPlates/NeatPlatesCore.lua:353>

Locals:
(*temporary) = "NeatPlates: Unsupported widget type (13) please report this and what you were doing to the addon author."
```

**Comment by Luxocracy** [comment]
Thank your for reporting this. I'll see what I can find out about this unsupported widget. And if it's something that should be supported or not.

In the mean time, you can check the _Use Blizzard Bar Widgets_ in the general Neatplates settings and that should stop the error. As well as display the intended blizzard widget.

**Comment by Nukme** [comment]
I'll pay close attention next time in ember court. I like NP's widget style and unchecked Blizzard's ugly bar widget on every character of mine, no worries, XD.

**Comment by Nukme** [comment]
The cause of the unsupported widget type is the Guest Happiness Widget in Ember Court. It's a icon underneath the original nameplate.

![Ember Court Guest Widget](https://user-images.githubusercontent.com/5374088/202907684-ac2d4353-0677-4970-ae5d-5edea05ac338.png)
