### ISSUE TITLE
Separate theme customization for friendly/enemy

### ISSUE THREAD

**Issue by eycaluton** [Luxocracy/NeatPlates#382]
Hello! Would it be possible (or is it possible?) to alter the nameplates of friendly targets and enemy targets separately?

More specifically, I would like to turn off certain aspects for friendly nameplates (as done in "Theme Customization"), but keep them active for enemy ones. Currently there are some work-arounds, such as placing friendly targets under "unit filter" which allows me to scale it separately from enemy nameplates. But it's quite restrictive, and also keeps me from using the unit filter for its intended use.

I completely understand if this request is too big in scope and would require too much work, but I figured I would ask.

Thank you for this wonderful addon <3

**Comment by Luxocracy** [comment]
This is something that has been requested before, and while I would like to allow for this at some point it is a rather big change that requires some core things to be changed. So while it might happen, I wouldn't expect it anytime soon sadly.

As for the unit filters, that is also something I've been wanting to rework to allow it to have some more flexibility. But I can't really give a timeframe for this either.
