### ISSUE TITLE
X/Y slide bars in Aura widget in Theme Customization doesnt work

### ISSUE THREAD

**Issue by martinboy1974** [Luxocracy/NeatPlates#383]
**What version of the game you are experiencing the issue with:**
Live Retail 10.0.2

X/Y bars in Aura widget in Theme Customization doesnt work

I expect to be able to move the placement of auras on nameplates up/down and left/rigt, but nothing happens when using the sliders for X/Y

**Comment by Luxocracy** [comment]
In the **Buffs & Debuffs** section there's a button that allows you to change the _Aura_ and _Emphasized Aura_ offsets. This is sadly one of the things I haven't been able to move over to the theme customization yet. But at least you can move it around from there.
