### ISSUE TITLE
Custom Font on Style

### ISSUE THREAD

**Issue by Diablolock** [Luxocracy/NeatPlates#385]
I know it's a features that many ppl ask and we probabily not getting it anytime soon, so I'd like to know if there's a work around.

I tried what this guy said: https://github.com/Luxocracy/NeatPlates/issues/272

But I only manage to change dee font of the NAME on nameplates.

Is there a way to manually change the font of the timers/stacks of DOTs?

**Comment by Luxocracy** [comment]
For changing the timer durations, you could look into using OmniCC to replace the timer texts as this is something that is supported.

You can set up a rule like this in OmniCC to change the font etc. specifically for Neatplates timers.
![image](https://user-images.githubusercontent.com/2884542/208287674-bd5bd907-c98e-4116-ab39-a0016822e856.png)

You also have to check the **Hide Aura Duration** option under the Buffs & Debuffs section in Neatplates to allow OmniCC to take control.

**Comment by Diablolock** [comment]
Thx for the reply! 

I could change the timer of debuffs on nameplates but what I couldn't change is the font of STACKS of the debuffs aka Agony DOT from Warlock.

I even tried checking the "Hide Aura Stacks" under Buffs & Debuffs section in Neatplates but it makes the stack text gone for good.

OmniCC seems to only take control of timers not stacks.

Any idea?
