### ISSUE TITLE
Classic/Retail Compatibility issue with _G["Settings"]

### ISSUE THREAD

**Issue by orionshock** [Luxocracy/NeatPlates#387]
**What version of the game you are experiencing the issue with:**
Wrath Classic 
NeatPlates-v427 -- Latest from Curseforge.

**Describe the bug**
This seems to be part of a Classic/Retail compatibility check.
NeatPlatesHub checking for the Blizzard Table _G["Settings"] and it's crashing / conflicting with ProfessionMaster addon. 
This happens if Profession Master loads first then NeatPlates has a bit of a conniption fit.

**To Reproduce**
1. Profession Master Loads first
2. NeatPlates loads afterwards
3. Lots of Errors starting with

```
1x Interface\AddOns\NeatPlatesHub\Templates.lua:1350: attempt to call field 'GetCategory' (a nil value)
[string "@Interface\AddOns\NeatPlatesHub\Templates.lua"]:1350: in function <Interface\AddOns\NeatPlatesHub\Templates.lua:1033>
[string "@Interface\AddOns\NeatPlatesHub\Hub.lua"]:797: in function <Interface\AddOns\NeatPlatesHub\Hub.lua:781>
[string "@Interface\AddOns\NeatPlatesHub\Hub.lua"]:817: in function <Interface\AddOns\NeatPlatesHub\Hub.lua:815>
[string "@Interface\AddOns\NeatPlatesHub\Hub.lua"]:979: in function <Interface\AddOns\NeatPlatesHub\Hub.lua:963>
```

I have also raised this issue with ProfessionMaster Addon
https://discord.com/channels/831203449675841567/938845705349529640/1053850331584397343

**Comment by Luxocracy** [comment]
Ah, I'm assuming their solution to the compatability was to create the "Settings" global that doesn't normally exist outside of dragonflighr. I would generally consider this bad practice, but to be fair I should probably also do a version check and not entirely rely on if this global exists.

I'll hopefully have some time today to check on this issue.

**Comment by orionshock** [comment]
Looking into this further, ProfessionMaster is straight up using "Setttings" as a saved variable . . .
