### ISSUE TITLE
Warlock ComboPoint Widget Error

### ISSUE THREAD

**Issue by Arkilyte** [Luxocracy/NeatPlates#390]
**What version of the game you are experiencing the issue with:**
Retail v428

**Describe the bug**
Soul shards will sometimes stop displaying on nameplate and throw lua error. This can also cause the targeting highlight and mouseover text to not function.

**To Reproduce**
1. Play warlock
2. Get in combat and spend souldshards
3. Switch through different mobs
4. Combat point style resource will show up at first then disappear and give error

**Expected behavior**
Should just show soul shards on targeted nameplate

**Additional context**
Message: ...erface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua:213: attempt to index field 'Anim' (a nil value)
Time: Mon Jan 16 15:37:59 2023
Count: 28609
Stack: ...erface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua:213: attempt to index field 'Anim' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua"]:213: in function <...erface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua:182>
[string "@Interface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua"]:333: in function <...erface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua:329>

Locals: 

Message: ...erface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua:213: attempt to index field 'Anim' (a nil value)
Time: Mon Jan 16 15:37:59 2023
Count: 37885
Stack: ...erface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua:213: attempt to index field 'Anim' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua"]:213: in function <...erface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua:182>
[string "@Interface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua"]:301: in function `UpdateContext'
[string "@Interface/AddOns/NeatPlatesHub/functions/Widgets.lua"]:688: in function `OnContextUpdate'
[string "@Interface/AddOns/NeatPlates/NeatPlatesCore.lua"]:962: in function <Interface/AddOns/NeatPlates/NeatPlatesCore.lua:947>
[string "@Interface/AddOns/NeatPlates/NeatPlatesCore.lua"]:809: in function <Interface/AddOns/NeatPlates/NeatPlatesCore.lua:800>
[string "@Interface/AddOns/NeatPlates/NeatPlatesCore.lua"]:380: in function <Interface/AddOns/NeatPlates/NeatPlatesCore.lua:353>

Locals:

Message: ...erface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua:213: attempt to index field 'Anim' (a nil value)
Time: Mon Jan 16 15:37:00 2023
Count: 56
Stack: ...erface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua:213: attempt to index field 'Anim' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua"]:213: in function <...erface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua:182>
[string "@Interface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua"]:333: in function <...erface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua:329>
[string "=[C]"]: in function `CameraOrSelectOrMoveStop'
[string "CAMERAORSELECTORMOVE"]:4: in function <[string "CAMERAORSELECTORMOVE"]:1>

Locals:  

Message: ...erface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua:213: attempt to index field 'Anim' (a nil value)
Time: Mon Jan 16 15:36:36 2023
Count: 17
Stack: ...erface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua:213: attempt to index field 'Anim' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua"]:213: in function <...erface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua:182>
[string "@Interface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua"]:333: in function <...erface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua:329>
[string "=[C]"]: in function `TargetNearestEnemy'
[string "TARGETNEARESTENEMY"]:2: in function <[string "TARGETNEARESTENEMY"]:1>

Locals:

**Comment by Luxocracy** [comment]
I pushed a minor update to fix this issue with the old combo/resource widget

**Comment by Arkilyte** [comment]
You say "old", is there a new widget?

Also, warlock resources seems resolved but it rogue combo points (specifically when using echoing reprimand) are having issues.

Message: ...erface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua:235: attempt to index field '?' (a nil value)
Time: Sat Jan 21 12:27:30 2023
Count: 363
Stack: ...erface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua:235: attempt to index field '?' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua"]:235: in function <...erface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua:182>
[string "@Interface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua"]:333: in function <...erface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua:329>

Locals: 

Message: ...erface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua:235: attempt to index field '?' (a nil value)
Time: Sat Jan 21 12:27:30 2023
Count: 3426
Stack: ...erface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua:235: attempt to index field '?' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua"]:235: in function <...erface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua:182>
[string "@Interface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua"]:301: in function `UpdateContext'
[string "@Interface/AddOns/NeatPlatesHub/functions/Widgets.lua"]:688: in function `OnContextUpdate'
[string "@Interface/AddOns/NeatPlates/NeatPlatesCore.lua"]:962: in function <Interface/AddOns/NeatPlates/NeatPlatesCore.lua:947>
[string "@Interface/AddOns/NeatPlates/NeatPlatesCore.lua"]:809: in function <Interface/AddOns/NeatPlates/NeatPlatesCore.lua:800>
[string "@Interface/AddOns/NeatPlates/NeatPlatesCore.lua"]:380: in function <Interface/AddOns/NeatPlates/NeatPlatesCore.lua:353>

Locals: 

Message: ...erface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua:235: attempt to index field '?' (a nil value)
Time: Sat Jan 21 12:27:02 2023
Count: 1
Stack: ...erface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua:235: attempt to index field '?' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua"]:235: in function <...erface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua:182>
[string "@Interface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua"]:333: in function <...erface/AddOns/NeatPlatesWidgets/ComboPointWidget.lua:329>
[string "=[C]"]: in function `CameraOrSelectOrMoveStop'
[string "CAMERAORSELECTORMOVE"]:4: in function <[string "CAMERAORSELECTORMOVE"]:1>

Locals:

**Comment by Luxocracy** [comment]
Yes, there is a new widget for displaying personal resource. It's under the **Personal Resource Display (BETA)** section. And especially if you are playing a rogue in Dragonflight I'd recommend using that one instead. As the older one has not been updated for Dragonflight, apart from some bug fixes.

It still lacks some of the styles the old one has, and as such the old one still exists as well for the time being.
