### ISSUE TITLE
Enemy Vehicle Nameplates not showing

### ISSUE THREAD

**Issue by Diablolock** [Luxocracy/NeatPlates#392]
Is there a way to make the Enemy Vehicle Nameplate to show in Epic Battlegrounds like Wintergrasp and Isle of Conquest?

In WG I can see only see the Siege nameplate but not Demolisher nor Catapults.

**Comment by Luxocracy** [comment]
You could try enabling the **Use Blizzard Bar Widgets** in the main settings and see if that helps. In case they've made a bar widget out of it as opposed to a regular nameplate.

If that doesn't work I'm not entirely sure what it could be. You could check if it works with Neatplates disabled at that point to make sure it isn't related to some hidden nameplate CVars.

**Comment by Diablolock** [comment]
I will test it later. ty.
