### ISSUE TITLE
Grow direction for buffs/debuffs

### ISSUE THREAD

**Issue by yah467958** [Luxocracy/NeatPlates#398]
Hi.

Asking because I can't find an option for that anywhere.

It is possible to change buffs/debuffs direction grow? Specifically debuffs/buffs that can be dispelled.
Right now they are expanding only upwards. 

If there is no option for that, it would be possible to add it in the near future?

**Comment by thread53** [comment]
The current sorting mode lets you choose between two options.
1. Default (by priority)
2. By duration (shortest to longest)

Can be found in game Interface > AddOns> NeatPlates > Default profile > Buffs and Debuffs. Additionally, there is an option to "Include Purgeable buffs" that is disabled by default.

HTH
