### ISSUE TITLE
Enemy Nameplates Become Stuck in Place

### ISSUE THREAD

**Issue by Apoxiosis** [Luxocracy/NeatPlates#402]
Experiencing this in wrath classic

This predominantly happens when enemies die but i ha ve had it happen to enemies who were still alive as well. Edit: you can actually see to the left of my screen by my unit frames nameplates of alive enemies stuck on the screen boundary as well

![image](https://github.com/Luxocracy/NeatPlates/assets/43189648/b5e960bc-22bf-45e2-adca-5b1fd52f7e2a)

**Comment by ShinyKangSquirrel** [comment]
This is happening to me too: 
![image](https://github.com/Luxocracy/NeatPlates/assets/146990164/63da3cac-fe7b-42d8-b221-d59baa78a389)
