### ISSUE TITLE
Range Indicator Hiding in Combat

### ISSUE THREAD

**Issue by Diablolock** [Luxocracy/NeatPlates#404]
I'm using the lastest version (4.29).

When you have the Range Indicator on, Regardless the Mode, Style or Shown On, right when you enter combat the Icon/Line will disappear and go back when you leave combat.

**Comment by Diablolock** [comment]
I got intel from WeakAuras discord that Blizzard protected the "IsItemInRange" function. They said the "LibRangeCheck-3.0" should fix this (ElvUI already has it) and also the "IsSpellInRange"is the new way to go for this?

ERROR:

5x [ADDON_ACTION_BLOCKED] AddOn 'NeatPlates' tried to call the protected function 'IsItemInRange()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: ?
[string "@NeatPlates/libs/LibRangeCheck-2.0-10000000000001/LibRangeCheck-2.0.lua"]:465: in function `checker'
[string "@NeatPlates/libs/LibRangeCheck-2.0-10000000000001/LibRangeCheck-2.0.lua"]:590: in function <...tPlates/libs/LibRangeCheck-2.0/LibRangeCheck-2.0.lua:585>
[string "=(tail call)"]: ?
[string "@NeatPlatesWidgets/RangeWidget.lua"]:67: in function <NeatPlatesWidgets/RangeWidget.lua:65>
[string "@NeatPlatesWidgets/RangeWidget.lua"]:167: in function `UpdateContext'
[string "@NeatPlatesHub/functions/Widgets.lua"]:721: in function `OnContextUpdate'
[string "@NeatPlates/NeatPlatesCore.lua"]:962: in function <NeatPlates/NeatPlatesCore.lua:947>
[string "@NeatPlates/NeatPlatesCore.lua"]:809: in function <NeatPlates/NeatPlatesCore.lua:800>
[string "@NeatPlates/NeatPlatesCore.lua"]:380: in function <NeatPlates/NeatPlatesCore.lua:353>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

**Comment by Luxocracy** [comment]
I've updated the range lib to 3.0 version maintained by WeakAuras. So hopefully this issue should be resolved

**Comment by Diablolock** [comment]
You have no idea how much joy it brings me just to see you around updating NeatPlates!

Tyvm n take care :)

**Comment by Diablolock** [comment]
I see you are working on updates for SoD version of the game.

Would you take a look on the range indicador not working properly when outta range? Thx in advance.

**Comment by Diablolock** [comment]
It works perfect now since the fix on v4.33!

Tyvm again, Lux! Take care.
