### ISSUE TITLE
NeatplatesCore.lua 79x bug

### ISSUE THREAD

**Issue by Marangwe** [Luxocracy/NeatPlates#406]
**What version of the game you are experiencing the issue with:**
Classic

**Describe the bug**
The bug isn't interfering with the game. I only noticed it because Bugsack kept going off. 

This is the error that appeared 79x. 
-----------------------------------------------------------
79x NeatPlates/NeatPlatesCore.lua:1804: attempt to index field '?' (a nil value)
[string "@NeatPlates/NeatPlatesCore.lua"]:1804: in function `?'
[string "@NeatPlates/NeatPlatesCore.lua"]:1578: in function <NeatPlates/NeatPlatesCore.lua:1576>

Locals:
self = "COMBAT_LOG_EVENT_UNFILTERED"
_ = 1701396795.565000
event = "SPELL_CAST_START"
_ = false
sourceGUID = "Player-5820-01D980BC"
sourceName = "Grimbrax"
sourceFlags = 1304
_ = 0
destGUID = ""
destName = nil
_ = -2147483648
_ = -2147483648
spellID = 410002
spellName = "Engrave Gloves - Crusader Strike"
spellSchool = 1
plate = NamePlate8 {
 0 = <userdata>
 driverFrame = NamePlateDriverFrame {
 }
 extended = Frame {
 }
 GetAdditionalInsetPadding = <function> defined @Interface_VanillaBlizzard_NamePlates/Blizzard_NamePlates.lua:367
 ApplyOffsets = <function> defined @Interface_VanillaBlizzard_NamePlates/Blizzard_NamePlates.lua:348
 UpdateMe = false
 showBlizzardPlate = false
 namePlateUnitToken = "nameplate2"
 template = "NamePlateUnitFrameTemplate"
 UnitFrame = Button {
 }
 UpdateHealth = false
 UpdateCastbar = false
 OnSizeChanged = <function> defined @Interface_VanillaBlizzard_NamePlates/Blizzard_NamePlates.lua:352
 GetPreferredInsets = <function> defined @Interface_VanillaBlizzard_NamePlates/Blizzard_NamePlates.lua:378
 OnRemoved = <function> defined @Interface_VanillaBlizzard_NamePlates/Blizzard_NamePlates.lua:335
 OnAdded = <function> defined @Interface_VanillaBlizzard_NamePlates/Blizzard_NamePlates.lua:326
 carrier = NeatPlatesCarrier-1 {
 }
 OnOptionsUpdated = <function> defined @Interface_VanillaBlizzard_NamePlates/Blizzard_NamePlates.lua:342
}
ownerGUID = nil
unitType = "Player"
_ = "5820"
_ = "01D980BC"
_ = nil
_ = nil
creatureID = nil
fixate = <table> {
 268074 = true
 282209 = true
}
currentTime = 445910746
spellEntry = <table> {
}
(*temporary) = nil
(*temporary) = 1
(*temporary) = <function> defined =[C]:-1
(*temporary) = Frame {
 0 = <userdata>
 Neutral = Texture {
 }
 Right = 1
 Left = 0
 SetTexCoord = <function> defined @NeatPlates/NeatPlatesStatusbar.lua:145
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 SetOrientation = <function> defined @NeatPlates/NeatPlatesStatusbar.lua:86
 SetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:422
 SetMinMaxValues = <function> defined @NeatPlates/NeatPlatesStatusbar.lua:112
 Bottom = 1
 MaxVal = 445604204.000000
 ApplyBackdrop = <function> defined @SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 Top = 0
 MinVal = 445601562.000000
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
 Orientation = "HORIZONTAL"
 NeutralMax = 0
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 NeutralMin = 0
 SetAllColors = <function> defined @NeatPlates/NeatPlatesStatusbar.lua:77
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 Value = 445603274.000000
 durationtext = FontString {
 }
 SetStatusBarTexture = <function> defined @NeatPlates/NeatPlatesStatusbar.lua:56
 GetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:409
 SetBackdropTexture = <function> defined @NeatPlates/NeatPlatesStatusbar.lua:154
 GetEdgeSize = <function> defined @SharedXML/Backdrop.lua:188
 GetMinMaxValues = <function> defined @NeatPlates/NeatPlatesStatusbar.lua:107
 SetStatusBarGradient = <function> defined @NeatPlates/NeatPlatesStatusbar.lua:65
 SetBackdropTexCoord = <function> defined @NeatPlates/NeatPlatesStatusbar.lua:150
 SetStatusBarColor = <function> defined @NeatPlates/NeatPlatesStatusbar.lua:60
 Backdrop = Texture {
 }
 SetNeutralZone = <function> defined @NeatPlates/NeatPlatesStatusbar.lua:129
 SetValue = <function> defined @NeatPlates/NeatPlatesStatusbar.lua:51
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 Dim = 102.000008
 HasBa

**Comment by Luxocracy** [comment]
I've pushed an update, which currently under review on Curseforge, that hopefully fixes this issue once it gets approved.
