### ISSUE TITLE
Can't remove enemy's CD/buff?

### ISSUE THREAD

**Issue by guccigang0** [Luxocracy/NeatPlates#409]
**What version of the game you are experiencing the issue with:**
Retail.

**Describe the bug**
I can't remove spell/cd icon on enemy whenever they have used it. It blocks my debuff on the enemy that I am keeping track of. See image. https://i.imgur.com/Gfvubp8.png

**To Reproduce**
Whenever enemy is using spells.

**Expected behavior**
I tried to find a toggle in the settings to disable it, but i cant find it.

**Screenshots**
https://i.imgur.com/Gfvubp8.png

**Comment by Luxocracy** [comment]
On first impression it doesn't seem like this is from Neatplates, but rather something else. As Neatplates does not track ability cooldowns, but maybe I am misunderstanding what the icon represents here.

It's probably a weakaura or something else that is anchoring to the nameplates incorrectly when combined with Neatplates.
But just to make sure, as it could potentially be an Emphasized aura, can you disable the **Aura Widget** all together and see if the icon still shows up?
<img width="109" alt="image" src="https://github.com/Luxocracy/NeatPlates/assets/2884542/d3e801bb-0e67-4678-a465-3c39750bb1bf">

**Comment by guccigang0** [comment]
Sorry! It was DBM that caused this. Everything is working great now!
