### ISSUE TITLE
Nameplate Max Distance slider range (for CVar nameplateMaxDistance)

### ISSUE THREAD

**Issue by dolandemort** [Luxocracy/NeatPlates#410]
**What version of the game you are experiencing the issue with:**
Retail

**Describe the bug**
The `Nameplate Max Distance` slider you provide (the one governing CVar `nameplateMaxDistance`) allows a maximum of 41, but the current allowed maximum by Blizzard is 60 (in Retail; it is lower in Classic, probably 20).

**Comment by Luxocracy** [comment]
You are indeed correct. I've modified this so to properly set the limit depending on which version of the game you are using.
I believe TBC and WotLK are 41, but this could have been changed.

Just for clarity the max values are now as follows (pending the new release)
| Version| Distance| 
|---|---|
| Retail | 60 yds| 
| WotLK | 41 yds | 
| TBC | 41 yds  | 
| Classic  | 20 yds  |

**Comment by dolandemort** [comment]
Very impressive response time. Thanks!
