### ISSUE TITLE
Lua error when clicking on (I think Pally or Shaman) but also trying to change colors

### ISSUE THREAD

**Issue by grospapa** [Luxocracy/NeatPlates#413]
**What version of the game you are experiencing the issue with:**
SoD

**Describe the bug**

**To Reproduce**
in BG, click on a Shaman or Paladin

![image](https://github.com/Luxocracy/NeatPlates/assets/58144668/6c8ca813-38b7-42c4-b151-e556e0728557)

and also trying to change the class color of any class:

![image](https://github.com/Luxocracy/NeatPlates/assets/58144668/cafb6393-c7c7-4f9d-9895-5c1db5c6f9d9)

**Expected behavior**

**Comment by Luxocracy** [comment]
The color picker issue should be resolved now in the latest release. However, I wasn't able to replicate the issue with paladin or shaman nameplates.

Hopefully that issue was also related to the color picker issue. But if it still doesn't work try setting the paladin class color, or resetting all class colors in the main Neatplates settings.

**Comment by grospapa** [comment]
Wow thanks!  I'll turn on error blocking and see if anything else pops

**Comment by grospapa** [comment]
Still get an error in BGs, unfortunately I didnt catch when it happened.
[image: image.png]
dont think I have custom text colors

**Comment by Luxocracy** [comment]
After looking at this again, I think this is actually related to the option "Friendly/Enemy Status Text".

What option do you have selected here?

**Comment by grospapa** [comment]
[image: image.png]

(I had set all class colors to class defaults)

**Comment by grospapa** [comment]
Got this too
[image: image.png]
in AB

**Comment by grospapa** [comment]
Hi,
another recurring issue:

10732x bad argument #2 to '?' (Usage: self:SetTextColor(color [, a]))
[string "=[C]"]: in function `SetTextColor'
[string ***@***.***/NeatPlatesCore.lua"]:1314: in function
<NeatPlates/NeatPlatesCore.lua:1299>
[string ***@***.***/NeatPlatesCore.lua"]:694: in function
<NeatPlates/NeatPlatesCore.lua:665>
[string ***@***.***/NeatPlatesCore.lua"]:810: in function
<NeatPlates/NeatPlatesCore.lua:800>
[string ***@***.***/NeatPlatesCore.lua"]:380: in function
<NeatPlates/NeatPlatesCore.lua:353>

Locals:
(*temporary) = "bad argument #2 to '?' (Usage: self:SetTextColor(color [,
a]))"

**Comment by Luxocracy** [comment]
Sorry for not responding to this for a while.

Could you export your profile from the main settings and post it here so I can maybe figure out what exactly is causing this for you?

Also, just as a note, when you attach images through email they don't show up on github.

**Comment by grospapa** [comment]
ok, thanks, will track down where those settings are:

391x bad argument #2 to '?' (Usage: self:SetTextColor(color [, a]))
[string "=[C]"]: in function `SetTextColor'
[string ***@***.***/NeatPlatesCore.lua"]:1314: in function
<NeatPlates/NeatPlatesCore.lua:1299>
[string ***@***.***/NeatPlatesCore.lua"]:694: in function
<NeatPlates/NeatPlatesCore.lua:665>
[string ***@***.***/NeatPlatesCore.lua"]:810: in function
<NeatPlates/NeatPlatesCore.lua:800>
[string ***@***.***/NeatPlatesCore.lua"]:380: in function
<NeatPlates/NeatPlatesCore.lua:353>

Locals:
(*temporary) = "bad argument #2 to '?' (Usage: self:SetTextColor(color [, a]))"

**Comment by grospapa** [comment]
Here:

**Comment by grospapa** [comment]
Whoops:

^1^T^STextShowOnlyOnActive^b^SWidgetAuraSort^N1^SWidgetResourceDisplayTimer^B^SUnitSpotlightLookup^T^t^SEnableOffTankHighlight^b^SStyleShowEnemyPowerBar^b^SSpellCastEnableFriendly^b^SWidgetPandemic^b^SStyleEnemyBarsInstanceMode^b^SEmphasizedAuraScale^N2^SColorSchoolHoly^T^Sa^N1^Sr^N1^Sg^F8124141093781504^f-53^Sb^F4521261069762560^f-53^t^SFriendlyNameColorMode^SByClass^SHighlightMouseoverScale^T^Sy^N1^Sx^N1^Soffset^T^Sy^N0^Sx^N0^t^t^SOpacityNonTarget^N1^SStyleEnemyBarsOnElite^B^SStyleEnemyBarsNoTotem^b^SOpacitySpotlightSpellInt^b^SIntCastWhoEnable^B^SColorSchoolArcane^T^Sa^N1^Sr^N1^Sg^F4521261069762560^f-53^Sb^N1^t^SStyleEnemyBarsClickThrough^b^SStyleFriendlyBarsClickThrough^b^SDefaultEnemyNameplatesOnNPCs^b^SStatusTextRight^N7^SStyleFriendlyBarsOnPlayers^B^SDefaultFriendlyNameplatesOnNPCs^b^SWidgetAuraTrackCurse^B^SColorSchoolFrost^T^Sa^N1^Sr^F4521261069762560^f-53^Sg^N1^Sb^N1^t^SWidgetQuestIcon^b^SStatusTextCenterColor^B^SColorBuffPurgeable^T^Sa^N1^Sr^N0^Sg^F7205760048037888^f-54^Sb^N1^t^SHighlightTargetMode^N1^SHeadlineFriendlySubtext^SRoleGuildLevel^SWidgetBuffPurgeable^B^SWidgetThreatIndicator^B^SHeadlineEnemyColor^N4^SWidgetAuraScaleOptions^T^Sy^N1^Sx^N1^Soffset^T^Sy^N0^Sx^N0^t^t^SColorRangeClose^T^Sa^N1^Sr^F7912207006302208^f-57^Sg^F7876884658388992^f-53^Sb^F7417694135517184^f-53^t^SClassPartyIcon^b^SSpellIconEnable^B^SWidgetRangeScaleOptions^T^Sy^N1^Sx^N1^Soffset^T^Sy^N0^Sx^N0^t^t^SStatusTextRightColor^B^SSpacerSlots^N1^SOpacityFilterFriendlyPlayers^b^SColorNeutral^T^Sa^N1^Sr^N1^Sg^N1^Sb^N0^t^SStyleFriendlyBarsOnElite^b^SCastBarWidth^N1^SStyleFriendlyBarsOnActive^B^SFriendlyBarColorMode^SByClass^STextStatusForceShadow^b^SStyleHeadlineOutOfCombat^b^SAltShortening^b^STextColorPartyMember^T^Sa^N1^Sr^F8477364572913664^f-55^Sg^F5934154986291200^f-53^Sb^N1^t^SDefaultFriendlyNameplatesOnPlayers^b^SUnitSpotlightGlowEnable^B^SWidgetAuraTrackDisease^B^SStyleForceBarsOnTargets^b^SColorMouseover^T^Sa^N1^Sr^N1^Sg^N1^Sb^N1^t^SWidgetDebuff^B^STextHealthPercentPrecision^N0^STextUseBlizzardFont^b^SColorPartyAggroText^b^SColorSchoolShadow^T^Sa^N1^Sr^F4521261069762560^f-53^Sg^F4521261069762560^f-53^Sb^N1^t^SScaleFiltered^N0.8^SScaleTargetSpotlight^b^SOpacitySpotlightMouseover^b^SOpacityFilterInactive^b^SWidgetRangeUnits^N2^SColorDangerGlowMode^N2^SWidgetResourceStyle^SNeat^SDefaultNeutralNameplatesOnNPCs^b^SStyleFriendlyMode^N2^SAdvancedEnableUnitCache^B^SFriendlySubtextColor^T^Sa^N0^Sr^N0^Sg^N0^Sb^N0^t^SHighlightMouseoverMode^N1^SOpacityFilterNeutralUnits^b^STextColorFriendlyNPC^T^Sa^N1^Sr^F6781891873079296^f-54^Sg^F7912207006302208^f-53^Sb^F5227708028026880^f-55^t^SOpacityFilterEnemyNPC^b^STextNameColorMode^N1^SEnemySubtextColor^T^Sa^N0^Sr^N0^Sg^N0^Sb^N0^t^SClassEnemyIcon^b^SOpacityTarget^N1^STextColorHostilePlayer^T^Sa^N1^Sr^N1^Sg^F7205760048037888^f-55^Sb^F4521261069762560^f-55^t^SWidgetAuraTrackPoison^B^SWidgetTotemIcon^b^SColorTapped^T^Sa^N1^Sr^F7770917614649344^f-54^Sg^F7770917614649344^f-54^Sb^F7770917614649344^f-54^t^SSpellCastEnableEnemy^B^SWidgetAbsorbMode^N1^STextHealthTextMode^N1^SWidgetRangeScale^b^SWidgetAuraTrackDispelFriendly^B^SColorFriendlyPlayer^T^Sa^N1^Sr^N0^Sg^N0^Sb^N1^t^SColorPartyAggroGlow^B^SWidgetThreatPercentage^b^SWidgetEliteIndicator^B^SIntCastEnable^B^SAuraScale^N1^SWidgetArenaIcon^b^SFriendlyHeadlineColor^SByReaction^SEnemyHeadlineColor^SByReaction^SScaleSpotlight^N1.29^SCastbarDurationMode^STimeCastTime^SColorFocus^T^Sa^N1^Sr^N1^Sg^N1^Sb^N1^t^STextColorBoss^T^Sa^F7205760048037888^f-53^Sr^N1^Sg^F7664950570909696^f-53^Sb^F7347049439690752^f-56^t^SUnitSpotlightOpacityEnable^B^SScaleCastingSpotlight^b^SStatusTextCenter^N5^SScaleIgnoreNeutralUnits^B^SBorderBuffEnrage^N1^SOpacityFilterNonElite^b^STheme^SNeon^SCastSpellNameEnable^B^SFriendlySubtext^SLevel^SColorTarget^T^Sa^N1^Sr^N1^Sg^N1^Sb^N1^t^SColorThreatWarning^T^Sa^N1^Sr^F7205760048037888^f-53^Sg^N0^Sb^N0^t^SWidgetRangeMode^N1^SStyleFriendlyBarsNoTotem^b^SColorThreatSafe^T^Sa^N1^Sr^F8477364572913664^f-57^Sg^F5298352723853312^f-53^Sb^F8124141093781504^f-53^t^SNameplateNoStackingFriendly^b^SOpacityFilterFriendlyNPC^b^SColorRangeMelee^T^Sa^N0^Sr^F8124141093781504^f-53^Sg^F8124141093781504^f-53^Sb^F8124141093781504^f-53^t^SWidgetComboPointsStyle^N2^SHideAuraInHeadline^b^SFrameVerticalPosition^N0.7^SHighlightFocustMode^N1^SCustomColorList^S^SWidgetEnableExternal^B^STextColorGuildMember^T^Sa^N1^Sr^F8477364572913664^f-55^Sg^F5934154986291200^f-53^Sb^N1^t^SStyleEnemyMode^N1^SColorPartyAggro^T^Sa^N1^Sr^N1^Sg^N0^Sb^F7205760048037888^f-54^t^SColorSchoolPhysical^T^Sa^N1^Sr^F4627228113502208^f-53^Sg^F6781891873079296^f-53^Sb^F6887858916818944^f-53^t^STextColorNeutral^T^Sa^N1^Sr^F8901232747872256^f-53^Sg^F6358023161249792^f-53^Sb^F7629628222996480^f-56^t^SWidgetResourceHideEmpty^b^SColorFriendlyNPC^T^Sa^N1^Sr^N0^Sg^N1^Sb^N0^t^SWidgetAuraTrackMagic^B^SScaleFunctionMode^SByThreat^STextColorFriendlyPlayer^T^Sa^N1^Sr^F8477364572913664^f-55^Sg^F5934154986291200^f-53^Sb^N1^t^SEnemyBarColorMode^SByThreat^SOpacityFullNoTarget^B^SColorHighHealth^T^Sa^N1^Sr^N0^Sg^N1^Sb^F7205760048037888^f-55^t^SColorSchoolNature^T^Sa^N1^Sr^F5439642115506176^f-54^Sg^N1^Sb^F5439642115506176^f-54^t^SStyleHeadlineMiniMobs^b^SHeadlineFriendlyColor^N4^SColorCastBySchool^b^SOpacityFilterList^SFanged~`Pit~`Viper~JLiberated~`Karabor~`Prisoner^SStyleFriendlyBarsNoMinions^b^SColorHealthBarMode^N3^STextShowUnitTitle^b^SColorHostileNPC^T^Sa^N1^Sr^N1^Sg^N0^Sb^N0^t^SThreatGlowEnable^B^SDefaultEnemyNameplatesOnPlayers^b^SStyleEnemyBarsOnActive^B^SColorGuildMember^T^Sa^N1^Sr^F8477364572913664^f-55^Sg^F5934154986291200^f-53^Sb^N1^t^SClassColorPartyMembers^b^SStyleShowFriendlyPowerBar^b^SThreatWarningMode^SAuto^SEmphasizedUnique^B^SHighHealthThreshold^N0.7^SOpacityFilterEnemyPlayers^b^SHideCooldownSpiral^b^SWidgetAuraAlignment^N1^SUnitSpotlightList^S^SBorderPandemic^N1^SCustomMouseoverColor^b^SWidgetEmphasizedAuraScaleOptions^T^Sy^N1^Sx^N1^Sanchor^STOP^Soffset^T^Sy^N0^Sx^N0^t^t^SEnemyAlphaSpotlightMode^SByThreat^SWidgetTargetHighlight^B^SFocusAsTarget^b^SCustomization^T^SNameOnly^T^t^SDefault^T^t^SWidgetConfig^T^t^t^SSafeColorSolo^b^SHeadlineEnemySubtext^SRoleGuildLevel^STextShowOnlyOnTargets^b^SFilterPriority^b^SOpacityFilterPartyMembers^b^SWidgetRangeIndicator^b^SEnemySubtext^SLevel^SEnemyStatusTextMode^SHealthFunctionTargetOf^SWidgetResourceTimerFontSize^N8^SColorUnIntpellCast^T^Sa^N1^Sr^F4627228113502208^f-53^Sg^F6781891873079296^f-53^Sb^F6887858916818944^f-53^t^SSpellTargetEnable^B^SWidgetBuffEnrage^b^SStyleHeadlineNeutral^b^SFrameBarWidth^N1^SEmphasizedSlots^N2^SCustomColorLookup^T^t^SUnitSpotlightColor^T^Sb^N0^Sg^N0^Sr^N0.8^t^SWidgetDebuffStyle^N1^SCustomTargetColor^b^SColorLowHealth^T^Sa^N1^Sr^N1^Sg^N0^Sb^N0^t^SStyleEnemyBarsNoMinions^b^SColorThreatTransition^T^Sa^N1^Sr^N1^Sg^F5651576202985472^f-53^Sb^N0^t^SWidgetAdditionalAuras^T^t^SWidgetBuffFilter^N3^SStatusTextLeft^N8^SColorSchoolFire^T^Sa^N1^Sr^N1^Sg^F4521261069762560^f-53^Sb^N0^t^SColorPandemic^T^Sa^N1^Sr^F8124141093781504^f-53^Sg^F5368997419679744^f-55^Sb^F5368997419679744^f-55^t^SOpacityFilterLowLevelUnits^b^SColorBuffEnrage^T^Sa^N1^Sr^N1^Sg^N0^Sb^F7205760048037888^f-55^t^SEnemyNameColorMode^SByClass^SScaleMouseoverSpotlight^b^SColorMediumHealth^T^Sa^N1^Sr^N1^Sg^N1^Sb^N0^t^SStyleFriendlyBarsInstanceMode^b^SOpacityFilterNonPartyMembers^b^SOpacityFilterMini^b^SOpacityFiltered^N0^SOpacitySpotlight^N1^SColorAttackingOtherTank^T^Sa^N1^Sr^F8477364572913664^f-57^Sg^F6004799682117632^f-53^Sb^F7064470656385024^f-53^t^SColorRangeOOR^T^Sa^N1^Sr^F8124141093781504^f-53^Sg^F7912207006302208^f-57^Sb^F5368997419679744^f-56^t^SOpacitySpotlightRaidMarked^b^SWidgetAbsorbIndicator^b^STextColorHostileNPC^T^Sa^N1^Sr^N1^Sg^F7205760048037888^f-55^Sb^F4521261069762560^f-55^t^SStatusTextLeftColor^B^SUnitSpotlightScale^N1.4^STextUnitNameArenaID^b^SPreciseAuraThreshold^N10^SStyleEnemyBarsOnNPC^B^SWidgetResourceMode^N1^SScaleIgnoreInactive^b^STextShowLevel^b^SStyleEnemyBarsOnPlayers^B^SColorShowPartyAggro^b^SScaleIgnoreNonEliteUnits^b^SOpacityFilterUntitledFriendlyNPC^b^SUnitSpotlightScaleEnable^B^SHighlightFocusScale^T^Sy^N1^Sx^N1^Soffset^T^Sy^N0^Sx^N0^t^t^SHighlightTargetScale^T^Sy^N1^Sx^N1^Soffset^T^Sy^N0^Sx^N0^t^t^SOpacitySpotlightSpell^b^SWidgetResourceSpacing^N0^SWidgetAbsorbUnits^N1^SOpacityFilterFriendlyPet^b^SOpacityFilterEnemyPet^b^SBuffSeparationMode^N1^SScaleStandard^N1^SClassIconScaleOptions^T^Sy^N1^Sx^N1^Soffset^T^Sy^N0^Sx^N0^t^t^SWidgetComboPointsScaleOptions^T^Sy^N1^Sx^N1^Soffset^T^Sy^N0^Sx^N0^t^t^SFriendlyAlphaSpotlightMode^SOnLowHealth^STextColorElite^T^Sa^F4521261069762560^f-53^Sr^F8124141093781504^f-53^Sg^F6322700813336576^f-53^Sb^F5439642115506176^f-54^t^SColorRangeFar^T^Sa^N1^Sr^N1^Sg^F4521261069762560^f-53^Sb^N0^t^SUnitSpotlightOpacity^N1^STextShowServerIndicator^B^SCustomFocusColor^b^SScaleSpotlightMode^N2^SHideAuraStacks^b^SColorNormalSpellCast^T^Sa^N1^Sr^F8901232747872256^f-53^Sg^F4945129244721152^f-53^Sb^N0^t^SLowHealthThreshold^N0.3^SHighlightFocusMode^N1^SThreatSoloEnable^B^STextColorNormal^T^Sa^F7205760048037888^f-54^Sr^F5863510290464768^f-53^Sg^F5863510290464768^f-53^Sb^F5863510290464768^f-53^t^SColorIntpellCast^T^Sa^N1^Sr^N1^Sg^N0^Sb^N0^t^SColorHostilePlayer^T^Sa^N1^Sr^N1^Sg^N0^Sb^N0^t^SBorderBuffPurgeable^N1^SWidgetComboPoints^N1^SUseGlobalSet^b^SColorPartyMember^T^Sa^N1^Sr^F8477364572913664^f-55^Sg^F5934154986291200^f-53^Sb^N1^t^SBlizzardStyleIcons^b^SColorRangeMid^T^Sa^N1^Sr^F5086418636374016^f-57^Sg^F7806239962562560^f-53^Sb^N0^t^SOpacityFilterLookup^T^SFanged~`Pit~`Viper^B^SLiberated~`Karabor~`Prisoner^B^t^SColorPartyAggroBar^b^SHideAuraDuration^b^SFilterScaleLock^b^SWidgetRangeMax^N40^SThreatMode^N1^SUnitSpotlightBarEnable^B^SWidgetRangeStyle^N1^SFriendlyStatusTextMode^SHealthFunctionPercent^SStyleFriendlyBarsOnNPC^B^SWidgetDebuffFilter^N2^SWidgetEliteIndicatorBoss^b^t^^

**Comment by Luxocracy** [comment]
This should hopefully no longer happen in the latest version. It seems to be related to colors not getting fetched correctly from the blizzard API for a units level. I've added some default values to these so we have something to fallback on and hopefully that resolves the issue.

**Comment by grospapa** [comment]
Awesome, thanks for the update!
