### ISSUE TITLE
Cata classic prepatch trigers many lua errors

### ISSUE THREAD

**Issue by Apoxiosis** [Luxocracy/NeatPlates#414]
Hello, actually quite a few lua errors on cata classic right now. 

76x NeatPlatesWidgets/TankTrack.lua:108: attempt to call global 'GetSpecialization' (a nil value)

70x NeatPlatesWidgets/ResourceWidget.lua:315: attempt to call global 'GetSpecialization' (a nil value)

75x NeatPlatesWidgets/ComboPointWidget.lua:345: attempt to call global 'GetSpecialization' (a nil value)

367x NeatPlates/NeatPlatesCore.lua:1955: attempt to call field 'SetSubText' (a nil value)

11x NeatPlates/NeatPlatesCore.lua:261: attempt to call field 'SetScale' (a nil value)

1x NeatPlates_Neon/Neon.lua:512: attempt to call field 'ApplyHubFunctions' (a nil value)

1x NeatPlatesHub/Hub.lua:17: attempt to index global 'NeatPlatesHubRapidPanel' (a nil value)

1x NeatPlatesHub/functions/Core.lua:173: attempt to index global 'NeatPlatesHubRapidPanel' (a nil value)

1x NeatPlatesHub/Templates.lua:176: attempt to index field 'PanelHelpers' (a nil value)

1x NeatPlates/NeatPlatesPanel.lua:17: attempt to index local 'PanelHelpers' (a nil value)

1x NeatPlates/NeatPlatesUtility.lua:804: attempt to call method 'SetBackdrop' (a nil value)

**Comment by Luxocracy** [comment]
I've pushed an update that should hopefully resolve all of these errors.

Most of these seem to be related to the fact that the addon could not longer identify the new pre-patch as a classic version, so hopefully it should just work now and I didn't miss any issues.

**Comment by Apoxiosis** [comment]
seems to be working so far, i appreciate the quick update a lot. i'll report back if anything break or i get any errors
