### ISSUE TITLE
Fresh DK

### ISSUE THREAD

**Issue by vandiel01** [Luxocracy/NeatPlates#419]
Neatplates v441

Reproducable: Fresh DK
Issue: Always give an error due to no spec selected (frost, unholy or blood) (didn't want to, needed to due to simple misc thing I need done)

Suggestion: Add Before line 81 in `NeatPlatesWidgets\ResourceWidget.lua`

'if GetSpecialization() == 5 then return end'

I did an /run print(GetSpecialization()) on a DK that hasn't picked a spec and shows me a '5'.  This line above stop the error on any fresh DK

**Comment by Luxocracy** [comment]
I've fixed this in the latest version.

While just returning out of the power method technically stops the issue, it also stops the functionality of the widget. So I've made it default to blood runes if it cannot figure out what ones to use. Which is what happened here.
