### ISSUE TITLE
Broken in 11.0

### ISSUE THREAD

**Issue by hollo6** [Luxocracy/NeatPlates#420]
**What version of the game you are experiencing the issue with:**
Retail

**Describe the bug**
Getting spammed by the following LUA error:

3631x NeatPlates/NeatPlatesCore.lua:1955: attempt to call field 'SetSubText' (a nil value)
[string "@NeatPlates/NeatPlatesCore.lua"]:1955: in function <NeatPlates/NeatPlatesCore.lua:1953>
[string "@NeatPlates/NeatPlatesCore.lua"]:654: in function <NeatPlates/NeatPlatesCore.lua:642>
[string "@NeatPlates/NeatPlatesCore.lua"]:678: in function <NeatPlates/NeatPlatesCore.lua:665>
[string "@NeatPlates/NeatPlatesCore.lua"]:810: in function <NeatPlates/NeatPlatesCore.lua:800>
[string "@NeatPlates/NeatPlatesCore.lua"]:380: in function <NeatPlates/NeatPlatesCore.lua:353>

Locals:
index = nil
unitSubtext = nil
unitPlateStyle = nil
(*temporary) = nil
(*temporary) = <table> {
 guid = "Creature-0-4241-2444-475-199220-000020B75C"
 isMouseover = false
 class = ""
 rawName = "Violetwing Stagbeetle"
 level = 1
 red = 1
 levelcolorRed = 0.500000
 isDangerous = false
 isPet = false
 name = "Violetwing Stagbeetle"
 pvpname = "Violetwing Stagbeetle"
 levelcolorBlue = 0.500000
 isBoss = false
 isFocus = false
 healthmax = 5
 isTarget = false
 levelcolorGreen = 0.500000
 alphaMult = 0.152941
 isMarked = false
 isTapped = false
 type = "NPC"
 blue = 0
 power = 0
 isInCombat = false
 threatSituation = "LOW"
 powermax = 0
 isTrivial = true
 health = 5
 showName = true
 reaction = "NEUTRAL"
 green = 1
 isCasting = false
 threatValue = 0
 unitid = "nameplate1"
 isMini = false
}
(*temporary) = "attempt to call field 'SetSubText' (a nil value)"
style = <table> {
 powerbar = <table> {
 }
 spellicon = <table> {
 }
 extrabar = <table> {
 }
 target = <table> {
 }
 spelltarget = <table> {
 }
 healthbar = <table> {
 }
 healthborder = <table> {
 }
 targetindicator_arrowright = <table> {
 }
 mouseover = <table> {
 }
 durationtext = <table> {
 }
 name = <table> {
 }
 hitbox = <table> {
 }
 raidicon = <table> {
 }
 customtext = <table> {
 }
 targetindicator = <table> {
 }
 eliteicon = <table> {
 }
 extratext = <table> {
 }
 spelltext = <table> {
 }
 extraborder = <table> {
 }
 threatcolor = <table> {
 }
 targetindicator_arrowtop = <table> {
 }
 castbar = <table> {
 }
 highlight = <table> {
 }
 threatborder = <table> {
 }
 skullicon = <table> {
 }
 focus = <table> {
 }
 targetindicator_arrowsides = <table> {
 }
 targetindicator_arrowleft = <table> {
 }
 castborder = <table> {
 }
 subtext = <table> {
 }
 level = <table> {
 }
 frame = <table> {
 }
 rangeindicator = <table> {
 }
 castnostop = <table> {
 }
}
activetheme = <table> {
 powerbar = <table> {
 }
 spellicon = <table> {
 }
 extrabar = <table> {
 }
 target = <table> {
 }
 spelltarget = <table> {
 }
 healthbar = <table> {
 }
 healthborder = <table> {
 }
 targetindicator_arrowright = <table> {
 }
 mouseover = <table> {
 }
 durationtext = <table> {
 }
 name = <table> {
 }
 hitbox = <table> {
 }
 raidicon = <table> {
 }
 customtext = <table> {
 }
 targetindicator = <table> {
 }
 eliteicon = <table> {
 }
 extratext = <table> {
 }
 spelltext = <table> {
 }
 extraborder = <table> {
 }
 threatcolor = <table> {
 }
 targetindicator_arrowtop = <table> {
 }
 castbar = <table> {
 }
 highlight = <table> {
 }
 threatborder = <table> {
 }
 skullicon = <table> {
 }
 focus = <table> {
 }
 targetindicator_arrowsides = <table> {
 }
 targetindicator_arrowleft = <table> {
 }
 castborder = <table> {
 }
 subtext = <table> {
 }
 level = <table> {
 }
 frame = <table> {
 }
 rangeindicator = <table> {
 }
 castnostop = <table> {
 }
}
unit = <table> {
 guid = "Creature-0-4241-2444-475-199220-000020B75C"
 isMouseover = false
 class = ""
 rawName = "Violetwing Stagbeetle"
 level = 1
 red = 1
 levelcolorRed = 0.500000
 isDangerous = false
 isPet = false
 name = "Violetwing Stagbeetle"
 pvpname = "Violetwing Stagbeetle"
 levelcolorBlue = 0.500000
 isBoss = false
 isFocus = false
 healthmax = 5
 isTarget = false
 levelcolorGreen = 0.500000
 alphaMult = 0.152941
 isMarked = false
 isTapped = false
 type = "NPC"
 blue = 0
 power = 0
 isInCombat = false
 threatSituation = "LOW"
 powermax = 0
 isTrivial = true
 health = 5
 showName = true
 reaction = "NEUTRAL"
 green = 1
 isCasting = false
 threatValue = 0
 unitid = "nameplate1"
 isMini = false
}
extended = Frame {
 stylename = ""
 requestedAlpha = 0
 unitcache = <table> {
 }
 widgetParent = Frame {
 }
 widgets = <table> {
 }
 regions = <table> {
 }
 Active = true
 stylecache = <table> {
 }
 style = <table> {
 }
 unit = <table> {
 }
 bars = <table> {
 }
 defaultLevel = 40
 visual = <table> {
 }
}
carrier = NeatPlatesCarrier-1 {
}
anchorgroup = <table> {
 1 = "healthborder"
 2 = "threatborder"
 3 = "castborder"
 4 = "castnostop"
 5 = "name"
 6 = "subtext"
 7 = "extraborder"
 8 = "extratext"
 9 = "spelltext"
 10 = "spelltarget"
 11 = "durationtext"
 12 = "customt

**To Reproduce**
Nothing needed, it's constantly spammed.

**Expected behavior**
There should be no errors.

**Screenshots**
N/AIf applicable, add screenshots to help explain your problem.

**Additional context**
N/A

**Comment by Luxocracy** [comment]
I've pushed a new release to curseforge, it should be available shortly.

I only really fixed the issues with the new menu system that I never fully integrated previously, and is now required. So there could still be somethings that don't work. So I'd appreciated it if you bring any new issues you find to my attention so they also can be fixed.

**Comment by hollo6** [comment]
New spam in 443:

391x bad argument #1 to '?' (not a numerical value - Usage: local inRange = C_SpellBook.IsSpellBookItemInRange(spellBookItem [, targetUnit]))
[string "=[C]"]: in function `IsSpellBookItemInRange'
[string "@WeakAuras/Libs/LibRangeCheck-3.0-19/LibRangeCheck-3.0.lua"]:89: in function <...akAuras/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua:88>
[string "@WeakAuras/Libs/LibRangeCheck-3.0-19/LibRangeCheck-3.0.lua"]:573: in function `checker'
[string "@WeakAuras/Libs/LibRangeCheck-3.0-19/LibRangeCheck-3.0.lua"]:786: in function <...akAuras/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua:781>
[string "=(tail call)"]: ?
[string "@WeakAuras/Libs/LibRangeCheck-3.0-19/LibRangeCheck-3.0.lua"]:861: in function <...akAuras/Libs/LibRangeCheck-3.0/LibRangeCheck-3.0.lua:842>
[string "=(tail call)"]: ?
[string "@NeatPlatesWidgets/RangeWidget.lua"]:67: in function <NeatPlatesWidgets/RangeWidget.lua:65>
[string "@NeatPlatesWidgets/RangeWidget.lua"]:173: in function `UpdateContext'
[string "@NeatPlatesHub/functions/Widgets.lua"]:721: in function `OnContextUpdate'
[string "@NeatPlates/NeatPlatesCore.lua"]:962: in function <NeatPlates/NeatPlatesCore.lua:947>
[string "@NeatPlates/NeatPlatesCore.lua"]:809: in function <NeatPlates/NeatPlatesCore.lua:800>
[string "@NeatPlates/NeatPlatesCore.lua"]:380: in function <NeatPlates/NeatPlatesCore.lua:353>

Locals:
(*temporary) = "bad argument #1 to '?' (not a numerical value - Usage: local inRange = C_SpellBook.IsSpellBookItemInRange(spellBookItem [, targetUnit]))"

**Comment by Luxocracy** [comment]
hmm, I can't seem to replicate this issue myself. But it does seem to have something to do with the third-party library for range checking.

Could you try and disable weakauras and see if the issue persists or if it changes? Because even after having updated weakauras I cannot replicate it.

**Comment by hollo6** [comment]
Only WA enabled -> no error
Only NP enabled -> no error
both enabled -> error

I can 100% reproduce this on a hunter, will try on something else in a bit.

**Comment by Luxocracy** [comment]
I was able to reproduce it now, I just had to restart the game fully after updating Weakauras for it to start giving me the same errors.

**Comment by Luxocracy** [comment]
I think it's something related to this issue in the library itself, I'll keep an eye out for a new release of this and push an update once it is available.

https://github.com/WeakAuras/LibRangeCheck-3.0/issues/26

**Comment by hollo6** [comment]
Thanks, it indeed went away.
I will report here if anything else pops up.

**Comment by hollo6** [comment]
Seems all good since. :)
