### ISSUE TITLE
LibRangeCheck C_Item.GetItemInfo nill

### ISSUE THREAD

**Issue by MrQiYin** [Luxocracy/NeatPlates#422]
**What version of the game you are experiencing the issue with:**
Classic WLK

**Describe the bug**
Need to add "C_Item and C_Item.GetItemInfo and " before use "C_Item.GetItemInfo", maybe "GetItemInfo" is nil at 3.4.3?

**Additional context**
```code
BugGrabberDB = {
	["session"] = 6,
	["lastSanitation"] = 3,
	["errors"] = {
		{
			["message"] = "...tPlates/libs/LibRangeCheck-3.0-20/LibRangeCheck-3.0.lua:1309: attempt to call field 'GetItemInfo' (a nil value)",
			["time"] = "2024/07/25 10:51:52",
			["session"] = 1,
			["counter"] = 310,
		}, -- [1]
		{
			["message"] = "...tPlates/libs/LibRangeCheck-3.0-20/LibRangeCheck-3.0.lua:722: attempt to call field 'GetItemInfo' (a nil value)",
			["time"] = "2024/07/25 10:51:51",
			["session"] = 5,
			["counter"] = 5,
		}, -- [2]
	},
}
```

**Comment by Luxocracy** [comment]
This might be something that needs to be take up with the library maintainers directly. As the only thing I could potentially do to resolve this is to disallow items being used for range checking.

But looking at their code they are using "C_Item" when fetching item info.

The error suggests that "GetItemInfo" doesn't exist within "C_Item". Do you still get this error when you disable all other addons? As this could be a conflict caused by another addon.

**Comment by MrQiYin** [comment]
> This might be something that needs to be take up with the library maintainers directly. As the only thing I could potentially do to resolve this is to disallow items being used for range checking.
> 
> But looking at their code they are using "C_Item" when fetching item info.
> 
> The error suggests that "GetItemInfo" doesn't exist within "C_Item". Do you still get this error when you disable all other addons? As this could be a conflict caused by another addon.

The above log I provided was given to me by BugGrabber.
"NeatPlates/libs/LibRangeCheck-3.0-20/LibRangeCheck-3.0.lua:1309"
"NeatPlates/libs/LibRangeCheck-3.0-20/LibRangeCheck-3.0.lua:722"
I don't really know what the impact is, except that WOW always gives me a pop-up saying "You have a lot of lua errors", and the BugGrabber log shows that errors are executed about two or three times per second, so I have fixed locally, the error is no longer happening.
