### ISSUE TITLE
光耀回响显示错误

### ISSUE THREAD

**Issue by MrQiYin** [Luxocracy/NeatPlates#423]
**What version of the game you are experiencing the issue with:**
Retail，China，11.0.0.55945

**Describe the bug**
光耀回响似乎被识别为了一个NPC，它的名字显示“光耀回响”，副标题显示为“UNKNOWN”

**Expected behavior**
应该显示为“光耀回响的倒计时”

**Screenshots**
![image](https://github.com/user-attachments/assets/bdf6155f-5b72-44d9-93b1-ba171cd10056)
![image](https://github.com/user-attachments/assets/1e0b4182-3e2a-433e-a063-6742c88c223a)

**Comment by Luxocracy** [comment]
If I'm understanding correctly. Try enabling this option in the main settings.

> Use Blizzard Bar Widgets(블리자드 바 위젯 사용)

This should disable the replacement of non-standard nameplates.

**Comment by MrQiYin** [comment]
> If I'm understanding correctly. Try enabling this option in the main settings.
> 
> > Use Blizzard Bar Widgets(블리자드 바 위젯 사용)
> 
> This should disable the replacement of non-standard nameplates.

它生效了，谢谢你，不好意思之前没能理解这个选项的意思。
