### ISSUE TITLE
Attempt to call field setsubset text (a nil value) TWW Patch 11.0.2.56110

### ISSUE THREAD

**Issue by Yarvillian** [Luxocracy/NeatPlates#426]
**What version of the game you are experiencing the issue with:**
Live/Retail,

**Describe the bug**
Addon Crashing on Startup.
673x NeatPlates/NeatPlatesCore.lua:1955: attempt to call field 'SetSubText' (a nil value)
[string "@NeatPlates/NeatPlatesCore.lua"]:1955: in function <NeatPlates/NeatPlatesCore.lua:1953>
[string "@NeatPlates/NeatPlatesCore.lua"]:654: in function <NeatPlates/NeatPlatesCore.lua:642>
[string "@NeatPlates/NeatPlatesCore.lua"]:678: in function <NeatPlates/NeatPlatesCore.lua:665>
[string "@NeatPlates/NeatPlatesCore.lua"]:810: in function <NeatPlates/NeatPlatesCore.lua:800>
[string "@NeatPlates/NeatPlatesCore.lua"]:380: in function <NeatPlates/NeatPlatesCore.lua:353>

Locals:
index = nil
unitSubtext = nil
unitPlateStyle = nil
(*temporary) = nil
(*temporary) = <table> {
 guid = "Creature-0-3024-2444-152-199220-0005BBCB38"
 isMouseover = false
 class = ""
 rawName = "Violetwing Stagbeetle"
 level = 1
 red = 1
 levelcolorRed = 0.500000
 isDangerous = false
 isPet = false
 name = "Violetwing Stagbeetle"
 pvpname = "Violetwing Stagbeetle"
 levelcolorBlue = 0.500000
 isBoss = false
 isFocus = false
 healthmax = 5
 isTarget = false
 levelcolorGreen = 0.500000
 isMarked = false
 alphaMult = 0.996078
 isTapped = false
 type = "NPC"
 blue = 0
 power = 0
 isInCombat = false
 threatSituation = "LOW"
 powermax = 0
 isTrivial = true
 health = 5
 showName = true
 reaction = "NEUTRAL"
 green = 1
 isCasting = false
 threatValue = 0
 unitid = "nameplate1"
 isMini = false
}
(*temporary) = "attempt to call field 'SetSubText' (a nil value)"
style = <table> {
 powerbar = <table> {
 }
 spellicon = <table> {
 }
 extrabar = <table> {
 }
 target = <table> {
 }
 spelltarget = <table> {
 }
 healthbar = <table> {
 }
 healthborder = <table> {
 }
 targetindicator_arrowright = <table> {
 }
 mouseover = <table> {
 }
 durationtext = <table> {
 }
 name = <table> {
 }
 hitbox = <table> {
 }
 raidicon = <table> {
 }
 customtext = <table> {
 }
 targetindicator = <table> {
 }
 eliteicon = <table> {
 }
 extratext = <table> {
 }
 spelltext = <table> {
 }
 extraborder = <table> {
 }
 threatcolor = <table> {
 }
 targetindicator_arrowtop = <table> {
 }
 castbar = <table> {
 }
 highlight = <table> {
 }
 threatborder = <table> {
 }
 skullicon = <table> {
 }
 focus = <table> {
 }
 targetindicator_arrowsides = <table> {
 }
 targetindicator_arrowleft = <table> {
 }
 castborder = <table> {
 }
 subtext = <table> {
 }
 level = <table> {
 }
 frame = <table> {
 }
 rangeindicator = <table> {
 }
 castnostop = <table> {
 }
}
activetheme = <table> {
 powerbar = <table> {
 }
 spellicon = <table> {
 }
 extrabar = <table> {
 }
 target = <table> {
 }
 spelltarget = <table> {
 }
 healthbar = <table> {
 }
 healthborder = <table> {
 }
 targetindicator_arrowright = <table> {
 }
 mouseover = <table> {
 }
 durationtext = <table> {
 }
 name = <table> {
 }
 hitbox = <table> {
 }
 raidicon = <table> {
 }
 customtext = <table> {
 }
 targetindicator = <table> {
 }
 eliteicon = <table> {
 }
 extratext = <table> {
 }
 spelltext = <table> {
 }
 extraborder = <table> {
 }
 threatcolor = <table> {
 }
 targetindicator_arrowtop = <table> {
 }
 castbar = <table> {
 }
 highlight = <table> {
 }
 threatborder = <table> {
 }
 skullicon = <table> {
 }
 focus = <table> {
 }
 targetindicator_arrowsides = <table> {
 }
 targetindicator_arrowleft = <table> {
 }
 castborder = <table> {
 }
 subtext = <table> {
 }
 level = <table> {
 }
 frame = <table> {
 }
 rangeindicator = <table> {
 }
 castnostop = <table> {
 }
}
unit = <table> {
 guid = "Creature-0-3024-2444-152-199220-0005BBCB38"
 isMouseover = false
 class = ""
 rawName = "Violetwing Stagbeetle"
 level = 1
 red = 1
 levelcolorRed = 0.500000
 isDangerous = false
 isPet = false
 name = "Violetwing Stagbeetle"
 pvpname = "Violetwing Stagbeetle"
 levelcolorBlue = 0.500000
 isBoss = false
 isFocus = false
 healthmax = 5
 isTarget = false
 levelcolorGreen = 0.500000
 isMarked = false
 alphaMult = 0.996078
 isTapped = false
 type = "NPC"
 blue = 0
 power = 0
 isInCombat = false
 threatSituation = "LOW"
 powermax = 0
 isTrivial = true
 health = 5
 showName = true
 reaction = "NEUTRAL"
 green = 1
 isCasting = false
 threatValue = 0
 unitid = "nameplate1"
 isMini = false
}
extended = Frame {
 stylename = ""
 requestedAlpha = 0
 unitcache = <table> {
 }
 widgetParent = Frame {
 }
 widgets = <table> {
 }
 regions = <table> {
 }
 Active = true
 stylecache = <table> {
 }
 style = <table> {
 }
 unit = <table> {
 }
 bars = <table> {
 }
 defaultLevel = 20
 visual = <table> {
 }
}
carrier = NeatPlatesCarrier-1 {
}
anchorgroup = <table> {
 1 = "healthborder"
 2 = "threatborder"
 3 = "castborder"
 4 = "castnostop"
 5 = "name"
 6 = "subtext"
 7 = "extraborder"
 8 = "extratext"
 9 = "spelltext"
 10 = "spelltarget"
 11 = "durationtext"
 12 = "customt

**Comment by ShrikeBTR** [comment]
Also experiencing this - addon is mostly ok until you are around mobs, then the error count starts climbing by about 100/s

Nameplates don't appear at all.

This appears to have begun within the last 24h or so.

**Comment by Luxocracy** [comment]
Blizzard seems to have finally removed a lot of deprecated functions that the addon was still using.

Seems most of them are simple name changes to get it working again, but for buffs and debuffs its not a one to one replacement. So I'll look at it later today when I have more time.

**Comment by hollo6** [comment]
Just a few quick fixes to at least have nameplates and no error spam:

NeatPlatesPanel.lua L13:
local version = C_AddOns.GetAddOnMetadata("NeatPlates", "version")

Hub.lua L574-575:
	local TPCEnabled = C_AddOns.GetAddOnEnableState(player, "TidyPlatesContinued") ~= 0
	local TPCHubEnabled = C_AddOns.GetAddOnEnableState(player, "TidyPlatesContinuedHub") ~= 0

AuraWidget.lua L11:
local _UnitAura = C_UnitAuras.GetAuraDataByIndex

TotemIconWidget.lua L14:
	local name, _, icon = C_Spell.GetSpellInfo(spellid)

**Comment by Luxocracy** [comment]
After looking a bit at the new aura structure I noticed Blizzard had a method in their AuraUtils that let me convert to new aura structure to the old one, so there were not changes necessary. For now at least...

I've fixed the other issues as well and pushed a release to curseforge.
