### ISSUE TITLE
Can't i add icon?

### ISSUE THREAD

**Issue by Jiasonthe** [Luxocracy/NeatPlates#427]
**Is your feature request related to a problem? Please describe.**
Just i need to shield icon for imunity spell interrupt

**Describe the solution you'd like**
Like this.
![Screenshot_20240817_122233_NAVER](https://github.com/user-attachments/assets/b9966ca1-a9a1-4165-89e8-630b37da1c01)

**Describe alternatives you've considered**
I dont know.

**Additional context**
![Screenshot_20240817_122233_NAVER](https://github.com/user-attachments/assets/6aac5607-54d1-4c33-93f0-437fe8a90fb3)

**Comment by Jiasonthe** [comment]
> **Is your feature request related to a problem? Please describe.** Just i need to shield icon for imunity spell interrupt
> 
> **Describe the solution you'd like** Like this. ![Screenshot_20240817_122233_NAVER](https://private-user-images.githubusercontent.com/178627441/358792403-b9966ca1-a9a1-4165-89e8-630b37da1c01.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NjYwODIsIm5iZiI6MTcyMzg2NTc4MiwicGF0aCI6Ii8xNzg2Mjc0NDEvMzU4NzkyNDAzLWI5OTY2Y2ExLWE5YTEtNDE2NS04OWU4LTYzMGIzN2RhMWMwMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QwMzM2MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTkzNGE3MzkxYzk3M2E0YzA1ZWUwOGY2NmZjZDA4Mzc4OWIwZWMxY2RkYmM1MmFjM2I3ODM1ZmJmMmMwOWUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5K_eaA9mKUxJoi1bG3rfJENMiRfBgklsS_FW3DBv89Q)
> 
> **Describe alternatives you've considered** I dont know.
> 
> **Additional context** ![Screenshot_20240817_122233_NAVER](https://private-user-images.githubusercontent.com/178627441/358792593-6aac5607-54d1-4c33-93f0-437fe8a90fb3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NjYwODIsIm5iZiI6MTcyMzg2NTc4MiwicGF0aCI6Ii8xNzg2Mjc0NDEvMzU4NzkyNTkzLTZhYWM1NjA3LTU0ZDEtNGMzMy05M2YwLTQzN2ZlOGE5MGZiMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxN1QwMzM2MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTNjMmQ3OTBlZmYwMDE4ZWQyZTk2ZGU5OTAwN2I3YjNmODI3Njc4NjA5M2YwNDRlNmIxYTM2YmUwZTQyYzk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lO8Z8qr3B-n6gmGIX2WLIRvHebXLmkXvQb9fx8uVi6k)

**Comment by Luxocracy** [comment]
This is already a thing.

Depending on the theme you use this might not the represented with a shield, but with a different border.

**Comment by Jiasonthe** [comment]
> This is already a thing.
> 
> Depending on the theme you use this might not the represented with a shield, but with a different border.

Can you add it to Quatre theme?
