### ISSUE TITLE
Unsupported widget

### ISSUE THREAD

**Issue by Nukme** [Luxocracy/NeatPlates#429]
**What version of the game you are experiencing the issue with:**
Retail

**Describe the bug**
Entering the very first quest delve, and the bug alarm goes off.

**To Reproduce**
1. Uncheck option 'Use Blizzard Bar Widgets'
1. Doing the mainline quest, entering the first delve to interact Brann Bronzebeard

**Expected behavior**

**Screenshots**

**Additional context**

```lua
7x NeatPlates/NeatPlatesCore.lua:1181: NeatPlates: Unsupported widget type (13) please report this and what you were doing to the addon author.
[string "=[C]"]: in function `error'
[string "@NeatPlates/NeatPlatesCore.lua"]:1181: in function <NeatPlates/NeatPlatesCore.lua:1156>
[string "@NeatPlates/NeatPlatesCore.lua"]:695: in function <NeatPlates/NeatPlatesCore.lua:676>
[string "@NeatPlates/NeatPlatesCore.lua"]:821: in function <NeatPlates/NeatPlatesCore.lua:811>
[string "@NeatPlates/NeatPlatesCore.lua"]:391: in function <NeatPlates/NeatPlatesCore.lua:364>

Locals:
(*temporary) = "NeatPlates: Unsupported widget type (13) please report this and what you were doing to the addon author."

```

**Comment by Luxocracy** [comment]
Not sure what this widget type actually does in-game and I'm unable to test it right now. So I've simply made it so that if we encounter this widget type we force display the blizzard widget instead to get rid of the error.
