### ISSUE TITLE
Aura filter not working - SoD

### ISSUE THREAD

**Issue by blackmyin** [Luxocracy/NeatPlates#434]
**What version of the game you are experiencing the issue with:**
Season of Discovery

**Describe the bug**
Using aura filter seems to be broken, trying to set up an aura to be exluded doesn't do anything and gives an lua error.

**To Reproduce**
Go to Options and under "General Aura Filters" add "New Aura" with any ID and select Exluded on "Aura Filter".
Enter combat and apply the aura.

**Expected behavior**
Aura should excluded and without any lua errors.

**Additional context**
Here is the report from the BugSack addon.

678x NeatPlates/NeatPlatesCore.lua:1596: attempt to index global 'spellCCList' (a nil value)
[string "@NeatPlates/NeatPlatesCore.lua"]:1596: in function `?'
[string "@NeatPlates/NeatPlatesCore.lua"]:1450: in function <NeatPlates/NeatPlatesCore.lua:1448>

Locals:
self = "COMBAT_LOG_EVENT_UNFILTERED"
_ = 1727366950.953000
event = "SPELL_AURA_APPLIED"
_ = false
sourceGUID = "Player-5827-02704DCA"
sourceName = "Colibri"
sourceFlags = 1298
_ = 0
destGUID = "Creature-0-5209-229-12351-9693-0001F5806A"
destName = "Bloodaxe Evoker"
_ = 2632
_ = 0
spellID = 439471
spellName = "Sebacious Poison"
spellSchool = 8
plate = NamePlate5 {
 driverFrame = NamePlateDriverFrame {
 }
 extended = Frame {
 }
 UpdateMe = false
 showBlizzardPlate = false
 namePlateUnitToken = "nameplate1"
 template = "NamePlateUnitFrameTemplate"
 UnitFrame = Button {
 }
 UpdateHealth = false
 UpdateCastbar = true
 carrier = NeatPlatesCarrier-1 {
 }
}
ownerGUID = nil
unitType = "Player"
_ = "5827"
_ = "02704DCA"
_ = nil
_ = nil
creatureID = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'spellCCList' (a nil value)"
PlatesByGUID = <table> {
 Creature-0-5209-229-12351-9693-0001F5806A = NamePlate5 {
 }
}
SpellSchoolByGUID = <table> {
 Creature-0-5209-229-12351-230695-0000758710 = 4
 Creature-0-5209-229-12351-9692-000275806A = 1
 Player-5827-0272A99B = 64
 Player-5827-01FE7103 = 2
 Player-5827-026C8CF0 = 8
 Creature-0-5209-229-12351-230695-000075871B = 4
 Creature-0-5209-229-12351-9717-000075806A = 16
 Creature-0-5209-229-12351-9583-000175806A = 1
 Creature-0-5209-229-12351-9583-0002F5806A = 1
 Player-5827-02704DCA = 1
 Creature-0-5209-229-12351-10220-000075806A = 1
 Player-5827-02721EEF = 1
 Creature-0-5209-229-12351-9693-0000F5806B = 4
 Creature-0-5209-229-12351-9583-000275806B = 1
 Creature-0-5209-229-12351-9716-0001F5806A = 1
 Creature-0-5209-229-12351-9268-000075806A = 1
 Creature-0-5209-229-12351-9268-000275806A = 1
 Creature-0-5209-229-12351-9692-000175806A = 1
 Creature-0-5209-229-12351-9693-0001F5806A = 64
 Player-5827-0273FEC5 = 8
 Creature-0-5209-229-12351-9583-0003F5806A = 1
 Creature-0-5209-229-12351-9693-000075806B = 64
 Creature-0-5209-229-12351-9692-000075806B = 1
 Creature-0-5209-229-12351-9583-000375806A = 1
 Creature-0-5209-229-12351-9693-0000F5806A = 64
 Creature-0-5209-229-12351-9583-000075806B = 1
 Creature-0-5209-229-12351-230695-000075861B = 4
 Creature-0-5209-229-12351-9716-0000F5806B = 1
 Creature-0-5209-229-12351-9692-0001F5806A = 1
 Player-5827-01DED792 = 64
 Creature-0-5209-229-12351-230695-00007586AC = 4
 Creature-0-5209-229-12351-230695-00007585C7 = 4
 Creature-0-5209-229-12351-9583-000175806B = 1
 Creature-0-5209-229-12351-9583-0000F5806B = 1
 Creature-0-5209-229-12351-9716-000075806B = 1
 Player-5827-02702462 = 2
 Player-5827-02722E8F = 2
 Creature-0-5209-229-12351-10602-0000758640 = 64
}
ShowIntCast = true

**Comment by Luxocracy** [comment]
The lua error should be fixed as of a few minutes ago. Could you check if the aura exclusion issues has been resolved along with it?

**Comment by blackmyin** [comment]
Confirmed no lua errors and auras are in fact being excluded correctly with latest version!
