### ISSUE TITLE
C_TooltipInfo Error in latest versions

### ISSUE THREAD

**Issue by Ainlaen** [Luxocracy/NeatPlates#443]
**What version of the game you are experiencing the issue with:**
Season of Discovery

**Describe the bug**
NPC nameplates trigger the following error. The specific NPC doesn't matter, and the error continues to occur with all other addons disabled. 

> Date: 2024-11-27 16:30:37
> ID: -1
> Error occured in: Global
> Count: 676
> Message: Interface/AddOns/NeatPlates/NeatPlatesUtility.lua line 401:
>    attempt to index global 'C_TooltipInfo' (a nil value)
> Debug:
>    [string "@Interface/AddOns/NeatPlates/NeatPlatesUtility.lua"]:401:
>       Interface/AddOns/NeatPlates/NeatPlatesUtility.lua:398
>    [string "@Interface/AddOns/NeatPlatesHub/functions/Text.lua"]:529: func()
>    [string "@Interface/AddOns/NeatPlatesHub/functions/Text.lua"]:622: SetSubText()
>    [string "@Interface/AddOns/NeatPlates/NeatPlatesCore.lua"]:1997:
>       Interface/AddOns/NeatPlates/NeatPlatesCore.lua:1995
>    [string "@Interface/AddOns/NeatPlates/NeatPlatesCore.lua"]:747:
>       Interface/AddOns/NeatPlates/NeatPlatesCore.lua:735
>    [string "@Interface/AddOns/NeatPlates/NeatPlatesCore.lua"]:1059:
>       Interface/AddOns/NeatPlates/NeatPlatesCore.lua:1045
>    [string "@Interface/AddOns/NeatPlates/NeatPlatesCore.lua"]:906:
>       Interface/AddOns/NeatPlates/NeatPlatesCore.lua:894
>    [string "@Interface/AddOns/NeatPlates/NeatPlatesCore.lua"]:459:
>       Interface/AddOns/NeatPlates/NeatPlatesCore.lua:430
> Locals:
> unit = <table> {
>  guid = "Creature-0-5176-1-74-3928-0000478D0B"
>  isMouseover = false
>  class = ""
>  rawName = "Rotting Slime"
>  level = 21
>  red = 1
>  levelcolorRed = 0.500000
>  isDangerous = false
>  isPet = false
>  name = "Rotting Slime"
>  pvpname = "Rotting Slime"
>  levelcolorBlue = 0.500000
>  isBoss = false
>  isFocus = false
>  healthmax = 643
>  isTarget = false
>  levelcolorGreen = 0.500000
>  alphaMult = 0.101961
>  isMarked = false
>  isTapped = false
>  type = "NPC"
>  blue = 0
>  power = 0
>  isInCombat = false
>  threatSituation = "LOW"
>  powermax = 0
>  isTrivial = true
>  health = 643
>  showName = true
>  reaction = "HOSTILE"
>  green = 0
>  isCasting = false
>  threatValue = 0
>  unitid = "nameplate1"
>  isMini = false
> }
> unitid = "nameplate1"
> questList = <table> {
> }
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = "attempt to index global 'C_TooltipInfo' (a nil value)"

**To Reproduce**
Install version 452 or greater and approach an NPC with nameplates showing.

**Comment by Luxocracy** [comment]
Really sorry about the slow response here, I did not see this issue at all until today.

I've release a new version that fixes this issue. I completely overlooked the fact that Classic versions don't yet have this new method.
