### ISSUE TITLE
Click through Request.

### ISSUE THREAD

**Issue by Rhess86** [Luxocracy/NeatPlates#48]
Hey man, thanks again for keeping this up.
So i was just wondering if there is a way to make npc and friendly players nameplates click through. Like, if i turn off the nameplates, blizzard's original are click through and you only interact with npcs by clicking on their body, with the nameplates on, it adds a clickable area around the names, which is fine, but having an option to make it click through will help a lot on high population areas when i try to select something but keep on getting people's/npc's target.
Thanks.

**Comment by Rhess86** [comment]
Awesome, thanks man.

**Comment by Rhess86** [comment]
Not sure why but that command doesn't do anything on my end, but i have no problem waiting for the update.

**Comment by Rhess86** [comment]
Still nothing.

**Comment by Luxocracy** [comment]
Seems I missed to capitalize the 'P' in plate. Sorry about that, don't have access to my computer at the moment so didn't spot it. If it still doesn't do anything I will just have to figure it out when I do.

`/run C_NamePlate.SetNamePlateFriendlyClickThrough(true)`

**Comment by Rhess86** [comment]
haha all good man, it worked now, thank you very much.

**Comment by Luxocracy** [comment]
This is now part of the latest release which can be downloader either through [Curse](https://wow.curseforge.com/projects/neat-plates) or [GitHub](https://github.com/Luxocracy/NeatPlates/releases/tag/6.22).
