### ISSUE TITLE
Converting your old TidyPlates settings

### ISSUE THREAD

**Issue by Luxocracy** [Luxocracy/NeatPlates#5]
Since going from the original TidyPlates to this one will cause you to lose all your settings I decided to give you an easy solution to the problem.

  Simply download and run [this file](http://www.mediafire.com/file/q24g69dzcp6n5pa/Convert_to_TidyPlatesContinued.ps1/file) or copy the code below into a new _.ps1_ file and run it to easily rename everything necessary to get your settings back.

```
Write-Host 'WARNING: Backup your WTF folder before doing this incase something goes wrong!'
$WTFPath =  Read-Host -Prompt 'Input WTF folder path(ex. C:\Battle.net\World of Warcraft\WTF)'

Get-ChildItem -Recurse -Path "$WTFPath" -Filter "*TidyPlates*.lua" | foreach-object {$name = $_.FullName; (Get-Content $name) -replace 'TidyPlates(?!Cont)', 'TidyPlatesCont' | Set-Content $name; Move-Item -Force $name ($name -replace 'TidyPlates(?!Cont)', 'TidyPlatesContinued'); Write-Host 'Processed File:'$name}

Read-Host -Prompt 'Done! Press Enter to exit'
```

**Comment by pldawn** [comment]
Yes! It works. Thank you very much!!!
I most couldn't play this game without this plug-in!!!!

**Comment by ja0b** [comment]
@hollo6 Go to your SavedVariables folder and check if you have TidyPlates files renamed to TidyPlatesContinued*

**Comment by a-lutz** [comment]
Thank you for the tip :)
On linux this could be in your terminal:
`/your/path/to/wow/WTF$ rename -v 's/TidyPlates/TidyPlatesContinued/' Account/youraccountname/yourrealm/*/SavedVariables/*`

**Comment by hollo6** [comment]
No, it didn't rename anything.

**Comment by ja0b** [comment]
@hollo6 try to run the ps1 as admin. if that doesn't work then you can do it manually.

**Comment by hollo6** [comment]
@ja0b no success :( I would do it manually just don't know what exactly should be done. Same files, only renamed to include Continued in the name? For every character?

**Comment by hollo6** [comment]
Yes I'm running PowerShell, isn't it I'm supposed to do?
Anyway that's a huge amount of files so I guess I'll just copy it to a Linux and do it there.

**Comment by Luxocracy** [comment]
@hollo6  think I managed to reproduce the issue that is happening to you and solve it. I also made it print out what file it is processing.

So try the updated script in the original post.

**Comment by hollo6** [comment]
@Luxocracy Does exactly the same. Looks like the line that should do the work doesn't run at all.

**Comment by Luxocracy** [comment]
@hollo6 So it isn't printing anything when you run it? Which version of windows are you running? Or could you maybe check what your PowerShell version you are running by typing `$PSVersionTable.PSVersion` into PowerShell.

**Comment by hollo6** [comment]
@Luxocracy No, just the last line (Done! Press Enter to exit:).
Win7 Ultimate SP1
PS Version:
Major  Minor  Build  Revision
-----  -----  -----  --------
2      0      -1     -1

**Comment by Luxocracy** [comment]
That might be the issue then, I'm running Win10 and the PowerShell version is 5.1. Gonna look into if any command is missing from the older version.

**Comment by hollo6** [comment]
Thank you! But I will be able to do it on Linux later if it's too much of a hassle. Or it might be easier to just do it in LUA.

**Comment by hollo6** [comment]
Nice! This works, and does not require admin mode. Though it did throw IOException for the files I already had there (because I tried to enable the addon for a character to check it), I think it should just overwrite them.

**Comment by Luxocracy** [comment]
Valid point, updated it once more so it should now also overwrite any existing file.

**Comment by hollo6** [comment]
Thanks, I really appreciate your kind and fast help, also the work on this project!

**Comment by TarzanMelton** [comment]
Where do I imput this code and which part am I copy pasting?

**Comment by Luxocracy** [comment]
Closing this as I no longer feel like this is relevant.
