### ISSUE TITLE
/hub drops an werror, unable to customize further...

### ISSUE THREAD

**Issue by 40P3** [Luxocracy/NeatPlates#54]
6x NeatPlates\NeatPlatesUtility.lua:991: attempt to index local 'panel' (a nil value)
NeatPlates\NeatPlatesUtility.lua:991: in function `OpenInterfacePanel'
NeatPlatesHub\Hub.lua:700: in function `ShowNeatPlatesHubPanel'
NeatPlatesHub\Hub.lua:716: in function `?'
FrameXML\ChatFrame.lua:4757: in function `ChatEdit_ParseText'
FrameXML\ChatFrame.lua:4418: in function `ChatEdit_SendText'
FrameXML\ChatFrame.lua:4454: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
panel = nil
(*temporary) = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'panel' (a nil value)"
fixed = false

**Comment by Luxocracy** [comment]
For now you should still be able to use `/np` or `/NeatPlates` for customization, it appears I overlooked this command when renaming the project.

**Comment by Luxocracy** [comment]
I pushed the fix to the GitHub and I'll make an update to the Twitch client later on day with the fix.

**Comment by Luxocracy** [comment]
I actually went ahead and released this already in the [6.22b-transition release](https://github.com/Luxocracy/NeatPlates/releases/tag/6.22b-transition) which is also aimed at making it easier for people to import their old TPC settings.

**Comment by 40P3** [comment]
Thanks the option now visible.
