### ISSUE TITLE
an issue

### ISSUE THREAD

**Issue by yishuangfrank** [Luxocracy/NeatPlates#55]
1x NeatPlates\NeatPlatesUtility.lua:991: attempt to index local 'panel' (a nil value)
NeatPlates\NeatPlatesUtility.lua:991: in function `OpenInterfacePanel'
NeatPlatesHub\Hub.lua:700: in function `ShowNeatPlatesHubPanel'
NeatPlatesHub\Hub.lua:716: in function `?'
FrameXML\ChatFrame.lua:4757: in function `ChatEdit_ParseText'
FrameXML\ChatFrame.lua:4418: in function `ChatEdit_SendText'
FrameXML\ChatFrame.lua:4454: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
panel = nil
(*temporary) = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'panel' (a nil value)"
fixed = false

**Comment by yishuangfrank** [comment]
When I type “/hub”

**Comment by Luxocracy** [comment]
This appears to be the same issue as reported [here](https://github.com/Luxocracy/NeatPlates/issues/54).
So I'm gonna close this and refer to that issue for further discussion.

**Comment by yishuangfrank** [comment]
BTW，do you have any plan to localize this great addon？

**Comment by Luxocracy** [comment]
I don't have any plans for localization at the moment, mostly because I haven't given it much thought.
But all I can really do is create the English localization file and then I would need someone else to actually do the translation to other languages from there.

**Comment by yishuangfrank** [comment]
OK，look forward the localization in the future.

**Comment by ja0b** [comment]
I can do Spanish :)
