### ISSUE TITLE
Feature request: showing name above nameplate (slim horizontal)

### ISSUE THREAD

**Issue by Vymrr** [Luxocracy/NeatPlates#58]
Would be nice there's an option to show name above nameplate, like default WOW, instead of below.

**Comment by Luxocracy** [comment]
I think this might be something specific to a certain theme, however I don't recall any theme having the name below the nameplate.
Which theme are you using?

**Comment by Luxocracy** [comment]
Generally, I won't spend time on adding features that only affect a single theme. So your best bet for this would be to edit the `NeatPlates_Slim_Horizontal.lua` file yourself and re-position the name and whatever else that would have to be moved as a result of this change.
