### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Luxocracy** [Luxocracy/NeatPlates#60]
Just creating this issue as a consolidation of anything to do with localization as well as a quick overview of what would need to be done if you wanted to contribute in translating.

Below are the two files that would be used as a reference when creating a new localization and empty slates for languages can be found in the parent folder of these files.

[English Localization File](https://github.com/Luxocracy/NeatPlates/blob/master/NeatPlates/locales/enUS.lua)

Update: Since apparently there is a [localization page](https://wow.curseforge.com/projects/neat-plates/localization) directly on Curse it might be better to use that system. I have also merged the files into one because that is how the Curse system handles it and will make the exporting of any translations there easier.

_It is very likely that I have missed things that would need translations, please do point them out if you notice any._

**Comment by yishuangfrank** [comment]
Great！
The Chinese localization files will be updated by my friend in a few hours.

**Comment by zeroagd** [comment]
I have made Chinese translation, but I found some parts aren't listed in profile page:
1. "Categories"(目录) button at upper right corner;
2. Given ranges like "9 yards"(9 码) in "Other Widgets";
3. The name of "Default Profile"(默认模板).
Do them need to be translated?
Chinese localization file:
[zhCN.txt](https://github.com/Luxocracy/NeatPlates/files/2783243/zhCN.txt)
Another issue: The messages "Sorry, can't delete the Default profile :(" and "The profile '%1' was successfully deleted." are both shown when I try to delete Default Profile.
![qq 20190122223030](https://user-images.githubusercontent.com/43439907/51543299-32f09280-1e98-11e9-9347-39b9cd5e52cf.png)

**Comment by zeroagd** [comment]
Anyway, some my friends like use Chinese word "万"(1万=10 thousands) and "亿"(1亿=100 million) to describe HP approximatly . Do you have any plan to add them together?

**Comment by Luxocracy** [comment]
I didn't have any plans to do so, mostly because I had no idea you shortened it like that. I'll see what I can do as this would only be a thing for the Chinese region I'm guessing.

Is "K"(thousand) and "M"(million) used as well and would you like those to be added to the locale in that case?

**Comment by Luxocracy** [comment]
I was considering just doing it like this


	if LOCALE_zhCN and number > 100000000 then
		return (ceil((number/10000000))/10).."亿"
	elseif number > 1000000 then
		return (ceil((number/100000))/10).." "..L["M"]
	elseif LOCALE_zhCN and number > 10000 then
		return (ceil((number/1000))/10).."万"
	elseif number > 1000 then
		return (ceil((number/100))/10).." "..L["K"]
	else
		return number
	end
So that this would just automatically enable if it detects that localization. Also do you happen to know if this is also a thing for the "zhTW" localization?

**Comment by zeroagd** [comment]
It will be "萬" and "億" for zhTW localization.

**Comment by zeroagd** [comment]
1 more unlisted part is found:
"Interrupted" in Cast Bar.
