### ISSUE TITLE
unit filter editbox display improperly in Chinese

### ISSUE THREAD

**Issue by Amoyblack** [Luxocracy/NeatPlates#61]
type a unit name to filter box in Chinese will be displayed as "???"

**Comment by Luxocracy** [comment]
This is because the default font used by the addon doesn't support Chinese characters and I haven't really been sure on how to fix it. But I believe the next release should resolve this issue as it should swap fonts based on your localization.

**Comment by Amoyblack** [comment]
> This is because the default font used by the addon doesn't support Chinese characters and I haven't really been sure on how to fix it. But I believe the next release should resolve this issue as it should swap fonts based on your localization.

thinks ,  Looking forward to your new version about Chinese localization

**Comment by Luxocracy** [comment]
This should have been fixed as of 6.22.1 which was released a few days ago.
