### ISSUE TITLE
Bug in combat (6.22.3a)

### ISSUE THREAD

**Issue by Vymrr** [Luxocracy/NeatPlates#63]
Getting this bug when in combat

Message: Interface\AddOns\NeatPlates\NeatPlatesCore.lua:584: Usage: UnitEffectiveLevel("unit")
Time: Mon Jan 28 22:18:07 2019
Count: 2
Stack: Interface\AddOns\NeatPlates\NeatPlatesCore.lua:584: Usage: UnitEffectiveLevel("unit")
[C]: ?
[C]: in function `UnitEffectiveLevel'
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:584: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:581>
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:457: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:454>
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1004: in function `?'
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1039: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:1038>

Locals:

**Comment by Luxocracy** [comment]
I can't seem to reproduce this one. Any chance you could expand a bit on when you are getting this error?
