### ISSUE TITLE
Friendly nameplates return to default Blizzard inside instances

### ISSUE THREAD

**Issue by jjholleman** [Luxocracy/NeatPlates#66]
I have friendly nameplates set up like this: https://cdn.discordapp.com/attachments/147370794635231232/539854197672116224/unknown.png
The HP bar is hidden and it shows only the friendly player's name classcolored.

However, inside instances this reverts completely to Blizzard's default nameplates
https://cdn.discordapp.com/attachments/396841400018403331/540300585845653514/unknown.png

With /script SetCVar('nameplateShowOnlyNames', 0) I was able to hide the HP bar, but the name is still on the default blizzard settings. I can't get it to work like the first image.

**Comment by Luxocracy** [comment]
Nothing can be done about this since this is caused by a restriction set in place by Blizzard. Basically addons aren't allowed to modify friendly nameplates in dungeons and raids. This was done somewhere in the middle of the Legion expasion.
