### ISSUE TITLE
HP

### ISSUE THREAD

**Issue by zwlwwhhjy** [Luxocracy/NeatPlates#67]
In Chinese, we don't need the  HP to be "million". Can you modify it?

	if GetLocale() == "zhCN" then
		if number > 100000000 then
			return (ceil((number/1000000))/100).." 亿"
		elseif number > 10000 then
			return (ceil((number/100))/100).." 万"
		elseif number > 1000 then
			return (ceil((number/10))/100).." 千"
		else
			return number
		end
	else
		if number > 1000000 then
			return (ceil((number/10000))/100).." M"
		elseif number > 1000 then
			return (ceil((number/10))/100).." k"
		else
			return number
		end
	end

This is a revision of my original version.

**Comment by Luxocracy** [comment]
I've removed "Million" from the chinese number shortening as well as added it as a toggleable option under "Funky Stuff" which should default to _Enabled_ for these regions in the latest version(6.22.4).

**Comment by zwlwwhhjy** [comment]
If "Use Chinese Number Shortening" is not enabled in Chinese, when HP is "K", Chinese "千" will be displayed.
