### ISSUE TITLE
Clamp Nameplate to Screen

### ISSUE THREAD

**Issue by Apoxiosis** [Luxocracy/NeatPlates#71]
Hey Lux. Thanks for the continued work and development on this addon. 

Something Ive had issues with is nameplates floating off the screen. When it happens i can google the cvar real quick to fix it but it seems like it randomly reverts and i dunno how or why and my nameplates begin floating off screen again.

Could an option to clamp nameplates of enemies youre actively in combat with to the screen to prevent them from floating off screen?

**Comment by Luxocracy** [comment]
As far as I know there's no way to control clamping outside of cvars. Positioning of nameplates in general is handled on blizzards end and isn't accessible to addons.

Most likely some other addon is changing this cvar, I know that DBM and elvui, supposedly, changed peoples cvars without their permission a while back. But I believe that should have been fixed.
