### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by yishuangfrank** [Luxocracy/NeatPlates#72]
I used the command "/console cvar_default", and got the following error. But it didn't happen later.

1x NeatPlatesWidgets\ComboPointWidget.lua:223: Usage: GetSpecializationInfo(specIndex[, isInspect[, isPet[, inspectTarget[, sex]]]])
[C]: in function `GetSpecializationInfo'
NeatPlatesWidgets\ComboPointWidget.lua:223: in function <NeatPlatesWidgets\ComboPointWidget.lua:220>
NeatPlatesWidgets\ComboPointWidget.lua:271: in function <NeatPlatesWidgets\ComboPointWidget.lua:270>
Locals:
(*temporary) = nil

**Comment by yishuangfrank** [comment]
I got this error again just now......

**Comment by Luxocracy** [comment]
This should be unrelated to you reseting your CVars, and when I tried it I couldn't reproduce it.

The only way this error would happen is if the server didn't respond with what your current spec is, which is odd. But I can fix it so the error doesn't show at least.

**Comment by yishuangfrank** [comment]
OK，Thanks again！
