### ISSUE TITLE
An issue

### ISSUE THREAD

**Issue by yishuangfrank** [Luxocracy/NeatPlates#73]
The nameplates of Souls can't change the colors according to my threat in Mythic Dungeon(Reaping).
It works well in other cases.

**Comment by Luxocracy** [comment]
I'm not sure what I can do about this as they don't seem to report threat properly like normal mobs. Gonna do some more testing to confirm and if anything can be done but doesn't look good.

**Comment by yishuangfrank** [comment]
[PlateColor.zip](https://github.com/Luxocracy/NeatPlates/files/2904736/PlateColor.zip)
My friend uses this addon which works well for Souls' threat.
Maybe it has reference value for you.

BTW, the current target is not obvious for me.
Is it possible that I can change its color?

**Comment by Luxocracy** [comment]
I'll check it out and see if I can find how that addon does it.

As for changing the color of current target, I guess I could add an option for it but I think it might cause some issues when interacting with the other color functions.
So this is something I will have to think about what the best approach might be.

Which theme are you using btw? Because this might also just be something that is particularly bad for some themes.

**Comment by yishuangfrank** [comment]
NeatPlates_Quatre

**Comment by yishuangfrank** [comment]
I contacted the writer of PlateColor and he told me Souls didn't report threat as you said.
And he just considered  the targets of the Souls.

**Comment by yishuangfrank** [comment]
He gave me the following code:

**Comment by Luxocracy** [comment]
I was already considering doing it like this by only considering if the unit is targeting you or not. However, I wanted to see if there was some other way of handling this that could have worked as a fallback if it happened in the future.
But at least this solution should work and hopefully Blizz will do something about it so this isn't necessary.

**Comment by yishuangfrank** [comment]
I used the latest version these days, and it worked well for Souls.
Do you have any plans for adding the new feature(changing the color of current target).
The white border for current target is not obvious for me.

**Comment by Luxocracy** [comment]
I totally forgot that we talked about that. But turns out that it was a lot more straightforward than I had first expected which made it quite easy to add. So the latest release should have an implementation of this as well as the ability to set custom colors for both _Focus_ and _Mouseover_ in addition to the _Target_.

**Comment by yishuangfrank** [comment]
OMG, YOU are my SUPER  STAR！

**Comment by yishuangfrank** [comment]
It is amazing that we can custom target/focus/mouseover units' color！
However, I find that color the target's nameplate is not ideal.
1. When the target's threat change
2. When the target is touched by hostile player first
the custom color will override original one. 
I was wondering if it will be better that adding an icon on the nameplate just like Target Nameplate Indicator.

**Comment by Luxocracy** [comment]
I did think of some these issues while implementing this. And looking the the "Target Nameplate Indicator" addon, I'm thinking it might be better to change the current highlight system into something that would allow for more customization, such as type or color of the highlight. As opposed to the current implementation.

**Comment by yishuangfrank** [comment]
I disabled "use custom target color" and downloaded Target Nameplate Indicator. But I am not uesd to it now. I am looking for your great idea for highlight system. How about  bold borde?

BTW, The target color is not gray(touched by hostile player) after I disabled "use custom target color".

**Comment by yishuangfrank** [comment]
![tim 20190306171409](https://user-images.githubusercontent.com/44251440/53869576-77448600-4033-11e9-9960-8cbe0aa13502.png)
 
How about the border of target nameplate can be changed?
width and color.

**Comment by yishuangfrank** [comment]
updated to 6.23-beta2
It's awesome!
