### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Rhess86** [Luxocracy/NeatPlates#75]
Hi, i'd like to ask if its possible to add a mover for the class icon on enemy nameplates. Its by default at the top right and it colides with buffs and debuffs like the pics bellow.
A full customization position would be ideal but a simple top right/left bottom right/left helps already.
Thanks a lot.

![image](https://user-images.githubusercontent.com/22274813/53986582-59dbee80-40fd-11e9-8b46-e499b886ece2.png)

**Comment by Luxocracy** [comment]
With the way themes are currently done it would be quite tricky to add an option like this, at least for a single option. And this would be something that would need a pretty big overhaul of how things are currently positioned

Currently, I would say this is something that is unlikely to happen any time soon. But mainly this seems to be an issue of a theme not being configured properly when using Class Icons. I'll take a look at the theme files and see where this could be better positioned, as the position in the image is quite bad.

**Comment by Rhess86** [comment]
Yeah, i figured it wasnt something easy. I mostly use it to tell mobs and player apart, if you see the colors i picked, the mob is a ligher tone of red while the player is a bright red and sometimes i cant tell them apart when my sight is tired. What could work for me also is hide the class icon when in battle with me, if thats an easier fix, because when in battle with me the health bars appear, so isnt a problem to tell them apart. If, not i'll just have to get used to lol
Thanks anyway.
