### ISSUE TITLE
Pandemic highlithing

### ISSUE THREAD

**Issue by Diablolock** [Luxocracy/NeatPlates#83]
When leaving the "Pandemic highlithing" on and applying Absolute Corruption from Affliction Warlock, the icon of corruption keeps highlithed forever. The talent makes the spell Corruption permanent.

ID: https://www.wowhead.com/spell=196103/absolute-corruption

**Comment by Luxocracy** [comment]
Hmm, does this always happen when applied? Or was the talent activated after corruption had been applied? Because I know I specifically made sure that abilities without a duration, like absolute corruption, didn't show pandemic.

**Comment by Diablolock** [comment]
It always happens yea. I had the talent up and went to dummies. Once I applied corruption it was highligthed forever. Try to get out of combat, /reloaded, nothing fixed it.

**Comment by Luxocracy** [comment]
I couldn't verify if absolute corruption specifically was fixed as my subscription isn't active, but I believe it should be fixed. I also improved general accuracy of the pandemic highlighting.

**Comment by Diablolock** [comment]
It's fixed now! tyvm sir.
