### ISSUE TITLE
Range Check on nameplate

### ISSUE THREAD

**Issue by Diablolock** [Luxocracy/NeatPlates#85]
Hi,

I´d like to sugest you to implement a range check based on range of a certain spell.

Right now I use a weakaura for that but on 8.2 I've heard you won´t be able to attach WAs on nameplates anymore.

The WA I use for that is here: https://wago.io/SyY_PPdPf (All credits to Asakawa).

You basically insert the spell ID to be tracked and the positon of the WA on your nameplate. It´s red for out of range and green for in range.
eg.: https://media.wago.io/screenshots/E7NazLGfQ/5c799917f90d3b206484a644.png 

Thx in advance.

**Comment by Luxocracy** [comment]
By any chance do you have any link/source on them restricting nameplate attaching, as that sounds quite troublesome in general, and I couldn't find anything on it.

But either way, this is a pretty solid feature to add regardless. And just to make sure, this is a thing that would appear on each nameplate and not just the current target?
And I'll probably use a library for the range checking, similar to how _RangeDisplay_ does, so a spell ID won't even be necessary and it would, potentially, be a lot more accurate so you could have more colors/actual range.

**Comment by Diablolock** [comment]
Source here: https://twitter.com/WeakAuras/status/1128810471346364416

Yes, the icon would appear on every nameplate shown, eg. if I have nameplates shown on 40 yards, all them would have the icon for range check.

Right now I gotta have 1 of that WA for each character cuz it's based on a single spell ID. For my lock I have Agony set which is 40 yrs and for my boomy I have lunar strike which is 45 yrs. Notice the range could vary according to the class you are playing at the moment.

I would sugest an option for positioning the icon as well since there are many themes for our NeatPlates.

Any more details you need just lmk. I've been using this for quite some time now.

**Comment by Luxocracy** [comment]
So, here's what I've looked into doing so far.

![](https://imgur.com/lpdJaCC.jpg)

I wasn't really a fan of simply using an icon display this information. Or I just couldn't find/think of an icon that I think would fit. So I'm leaning towards using a line underneath/above the nameplate. But if you really prefer an icon, I could definitely add that as an option.

There's also an option, which is enabled in the image above, that scales the width based on how far away you are from the unit.

**Comment by Luxocracy** [comment]
So I released a [beta](https://wow.curseforge.com/projects/neat-plates/files/2717012) with these additions in it if you wanted to check it out and if there's anything missing from it.

**Comment by Diablolock** [comment]
Just tested it. Works like a charm. Have all the options that that WA has. good work man!

One question, have you changed anything on the texture of the Neon theme?

**Comment by Luxocracy** [comment]
It could be the highlighting, set mouseover to glow/highlight. It might also require a reload before it works properly.

Byt yeah, in general the new highlighting system will probably be scrapped or at least changed as it hasn't turned out the way I wanted.
