### ISSUE TITLE
PTR Issue

### ISSUE THREAD

**Issue by MetalHeadSeven** [Luxocracy/NeatPlates#86]
With Neat Plates enabled on the current PTR name plates are not showing at all.  No error just no name plates.   Using Neat Plates version 6.22.11

**Comment by Luxocracy** [comment]
This isn't something I'm able to reproduce, nameplates appear just as expected for me on the PTR.

Are you sure that the addon is enabled on the PTR and that nameplates are enabled in general?

**Comment by MetalHeadSeven** [comment]
I don't know what the problem was but I uninstalled, removed saved variables and reinstalled.  Problem is resolved.

**Comment by Shimiya** [comment]
Sorry to post in a closed issue, but I had this problem on the PTR, so I made a new profile and re-applied each setting one by one (+ reload ui after each tick) and found the culprit : 

In my case that was the setting "Show Threat Percentage", activate this setting make the nameplates disappear (without any lua error).

**Comment by Luxocracy** [comment]
I managed to find what the cause was, there was some leftover code that tried to align the Threat Percentage frame to a frame that didn't exist.

What is weird is that on live it just seems to ignore it, but on the PTR it causes everything to break without throwing an error :/

**Comment by Shimiya** [comment]
Thanks for read my post & fix this issue !
