### ISSUE TITLE
Error after last Update

### ISSUE THREAD

**Issue by MetalHeadSeven** [Luxocracy/NeatPlates#87]
Getting error with 6.23-beta2

Message: Interface\AddOns\NeatPlates\NeatPlatesCore.lua:708: attempt to index field 'color' (a nil value)
Time: Wed May 29 07:50:10 2019
Count: 89
Stack: Interface\AddOns\NeatPlates\NeatPlatesCore.lua:708: attempt to index field 'color' (a nil value)
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:708: in function `UpdateIndicator_Highlight'
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:340: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:325>
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:457: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:447>
Interface\AddOns\NeatPlates\NeatPlatesCore.lua:166: in function <Interface\AddOns\NeatPlates\NeatPlatesCore.lua:143>

Locals: current = "target"
(*temporary) = <function> defined =[C]:-1
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'color' (a nil value)"
unit = <table> {
 pvpname = "Zebast the Everliving"
 name = "Zebast the Everliving"
 levelcolorBlue = 0
 isMouseover = false
 class = ""
 isBoss = false
 guid = "Creature-0-3019-1642-15980-141905-00006E9C1E"
 isMini = false
 isFocus = false
 healthmax = 208128
 isTarget = true
 rawName = "Zebast the Everliving"
 level = 120
 levelcolorGreen = 0.820000
 red = 0.999998
 isTapped = false
 type = "NPC"
 levelcolorRed = 1
 threatSituation = "LOW"
 blue = 0
 isInCombat = false
 unitid = "nameplate1"
 health = 208128
 isDangerous = false
 isMarked = false
 reaction = "HOSTILE"
 green = 0
 isCasting = false
 threatValue = 0
 style = "NameOnly"
}
style = <table> {
 customtext = <table> {
 }
 highlight = <table> {
 }
 threatcolor = <table> {
 }
 spellicon = <table> {
 }
 spelltext = <table> {
 }
 target = <table> {
 }
 level = <table> {
 }
 healthbar = <table> {
 }
 healthborder = <table> {
 }
 threatborder = <table> {
 }
 skullicon = <table> {
 }
 castnostop = <table> {
 }
 castborder = <table> {
 }
 name = <table> {
 }
 hitbox = <table> {
 }
 castbar = <table> {
 }
 frame = <table> {
 }
 eliteicon = <table> {
 }
 raidicon = <table> {
 }
}
visual = <table> {
 customtext = <unnamed> {
 }
 eliteicon = <unnamed> {
 }
 spellicon = <unnamed> {
 }
 focus = <unnamed> {
 }
 target = <unnamed> {
 }
 level = <unnamed> {
 }
 healthbar = <unnamed> {
 }
 healthborder = <unnamed> {
 }
 threatborder = <unnamed> {
 }
 mouseover = <unnamed> {
 }
 spelltext = <unnamed> {
 }
 name = <unnamed> {
 }
 castbar = <unnamed> {
 }
 castnostop = <unnamed> {
 }
 skullicon = <unnamed> {
 }
 castborder = <unnamed> {
 }
 raidicon = <unnamed> {
 }
}

**Comment by Luxocracy** [comment]
The errors should be fixed in the new beta3, but I did find some other issues regarding Headline view and the changed highlight system. So that's something that will most likely have to be redone before 6.23 releases.

**Comment by MetalHeadSeven** [comment]
Thanks for the quick fix.  Errors are gone.
