### ISSUE TITLE
Absorb Bars on all units

### ISSUE THREAD

**Issue by Diablolock** [Luxocracy/NeatPlates#88]
Hi again,

I was looking for an addon for class colored friendly names (not friendily nameplates) and I found this topic you answered: https://github.com/Luxocracy/NeatPlates/issues/43

All everything and it's working flawless except for the absorbs bars.

Even if I have friendly nameplates off the absorb bar keeps showing as the s/s below:
[https://imgur.com/MVLS8HD]

If i toogle off the option "Show on: Target only" the abosrb bar goes away but I need them on every enemy nameplate regardless.

I know the absorb feature is pretty new so maybe we skip that.

Another thing is the class colored names won't work in raids/dgs. Is this caused to blizz protected issue mentioned before?

**Comment by Luxocracy** [comment]
This is probably just an overlooked interaction between absorbs and the headline option. It's an option I often forget about as I don't use it. I'll look into getting it fixed.

And as for dungeons etc, it is indeed a restriction implemented by blizzard.

**Comment by Luxocracy** [comment]
This should be working correctly now as of 6.23-beta4

**Comment by Diablolock** [comment]
Just tested and it's working now. Ty.
