### ISSUE TITLE
Target touched by hostile players is colored in error(v6.23)

### ISSUE THREAD

**Issue by yishuangfrank** [Luxocracy/NeatPlates#91]
Target touched by hostile players should be grey.

![TIM截图20190603200201](https://user-images.githubusercontent.com/44251440/58808578-dd4da300-864c-11e9-858b-b59d944d9304.png)
![TIM截图20190603203336](https://user-images.githubusercontent.com/44251440/58808591-e179c080-864c-11e9-9c2d-f5dcdcfd5ce9.png)

**Comment by Luxocracy** [comment]
I can't seem to reproduce this on my side. Is this something that always happens or is there some particular way to make it happen?

**Comment by yishuangfrank** [comment]
It always happens.
Here is my NeatPlatesHub.lua
[NeatPlatesHub.zip](https://github.com/Luxocracy/NeatPlates/files/3248111/NeatPlatesHub.zip)

**Comment by Luxocracy** [comment]
Aaah, I see what's happening now.

There's a color select for _Tapped Units_ under Reaction that was set to a red color, I changed it back to the default value(gray) for you. I forgot I added that a while back.

[NeatPlatesHub.zip](https://github.com/Luxocracy/NeatPlates/files/3249053/NeatPlatesHub.zip)

**Comment by yishuangfrank** [comment]
Thanks a lot.
