### ISSUE TITLE
NeatPlates doesn't work in Azeroth I went to the swamp and it doesn't work.

### ISSUE THREAD

**Issue by timbooo1** [Luxocracy/NeatPlates#93]
Why is NeatPlates sometimes working and sometimes not working. What do I need to do to keep it working? In the Swamp of Azeroth expansion it isn't working. I checked all my other mods and updated everything. And it still is not working.

**Comment by Luxocracy** [comment]
I would check these three things to start with:
1. Make sure nameplates are enabled in the default options.(Located under _Names_)
1a. Also check what your _Health Bars_ settings are, as they might only be turned on for certain units.
2. In the Main NeatPlates settings, check if _Automation_ is turned on.
3. Still in the Main NeatPlates settings, check that _Nameplate Max Distance_ isn't set to something extremely low. This should be set to _60_ by default.

If none of these things resolve your issue. I would need some more information on what it is that doesn't work properly. Like, are there no nameplates at all? Are the nameplates not updating properly?
And if you could identify when and where the nameplates aren't working more specifically as well, as _somtimes_ isn't really that helpful sadly.

**Comment by timbooo1** [comment]
What I meant with sometimes is that in the swamp it doesn't work at all, and in the area with all the dinosaurs it did, earlier today. Basically I relogged and it stopped working. I'll try checking these settings and if they changed at all. And what I meant with they don't work. Is that nothing is customized. Just the normal blizzard UI for the nameplates.

**Comment by timbooo1** [comment]
I did everything you said. Automation is turned off on 'no automation' 
Nameplate distance is set to 60. 
Nameplates in default settings are put on always show nameplates. 

Whenever I press reset configuration it shows me the right thing, But when I press on okay, it basically removes everything on the screen that it added. So it looks like regular WoW plates again. Like I have no addon.

**Comment by Luxocracy** [comment]
Hmm, if the default plates appear my first thought would be that the addon isn't loaded. Make sure that _**Neat Plates, Neat Plates Hub, Neat Plates Widgets**_ and at least one theme are enabled in the addon list.

**Comment by timbooo1** [comment]
Do I need all these Neat Plates addons?

**Comment by timbooo1** [comment]
https://gyazo.com/36554f5736898e5075c8865db66978ab Never mind, They're all enabled.

**Comment by timbooo1** [comment]
I reloaded the UI and that seems to have fixed it. o_o Welp, thanks anyways :p

**Comment by Luxocracy** [comment]
Weird, glad it works for you now. Never seen it behave in the way you described so hopefully it won't happen again.
