### ISSUE TITLE
Nameplate width

### ISSUE THREAD

**Issue by eatticks** [Luxocracy/NeatPlates#94]
In the last week or so I noticed that nameplate bars no longer can be adjusted in width.  I had shortened the length of the nameplate bars using a feature at the bottom of the page on neat plates addon but it no longer works.  When it first happened it still showed me the reduced size I wanted with some lines around it but then the bar just extended out on both sides to the length of the regular bar anyway.

**Comment by eatticks** [comment]
Great - Thanks!

**Comment by eatticks** [comment]
Hi - I just downloaded a new update for neat plates this morning and the
issue is still present.  Is this slated for the next update?  Thanks.

**Comment by Luxocracy** [comment]
It should have been fixed as of version 6.23.1

Make sure you've restarted the game client, and check that the version is correct.

**Comment by eatticks** [comment]
I was trying to correct it with the wrong nob (clickable nameplate width as
opposed to health bar width).  Working now.  Thanks!
