### ISSUE TITLE
NeatPlatesCore.Lua errors

### ISSUE THREAD

**Issue by TimeToCreate** [Luxocracy/NeatPlates#95]
693x NeatPlates\NeatPlatesCore.lua:707: attempt to index field 'focus' (a nil value)
NeatPlates\NeatPlatesCore.lua:707: in function <NeatPlates\NeatPlatesCore.lua:703>
NeatPlates\NeatPlatesCore.lua:340: in function <NeatPlates\NeatPlatesCore.lua:325>
NeatPlates\NeatPlatesCore.lua:457: in function <NeatPlates\NeatPlatesCore.lua:447>
NeatPlates\NeatPlatesCore.lua:166: in function <NeatPlates\NeatPlatesCore.lua:143>

Locals:
current = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'focus' (a nil value)"
unit = <table> {
 guid = "Creature-0-3770-1771-10674-127482-000285E215"
 isMouseover = true
 class = ""
 rawName = "Sewer Vicejaw"
 threatSituation = "LOW"
 red = 0.999998
 isInCombat = false
 isDangerous = false
 name = "Sewer Vicejaw"
 isElite = true
 pvpname = "Sewer Vicejaw"
 levelcolorBlue = 0
 isBoss = false
 isFocus = false
 healthmax = 421372
 isTarget = true
 levelcolorGreen = 0.820000
 isMarked = false
 absorbmax = 0
 isTapped = false
 absorb = 0
 blue = 0
 style = "Default"
 levelcolorRed = 1
 level = 120
 type = "NPC"
 isCasting = false
 reaction = "HOSTILE"
 green = 0
 health = 421372
 threatValue = 0
 unitid = "nameplate1"
 isMini = false
}
style = <table> {
 customtext = <table> {
 }
 highlight = <table> {
 }
 threatcolor = <table> {
 }
 spellicon = <table> {
 }
 spelltext = <table> {
 }
 target = <table> {
 }
 level = <table> {
 }
 castnostop = <table> {
 }
 healthbar = <table> {
 }
 healthborder = <table> {
 }
 skullicon = <table> {
 }
 threatborder = <table> {
 }
 mouseover = <table> {
 }
 focus = <table> {
 }
 castbar = <table> {
 }
 name = <table> {
 }
 castborder = <table> {
 }
 hitbox = <table> {
 }
 eliteicon = <table> {
 }
 frame = <table> {
 }
 rangeindicator = <table> {
 }
 raidicon = <table> {
 }
}
visual = <table> {
 highlight = <unnamed> {
 }
 customtext = <unnamed> {
 }
 healthbar = <unnamed> {
 }
 healthborder = <unnamed> {
 }
 castborder = <unnamed> {
 }
 threatborder = <unnamed> {
 }
 skullicon = <unnamed> {
 }
 castnostop = <unnamed> {
 }
 spellicon = <unnamed> {
 }
 eliteicon = <unnamed> {
 }
 name = <unnamed> {
 }
 spelltext = <unnamed> {
 }
 target = <unnamed> {
 }
 level = <unnamed> {
 }
 castbar = <unnamed> {
 }
 raidicon = <unnamed> {
 }
}

**Comment by Luxocracy** [comment]
Are you on the latest version? And does this error still happen after restarting WoW?

Because it doesn't really make sense that this error occurs at that point in the code. It should be happening at a different point because it seems like some texture frames aren't getting created.

**Comment by TimeToCreate** [comment]
Yes, I have it every time I start my world of warcraft from week or two, not sure about the time and yes I'm with the latest version, I use twitch to update my addons and do that every morning.

**Comment by Luxocracy** [comment]
Just gonna ask you the same thing as I did in the other thread about this issue. #96 
> Does this still happen if Neatplates is the only active addon? And if it does could you attach your _NeatPlatesHub.lua_ file located here: `World of Warcraft\_retail_\WTF\Account\ACCOUNTID\SavedVariables` so I can easily rule out if this is caused by an interaction of certain settings, as I'm having a really hard time getting this error to occur on my end.

**Comment by Luxocracy** [comment]
Since the other thread on this got resolved, I would also add that you should check so no other nameplate addons are running such as Tidyplates as that would mess with the nameplate frames that are created by this addon.

**Comment by TimeToCreate** [comment]
Yea I think that was the issue.

**Comment by naeshy** [comment]
Just to confirm I also had this error and realized TidyPlates got re-enabled.  Disabling it resolved it for me as well.
