### ISSUE TITLE
Bars show up on units not in combat.

### ISSUE THREAD

**Issue by jhemfl** [Luxocracy/NeatPlates#97]
I have it set so that my headline (text only) overrides while no target is selected and not in combat. 

When I engage a unit in combat. ALL UNITS within range now gain a health bar. 

Looking for a way for units that are NOT IN COMBAT to not have a bar displayed. 
![in combat](https://user-images.githubusercontent.com/52520890/60641267-1d917400-9df9-11e9-95ed-8920e4b7c390.png)
![out of combat](https://user-images.githubusercontent.com/52520890/60641268-1d917400-9df9-11e9-9797-1884bf877368.png)

**Comment by jhemfl** [comment]
Really don't want health bars showing up for no reason when i'm not engaged with the unit in combat.

**Comment by jhemfl** [comment]
I guess maybe like a..... "Force Headline when unit is not engaged in combat"

**Comment by Luxocracy** [comment]
The **Active/Damaged Units** option is a little weird and I should probably change it so it works the way you expect, or at least add a tooltip that clarifies how it currently works.

You can't have **All NPCs** checked as this overrides the **Active/Damaged Units** option. The same goes for **Elite Units** & **Players**, but I feel like it makes a little bit more sense for those options.

**Comment by jhemfl** [comment]
I don't truly understand your reply. Is there an option for this or not? 

Having it render on all npc's but ONLY BARS showing on units in combat?

**Comment by jhemfl** [comment]
It just seems a little janky to have it force bars on all local NPC's when I only have 1 in combat.

**Comment by jhemfl** [comment]
Wow, you fixed it! Idk what you did but the update today works!

**Comment by jhemfl** [comment]
![all fixed](https://user-images.githubusercontent.com/52520890/60670346-691a4100-9e3e-11e9-8c24-46b8ced39878.png)

**Comment by jhemfl** [comment]
This is truly a great addon, I'm very very picky about my nameplates and this has the perfect settings

**Comment by Luxocracy** [comment]
Weird, the update was only some minor redepositing of things for the headline style, as I noticed some were a bit off.

But what I was saying was that basically only the option **Active/Damaged Units** should be checked under _Enemy Health Bars_, to get what you were after. As the other options prevent it from working.
![image](https://user-images.githubusercontent.com/2884542/60670727-a946e700-9e71-11e9-89d5-be8886b6099b.png)

Not sure what settings you are using, but I know the interaction between some of them can be a bit janky.

**Comment by jhemfl** [comment]
Idk what happened but this completely fixed the issue
