### ISSUE TITLE
"AbsorbWidget" is not updated.

### ISSUE THREAD

**Issue by DogmaTX** [Luxocracy/NeatPlates#99]
If "TextOnly" is enabled, then "AbsorbWidget" itself is not updated.
_*Google translator_

[imgur.com/vUYsbH5](https://imgur.com/vUYsbH5)

**Comment by Luxocracy** [comment]
This should be fixed now.
The reason for this was that the absorb bar only updates when something has changed, and it didn't recognize the change between 'TextOnly' and the bar mode as a change.
